### ISSUE TITLE
Tooltips for people, comments and checklist are blurred

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1000]
This is only the case in Chrome. Firefox, Safari and Edge 14 are fine. 
![screen shot 2016-11-04 at 11 09 37](https://cloud.githubusercontent.com/assets/13200338/20003604/58464832-a27f-11e6-853f-93ff10f81ac7.png)

**Comment by hashraf88** [comment]
https://github.com/google/material-design-lite/issues/4574
This seems to be an issue with Chrome version 53.x 
Will monitor in Chrome 54.x (latest) and reopen if needed.

**Comment by DenisVuyka** [comment]
Seems to be working fine for [official demo](https://getmdl.io/components/index.html#tooltips-section)

**Comment by DenisVuyka** [comment]
The workaround is adding the following css for the tooltip:

```css
.mdl-tooltip {
    will-change: unset;
}
```

**Comment by hashraf88** [comment]
It may be required as just reproduced using latest version of Chrome. 
Firstly all three, people, comments and checklist, tooltips were blurred. Refreshed and then comments and checklist tooltips were blurred, refreshed again and all three tooltips were fine. 

<img width="183" alt="screen shot 2016-11-08 at 14 30 12" src="https://cloud.githubusercontent.com/assets/13200338/20102947/e2b15582-a5bf-11e6-840e-a9e40782f24d.png">
<img width="410" alt="screen shot 2016-11-08 at 14 30 05" src="https://cloud.githubusercontent.com/assets/13200338/20102948/e2ce4962-a5bf-11e6-805c-a4945605459a.png">
