### ISSUE TITLE
Once person has been added to task people dialog should disapper

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1001]
<img width="408" alt="screen shot 2016-11-04 at 11 31 05" src="https://cloud.githubusercontent.com/assets/13200338/20004112/4888fbda-a282-11e6-836c-036efb767807.png">

**Comment by DenisVuyka** [comment]
What if I want adding multiple people? do I need opening dialog many times then?

**Comment by hashraf88** [comment]
@VitoAlbano did mention this, within Activiti the dialog disappears once a user has been added. Depends on if we want to replicate Activiti behaviour and what behaviour we want in general

**Comment by VitoAlbano** [comment]
@magemello what do you think about it? should we change the actual behaviour to match the activiti one?

**Comment by magemello** [comment]
It's ok the actual behaviour but let's change the label of the button from cancel to close

**Comment by hashraf88** [comment]
'cancel' changed to 'close'
