### ISSUE TITLE
Add webpack to the demo shell

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1026]
Major actions:

- [x] remove `module.id` from all components
- [x] remove `@types/core-js` from all components (due to conflicts), replaced with `tsconfig.json` extensions
- [x] ensure i18n, images and external templates are loading
- [x] upgrade demo shell to use webpack 1 (official released version)
- [x] unit testing support for demo shell
- [ ] provide documentation updates for all components affected
- [ ] tslint configuration for webpack 

Optional:

- [ ] move dependencies to demo projects (polyfills, MDL and other should be part of demo project and not of the component library)
- [ ] migrate unit tests for all components to webpack
- [ ] upgrade code coverage configuration for all components
- [ ] migrate project demos for all components to webpack
- [ ] provide sever configuration for demo shell bundle (when building in production mode)

**Comment by DenisVuyka** [comment]
Changes related to webpack should be also ported to yeoman app generator.

**Comment by magemello** [comment]
The demo shell works with webpack and angular-cli. To do so I had to change all the templates and the css of the components and require it, also introduce a gulp task that copy all the images and the internationalization files in the demo shell. This bring 2 problems:

1. All the test are broken
2. All the components demo are broken

Now we have 2 choices : 

1. Find the way to make the demo-shell working without to require all the template and the css in the components.
2. Fix the tests and the demos :)

**Comment by DenisVuyka** [comment]
I am not sure about angular-cli support at this point. Couple of cli commands may work but we have no support for entire cli.
