### ISSUE TITLE
When starting a process should user need to provide a name? 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1037]
Comparing starting a process within Activiti to that in the adf components there are some differences, which may be intentional? 

1. Unsure what the dropdown 'type' refers to, should this be 'process'?
2. A process can only be started if a name is added ('start' option is greyed out), should renaming a process be avaliable to the user and if so should it be optional? 
3. If the name is optional should, when the process is started, include the process name or the name given when starting the task? 

**Components**
![screen shot 2016-11-10 at 12 45 13](https://cloud.githubusercontent.com/assets/13200338/20177315/1552a3da-a744-11e6-9781-0c53a2d86d70.png)

**Activiti**
![screen shot 2016-11-10 at 12 45 28](https://cloud.githubusercontent.com/assets/13200338/20177348/36966be4-a744-11e6-8f45-16ddac0b4eca.png)

**Comment by wabson** [comment]
A name is required to start a process instance, the Activiti-app UI gets around this by making up a name based on the process name and date, which we do not do. So the user must enter the name.

We could allow the name to be generated automatically in our component, but I never found the auto-generated names in activiti-app to be particularly helpful when trying to find the process afterwards, nor was it clear how to override the default name (even worse). So I think we'd need to think about the design a bit first.

Or leave it as it is.

**Comment by hashraf88** [comment]
@magemello what would you recommend?

**Comment by magemello** [comment]
I Agree with Will...better have name a required field

**Comment by hashraf88** [comment]
Will close for now as that covers all 3 points above.
