### ISSUE TITLE
After completing a task within the start process dialog this is not displayed in the completed tasks in tasklists

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1039]
Firstly with the two being seperate componets should this occur?

1. Start a new process that includes a form to complete in its start event
2. Complete the form 
3. Go to the task list component
4. Go to the completed tasks filter

**Expected results**
Task completed in step 1 is displayed

**Actual results**
Task completed in step 1 is not displayed

**Comment by hashraf88** [comment]
Same behaviour in Activiti

**Comment by magemello** [comment]
Is it a problem with the API?

**Comment by hashraf88** [comment]
No issue, misunderstanding as start event is not considered a task hence why it does not appear in completed tasks.
