### ISSUE TITLE
Clicking on a new tab refreshes the page 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1040]
If the start event contains a form that has a more than one tab, if anything other than the first tab is clicked the page is refreshed. 

N.b. this is a form, that may help, which has been compressed
[form with all widgets.json.zip](https://github.com/Alfresco/alfresco-ng2-components/files/583577/form.with.all.widgets.json.zip)

**Comment by magemello** [comment]
can't rproduce it

**Comment by hashraf88** [comment]
Reproduced with latest of development on all browsers (Safari, Chrome, Firefox)
[reload.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/584786/reload.mp4.zip)
