### ISSUE TITLE
Right hand side and bottom of form not displayed within form attached to start event

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1042]
**activiti**
![screen shot 2016-11-10 at 14 41 38](https://cloud.githubusercontent.com/assets/13200338/20180792/d0ca80f6-a753-11e6-8c1f-986782eaf36c.png)

**component**
![screen shot 2016-11-10 at 14 40 40](https://cloud.githubusercontent.com/assets/13200338/20180771/b67a24e0-a753-11e6-853f-58f2550a1f7e.png)

N.b. this is a form, that may help, which has been compressed
[form with all widgets.json.zip](https://github.com/Alfresco/alfresco-ng2-components/files/583577/form.with.all.widgets.json.zip)

**Comment by hashraf88** [comment]
the dialog is now larger but again all widgets within a form are not displayed (right hand side and bottom)

**component**
<img width="1328" alt="screen shot 2016-11-11 at 00 54 21" src="https://cloud.githubusercontent.com/assets/13200338/20200523/8ed9bf9e-a7a9-11e6-99a6-4759aae16a4e.png">


**Activiti**
![screen shot 2016-11-11 at 00 55 58](https://cloud.githubusercontent.com/assets/13200338/20200594/eefa35ac-a7a9-11e6-844d-5aea2291ed8c.png)

**Comment by magemello** [comment]
it should be fixed with #1060
