### ISSUE TITLE
date picker displays behind start proces dialog 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1048]
Include date widget within form attached to start event and click date picker.
Fine in Firefox and Safari, issue only in Chrome. 

<img width="729" alt="screen shot 2016-11-10 at 15 27 29" src="https://cloud.githubusercontent.com/assets/13200338/20182669/72689f82-a75a-11e6-908e-1b90799240bf.png">

**Comment by DenisVuyka** [comment]
We need replacing dialog with inline page, there are too many limitations current <dialog> element has.
