### ISSUE TITLE
Cannot go to task from process

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1053]
1. Start a process
2. Click on task 
3. Notice no actions occur

![screen shot 2016-11-10 at 17 54 57](https://cloud.githubusercontent.com/assets/13200338/20188068/edeea7fa-a76e-11e6-812a-1cc745004b10.png)

Works fine in Chrome but not Firefox or Safari

**Comment by wabson** [comment]
This is a dialog issue, the workaround for non-Chrome browsers needs adding into the component

**Comment by hashraf88** [comment]
Works for all other tasks but not the start form (#1058) which may have been implemented after this fix.
