### ISSUE TITLE
Standardize events name

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#1067]
Some of our events don't follow the good pratice for the angular2 Style name events. The goals of this issue are:

- [ ] Create a wiki with the style and the name to use in the common scenario  
- [ ] Sanitize the events that don't follow the standard

Above an example take from the official angular2 style guide:

Do name events without the prefix on.
Do name event handler methods with the prefix on followed by the event name.

Why? This is consistent with built-in events such as button clicks.
Why? Angular allows for an alternative syntax on-*. If the event itself was prefixed with on this would result in an on-onEvent binding expression.

WRONG
```javascript
/* avoid */
@Component({
  selector: 'toh-hero',
  template: `...`
})
export class HeroComponent {
  @Output() onSavedTheDay = new EventEmitter<boolean>();
}
```
```html
<!-- avoid -->
<toh-hero (onSavedTheDay)="onSavedTheDay($event)"></toh-hero>
```

CORRECT
```javascript

app/app.component.html
app/heroes/hero.component.ts app/app.component.html
export class HeroComponent {
  @Output() savedTheDay = new EventEmitter<boolean>();
```

```html
<toh-hero (savedTheDay)="onSavedTheDay($event)"></toh-hero>
```

Infact the two way to bind an event are

```html
(eventname) = "statement"   //surrounded by punctuation
on-eventname = "statement" //preceded by a prefix 
```

If you add on as prefix in an event for example onSuccess the result in the case you are using the preceded by a prefix  way will be :

```
on-onSuccess="statement"
````
not a really nice result

**Comment by wabson** [comment]
Couple of additional points

- All event names should be verbs, wherever reasonable
- I think we should also use the present tense, also, same as DOM events. For example `cancel` instead of `cancelled`
- If some context is required then noun goes before the verb, e.g. `formSelect`, not `selectForm`

**Comment by DenisVuyka** [comment]
Present-only tense may produce some confusion in terms of pre- and post- event handlers. As historically past tense i.e. `formSelected` has been widely used for post- handlers, the `formSelect` can be treated by many as pre- handler (similar to `formSelecting`).

I personally like how Apple solved that in Swift by introducing absolutely clear `willSet` and `didSet`:

- willSet is called just before the value is stored.
- didSet is called immediately after the new value is stored.

In any case we should have both pre- and post- guides and stick to them everywhere.
