### ISSUE TITLE
When logging into either ECM or BPM both are displayed 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1072]
1. Login with either ECM or BPM 
2. Go to user info component

**Expected results**
If logged with ECM or BPM only ECM or BPM user is displayed

**Actual results**
Both users informations are displayed, regardless of who is logged in

**Comment by hashraf88** [comment]
This fix has regressed with latest code.

**Comment by magemello** [comment]
can we add a unit test to make sure we don't regress again in the future?

**Comment by hashraf88** [comment]
Cannot reproduce on latest development

**Comment by hashraf88** [comment]
This fix has regressed with latest code.
