### ISSUE TITLE
dynamic table is not greyed out on completed forms

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1085]
![screen shot 2016-11-11 at 15 52 11](https://cloud.githubusercontent.com/assets/13200338/20224947/d4ff7d76-a838-11e6-8065-8cac07fcca42.png)

**Comment by mauriziovitale** [comment]
@hashraf88 I'm unable to replicate the case. Can you retest the issue, please ? 
<img width="1312" alt="screen shot 2016-11-15 at 17 32 24" src="https://cloud.githubusercontent.com/assets/14923305/20316476/e3045792-ab59-11e6-9363-3aa987253c04.png">

**Comment by hashraf88** [comment]
The dynamic table should be greyed out, same as other widgets, on a completed form.
Can see  in above screenshot is is not.
