### ISSUE TITLE
Upgrade custom material-design-lite theme

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#1111]
Our custom orange-blue theme does not support the latest features of MDL (e.g. [chips](https://getmdl.io/components/index.html#chips-section)) and may have bugs which are fixed in more recent versions. We should consider upgrading.

**Comment by magemello** [comment]
The dependency to MDL is also in the core and all the sub demos in the components

**Comment by DenisVuyka** [comment]
@magemello Dependency is already new, we need getting latest CSS theme for demo shell

**Comment by magemello** [comment]
Gotcha

**Comment by DenisVuyka** [comment]
@mauriziovitale can you take a look please? it seems we have a modified .min.css file instead of a standard one. Whatever I generate with MDL theme generator does not work properly anymore.
