### ISSUE TITLE
Use MDL chips in picker results

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#1112]
[Chips](https://getmdl.io/components/index.html#chips-section) present selected items in a standard wrapper, which can optionally have a 'remove' button and an icon.

We should consider migrating file pickers and user/group pickers in the relevant form widgets to use these components.

Requires #1111

**Comment by hashraf88** [comment]
If search is blank either no results or all results should be displayed

1. Click people picker
**2. Notice no results are displayed**
3. Enter a character to return results
4. Remove character
**5. Notice all people are displayed** 

[people.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/708914/people.mp4.zip)

**Comment by hashraf88** [comment]
Above #1484
