### ISSUE TITLE
Completed form shows typeahead option index not text

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1117]
<img width="459" alt="screen shot 2016-11-17 at 12 24 24" src="https://cloud.githubusercontent.com/assets/13200338/20389372/3aa96cb8-acc1-11e6-98d3-b9457e2ad9bc.png">

**Completed form**
<img width="377" alt="screen shot 2016-11-17 at 12 24 12" src="https://cloud.githubusercontent.com/assets/13200338/20389371/3aa963d0-acc1-11e6-9d84-2b2f14932a3f.png">

**Comment by VitoAlbano** [comment]
![screen shot 2016-11-17 at 17 19 42](https://cloud.githubusercontent.com/assets/7974125/20399883/9929ebc2-acea-11e6-9a46-720e0f80af14.png)

I am not able to reproduce this, have you tested with the latest version of the code?
