### ISSUE TITLE
Page is not displayed correctly 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1123]
Only appears after initially starting the demo shell

1. Npm start in demo shell folder

![screen shot 2016-11-18 at 10 41 13](https://cloud.githubusercontent.com/assets/13200338/20427413/b790f542-ad7b-11e6-8170-456ca365f9d7.png)

**Comment by DenisVuyka** [comment]
see also #1076

**Comment by mauriziovitale** [comment]
Should be fixed with #1076
