### ISSUE TITLE
Tabs do not display in completed tasks

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1128]
1. Start a new process
2. Ensure user task within process has form attached that includes more than one tab
3. Go to tasklist
4. Complete task 
5. Go to process list
6. Open task completed

**Expected results**
All tabs are displayed

**Actual results**
Only one tab is displayed

**Comment by VitoAlbano** [comment]
@hashraf88  i've retried it with the latest development and it seems fine, could you please retry it?

<img width="1043" alt="screen shot 2016-11-23 at 17 11 29" src="https://cloud.githubusercontent.com/assets/7974125/20571593/03802ed2-b1a0-11e6-80b6-011ed01beeab.png">

**Comment by hashraf88** [comment]
2. Ensure user task within process has form attached that includes more than one tab

Ensure testing against a user task not a form attached start event
