### ISSUE TITLE
Dynamic table is not greyed out in completed form

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1130]
Dynamic table not greyed out in a **completed form** attached to a **start event**

<img width="656" alt="screen shot 2016-11-23 at 09 44 29" src="https://cloud.githubusercontent.com/assets/13200338/20556996/83e276b4-b161-11e6-9333-70903601a310.png">

**Comment by mauriziovitale** [comment]
Should be fixed with #1085
