### ISSUE TITLE
When switching between filters if task name is the same task details do not change

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1132]
1. Ensure under 2 or more filters the first task listed has the same name
2. Click between filters

**Expected results**
Task details change accordingly

**Actual results**
Task details remain same 

[first.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/608592/first.mp4.zip)

**Comment by wabson** [comment]
@hashraf88 both Save and Complete buttons appear for me, after clicking on tasks associated with this process. I noticed clicking Complete does not close the dialog and reload the processlist, but that would be a different issue.

**Comment by hashraf88** [comment]
@wabson is the above comment for #1135 ?
I will retest #1135 and move this back to 'in development' for more investigation

**Comment by wabson** [comment]
@hashraf88 yes, sorry please ignore the comment above. I could not reproduce this issue here could when I tried it myself.

**Comment by hashraf88** [comment]
Cannot reproduce on latest
