### ISSUE TITLE
Visiting active tasks within process

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1135]
When accessing active tasks from the process details should the fields be editable and if so once edited what should occur? 

Possible changes could be, 
1. Include a save button
2. Direct to task within tasklist

**App used in testing**
[simple app.zip](https://github.com/Alfresco/alfresco-ng2-components/files/608969/simple.app.zip)

**Comment by wabson** [comment]
Comment mistakenly added on #1132 which should have been added here

> both Save and Complete buttons appear for me, after clicking on tasks associated with this process. I noticed clicking Complete does not close the dialog and reload the processlist, but that would be a different issue.
