### ISSUE TITLE
Dropdown option set as default is not selected as default for form attached to user task

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1136]
**For a form attached to a user task**, if a dropdown widget is added if an option is set as default it is not selected as the default option in the form. 

**Activiti**
<img width="748" alt="screen shot 2016-10-31 at 15 35 11" src="https://cloud.githubusercontent.com/assets/13200338/19860183/bd99c8d8-9f7f-11e6-989a-4e9d5b7935a8.png">

**Activiti**
<img width="473" alt="screen shot 2016-10-31 at 15 39 32" src="https://cloud.githubusercontent.com/assets/13200338/19860342/3d7e006e-9f80-11e6-96e3-a07c4709dba9.png">

**Component**
![screen shot 2016-10-31 at 15 40 04](https://cloud.githubusercontent.com/assets/13200338/19860368/520c9400-9f80-11e6-9552-91a2f43d0ce4.png)

**Comment by mauriziovitale** [comment]
@hashraf88 can you check this issue again ? It seems to work fine
<img width="872" alt="screen shot 2016-11-24 at 16 43 58" src="https://cloud.githubusercontent.com/assets/14923305/20605900/933fcdaa-b265-11e6-929f-4110563c26a9.png">

**Comment by hashraf88** [comment]
Replicate on latest, ensure when trying to replicate **testing against a form attached to a user task**

Steps to reproduce:
1. Import below app
2. Start process
3. Complete form attached to start event (notice default dropdown values are set correctly)
4. Go to task list > involved tasks
5. Go to task 'first task with all' 

**Expected results**
Dropdowns have option 2 set as default

**Expected results**
Dropdowns do not have any option set as default

n.b. the same form is used in start event and 'first task with all' task and so behaviour in both forms should be the same
[simple app.zip](https://github.com/Alfresco/alfresco-ng2-components/files/612128/simple.app.zip)

**Comment by VitoAlbano** [comment]
It seems that now is fixed could you please retry it again?

![screen shot 2016-11-28 at 11 03 33](https://cloud.githubusercontent.com/assets/7974125/20666082/63df1370-b55a-11e6-90ce-a94373bed0ff.png)
