### ISSUE TITLE
Unable to create default reports for new user - CSRF error

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#1142]
As observed by @ohej 

**Type of issue:**  (check with "[x]")

- [ ] New feature request
- [x] Bug  
- [ ] Support request

**Current behavior:**
A new user logging into the demo-shell for the first time is not able to see any reports. The back-end call to create the reports fails with 403 response indicating that the CSRF policy was not satisfied.

Looking into the actual POST request to `default-reports` endpoint showed that the CSRF token was provided via the `Cookie` header but not via the custom `X-CSRF-Token` header.

Reports are shown OK if the user has first created these inside the Angular1 app.

**Expected behavior:**
Default reports should be created OK and displayed on the LHS panel

**Steps to reproduce the issue:**
1. Create a user in activiti and give them the analytics capability
2. Navigate to Reports in the demo shell

**Component name and version:** 

ng2-activiti-analytics

**Comment by magemello** [comment]
this issue wil be solved when we will move the analytics call inside the js-api #992
