### ISSUE TITLE
Completing tasks from process details does not update the view

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#1148]
**Type of issue:**

- [ ] New feature request
- [x] Bug  
- [ ] Support request

**Current behavior:**

When a task is completed from the process details view the dialog containing the task does not close, the details do not get updated to reflect the fact that the task has been completed and the processlist itself does not update (say if this is the last task in the process, it should be removed from *My Tasks*.

**Expected behavior:**

After the task is completed via its form or via the button (for tasks with no form) the task dialog should close, the details should get updated to reflect the fact that the task has been completed (for processes with tasks still remaining) and the processlist should get updated (e.g. when this is the last task in the process).

**Steps to reproduce the issue:**

1. Start a new process which has at least one user task within it, from the Start Process comp
2. In the process details view, click the first task to bring up the task details
3. Complete the task, filling out any mandatory form fields if required to do this

**Component name and version:** 

ng2-activiti-processlist

**Comment by hashraf88** [comment]
The dialog is now closed for once a task is completed, refreshing of the process list will be investigated in #1157
