### ISSUE TITLE
Cannot rename a report

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#1174]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

When i create a report and give it a custom name, unlike Activiti, i cannot double click on the title and change it
**Expected behavior:**

It should be the same as in activiti, i.e  click to highlight then second click makes the title editable and once its changed it s saves it and makes it a persisent change
**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

Chrome, MacOs Version 54.0.2840.98 (64-bit)
 
**Node version (for build issues):**  

**New feature request:**

**Comment by hashraf88** [comment]
When editing the report name a double click is required, one click to focus and one click to enter the text area.

Also to make the report more noticeable it can be edited,
1. When hovering over the report name the cursor could change to a hand picker 
2. When hovering over the report name the text could be highlighted
