### ISSUE TITLE
Seperate Report Definition from Report Rendering

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#1175]
**Type of issue:**  (check with "[x]")
```
- [X] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**

Currently we have the definition filter options as part of the charts and reports making it hard to include the reports in a dashboard. 
**Expected behavior:**

Currently we have the definition filter options as part of the charts and reports making it hard to include the reports in a dashboard. 

The definition options should be a screen (and component) of its own. This is what the user sees when they create a new report.

For instance for a Process heat map a user's start with this. 

![reportdefinition](https://cloud.githubusercontent.com/assets/2410281/21068908/05974834-be6d-11e6-8ec1-4feed82b24bc.png)

An when they save it the report and any other defines report  looks like below, with the choices being legends and a  settings icon that can bring up the options and change them. Once done the user  they can either save it and the changes are reflected
![heatmapreport](https://cloud.githubusercontent.com/assets/2410281/21068897/e5ba7df6-be6c-11e6-81e3-5c9c72953433.png)
**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

The current implemenation of the reports components mimics the end user experience of Actviti. However, the purpose of the component is to allow to embed defined reports in user dashboards. With the current UI it's very hard to do that, unless you follow the prededined Activiti Analytics UI.

**Comment by magemello** [comment]
@jsotiro needs more details here.

**Comment by jsotiro** [comment]
@magemello details added
