### ISSUE TITLE
Demo Shell menu bar dissapears in responsive mode

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#1177]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

When testing the demo shell for responsive behaviour the components respond as expected but when going to tablet or smartphone size the top menu bar (with the logo, options, settings etc) dissapears. This is farily new. it used to work fine
**Expected behavior:**

It should have a responsive menue
**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by magemello** [comment]
closing solved in #1178
