### ISSUE TITLE
Header bar get hidden for mobile and tablet

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1178]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
```
**Current behavior:**

On mobile and tablet devices the header bar is hiddem
**Expected behavior:**

On mobile and tablet devices the header bar should be visible after the login

**Steps to reproduce the issue:**

Login on a mobile device or tablet. 
**Component name and version:** 

demo shell
**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by hashraf88** [comment]
Header is now displayed but none of the components are avaliable within the header e.g. document list, activiti etc

<img width="501" alt="screen shot 2016-11-30 at 13 11 09" src="https://cloud.githubusercontent.com/assets/13200338/20753478/88dcd2e8-b6fe-11e6-925c-26e66e28f4d7.png">

**Comment by magemello** [comment]
I suppose we have to show the options under the burger icon...

**Comment by DenisVuyka** [comment]
Previously before it got broken menus were also displayed as left sliding menu on mobile devices, see Navigation layouts: https://getmdl.io/components/index.html#layout-section/layout

**Comment by hashraf88** [comment]
I cannot see the options under the burger icon

<img width="920" alt="screen shot 2016-11-30 at 20 13 14" src="https://cloud.githubusercontent.com/assets/13200338/20769367/812da08c-b739-11e6-8631-f844d03796d9.png">

**Comment by DenisVuyka** [comment]
Now the UI is even uglier than was before:

<img width="1440" alt="screen shot 2016-12-01 at 09 48 10" src="https://cloud.githubusercontent.com/assets/503991/20789283/9adc728e-b7ab-11e6-8817-f8fe5c6d22bc.png">
