### ISSUE TITLE
No cancel button when starting a process

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1182]
When starting a process there is no cancel button, only start.
The question could be asked if one is needed. 

<img width="894" alt="screen shot 2016-11-30 at 17 22 55" src="https://cloud.githubusercontent.com/assets/13200338/20763408/d5d0c21c-b721-11e6-8d85-ef1e2ba79b97.png">

**Comment by magemello** [comment]
Cancel button not needed, navigating away already cancel the start process
