### ISSUE TITLE
Actviti reports dont have save report or export data

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#1184]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

When viewing a report compoenent, there is no export or save report functionality
**Expected behavior:**

We should have it as part of the UI but with the option to show and hide or call it using javascript function so that it can be called from a contextual menu or other buttons the developer may provide
**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by magemello** [comment]
is not a bug is a new feature...

**Comment by hashraf88** [comment]
Issues found reported below

Issue reported in Activiti also present https://github.com/Alfresco/activiti-bpm-suite/issues/3553 
#1652
#1654
