### ISSUE TITLE
Can obtain password from post requests in browser console for ECM and/or BPM

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1185]
<img width="692" alt="screen shot 2016-11-30 at 20 28 56" src="https://cloud.githubusercontent.com/assets/13200338/20769921/c521d93c-b73b-11e6-8582-24b21689a431.png">

**Comment by eromano** [comment]
Every data sent through HTTP connection could be intercepted by someone on its route to the server. The only way to protect the data is to send it through SSL (HTTPS instead of HTTP).
