### ISSUE TITLE
Create CI chain

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#12]
We need:
- Build system QA/DEV/PRODUCTION
- Execution of the Automation tests at prescheduled time.
- Execution of the unit tests on each PR (we could use [Travis](https://travis-ci.org/))
- Publish everything on a private endpoint
- Automation Test Monitor
- Build bot for skype & slack channel

**Comment by enzor** [comment]
CI chain - pull/build/push and deploy to rancher is done.
Created the docker container for @VitoAlbano to use robotframework for tests online, waiting for his approval to put this on Jenkins

**Comment by VitoAlbano** [comment]
The containers seems to be fine, let's upgrade with that the jenkins task please 👍

**Comment by VitoAlbano** [comment]
Unfortunately , we need to upgrade the container to install the new libraries generated in python from swagger.
Actually the tests are not running.

**Comment by enzor** [comment]
which libraries you need? (yaaay)
