### ISSUE TITLE
Validation on length of username and password is not required

### ISSUE THREAD

**Issue by john-knowles** [Alfresco/alfresco-ng2-components#1211]
**Type of issue:**  (check with "[x]")
```
- [ x ] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behaviour:**
When entering username or password a validation appears saying what has been entered is not long enough.

![snip20161206_9](https://cloud.githubusercontent.com/assets/18680913/20992383/b8da99ac-bcdb-11e6-89e6-0e443984b3f4.png)

**Expected behaviour:**
Validation on length of inputted characters is not required on a login page.

**Steps to reproduce the issue:**
1. Go to login page
2. Enter 2 characters in the username and password fields

**Component name and version:** 
ng2-alfresco-login

**Browser and version:** 
all
 
**Node version (for build issues):**  

**New feature request:**

**Comment by magemello** [comment]
@john-knowles this validation is set inside the component that integrates the <login-component>. So you can override it changing the custom validation. Example: in the demo shell login-demo.component.ts, try to remove the following code:

```
this.customValidation = {
            username: ['', Validators.compose([Validators.required, Validators.minLength(4)])],
            password: ['', Validators.required]
        };
```

**Comment by john-knowles** [comment]
Thank you, have passed that on to the team.
