### ISSUE TITLE
Configurable Remember Me check box, Register link and Need Help link

### ISSUE THREAD

**Issue by john-knowles** [Alfresco/alfresco-ng2-components#1212]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behaviour:**
Remember Me check box, Register link and Need Help link are not configurable.

**Expected behaviour:**
Remember Me check box, Register link and Need Help link should be optional.

**Steps to reproduce the issue:**

**Component name and version:** 
 ng2-alfresco-login.

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

- Remember me, for some solutions, is not suitable due to potential security implications.
- Register is not a feature in Alfresco on-premise solutions
- Need help (or forgotten password) is not a current feature of Alfresco ECM

**Comment by magemello** [comment]
It would be nice be able also to add custom content in the bottom of the login component
