### ISSUE TITLE
Error on login when user has non-latin character in username or password

### ISSUE THREAD

**Issue by john-knowles** [Alfresco/alfresco-ng2-components#1213]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behaviour:**
Error occurs and login fails.
![snip20161206_12](https://cloud.githubusercontent.com/assets/18680913/20992648/61345704-bcdd-11e6-8f7b-ae558c7522d8.png)

**Expected behaviour:**
Login is successful without errors.

**Steps to reproduce the issue:**
_Pre-conditions:_
1. Go to Alfresco Content Services (Platform or Share) and create any valid user that contains in its username and password non-Latin characters (e.g. Russian, Chinese, French, Romain characters ,etc) 
2. In a browser enter: http://<hostname>:<port>/login
3. Enter the user's details created in preconditions and press SIGN IN button.

**Component name and version:** 
ng2-alfresco-login

**Browser and version:** 
Chrome
 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
Fixed with the update to alfesco-js-api: https://github.com/Alfresco/alfresco-js-api/pull/155

**Comment by hashraf88** [comment]
Tried with the below and only French allowed for a login.

- Chinese (traditional) 請請請請 / 請請請請
- Russian админ/админ
- French plaît/plaît

**Comment by DenisVuyka** [comment]
@hashraf88 the fix was on alfresco-js-api side, nothing changed in ADF, so you need getting and linking latest `alfresco-js-api` lib
