### ISSUE TITLE
Password label moves inside the input field

### ISSUE THREAD

**Issue by john-knowles** [Alfresco/alfresco-ng2-components#1214]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behaviour:**
Password label moves into the input field after logout
![snip20161206_10](https://cloud.githubusercontent.com/assets/18680913/20992807/766c3c44-bcde-11e6-8e4a-108d5c8f29e7.png)

**Expected behaviour:**
Password label stays in the correct location.

**Steps to reproduce the issue:**
1. Go to Alfresco (Platform or Share) and create any valid user.
2. In a browser that has Save Password functionality embedded  (e.g. Chrome) go and enter: http://<hostname>:<port>/login
3. Enter the username and password and press SIGN IN button.
4. Logout from the application and open again http://<hostname>:<port>/login page

**Component name and version:** 
ng2-alfresco-login.

**Browser and version:** 
Chrome
 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
This is issue in the material-design-lite repo seems to be related https://github.com/google/material-design-lite/issues/1152

**Comment by VitoAlbano** [comment]
@hashraf88  seems to work fine now, could you please test this?

![screen shot 2017-01-19 at 10 55 32](https://cloud.githubusercontent.com/assets/7974125/22104163/e9f190b0-de35-11e6-8e81-01ade7becb4e.png)

**Comment by corinazaharia** [comment]
The issue is still reproducing on the latest released ADF components ( on SFS app).

**Comment by ohej** [comment]
Reopening for reinvestigation

**Comment by DenisVuyka** [comment]
Current component (MDL input) we are using is known for these kinds of problems. We had the same with Form component. I suggest we migrate login to [material/input](https://material.angular.io/components/component/input) to get the same look and feel but more stable implementation. We already use that library so migration efforts should be minimal.
