### ISSUE TITLE
When clicking on an app after login an error is showed in console.

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#1217]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

**Expected behavior:**

**Steps to reproduce the issue:**

1. Login into the demo shell with an app already deployed on activiti
2.Click on Activiti
3.Click on the deployed app

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

![screen shot 2016-12-09 at 11 57 26](https://cloud.githubusercontent.com/assets/7974125/21048394/f95d3f58-be06-11e6-9b25-70f1419d96f8.png)

**Comment by magemello** [comment]
@VitoAlbano  can you still reproduce it?

**Comment by VitoAlbano** [comment]
@magemello  not anymore so i would consider this fixed.

**Comment by magemello** [comment]
ok
