### ISSUE TITLE
Upload Folder does not interact with automation

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#122]
Using the common system to send the path to the element of upload folder doesn't work. We need further investigation to understand if it is possible to automate.

**Comment by magemello** [comment]
do we have any update about the folder?

**Comment by magemello** [comment]
@VitoAlbano  & @hashraf88 do we have any update about it?

**Comment by VitoAlbano** [comment]
Actually the bug is fixed on a canary version of Chrome, so when the put it available we can see if Selenium2Library implements it.
Anyway i think that due the change of technology this is something which needs to be re evaluated.
@magemello  what do you think about it?
