### ISSUE TITLE
Erratic Data Picker 

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#1223]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [X] Bug  
- [ ] Support request
```
**Current behavior:**

When hit the back arrow a few times the date picker will either stop moving back by  a month or becomes overized. See attached screenshot. This could also be the case in other components but i have only tested it during testing the Analytics components 

<img width="951" alt="pregnantdatepicker" src="https://cloud.githubusercontent.com/assets/2410281/21070097/5a7122c0-be78-11e6-9b0c-175d56144202.png">
**Expected behavior:**

The date picker should behave consistently 
**Steps to reproduce the issue:**

Click fats a few times the back arrow next to the 
**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
Seems to be a `md-date-time-picker` component bug.

**Comment by magemello** [comment]
can you point any open issue on their repo?

**Comment by hashraf88** [comment]
I can replicate, the only steps I can advise are clicking the next or back arrow before the month is displayed (while the mouse pointer changes to the 'no entry' symbol). 
Cannot see anything in the console or network tab that is suspicious.
