### ISSUE TITLE
Detailed Task Statistics miss assigne stats subtable

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#1224]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [X] Bug  
- [ ] Support request
```
**Current behavior:**

When using a a Task Overview report, the Detailed Task Statistics does not have the stats sub-table for each assigner for the selected row. 
**Expected behavior:**

It should have the same behaviour as the Activiti report - i.e when the user clicks on a row, it should show the subtable with the stat details per assignee. See screeenshot
<img width="787" alt="subtable" src="https://cloud.githubusercontent.com/assets/2410281/21070253/3c09630e-be7a-11e6-89aa-b0becb596678.png">

**Steps to reproduce the issue:**

Create a Task Overview report for a process with tasks with more than one assignee. Scroll down and llok at the Detailed Task Statictics table. there is no facility to select a row and show the assignee breakdown subtable 
**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by hashraf88** [comment]
Graph does not display correctly in Firefox and does not display at all in Safari, fine in Chrome.

**Firefox**
<img width="932" alt="screen shot 2017-01-09 at 16 54 37" src="https://cloud.githubusercontent.com/assets/13200338/21775021/6c4c4bec-d68c-11e6-86e6-2cc87b738aa9.png">

**Chrome**
<img width="941" alt="screen shot 2017-01-09 at 16 54 26" src="https://cloud.githubusercontent.com/assets/13200338/21775022/6c4f105c-d68c-11e6-97a0-01a9a4a7139a.png">

**Safari**
<img width="925" alt="screen shot 2017-01-09 at 16 54 08" src="https://cloud.githubusercontent.com/assets/13200338/21775020/6c4c169a-d68c-11e6-9d2c-3427934c03c5.png">

**Comment by hashraf88** [comment]
Above reported in #1440
