### ISSUE TITLE
Search folder, cannot use pagination after accessing a folder

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1247]
1. Search for a folder (ensure has more than 20 items in that folder)
2. Click on a folder in list of suggestions
3. Using pagination options click next page

**Expected results**
Next page of items within folder displayed

**Actual results**
No actions occur

**Comment by wabson** [comment]
Please retest, seems to be working OK now on latest `development`

**Comment by hashraf88** [comment]
Cannot replicate on latest of development
