### ISSUE TITLE
Creating a new checklist does not create a new task 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1259]
1. Create a new task within activiti task list component
2. Create a new checklist against newly created task
3. Refresh page/change filter

**Expected results**
A new task is created, task name is checklist created in step 2

**Actual results**
No new task is created for checklist item created in step 2

**Comment by hashraf88** [comment]
New task is now created when checklist is added to a task but tasklist is not instantly updated a refresh of the tasklist if required (clicking on one filter then back to original).

**Comment by VitoAlbano** [comment]
@hashraf88 this happen on activiti too, we can improve it, but i don't think it is the same bug.

**Comment by hashraf88** [comment]
Above issues fixed however slight issue raised in #1441
