### ISSUE TITLE
http://localhost:3000/ should be directed to login page not home page

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1263]
When accessing http://localhost:3000/ should be directed to Login page not home page.

**Comment by DenisVuyka** [comment]
The behaviour is that you by default go to the Home page, in case you are not authenticated - you are redirected to the Login one.

**Comment by magemello** [comment]
can we close it?

**Comment by DenisVuyka** [comment]
Yes, that was the intended behaviour to have a Home page as default route. Next time users go to the web address they access Home instead of Login even after they logged in 1 minute ago

**Comment by hashraf88** [comment]
Should I have the top border and left hand menu avaliable if I am not logged in? 
Currently I do as Home page is default

**Comment by magemello** [comment]
If you are not logged in...you should be redirected to the login page
