### ISSUE TITLE
File  Format  .docx ,  .xlx  not  supported 

### ISSUE THREAD

**Issue by vikashsingh005** [Alfresco/alfresco-ng2-components#1268]
Not  All  File  Format  Supported  while  uploading  Doc  to alfresco  please  find  below  attached  screen

![image](https://cloud.githubusercontent.com/assets/7962189/21190542/272c041a-c248-11e6-84ce-2dade50e7581.png)

**Comment by eromano** [comment]
Hi @vikashsingh005 ,
in the readme of the viewer component there is a list of the [currently supported extension](https://github.com/Alfresco/alfresco-ng2-components/tree/master/ng2-components/ng2-alfresco-viewer).
This asked by you is a new feature already mapped in  the issue [509](https://github.com/Alfresco/alfresco-ng2-components/issues/509)
