### ISSUE TITLE
Can edit date widget on completed form attached to start event

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1274]
1. Attach form with date widget to start event
2. Complete process
3. Go to completed processes

<img width="616" alt="screen shot 2016-12-14 at 22 14 15" src="https://cloud.githubusercontent.com/assets/13200338/21203543/d795c87a-c24a-11e6-9bc6-e54bbf7805c7.png">

**Comment by magemello** [comment]
can't reproduce it

**Comment by hashraf88** [comment]
Sorry, firefox only

**Comment by VitoAlbano** [comment]
Retried and now seems to work fine.

@hashraf88  could you please retest it?

<img width="522" alt="screen shot 2017-01-03 at 11 37 26" src="https://cloud.githubusercontent.com/assets/7974125/21606692/075fad7e-d1a9-11e6-861a-1c47871872bc.png">

<img width="772" alt="screen shot 2017-01-03 at 11 37 14" src="https://cloud.githubusercontent.com/assets/7974125/21606693/077a84a0-d1a9-11e6-931b-d83918980aa6.png">

**Comment by hashraf88** [comment]
Cannot reproduce
