### ISSUE TITLE
Process Heat map - graph not displayed correctly

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1276]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
```
**Current behavior:**

<img width="1026" alt="screen shot 2016-12-15 at 10 16 51" src="https://cloud.githubusercontent.com/assets/688226/21220300/1d71f296-c2b0-11e6-91a6-c5d5f172c68e.png">
**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by hashraf88** [comment]
Unfortunately still the same for me
<img width="1061" alt="screen shot 2016-12-15 at 18 58 28" src="https://cloud.githubusercontent.com/assets/13200338/21237830/81979882-c2f8-11e6-95e7-3865e3be4632.png">
