### ISSUE TITLE
ByPass Login  Page  to  Generate Token

### ISSUE THREAD

**Issue by vikashsingh005** [Alfresco/alfresco-ng2-components#1279]
Can  i  Customize login   page  of  alfresco like  here  after  enter  username  and  password User will  display  DocumentList,  can  i  ByPass  this  Page  by  HardCoded username  and  Password  to generate  Token  from  alfresco  why  because  our  alfresco  is  integrated  with  Active  Directory  and  this  Appliction  i  dont  want  to  Enter  User name  Password  again  So,  please  guide  me   where  to  change  username  and  password  as  hardcoded so   that  it  will  generate  Token  and  i   byPass Login  Page 

i  search  in  \alfresco-ng2-components-master\demo-shell-ng2\node_modules\ng2-alfresco-core\src\services  location AlfrescoAuthentication.service  file 

login(username: string, password: string) {
	console.log(login);
        return Observable.fromPromise(this.callApiLogin("admin", "admin"))
            .map((response: any) => {
                this.saveTickets();
                return {type: this.alfrescoSetting.getProviders(), ticket: response};
            })
            .catch(this.handleError);
    }

    /**
     * Initialize the alfresco Api with user and password end call the login method
     * @param username
     * @param password
     * @returns {*|Observable<any>}
     */
    private callApiLogin(username: string, password: string) {
        return this.alfrescoApi.login("admin", "admin");
    }

But  its  Still  having  403  un-authorize

**Comment by eromano** [comment]
Hi @vikashsingh005 ,
I don't suggest you to modify the components in node modules otherwise you will not able to update it in future but instead you can write something like the script below :
For future help if is not a bug I suggest you to use the gitter cahnnel https://gitter.im/Alfresco/alfresco-ng2-components
```javascript 
import { NgModule, Component, Input, OnInit } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { CoreModule, AlfrescoSettingsService, AlfrescoAuthenticationService, StorageService } from 'ng2-alfresco-core';

@Component({
    selector: 'alfresco-app-demo',
})
class AppDemo implements OnInit {

    authenticated: boolean;

    ecmHost: string = 'http://127.0.0.1:8080';

    ticket: string;

    constructor(private authService: AlfrescoAuthenticationService,
                private settingsService: AlfrescoSettingsService,
                private storage: StorageService) {

        settingsService.ecmHost = this.ecmHost;
        settingsService.setProviders('ECM');

        if (this.authService.getTicketEcm()) {
            this.ticket = this.authService.getTicketEcm();
        }
    }

    ngOnInit() {
        this.login();
    }

    login() {
        this.authService.login('admin', 'admin').subscribe(
            ticket => {
                console.log(ticket);
                this.ticket = this.authService.getTicketEcm();
                this.authenticated = true;
            },
            error => {
                console.log(error);
                this.authenticated = false;
            });
    }
}

@NgModule({
    imports: [
        BrowserModule,
        CoreModule.forRoot()
    ],
    declarations: [ AppDemo ],
    bootstrap:    [ AppDemo ]
})
export class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);

```
