### ISSUE TITLE
Get the correct node path for a normal user

### ISSUE THREAD

**Issue by chris-equis** [Alfresco/alfresco-ng2-components#1280]
When getting a node path (with getNodePath()) in [DocumentList component](https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-alfresco-documentlist/src/components/document-list.ts#L282) there’s a part of the path that’s being trimmed, “/Company Home”.

This works only for an admin user, but for another user, e.g. user1 the path is a bit different, “/Company Home/User Homes/User1” that needs to be trimmed too in order to create a the correct relative path.

Requesting nodes with relativePath=/User Homes/User1/Folder doesn’t work at all since the relative path should be "/Folder".

**Comment by DenisVuyka** [comment]
I think we need navigation based on node IDs rather than relative paths. We already have support for ID-based navigation, the click/double-click behaviours might need updates.
