### ISSUE TITLE
Folder suggestions only appear after five characters are entered

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1293]
1. Create a new folder with name more than five characters
2. Search for folder by only entering four characters (same as that when searching for files)

**Expected results**
Files and folder suggestions are shown after four characters are entered

**Actual results**
Only files are listed in the suggestions until a further character is entered

**Comment by wabson** [comment]
Only whole tokens are matched by the search API, so entering 'turbin' for example will not match a file 'turbine.jpg'. If I create a folder called 'tst' and then search for it after a few seconds then it comes back OK. So I think this is a red herring.

The new search API has more options than the simple node queries we do today but we don't currently use this.

**Comment by wabson** [comment]
@magemello @hashraf88 I think this can be closed based on feedback above
