### ISSUE TITLE
User info doesn't adapt to a mobile devices viewport

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#1296]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

<img width="494" alt="screen shot 2016-12-16 at 09 37 36" src="https://cloud.githubusercontent.com/assets/1030050/21258133/8c48f3b8-c373-11e6-8be2-03f992a04146.png">

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by hashraf88** [comment]
Fine in mobile devices, however not tablet devices e.g.  ipad, ipad pro

**View in tablets**
<img width="233" alt="screen shot 2016-12-16 at 15 47 46" src="https://cloud.githubusercontent.com/assets/13200338/21268515/112bdfb8-c3a7-11e6-87f2-40088c8c98de.png">

Also on mobile devices the background image for BPM is a little short

**View in mobile devices**
<img width="373" alt="screen shot 2016-12-16 at 15 50 08" src="https://cloud.githubusercontent.com/assets/13200338/21268625/74b4afd8-c3a7-11e6-956b-cb40fdbc8038.png">
