### ISSUE TITLE
Loading Bar doesn't appear anymore

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#1297]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**

Loading text is present but the bar id disappeared 
<img width="424" alt="screen shot 2016-12-16 at 09 43 12" src="https://cloud.githubusercontent.com/assets/1030050/21258299/3ef11bee-c374-11e6-8f65-ad0080e0d85f.png">

**Expected behavior:**

Loading text and loading bar should be present 

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
I assume that's because MDL is not part of the same bundle as the main app
