### ISSUE TITLE
Improve the process variables evaluation

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#1301]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
The form elements are not evaluated in a successive form.
In the visibility service - also the process variable call doesn't go through the js api #588 
**Expected behavior:**
At the moment a form element can be evaluated for the visibility event in the next forms. This is possible because the form elements are passed via process variables.

**Steps to reproduce the issue:**

**Component name and version:** 
ng2-activiti-form

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by hashraf88** [comment]
Visibility is now fixed however when starting the below process the process completes when at least 2 user tasks should be started. 

[Risk Limit Management.zip](https://github.com/Alfresco/alfresco-ng2-components/files/659386/Risk.Limit.Management.zip)

Is this fix only for the visibility conditions or more?

**Comment by VitoAlbano** [comment]
@hashraf88 This is a fix only for the visibility. The problem you are having about the completed process is caused by the wrong outcome provided in the start form. This will be fixed with another PR
