### ISSUE TITLE
Process not displayed in process list when using activiti enterprise api 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1308]
Beacuse there is no appid within the activiti enterprise api only the activiti private api can be used to create a process. 

https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-activiti-rest-api/docs/ProcessApi.md#startNewProcessInstance

Using activiti enterprise api
1. Select an app
2. Create a new process

**Expected results**
Process is dislayed in process list

**Actual results**
Process not displayed in process list 
Process does however display in the process list of the task app because the appId is null and so all are displayed

**Comment by magemello** [comment]
The problem is not given by the api, they have the same behaviour. We are passing the wrong data for the following fields : name, ended and variables.
