### ISSUE TITLE
Regardless of user logged in as only ECM user info is displayed

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1317]
Login with ECM and BPM or only BPM and only ECM user info is displayed. 

IE 11 only, fine on IE10. 
<img width="568" alt="screen shot 2016-12-16 at 16 01 20" src="https://cloud.githubusercontent.com/assets/13200338/21269008/e7fbf432-c3a8-11e6-891d-ac1311f2866e.png">

**Comment by magemello** [comment]
Can you test it again linking the latest version of the js-api?

**Comment by hashraf88** [comment]
Can no longer reproduce.
