### ISSUE TITLE
Long comments not displayed in task details

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1324]
Long comment on tasks are cut short 

<img width="312" alt="screen shot 2016-12-16 at 17 59 37" src="https://cloud.githubusercontent.com/assets/13200338/21273012/7edf0bae-c3b9-11e6-911d-5107ff16b0f8.png">

<img width="288" alt="screen shot 2016-12-16 at 17 59 45" src="https://cloud.githubusercontent.com/assets/13200338/21273011/7ec8cd30-c3b9-11e6-9a56-5aca2d314375.png">

**Comment by mauriziovitale** [comment]
@hashraf88  
please, try to use long words that make sense
