### ISSUE TITLE
Process list always shows the running one after a new process is started

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#1332]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
After start a new process which will be completed afterward, the process list shows the wrong tab 

**Expected behavior:**
After start a new process which will be completed afterward, the process list should show the just completed process.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by jdosti** [comment]
After starting a new process, the "Process Details" table doesn't show the details of the process that was just created.

<img width="508" alt="screen shot 2017-01-16 at 15 45 55" src="https://cloud.githubusercontent.com/assets/24432311/21989473/e73913e6-dc02-11e6-8b67-ad883052f05c.png">

The process details are only shown on the "Running", "All" and "Completed" (If the process is completed) sections.

<img width="1388" alt="screen shot 2017-01-16 at 15 52 46" src="https://cloud.githubusercontent.com/assets/24432311/21989708/e37d31be-dc03-11e6-8990-063560af32c5.png">
