### ISSUE TITLE
Logout from ECM and login on BPM returns an error.

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#1342]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
Loggin out from ECM and logging in to BPM returns an error in logging in.

![screen shot 2016-12-20 at 16 52 21](https://cloud.githubusercontent.com/assets/7974125/21360097/74459f62-c6d6-11e6-9b0b-092e30cb9f24.png)

**Expected behavior:**
Loggin out from ECM and logging in to BPM should not return any error.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by VitoAlbano** [comment]
We should test even the scenario from #1343

**Comment by VitoAlbano** [comment]
this seems to be fixed.

**Comment by hashraf88** [comment]
I can still reproduce this, exact steps and results listed below,

1. Login to ECM (ECM enabled, BPM disabled, CSRF enabled)
2. Click login or logout (issue occurs regardless)
3. Enter credentials for BPM and click login (ECM disabled, BPM enabled, CSRF enabled)
**4. Notice error (same as originally reported)**
5. Click login again 
6. Navigated to home page however **no user info icon** and if **activiti is navigated to nothing is displayed**

**Comment by magemello** [comment]
Can you test it again linking the latest js-api?

**Comment by hashraf88** [comment]
Can reproduce with latest js-api

**Comment by VitoAlbano** [comment]
@hashraf88 can you please retest it? should be fixed with latest api/

**Comment by hashraf88** [comment]
Cannot reproduce with latest of js-api
