### ISSUE TITLE
Login error on ECM and BPM

### ISSUE THREAD

**Issue by mauriziovitale** [Alfresco/alfresco-ng2-components#1343]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
When you perform a ECM login and after a ECM and BPM login you receive this error: 
AlfrescoAuthentication.service.ts:216Error when logging in TypeError: Cannot read property 'basicAuth' of null
    at http://dev.londonlab.alfresco.me/vendor.006aa58ddc0591919b29.js:363:14814
    at Array.forEach (native)
    at BpmClient.n.applyAuthToRequest (http://dev.londonlab.alfresco.me/vendor.006aa58ddc0591919b29.js:363:14771)
    at BpmClient.AlfrescoApiClient.callApi (http://dev.londonlab.alfresco.me/vendor.006aa58ddc0591919b29.js:370:11057)

**Expected behavior:**
The login should be performed without error

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by VitoAlbano** [comment]
#1342 - Same problem but different scenario.
