### ISSUE TITLE
Alfresco Viewer  integration support out-of-box

### ISSUE THREAD

**Issue by venkateshm383** [Alfresco/alfresco-ng2-components#1358]
Currently  Alfresco   Viewer  having  Blank  Screen   where  it  just  show  Document  name  and  Close  Button  ,  what  we  want  is  to  support  of   Other  Functionality  of  Document  Action  which  belongs  to  particular  Doc  MetaData Object  

I  am  attaching  features Screen-shots  here
![documentpreview](https://cloud.githubusercontent.com/assets/13992946/21479836/bce07d72-cb7d-11e6-80de-2e7f9dc761b9.png)

**Comment by ohej** [comment]
The document metadata and actions should not be in the viewer component. The viewer does exactly what it's supposed to do: Previewing documents. If you need to display the metadata you can create a new component that brings in the viewer and the metadata, similar to what the Document Details page does in Share. 

We have plans to add a metadata drawer in the document list.
