### ISSUE TITLE
Activiti components demo style fix

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1360]
- remove ugly 3D borders/shadows from components
- remove useless labels from components (Task Filters, Task List, Task Details)
- fix Task Details `Assignee` field - uses `null` in the name

<img width="1417" alt="screen shot 2016-12-29 at 10 49 24" src="https://cloud.githubusercontent.com/assets/503991/21542296/b290f8e0-cdb4-11e6-9065-9c789a535d0d.png">

**Comment by magemello** [comment]
Let's park for now this kind of fix, we will review this part with the design team.

**Comment by DenisVuyka** [comment]
We need figuring out whether some CSS files got lost during bundling or this is something brought by recent refactorings.
