### ISSUE TITLE
TypeScript configs missing output directory

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1361]
All output folders gone missing in `tsconfig.json` files. That is causing lots of inline files generated (i.e. `.d.ts`) that are causing numerous build issues and branch switching.

**Comment by magemello** [comment]
Seems to be needed for the new packaging system. Maybe something to be refined there @eromano

**Comment by DenisVuyka** [comment]
Closing this issue. Once component projects are upgraded to webpack this should not be a problem.
