### ISSUE TITLE
Travis is constantly broken for the same matrix entries

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1362]
This happens for branches, job restarts no longer help.

<img width="836" alt="screen shot 2016-12-29 at 12 25 51" src="https://cloud.githubusercontent.com/assets/503991/21543871/200762bc-cdc2-11e6-8a51-5bb907dd1558.png">

**Comment by magemello** [comment]
what branch? develop and master are ok

**Comment by DenisVuyka** [comment]
you can test dev-denys-1355 and inspect it's Travis build history. It seems a Jasmine timeout issue

**Comment by DenisVuyka** [comment]
This part of the documentation might be of interest: https://jasmine.github.io/2.0/introduction.html#section-42
