### ISSUE TITLE
DocumentList fails navigating user home subfolders

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1366]
Configuration:

```ts
currentPath: string = '/';
rootFolderId: string = '-my-';
```

DocumentList component throws exception on navigating to subfolder:

**{"error":{"errorKey":"The entity with relativePath: /User Homes/<EMAIL>/screenshots was not found.","statusCode":404,"briefSummary":"11300032 The entity with relativePath: /User Homes/<EMAIL>/screenshots was not found.","stackTrace":"For security reasons the stack trace is no longer displayed, but the property is kept for previous versions.","descriptionURL":"https://api-explorer.alfresco.com"}}**

Username is a full email address.

**Comment by john-knowles** [comment]
Does this issue relate to https://github.com/Alfresco/alfresco-ng2-components/issues/1280?

**Comment by DenisVuyka** [comment]
@john-knowles probably yes, however the fix will be moving to node ID-based navigation, that solves several problems (relative paths, non-English folder names, etc).
