### ISSUE TITLE
Enhance flexibility for pooled tasks

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#1371]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```
**New feature request:**
In 0.5 a pooled task would still display the form, but you would be unable to complete it because it needs to be claimed first. In 1.0 the "Claim" button is introduced, but the form is no longer displayed.
This makes it impossible to implement a "Claim & Complete" button.

Essentially the request is the possibility to do "Claim and complete" in one single click.
The form component / task details component should have the ability to render the form for an unclaimed task. In addition, it should be possible to hook into the button behaviour before it completes the task.

**Comment by magemello** [comment]
In case someone has already claimed the task we will show an error.
