### ISSUE TITLE
Error is logged when trying to complete the Risk Process

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#1373]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [X] Bug  
- [ ] Support request
```
**Current behavior:**
Start the Risk Process (attached to this issue) 
Go on Task Approver Review Request
Select Approve and complete
Go on Task Implement Request
Select Approve and then click Implemented.
An error is triggered and the process is stucked.

**Expected behavior:**
User should be able to complete the process

**Steps to reproduce the issue:**

**Component name and version:** 

<img width="1430" alt="screen shot 2017-01-03 at 17 28 36" src="https://cloud.githubusercontent.com/assets/7974125/21616631/149ad5a0-d1da-11e6-8ee9-bb8ff0417d39.png">

[Risk Limit Management.zip](https://github.com/Alfresco/alfresco-ng2-components/files/682863/Risk.Limit.Management.zip)

**Comment by DenisVuyka** [comment]
Reproduced with former Activiti UI as well, main error is not related to Form component.

**Comment by hashraf88** [comment]
Reproduced in Activiti too, issue opened in https://github.com/Alfresco/activiti-bpm-suite/issues/3375 and will be investigated on this ticket.
