### ISSUE TITLE
Issue while testing the Demo Shell Application(Karma Syntax Error)

### ISSUE THREAD

**Issue by infad-kachancheri** [Alfresco/alfresco-ng2-components#1378]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [X] Bug  
- [ ] Support request
```
**Issue Description:**

Demo Shell Application throwing syntax error while testing the application. Install the demo shell then used 'npm test' to test the application using karma.  but its throwing '**syntax error: use of reserved word export'**. Please find screenshot for detailed error details.

**Screenshot:**

![screen03](https://cloud.githubusercontent.com/assets/20041687/21637889/fd378e20-d28e-11e6-8398-69bb33acba50.PNG)

**Comment by magemello** [comment]
I was able to reproduce the same problem with an app generated by the generator.
