### ISSUE TITLE
Process instances overview: pie and bar chart not displayed correctly

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1379]
1. Generate a process instance overview report
2. Take note of pie chart (not displayed) and bar chart (not displayed correctly)
3. Click "stacked"
4. Notice bar chart is now displayed correctly, bar chart is now displayed correctly regardless of if "stacked" is clicked or not

N.b. Fine in Chrome, Safari does not display graph at all #1380

<img width="931" alt="screen shot 2017-01-04 at 10 23 26" src="https://cloud.githubusercontent.com/assets/13200338/21639584/c3c7f6fa-d268-11e6-8778-93695d479759.png">

**Comment by mauriziovitale** [comment]
It should be fixed by the issue #1440
@hashraf88  can you test it again?
