### ISSUE TITLE
Process instances overview: process instance counts bar graph not displayed

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1380]
1. Generate a process instance overview report
2. Take note of pie chart (not displayed) and bar chart (not displayed)

N.b. Fine in Chrome, firefox issues reported in #1379

<img width="917" alt="screen shot 2017-01-04 at 10 35 03" src="https://cloud.githubusercontent.com/assets/13200338/21639733/7cb64838-d269-11e6-8cf4-ea3817892ef4.png">

**Comment by mauriziovitale** [comment]
It should be fixed by the issue #1440
@hashraf88  can you test it again?

**Comment by hashraf88** [comment]
Can reproduce on latest of development
