### ISSUE TITLE
Images not displayed in document list component demo

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1387]
When starting the document list component (outside of demo shell) the images and icons are not displayed correctly

<img width="1381" alt="screen shot 2017-01-04 at 16 19 18" src="https://cloud.githubusercontent.com/assets/13200338/21649686/78f7f5c6-d29a-11e6-87ce-b9b7e1103b98.png">

**Comment by magemello** [comment]
This issue is relative only to systemjs, and is present as well in the userinfo and login component.

**Comment by hashraf88** [comment]
On just testing the document list I can still see the same issue as originally reported
