### ISSUE TITLE
Support scoping documentlist to specific folder

### ISSUE THREAD

**Issue by davidcognite** [Alfresco/alfresco-ng2-components#1398]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```
**Component name and version:** 

ng2-alfresco-documentlist 1.0

**New feature request:**

As an application developer I would like to scope a document library to a specific root 
so that I can prevent users navigating further up the tree than is useful to them.

E.g. creating an RM file plan. The highest level the user should see is the documentlibrary folder within the RM site.

I'd like a config option to be able to specify the root of the component, rather than it having to be company home.

**Comment by DenisVuyka** [comment]
You can set any node ID for the `currentFolderId` property of the DocumentList including well-known aliases **-my-** | **-shared-** | **-root-**.
