### ISSUE TITLE
Naming convention for core component

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1405]
AlfrescoAuthentication.service.ts	->  authentication.service.ts
AlfrescoContent.service.ts	-> content.service.ts
AlfrescoSettings.service.ts	-> settings.service.ts
AlfrescoTranslation.service.ts  -> translation.service.ts
alfresco-api.service.ts -> api.service.ts
AlfrescoApi.mock.ts -> api.mock.ts

**Comment by DenisVuyka** [comment]
Current state:

<img width="263" alt="screen shot 2017-01-06 at 14 52 10" src="https://cloud.githubusercontent.com/assets/503991/21721333/c395b36c-d41f-11e6-8b12-6e5e28096c01.png">

Some of the old names are still present for backwards compatibility.

**Comment by magemello** [comment]
We are already committing breaking changes in the next versions.
