### ISSUE TITLE
Refresh icon on a start form not working

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1411]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ x] Bug  
- [ ] Support request
```
**Current behavior:**
A refresh icon is shown on a start form at the moment. However upon clicking it is not doing anything on a start form.

**Expected behavior:**
For a task form it refreshes the data which is available in the database. Since a start form cannot be saved, there is no data to be refreshed. However it would be a good idea to clear all the data upon the click of a refresh in a start form.

**Steps to reproduce the issue:**
Start a process with a start form and observe this on start form

**Component name and version:** 
ng2-activiti-form v1.0.0

**Browser and version:** 
All

**Comment by hashraf88** [comment]
It seems now when clicking refresh on a form within start event the application can crash i.e. no other navigation within the component can occur.

**app used to test**
[all widgets.zip](https://github.com/Alfresco/alfresco-ng2-components/files/694191/all.widgets.zip)

**video of steps**
[refresh start form.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/694188/refresh.start.form.mp4.zip)

**Comment by hashraf88** [comment]
Cannot reproduce above on latest of development
