### ISSUE TITLE
Investigate and reduce webpack bundle sizes

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1412]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**

**Expected behavior:**

Investigate output sizes for webpack setups (demo shell, separate components).
Optionally provide integration/scripts for the [source-map-explorer](https://www.npmjs.com/package/source-map-explorer) tool. 
Try reducing production build size as much as possible.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by magemello** [comment]
test comment

**Comment by DenisVuyka** [comment]
`vendors.js` file for Demo Shell

<img width="1431" alt="screen shot 2017-01-09 at 15 32 08" src="https://cloud.githubusercontent.com/assets/503991/21772037/99073aee-d681-11e6-868f-102fb772d8c1.png">

**Comment by DenisVuyka** [comment]
Maybe we consider splitting `alfresco-js-api` into separate ECM and BPM client libs to reduce bundle size?

**Comment by DenisVuyka** [comment]
We have fixed minification, and greatly improved bundle sizes by removing comments from the code.
