### ISSUE TITLE
Tabs not displayed in completed start form

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1413]
1. Start a process that has a form attached to its start event, ensure form has more than one tab 
2. Complete start event
3. Complete process
4. Go to 'completed' filter
5. Go to completed start form 

**Expected results**
All tabs should be displayed

**Actual results**
Only first tab is displayed correctly

<img width="627" alt="screen shot 2017-01-09 at 11 24 25" src="https://cloud.githubusercontent.com/assets/13200338/21765118/b9ce83e0-d65e-11e6-9d37-115ef4d5679c.png">

**Comment by VitoAlbano** [comment]
@hashraf88 it seems to be fixed now, can you retest it please?

**Comment by hashraf88** [comment]
The above is actually due to #1491 which will not track investigation
