### ISSUE TITLE
No processes are displayed when starting process within task app

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1416]
1. Go to task app
2. Go to processes
3. Start a process

**Expected results**
List of avaliable processes are displayed 

**Actual results**
No  processes are displayed

N.b. processes display within individual apps

<img width="576" alt="screen shot 2017-01-09 at 11 50 07" src="https://cloud.githubusercontent.com/assets/13200338/21765758/bb52885c-d662-11e6-865d-0ee686d29adc.png">

**Comment by DenisVuyka** [comment]
`Tasks` app should be listing and starting all available processes (in all deployed apps) in the dropdown list.
