### ISSUE TITLE
Clicking on a completed task within a process navigates to tasklist

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1420]
1. Complete a process (ensure at least 1 user task with form is completed)
2. Go to processes > completed processes filter
3. Click on completed task

**Expected results**
Dialog shown displaying completed 

**Actual results**
Navigated to tasklist within activiti component

**Comment by VitoAlbano** [comment]
@hashraf88 - this is not a bug, this is happening to replicate the same activiti behaviour and it is changed after the dialog refactoring.
I'll put it in done because this is as intended

**Comment by hashraf88** [comment]
@VitoAlbano this is a duplicate of #1431 , I will close this issue as #1431 has more detail
