### ISSUE TITLE
activiti-processlist component uses TaskQueryRequestRepresentationModel to build request

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1422]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
Currently it works, however when I look at the source code it doesn't make sense to use a TaskQuery representation for process instance query! Wondering if this needs to be fixed, raising an issue anyway!

**Expected behavior:**
Process Instance query request to be built from a process query representation model.

**Component name and version:** 
ng2-activiti-processlist v1.0.0

**Browser and version:** 
all

**Comment by cijujoseph** [comment]
I was looking at the commits. The issue I raised was to do with the use of "TaskQueryRequestRepresentationModel" in activiti-processlist.component.ts component. Good that the filter representation is fixed, however the query model also needs to be fixed!.

**Comment by wabson** [comment]
Hi @cijujoseph I checked `activiti-processlist.component.ts` again and on the `development` branch there are no imports of any tasklist classes in that [file](https://github.com/Alfresco/alfresco-ng2-components/blob/development/ng2-components/ng2-activiti-processlist/src/components/activiti-processlist.component.ts).

Could you point to the location where you see this usage?

**Comment by cijujoseph** [comment]
Sorry Will. I was looking at the wrong branch! Sorry again!

**Comment by cijujoseph** [comment]
I was looking at the commited files linked to this issue!
