### ISSUE TITLE
Allow customisation of activiti-process-instance-list data table

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1423]
**Type of issue:**  (check with "[x]")
```
- [x ] New feature request
- [ ] Bug  
- [ ] Support request
```
**New feature request:**
 I’m trying to configure the columns in the process list datatable (activiti-process-instance-list component). Currently I’m able to display only Id, Name and Started values in my table. All the other attributes of process instance model are getting filtered in createDataRow()

Also, is it possible to add an extra input "includeProcessVariables" for this component. It is fine to set it to false by default, however if I can get process variables as part of my response, this would allow the use of process variables in my data table.

**Comment by mauriziovitale** [comment]
Should be fixed with 
#1625
