### ISSUE TITLE
It takes at least 1 hour to rebuild all components

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1425]
Process of cleaning and rebuilding all components (i.e. linking demo shell scenario) takes at least 1 hour.

| script | time |
| --- | --- |
| npm-clean.sh | ±6m |
| npm-link-demo-shell.sh | ± 52m |

**Comment by eromano** [comment]
can we move it in done as part of https://github.com/Alfresco/alfresco-ng2-components/issues/1588 ?

**Comment by DenisVuyka** [comment]
Yes, moved to done.
