### ISSUE TITLE
Process instances overview: Bar and pie charts are too large 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1439]
<img width="1015" alt="screen shot 2017-01-11 at 13 58 09" src="https://cloud.githubusercontent.com/assets/13200338/21851249/21daec6e-d806-11e6-8bde-f2cae210c738.png">
<img width="1430" alt="screen shot 2017-01-11 at 13 57 27" src="https://cloud.githubusercontent.com/assets/13200338/21851250/21f575ca-d806-11e6-9aca-d3ea99e50b06.png">

**Comment by mauriziovitale** [comment]
It should be fixed by the issue #1440
@hashraf88 can you test it again?

**Comment by hashraf88** [comment]
Issue is now in Chrome
