### ISSUE TITLE
Spaces required on DataTable title on homepage.

### ISSUE THREAD

**Issue by jdosti** [Alfresco/alfresco-ng2-components#1442]
<img width="690" alt="screen shot 2017-01-12 at 10 23 19" src="https://cloud.githubusercontent.com/assets/24432311/21885846/5cd983ba-d8b1-11e6-9f9e-d8dacae66b92.png">

There should be spaces in DataTable title, should read 'DataTable - ECM & BPM'.

**Comment by magemello** [comment]
We choose to have it like that to avoid to enlarge the container.
