### ISSUE TITLE
Permissions need to be taken into consideration when using Node ID/virtual folder-based navigation for document list 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1446]
If I have 2 users (user A and user B) and map the currentFolderId to a folder that can only be seen by user A (using node ID or virtual folder (-my- or -root-)) both user A and user B have the same ‘landing page’ in the document list however user B shouldn’t be able to see this and can trail back using breabcrumbs to files/folders they shouldn’t have access to.

1. Create 2 users in Alfresco (User A and User B)
2. Create a folder within User A's account
3. Add a file into this folder
4. Get node ID of this folder
5. Within .../demo-shell-ng2/app/components/files set to node ID e.g.
`[currentFolderId]="'5c28024d-54ea-4831-800f-648c414fbe91'"`
6. Login as User B (who has no files or flders uploaded) and go to document list

**Expected results**
1) Can not access other users files and folder
2) Can not navigate around other users files and folders using breadcrumbs
3) "Permission denied" message of some sort (optional)
4) A default 'landing page' if another users folder has been set (optional)

**Actual results**
1) Can access other users files and folder
2) Can navigate around other users files and folders using breadcrumbs
3) Can not upload files or create new folder 

**Current error in console when trying to create a folder or upload file in other users account**
<img width="1173" alt="screen shot 2017-01-12 at 15 21 18" src="https://cloud.githubusercontent.com/assets/13200338/21897245/ea9cad60-d8e0-11e6-8e2c-13cf7232e171.png">

N.b. 
-shared- is not applicable as is a shared folder seen by all users

**Comment by wabson** [comment]
I can't reproduce this with two normal users, when logging in as the second user and clicking on *DocumentList* in the main nav I get presented with an error indicating that permission (to view the folder) was denied.

<img width="1415" alt="screen shot 2017-01-16 at 12 22 04" src="https://cloud.githubusercontent.com/assets/1727487/21983054/252aeea2-dbe7-11e6-86ca-2ab085deb3b1.png">

Did you use admin as one of the users? That user is 'special' and has their *home space* set to the root *Company Home* folder, which all other users can see. Other users get their own home space created under *User Homes* and only they get given permission to view that folder and anything within it.

**Comment by hashraf88** [comment]
1. Can not access other users files and folder **Retested and this is not the case**
2. Can not navigate around other users files and folders using breadcrumbs **Due to lack of understanding of Share**
3. "Permission denied" message of some sort **Will be investigated in #1518, #1519 and #1520**
4. A default 'landing page' if another users folder has been set **Due to lack of understanding of Share**
