### ISSUE TITLE
Activiti Form fields are not aligned correctly

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1454]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
```
**Current behavior:**
In a multicolumn view, the form fields of different types are not well aligned horizontally.

**Expected behavior:**
Expecting the form components to align the form fields correctly as it does in OOTB activiti-app. Understand that it could be difficult to align few field types like Multiline Text. However fields like dropdown, date etc should align correctly.

**Steps to reproduce the issue:**
Design a form with different field types in a two column layout. View the form in ADF demo app. 
Please find attached two screenshots (one from ADF App and another from OOTB Activiti UI)
<img width="908" alt="screen shot 2017-01-12 at 3 08 43 pm" src="https://cloud.githubusercontent.com/assets/2080360/21908551/c6a56994-d8d9-11e6-8d14-2b1c70c3e3ca.png">
<img width="1375" alt="screen shot 2017-01-12 at 3 08 17 pm" src="https://cloud.githubusercontent.com/assets/2080360/21908552/c6a98baa-d8d9-11e6-8d7a-fef7b7123513.png">

**Component name and version:** 
ng2-activiti-form v1.0.0

**Browser and version:** 
possibly in all (tested just in Chrome)

**Comment by jdosti** [comment]
The alignment is not correct when both:
a) left and right container do not contain widgets that do not take up the same amount of space and 
b) widgets are ‘merged’ into one container

<img width="786" alt="screen shot 2017-01-25 at 14 44 04" src="https://cloud.githubusercontent.com/assets/24432311/22294913/00c09df0-e30d-11e6-93aa-872f0dafe40a.png">

**Comment by VitoAlbano** [comment]
#1687 - added a fix with this PR
