### ISSUE TITLE
Setting showTitle=false not hiding the icon

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1455]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
```
**Current behavior:**
Setting the showTitle flag on activiti-form component, hides the title text. The material icon remains there. Shouldn't that be applied on the parent div so that both gets hidden if set to false?

**Expected behavior:**
Expected both the material icon and title text to be hidden on setting showTitle to false

**Steps to reproduce the issue:**
Open a task form with showTitle=false

**Component name and version:** 
activiti-form component in ng2-activiti-form v1.0.0

**Browser and version:** 
all

**Comment by DenisVuyka** [comment]
In fact this icon shows form validation status and is not part of the title. However we can introduce a separate flag to toggle it, i.e. `showValidationIcon=true|false` with `true` by default.
