### ISSUE TITLE
Inconsistent handling of process with `null` name

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#1461]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
```
**Current behavior:**
A process instance which completes straight away never gets its supplied name set (see Alfresco/activiti-bpm-suite#3362. The processlist components handle this `null` value in different ways, but we should decide on the correct way and apply this consistently.

<img width="1377" alt="screen shot 2017-01-13 at 12 05 33" src="https://cloud.githubusercontent.com/assets/1727487/21929672/eba68312-d989-11e6-8c13-38f2053ce3a7.png">

**Expected behavior:**

A default name should be generated from the process definition name and the creation time, in the event of the `name` property being `null`, similar to the Angular1 app. This should be displayed in the process instance list and also as the content of the heading inside the process instance detail component.

**Steps to reproduce the issue:**

1. Create a new process instance that has no user tasks in it and which therefore will complete straight away and give it a name
2. Click the 'Completed' process filter and observe how the name is shown in the process instance list (*No name*) vs in the title of the process instance detail component (text *null* is displayed)

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by jdosti** [comment]
When completing a process instance that has no user tasks, Process List and Process Details should display the name given in the process when started.

The Date next to the process name is not needed.

**Comment by wabson** [comment]
@jdosti the name value is not applied due to a bug on the server-side. This issue concerns what we do in the ADF in this case, from the description above:

> A process instance which completes straight away never gets its supplied name set (see Alfresco/activiti-bpm-suite#3362

**Comment by hashraf88** [comment]
@magemello should we wait for Alfresco/activiti-bpm-suite#3362 to be resolved before closing this issue or close earlier?

**Comment by wabson** [comment]
On the Safari issue it seems we have problems throughout the processlist components and also in the documentlist with rendering dates as the following screenshots show.

I'd suggest we open separate issues for that, and close this one since on all other browsers the issue is fixed and the date-formatting problems that do exist on Safari pre-date this issue.

<img width="1391" alt="screen shot 2017-01-24 at 15 59 23" src="https://cloud.githubusercontent.com/assets/1727487/22255131/6bac5844-e24e-11e6-855a-83d84c5fbe1c.png">
<img width="1388" alt="screen shot 2017-01-24 at 15 59 38" src="https://cloud.githubusercontent.com/assets/1727487/22255135/6f884acc-e24e-11e6-9be5-fececf7ca6ab.png">
<img width="1417" alt="screen shot 2017-01-24 at 15 58 07" src="https://cloud.githubusercontent.com/assets/1727487/22255125/682d68b6-e24e-11e6-878b-dc26898b9c99.png">
<img width="677" alt="screen shot 2017-01-24 at 16 04 38" src="https://cloud.githubusercontent.com/assets/1727487/22255296/de81a7a2-e24e-11e6-9e93-5cbb935c71f7.png">
