### ISSUE TITLE
A completed form to show only the outcome that the user has selected upon completion

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1467]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
```
**Current behavior:**
A completed form (read-only) showing all the outcomes on the form

**Expected behavior:**
A completed form to show only the outcome that the user has selected upon completion.

**Steps to reproduce the issue:**
Complete a task form with two outcomes (eg: Approve, Reject).
An active task should show three buttons - Save, Approve and Reject. This is working fine.
Once the task is completed and when I open the completed task I should see only one button (either Approve or Reject). Currently it shows all three buttons.

**Component name and version:** 
activiti-task-details (ng2-activiti-tasklist) and activiti-form (ng2-activiti-form)

**Browser and version:** 
all

**Comment by jdosti** [comment]
The outcome is not displayed on a form attached to a start event.

<img width="608" alt="screen shot 2017-01-19 at 11 49 08" src="https://cloud.githubusercontent.com/assets/24432311/22105810/bb46f02c-de3d-11e6-94ec-6fda4c1cb426.png">

<img width="741" alt="screen shot 2017-01-19 at 11 49 55" src="https://cloud.githubusercontent.com/assets/24432311/22105933/5c2928b6-de3e-11e6-9428-074afb5a10cd.png">

**Comment by mauriziovitale** [comment]
@jdosti did you get the latest from development?
I can see the "Start process" button.
<img width="702" alt="screen shot 2017-01-23 at 17 59 52" src="https://cloud.githubusercontent.com/assets/14923305/22216157/d877503c-e195-11e6-9a65-ec397d206539.png">
