### ISSUE TITLE
Task Header in TaskDetails component shows Assignee, DueDate but are not working

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1473]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ x] Bug  
- [ ] Support request
```
**Current behavior:**
The task header in activiti-task-details (ng2-activiti-tasklist) shows Assignee, DueDate and Form as a clickable link in blue. However there are not!
<img width="1383" alt="screen shot 2017-01-13 at 12 33 00 pm" src="https://cloud.githubusercontent.com/assets/2080360/21941401/397ff4d4-d98e-11e6-8a6d-f5157604b995.png">

**Expected behavior:**
Should have necessary api integration to Assignee and DueDate. In activiti-app, there is a Show Form/ShowDetails toggle available which I think should appear in ADF too instead of just formName. The other option is to have the ShowForm/ShowDetails button in addition to the current FormName.

When implementing this it would also be nice to have a read-only configuration option on these items. The use case is: some customers may not want the task assignees to re-assign the task or change the due date. Though that is the current default view, the blue colour could make people think that it is an actionable link!

**Steps to reproduce the issue:**
Open a task form via activiti-task-details component.

**Component name and version:** 
activiti-task-details (ng2-activiti-tasklist) v1.0.0

**Browser and version:** 
all

**Comment by magemello** [comment]
Hi Ciju, from my tests they are blue but not clickable....

**Comment by cijujoseph** [comment]
Hi Mario, Agree, it may not be a bug. But I think it is confusing where the text appears to be clickable. Why are they blue when they are not clickable?

**Comment by magemello** [comment]
Ciju, we will review it with our design team. For now blue doesn't imply clickable unless the you have a pointer click.

**Comment by magemello** [comment]
won't fix until we have the new design in plae

**Comment by eromano** [comment]
This issue will be focused only on api integration to Assignee and DueDate .As in the activiti-app should be possible assigne the task to another user and change the dueDate.
