### ISSUE TITLE
ECM username only has to be 2 characters long, login component requires 4 characters

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1480]
ECM username only needs 2 characters to be entered whereas the login component requires 4 characters to be entered

**ECM**
![screen shot 2017-01-16 at 12 24 35](https://cloud.githubusercontent.com/assets/13200338/21983044/1b272cd6-dbe7-11e6-96b0-66f7c8e3440b.png)

**Component**
![screen shot 2017-01-16 at 12 27 35](https://cloud.githubusercontent.com/assets/13200338/21983065/2e7e7960-dbe7-11e6-9eba-76ccde991431.png)

**Comment by jdosti** [comment]
The message on Demo Shell needs to change. 

<img width="349" alt="screen shot 2017-01-18 at 14 56 50" src="https://cloud.githubusercontent.com/assets/24432311/22068969/a34893e0-dd8e-11e6-8b71-5aa9bf9440fb.png">

This is the correct message.

<img width="298" alt="screen shot 2017-01-18 at 14 57 16" src="https://cloud.githubusercontent.com/assets/24432311/22068985/b1000518-dd8e-11e6-88e8-181284eebc07.png">
