### ISSUE TITLE
"Attach a Form" dropdown should be displayed as 'None' when starting a Task.

### ISSUE THREAD

**Issue by jdosti** [Alfresco/alfresco-ng2-components#1481]
1. Go to Tasks.
2. Start a new Task.

**Expected Results**
On Attach a Form section ‘None’ is selected by default on dropdown.

<img width="308" alt="safari" src="https://cloud.githubusercontent.com/assets/24432311/21983568/de1a2f8e-dbe9-11e6-9f32-2a03ba1aed25.png">

**Actual Results**
"None" is not selected by default on dropdown in Chrome, Firefox and Opera. Works fine in Safari.
<img width="309" alt="chrome" src="https://cloud.githubusercontent.com/assets/24432311/21983596/f988aa7a-dbe9-11e6-93c3-2310f35ba4f9.png">

**Comment by hashraf88** [comment]
- [ ] Forms (start forms)
- [ ] Forms (user tasks)
- [ ] Forms (completed forms) 
- [ ] Analytics
- [ ] Attach form in create task dialog
- [ ] Process list
