### ISSUE TITLE
Upgrade Health Care App to Adf 1.0

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#1489]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by magemello** [comment]
Tracked here: https://github.com/Alfresco/health-care-app/issues/11
