### ISSUE TITLE
Attached files are not displayed on a completed task or start form

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1490]
File name and preview (if avaliable) not displayed
**Firefox**
<img width="699" alt="screen shot 2017-01-17 at 12 18 54" src="https://cloud.githubusercontent.com/assets/13200338/22020341/a4302654-dcaf-11e6-8e70-9e5707d3ccbd.png">

**Chrome**
![screen shot 2017-01-17 at 12 27 27](https://cloud.githubusercontent.com/assets/13200338/22020466/533649b2-dcb0-11e6-8d98-47574f1cd9b2.png)

**Safari**
<img width="401" alt="screen shot 2017-01-17 at 12 28 06" src="https://cloud.githubusercontent.com/assets/13200338/22020481/6c17d126-dcb0-11e6-8db0-e13fdcfab642.png">

**Comment by hashraf88** [comment]
Linked to #1491

**Comment by mauriziovitale** [comment]
@hashraf88  can you retest it? The issue should be fixed by #1236

**Comment by hashraf88** [comment]
Will be tracked in #1236
