### ISSUE TITLE
App freezes if accessing a completed form (start event or user task) that includes attach widget

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1491]
1. Include an attach widget to a form (user task or start event)
2. Attach a file
3. Complete task
4. Navigate to completed task 

**Expected results**
Can navigate around 

**Actual results**
App freezes and error occurs

![screen shot 2017-01-17 at 12 38 14](https://cloud.githubusercontent.com/assets/13200338/22020750/d782ae26-dcb1-11e6-8788-c12fa81086fb.png)

```
EXCEPTION: Error in ./DisplayValueWidget class DisplayValueWidget - inline template:75:63 caused by: Cannot read property 'bpmHost' of undefined
ORIGINAL EXCEPTION: Cannot read property 'bpmHost' of undefined
TypeError: Cannot read property 'bpmHost' of undefined
```

**Comment by mauriziovitale** [comment]
@hashraf88 The problem should be fixed with this commit https://github.com/Alfresco/alfresco-ng2-components/commit/47ea6e569594753c3c13736d2eb47a2d8d35cd2d

**Comment by hashraf88** [comment]
Above resolve, other issues around upload widget reported in #1531
