### ISSUE TITLE
A text field's "Advanced Tab" settings are not reflected in activiti-form in ADF

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1501]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
```
**Current behavior:**
A text field's "Advanced Tab" settings are not reflected in activiti-form in ADF. For example, I have configured a text field's "input mask" and "input mask placeholder" properties and please find attached the screenshots. 

**Form Field Configuration**
<img width="841" alt="screen shot 2017-01-18 at 12 03 08 pm" src="https://cloud.githubusercontent.com/assets/2080360/22076676/b3c58894-dd76-11e6-84e3-3a69290deae2.png">

**This is how it looks in Activiti-App at runtime**

<img width="893" alt="screen shot 2017-01-18 at 12 00 48 pm" src="https://cloud.githubusercontent.com/assets/2080360/22076674/b3c1fe36-dd76-11e6-8fca-36308a3c96a6.png">

**This is how it looks in an ADF APP**

<img width="1369" alt="screen shot 2017-01-18 at 12 02 11 pm" src="https://cloud.githubusercontent.com/assets/2080360/22076675/b3c42c92-dd76-11e6-927f-9a186ee3e7bd.png">

**Expected behavior:**
Expected those "input mask" and "input mask placeholder" settings reflected in ADF component

**Component name and version:** 
ng2-activiti-form.

**Browser and version:** 
tested in Chrome,  possibly in all!

**Comment by magemello** [comment]
Hi @cijujoseph can you provide more details?

**Comment by cijujoseph** [comment]
Hi @magemello, the details are attached in the issue description (three images):

The first image under the heading "Form Field Configuration" is the Advanced Configuration I did on Contact Number. Please check the Input Mask and Input Mask PlaceHolder configurations on the field.
The second image is under the heading "This is how it looks in Activiti-App at runtime" is how the field appears in activiti-app. Please check the two contact number fields and its appearance when there is data and when empty(placeholder)

The third image is under the heading "This is how it looks in an ADF APP" is how the field appears in ADF app. Please check the two contact number fields where those configurations are not reflected.

**Comment by DenisVuyka** [comment]
Input masks are not yet supported due to absence of Material Design specs and corresponding JS/angular components for the moment of creating the corresponding widgets.

**Comment by DenisVuyka** [comment]
Custom date formats are not yet supported as well btw.

**Comment by magemello** [comment]
Unless there is a date to have this functionality in material design, we may have to consider to develop this functionality by our own.

**Comment by DenisVuyka** [comment]
It's a point of searching the right component. As angular 2 is released more and more components get released. Here's a possible candidate for input masks for instance: https://github.com/text-mask/text-mask
