### ISSUE TITLE
When you go on to the tag page initially and enter a tag name the placeholder remains.

### ISSUE THREAD

**Issue by jdosti** [Alfresco/alfresco-ng2-components#1506]
1. Enter text into tag text field.

**After refreshing the page the placeholder works fine.** 

**Expected Results**
When entering a tag name the placeholder should disappear.

<img width="338" alt="screen shot 2017-01-20 at 15 51 58" src="https://cloud.githubusercontent.com/assets/24432311/22155736/6c46aecc-df28-11e6-8e80-788cc3fb79b1.png">

**Actual Results**
After entering text into tag name text field the placeholder remains. 

<img width="351" alt="screen shot 2017-01-20 at 15 04 57" src="https://cloud.githubusercontent.com/assets/24432311/22154462/9003228c-df23-11e6-936a-7d56c6e570d1.png">

**Comment by hashraf88** [comment]
I can reproduce on latest of development.

[tag.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/803485/tag.mp4.zip)
