### ISSUE TITLE
When creating/deleting a Tag it's not updated on "Tag list By Node ID" table immediately.

### ISSUE THREAD

**Issue by jdosti** [Alfresco/alfresco-ng2-components#1507]
1. Add/delete a tag from your Tag list.

**Expected Results**

The tag that was added/deleted it is updated immediately on "Tag list By Node ID" table.

**Actual results**

The tag that was added/deleted it's not updated immediately on "Tag list By Node ID" table. After refreshing the page the tag is updated.

**Comment by eromano** [comment]
Now with this PR the list are refreshed anyway because some latency in the content service the list of all ECM tags could be not refreshed immediately.
