### ISSUE TITLE
When a tag has zero references it shouldn't be shown on the list of tags.

### ISSUE THREAD

**Issue by jdosti** [Alfresco/alfresco-ng2-components#1508]
The list of tags should be the same within ECM and the list within tag components. 
Tags that have zero reference to a file/folder are not shown in ECM however are in the component.

1. Add a tag (ensure a valid ID is entered).
2. Remove the tag.

**Expected Results**

The tag is removed from the "List Tags ECM".

<img width="138" alt="screen shot 2017-01-20 at 17 10 30" src="https://cloud.githubusercontent.com/assets/24432311/22158263/6357a1f8-df33-11e6-9a63-1a3bd79c7ba3.png">

**Actual Results**

The tag is still on the "List Tags ECM".

<img width="185" alt="screen shot 2017-01-20 at 17 10 14" src="https://cloud.githubusercontent.com/assets/24432311/22158269/693ab696-df33-11e6-8020-69d1031b4a79.png">

**Comment by eromano** [comment]
This information is not still available on the rest API.
I opened a new issue on the repo side https://issues.alfresco.com/jira/browse/REPO-2247
we have to wait the next releases
