### ISSUE TITLE
Permission  Require   to  Upload  File  and  Folder after  Changes  Node  based  Navagation

### ISSUE THREAD

**Issue by vikashsingh005** [Alfresco/alfresco-ng2-components#1510]
Currently   Node  based   Navigation   features  Working   Fine  with  Implemented  Node  id  or  fixed  Folder  name,But   its   only   work   for  admin   user  .If  we  have   some  Other  User  who   don,t  have   Admin  Permission   then theyn   dont   have  Permission  to  Perform  Either  File  or  Folder  Upload

please   find   below   screen-shots

![image](https://cloud.githubusercontent.com/assets/7962189/22182055/4efa9a32-e0c1-11e6-98da-e7c7a3edee5f.png)

**Comment by DenisVuyka** [comment]
Here's the workflow I was using to test this issue:

- Create regular account in Share admin tools
- Log in as a new user
  * ensure I can't upload anything to `/Sites/swsdp` via Share UI
  * ensure I can't upload anything to `/Sites/swsdp` via ADF UI
- Log in as `admin` and add newly created user as `Site Contributor` for the `/Sites/swsdp`
  * ensure I can upload files via Share UI (including subfolders)
  * ensure I can upload files via ADF UI (including subfolders)

**Comment by hashraf88** [comment]
Closing, please see #1446 for further investigation that will occur around this area.
