### ISSUE TITLE
upload dialog  Wrong  number   on  File  Upload  Count

### ISSUE THREAD

**Issue by vikashsingh005** [Alfresco/alfresco-ng2-components#1511]
Currently   File  Upload  Count  Value   is   Taking    from  Internal  Queus,where Each  file  is   in  Queue ,When Ever I   have  Uploaded  new  File  or  Folder  its  always  Display  Count  from  Previous  File  

for  Example:  Lets  say  i  have  uploaded 1   file  and  Close File-Dialogue After  that  i  have   upload  a  Folder So.  it  should   display  Current  Progress  i.e 1  but   Currenly  it  showing 2  one  for  Previous  File  and  1  For  Folder

**Comment by magemello** [comment]
@vikashsingh005 please next time keep the template :)

**Comment by hashraf88** [comment]
A few scenarios where the file upload count might want to be reset:

1. When a new folder is navigated into
2. If the upload dialog is closed 
3. If user clicks "refresh count" button
