### ISSUE TITLE
ADF Rebranding

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#1512]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**

Currently we have ECM and BPM. Based on the new product rebranding we should rename all references to Content Services & Process Services instead 
**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by hashraf88** [comment]
1. Settings
![screen shot 2017-02-23 at 11 05 44](https://cloud.githubusercontent.com/assets/13200338/23256635/2c04231c-f9b8-11e6-909c-3e58f87528b6.png)

2. Component names
<img width="340" alt="screen shot 2017-02-23 at 11 09 00" src="https://cloud.githubusercontent.com/assets/13200338/23256699/875f2928-f9b8-11e6-9287-0feb9e336b98.png">

3. Demo app header
<img width="678" alt="screen shot 2017-02-23 at 11 09 27" src="https://cloud.githubusercontent.com/assets/13200338/23256707/92df758c-f9b8-11e6-864e-99c028ce199f.png">

**Comment by magemello** [comment]
Also we should check the generators...

**Comment by magemello** [comment]
For this iteration we are not going to change the name of the components...

**Comment by hashraf88** [comment]
Just issues 1 and 3 above need to rectified

**Comment by jdosti** [comment]
1. Components list

<img width="197" alt="screen shot 2017-03-02 at 10 32 57" src="https://cloud.githubusercontent.com/assets/24432311/23503529/0a617bca-ff34-11e6-8d1f-d71b63cd140c.png">


2. Tag Component

<img width="304" alt="screen shot 2017-03-02 at 10 22 40" src="https://cloud.githubusercontent.com/assets/24432311/23503540/12dc26a6-ff34-11e6-8c4b-e2b644e6beb8.png">
