### ISSUE TITLE
After creating a new task, details are not displayed immediately 

### ISSUE THREAD

**Issue by jdosti** [Alfresco/alfresco-ng2-components#1517]
1. Go to Tasks.
2. Start a Task.
3. Start another Task.

**Expected Results**

The "Task List" and "Task Details" should display the newly created task created in step 3.

<img width="565" alt="screen shot 2017-01-23 at 15 23 52" src="https://cloud.githubusercontent.com/assets/24432311/22210036/5ffd7916-e180-11e6-9ece-95ede7211ca3.png">

**Actual Results**

The "Task List" and "Task Details" point on the first created Task.

<img width="591" alt="screen shot 2017-01-23 at 15 20 26" src="https://cloud.githubusercontent.com/assets/24432311/22210092/93a04230-e180-11e6-8558-01619ac3efa5.png">

**Comment by VitoAlbano** [comment]
@jdosti it seems that the behaviour of this part is changed, now when i create a new task Completed Task filter is opened. Is this bug still valid? Could you retest it again?

**Comment by jdosti** [comment]
When creating a Task:

**Expected Results**
- "Task List" displays the name of the newly created task.
- "Task Details" displays the details of the newly created task.

**Actual results**
Different apps give different results: 

Deployed app: 
 - "Task List" displays completed task.
- "Task Details" displays the details of the last completed task.

Task App:
- "Task List" displays 'No tasks list found' message.
- "Task Details" displays 'No task details found' message.
