### ISSUE TITLE
Update to Angular 4

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1522]
**Type of issue:**  (check with "[x]")
```
- [ x ] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
Involves upgrade of **ng2-translate** library that is already 5.0.0 (we are using 2.x) and goes trough renaming in order to drop the version or angular.

**Comment by ikourfaln** [comment]
Ohhhh, waiting for 1.4.0
