### ISSUE TITLE
Incorrect behaviour on completed task if a tab contains the upload widget 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1531]
On a completed task if a tab contains the upload widget the first tab will display all the contents of all tabs and also when actually clicking on the tab that contains the upload widget a refresh occurs which can also cause the app the freeze and crash, similar to issues in #1491.

In the below screenshot each tab should only contain one widget on each
![screen shot 2017-01-24 at 12 08 45](https://cloud.githubusercontent.com/assets/13200338/22246732/1e0ed76c-e22e-11e6-87ac-8d905290ef7c.png)

**Form used for testing**
[tabs.json.zip](https://github.com/Alfresco/alfresco-ng2-components/files/726599/tabs.json.zip)

**Comment by mauriziovitale** [comment]
Should work fine after the issue #1236
