### ISSUE TITLE
Script build refactoring

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#1533]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [x] Support request
```
**Current behavior:**

In the script folder, there are three scripts that seem to be really similar. Do we need all of them?
npm-build-bundle-all.sh	
npm-build-all.sh
npm-link-all-components-demo.sh	
npm-link-demo-shell.sh

**Comment by magemello** [comment]
npm-link-all-components-demo.sh : builds and links all the demo folder inside each components
npm-link-demo-shell.sh: builds and links all the components and the demo shell
npm-build-all.sh : builds all the components

**Comment by magemello** [comment]
I guess we need to update the Readme inside : https://github.com/Alfresco/alfresco-ng2-components/tree/master/scripts
