### ISSUE TITLE
Broken example in documentation

### ISSUE THREAD

**Issue by skopf** [Alfresco/alfresco-ng2-components#1541]
On this page:
https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-alfresco-core/README.md

This example seems to be broken:
```typescript
export class MyComponent implements OnInit {

    constructor(private apiService: AlfrescoApiService) {   
    }

    ngOnInit() {
        let nodeId = 'some-node-id';
        let params = {};
        this.getAlfrescoApi().nodes
            .getNodeChildren(nodeId, params)
            .then(result => console.log(result));
    }
}
```
Where does `this.getAlfrescoApi()` come from? Did you mean `this.apiService`?

**Comment by DenisVuyka** [comment]
Yes, the readme must be updated, thanks for reporting.
