### ISSUE TITLE
Working with development branch documentation

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1543]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [ ] Support request
- [ x ] Documentation
```
We need some basic documentation on how to setup the development branch and get it working.

**Comment by steve-codes** [comment]
Can we add some details to this documentation around what developers can expect on the development branch - for example - whether breaking changes will exist, the reliability of the builds etc.

**Comment by DenisVuyka** [comment]
@magemello we still need unstable staging branch, if we start making `development` public and documented it will no longer be development branch in the sense we created it for

**Comment by DenisVuyka** [comment]
@steve-codes development branch is where all feature branches are merged before testing begins, this is "use at your own risk" branch for the moment. we can't document what's breaking there as it is an internal branch QA takes for testing

**Comment by steve-codes** [comment]
@DenisVuyka Ok - Given these two comments, I would advise that we need to think about what we do in terms of suggesting that other teams use it for their development. It's a little hard to build applications against a moving target, so I'd prefer if we didn't suggest it as an option for development.

**Comment by DenisVuyka** [comment]
@steve-codes yes, I fully agree, my main concern is that keeping documentation around development branch will fully block the team, we all be doing only documentation. What are the expectations? do we update docs on every PR merge? if we merged 10-15 feature branches a day, should we compile "what's changed"? if the bug was found in the dev branch and we fixed it next day - should documentation be updated?

**Comment by steve-codes** [comment]
That's a good question. I have opinions, but I'm not writing code using ADF every day, so I'm probably not the best person to give you answers to these. I'll try and get some examples for you.

**Comment by DenisVuyka** [comment]
No worries, those are rhetoric questions we all need to answer.

**Comment by eromano** [comment]
https://github.com/Alfresco/alfresco-ng2-components/wiki/Working-with-development-branch
