### ISSUE TITLE
No message given if no licence found within BPM

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1545]
If Activiti is in read-only mode due to no licence being found no message is displayed when in any Activiti component or when logging in

<img width="1081" alt="screen shot 2017-01-25 at 15 59 21" src="https://cloud.githubusercontent.com/assets/13200338/22298251/be554a50-e317-11e6-8e82-5723b8646cc4.png">

**Comment by magemello** [comment]
closing...it's going to be implemented in the feature #1493
