### ISSUE TITLE
DataTableAdapter needs more documentation

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1552]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [ ] Support request
- [ x ] Documentation
```
**Current behavior:**

The documentation present now in the repository is not enough to use the DataTableAdapter.
**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
What kind of information is needed? For now the data layer is represented by a set of interfaces. You cannot use DataTableAdapter directly, you need to implement it. As an example we give `ObjectDataTableAdapter` and link to the source code.

**Comment by magemello** [comment]
is not clear what information needs to be returned from each method
