### ISSUE TITLE
Pagination within search: last page of results is incorrect

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1557]
Instead of last page of results the below screenshot is displayed 

![screen shot 2017-01-27 at 14 49 54](https://cloud.githubusercontent.com/assets/13200338/22374951/1d2d5e9e-e4a0-11e6-8c15-db97fa666c0b.png)
**video**
[lastPage.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/735481/lastPage.mp4.zip)

**Comment by hashraf88** [comment]
Above issues reported in #1557 and #1558

**Comment by magemello** [comment]
can't reproduce it
