### ISSUE TITLE
Pagination within search: count of documents on page is incorrect on last page 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1558]
The total count of documents `on the page` is incorrect on last page, in the below example cannot have item 80 of 78. 

![screen shot 2017-01-27 at 14 57 49](https://cloud.githubusercontent.com/assets/13200338/22375449/fe0ddb40-e4a1-11e6-85eb-d6ec19ff0af5.png)

**video**
[lastPage.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/735481/lastPage.mp4.zip)

**Comment by magemello** [comment]
can't reproduce it...
