### ISSUE TITLE
Document how to override strings in components

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#1563]
I can't find any documentation on how to use the `custom-translation` folder in the demo-shell. Specifically we should tell people

* How to override a specific string from a component or from inside the app
* How to add their own language?

**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
```
**Current behavior:**

No documentation on translation linked into README

**Expected behavior:**

Documentation should be accessible from README

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
Fixed as part or the #1608, `custom-translation` folder was renamed to `resources/i18n` as it contained valid translations for demo shell. Documentation was extended with examples on how translations are configured (`ng2-alfresco-core` readme)
