### ISSUE TITLE
Missing documentation for Report Rendering

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1568]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [ ] Support request
- [ x ] Documentation
```
The new feature  #1175 has a lack of documentation.

**Comment by mauriziovitale** [comment]
@magemello is it enough?
https://github.com/Alfresco/alfresco-ng2-components/tree/master/ng2-components/ng2-activiti-analytics#basic-usage-example-analytics-generator

**Comment by magemello** [comment]
@mauriziovitale  I think we need to document also what is reportParamQuery and how to build it. Also in general the template of the options needs also the type column : 

| Name | Type | Required | Description |
| --- | --- | --- | --- |
| `` | {} | info |
