### ISSUE TITLE
Missing documentation for staticTitle upload component

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1570]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [ ] Support request
- [ x ] Documentation
```
**Current behavior:**

The "staticTitle" parameter added has part of the feature #1566 has not been documented
**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
this functionality has also missing test
