### ISSUE TITLE
I can`t open repository

### ISSUE THREAD

**Issue by kodermax** [Alfresco/alfresco-ng2-components#1571]
When I open directory in respository, i see error
![image](https://cloud.githubusercontent.com/assets/590985/22421580/f3c58eae-e6f8-11e6-827d-d42d9f93ffac.png)

![image](https://cloud.githubusercontent.com/assets/590985/22421586/facb36ea-e6f8-11e6-9f51-a207dd23242f.png)

**Comment by DenisVuyka** [comment]
@kodermax can you please use all fields from the "New issue template" to save everyone's time? thanks
