### ISSUE TITLE
Unsuccessful login when putting a space next to the username.

### ISSUE THREAD

**Issue by jdosti** [Alfresco/alfresco-ng2-components#1575]
1. Go to login page.
2. Type a valid username with a space.
3. Type a valid password.

**Expected Results**
The browser ignores the space next to the username and the login is successful.

**Actual Results**
"You have entered an invalid username or password" message is shown.

<img width="327" alt="screen shot 2017-01-30 at 16 59 46" src="https://cloud.githubusercontent.com/assets/24432311/22432665/92fda916-e70d-11e6-8f40-01f06b01f35d.png">

Works fine in Safari, Firefox and Opera.

**Comment by hashraf88** [comment]
Can still replicate this on the latest of development now on all browsers.

**Comment by DenisVuyka** [comment]
We should not trim username on blur, the fix should be on the level of alfresco-js-api instead

**Comment by eromano** [comment]
you are not testing against the last

**Comment by eromano** [comment]
@DenisVuyka  good idea. I moved it on the js-api https://github.com/Alfresco/alfresco-js-api/issues/184
In order to test it link the last development branch of the js-api.
