### ISSUE TITLE
Explain versioning system between components and alfresco-js-api

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1577]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [ ] Support request
- [ x ] Documentation
```
A section where is explained what type of versioning we use and how works the versioning between the components the generators and the alfresco-js-api.

**Comment by eromano** [comment]
https://github.com/Alfresco/alfresco-ng2-components/wiki/Versioning-system-between-components-and-alfresco-js-api
