### ISSUE TITLE
Issue while running in production mode

### ISSUE THREAD

**Issue by infad-kachancheri** [Alfresco/alfresco-ng2-components#1579]
I tried to run it in production mode its throwing following error:

ERROR in vendor.d8fccf173d2779592de7.js from UglifyJs
SyntaxError: Unexpected token: name (AlfrescoApi) [./~/angular2-template-loader!
./~/source-map-loader!./config/loaders/system.js!./~/source-map-loader!./~/alfre
sco-js-api/src/alfrescoApi.js:18,0]

Please find screenshot for more details about error.

![screen004](https://cloud.githubusercontent.com/assets/20041687/22465571/6c5e85e8-e7e2-11e6-84dd-063c40419958.PNG)

**Comment by infad-kachancheri** [comment]
Got fix for it.

**Comment by magemello** [comment]
#1576
