### ISSUE TITLE
Actions placement

### ISSUE THREAD

**Issue by kodermax** [Alfresco/alfresco-ng2-components#1581]
**Type of issue:**  (check with "[x]")
```
- [X] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**

Now actions is located at the end of row

**Browser and version:** 
all
 
**New feature request:**
I'd like too see this button at the beginning of the row.
I think it be more comfortable

![image](https://cloud.githubusercontent.com/assets/590985/22467508/05001c7e-e7d6-11e6-8dab-9363c5bbcd9d.png)

**Comment by magemello** [comment]
In this case, I think we can implement an option on the documentlist to decide if to display it on right or on the left.
