### ISSUE TITLE
Provide tab view of the analytics-report-list

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1583]
**Type of issue:**  (check with "[x]")
```
- [ x ] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```

We want to have a way to define the layout of the analytics list component. The proposed solution is the same adopted for the tasklist-app:

```
<analytics-report-list [layoutType]="'GRID'></analytics-report-list>
```

#### Options

| Name | Type | Required | Description |
| --- | --- | --- | --- |
| `layoutType` | {string} | required | Define the layout of the apps. There are two possible values: GRID or LIST. |

**Comment by mauriziovitale** [comment]
@magemello What do you think about that ?
<img width="923" alt="screen shot 2017-02-01 at 15 51 44" src="https://cloud.githubusercontent.com/assets/14923305/22514919/c6449d5c-e898-11e6-8239-a3feab15d7ae.png">
<img width="922" alt="screen shot 2017-02-01 at 15 49 59" src="https://cloud.githubusercontent.com/assets/14923305/22514918/c62e344a-e898-11e6-9847-7f64f4ba07f9.png">

**Comment by DenisVuyka** [comment]
I suggest also round/floor/ceil decimals, and probably trimming names.
