### ISSUE TITLE
Activiti Task Form Fails with "display value" field set to display a document

### ISSUE THREAD

**Issue by lcreswick** [Alfresco/alfresco-ng2-components#1586]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**
when a task form is configured with a "display value" field, and that "display value" field is set to display a variable of type document, then the task form fails to render properly and cant be used (outcome buttons don't appear, tabs don't work, etc).

**Expected behavior:**
display the form correctly, and show a link to the document, if "Show document content embedded in form" not ticked, or display preview of document if "Show document content embedded in form" is ticked, and allow document to be edited in MS Office if "Allow editing documents in Office" is ticked.

**Steps to reproduce the issue:**
Create a new process, with:
- task form with an "attach document" field
- user task with a form with a "display value" field set to display the document attached on start form

**Component name and version:** 
ng2-activiti-form

**Browser and version:** 
Firefox 51.0.1
 
**Node version (for build issues):**  
7.3.0

**New feature request:**

**Comment by lcreswick** [comment]
if the "attach document" field has no value then the "display value" field (set to display the document) renders correctly and the form is ok. Only when the "attach document" field has a document attached, does the "display value" field fail and cause the form rendering to fail.

**Comment by lcreswick** [comment]
Issue seems to be in file display-value.widget.html
1) use of {{settingsService.bpmHost}} causes rendering to fail and the form to be broken/unusable. when i replace this with "http://demo:9090" (i.e. my host:port) it renders correctly
2) not core to the issue causing the rendering to fail, but i don't believe that use of "/activiti-app/app/rest/content/{{id}}/raw" is correct. Probably this is better "/activiti-app/app/rest/content/{{id}}/rendition/thumbnail" as it will render the auto generated thumbnail

**Comment by lcreswick** [comment]
As a workaround, this is what i did to fix the issue whereby ADF fails to render a task form which has a “display value” field set to display a document, AND add the ability to edit the document in MS Office:

In file <APP_ROOT>/node_modules/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html

Change:

<div *ngSwitchCase="'upload'">
        <div class="upload-widget">
            <div>
                <label class="upload-widget__label" [attr.for]="field.id">{{field.name}}</label>
            </div>
            <div>
                <img *ngIf="hasFile" class="img-upload-widget" src="{{settingsService.bpmHost}}/activiti-app/app/rest/content/{{id}}/raw">
            </div>
            <div>
                <i *ngIf="hasFile" class="material-icons upload-widget__icon">attachment</i>
                <span *ngIf="hasFile" class="upload-widget__file">{{value}}</span>
            </div>
        </div>
    </div>

To:

<div *ngSwitchCase="'upload'">
        <div class="upload-widget">
            <div>
                <label class="upload-widget__label" [attr.for]="field.id">{{field.name}}</label>
            </div>
            <div>
                <img *ngIf="hasFile" class="img-upload-widget" src="http://demo:9090/activiti-app/app/rest/content/{{id}}/rendition/thumbnail">
            </div>
            <div>
                <i *ngIf="hasFile" class="material-icons upload-widget__icon">attachment</i>
                <span *ngIf="hasFile" class="upload-widget__file">{{value}}</span>
            </div>
			<div>
				<a href="ms-word:ofe|u|http://demo:9090/activiti-app/aos/{{id}}/{{value}}">Edit in MS Office</a>
			</div>
        </div>
    </div>

Note, I am still yet to fix this, but the edit in MS Word URL gets changes by Angular2 to be prefixed with “unsafe:”. Apparently the non-standard protocol (i.e. “ms-word:ofe|u|”) needs to be explicitly added to the Angular2 whitelist.

**Comment by DenisVuyka** [comment]
@lcreswick I've updated your comment to enable all content

**Comment by mauriziovitale** [comment]
@lcreswick  The problem should be fixed with this issue 
https://github.com/Alfresco/alfresco-ng2-components/issues/1236

**Comment by jdosti** [comment]
Needs to be retested once #1236 is resolved.
