### ISSUE TITLE
Provide fast rebuild configuration 

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1588]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**
Right now when developers want rebuilding everything the most reliable workflow is

```sh
./npm-clean.sh
./npm-link-demo-shell.sh
```

The scripts case 15+ projects to be rebuilt and relinked locally via **npm link**. 
The build process is taking time (±30 mins) because of the following issues:

- no npm cache involved
- tslint for 15+ projects takes time
- license checking for 15+ projects takes time
- **npm link** causes **prepublish** script to be executed, that involves unit testing and code coverage generation for 15+ projects
- it is not possible having more than one cloned repository in development due to npm link behaviour (symlinks via global scope)

**Expected behavior:**

We should provide a dedicated configuration/scripts for fast rebuilds and dev setups on local machines.

- using npm caching
- switching off tslint/license check
- switching off unit testing and coverage reports
- (optional) using traditional symlinks to enable more than one environment 

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
I did some modify are in the branch dev-eroamno-1588 :

***npm-build-all.sh*** run the test only if is asked with npm-build-all.sh -t or npm-build-all.sh -test I have also added the help and updated the readme.

***In any package JSON*** there was un delete of the dist folder more

***npm-link-all-components-demo.sh*** there was also npm install but npm link already execute the install

In others PR I already fixed the script

***start.sh*** adding the help and those options:

"-i or -install start the demo shell and install the dependencies"
"-u or -update start the demo shell and update the dependencies"
"-c or -cleanInstall clean the demo shell install the dependencies and start the the demo shell"
"-l or -link all the ng2-components in the demo shell and start the the demo shell"
