### ISSUE TITLE
Cannot easily check if DocumentList "isEmpty"

### ISSUE THREAD

**Issue by chris-equis** [Alfresco/alfresco-ng2-components#1589]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**

The only way we can say that DocumentList is empty (or it has nothing to show) is by querying the rows and check the length `!this.documentList.data.getRows().length;`

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

Maybe an easier way to do so will be better `this.documentList.isEmpty` or anything that fits in.
It would be also good to have a class name attached to `<alfresco-document-list>` that says so.

**Comment by DenisVuyka** [comment]
I suggest we also add a special CSS class to the top element if document list is empty, i.e. "document-list__empty" or similar. That may simplify external theming.
