### ISSUE TITLE
No validation if path is incorrect for anchor/URL based navigation 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#159]
If an incorrect path is set within demo-shell-ng2/app/components/files/files.component.html there is no validation on the FE. 

E.g. of incorrect path
<button (click)="documentList.changePath('/Sites/swsdp/documentLibrary/Agency Files/Contracts')">Go to agency contracts</button>

There is however an error provided in the console
<img width="1387" alt="screen shot 2016-06-07 at 15 16 56" src="https://cloud.githubusercontent.com/assets/13200338/15861207/c1e38cfa-2cc3-11e6-88d1-128e4b6c0a43.png">

**Comment by DenisVuyka** [comment]
For this task we just need handling navigation exceptions in DocumentList and exposing details via 
(error) event (to be added).
