### ISSUE TITLE
User should be notified that can't create a tag with an existing name.

### ISSUE THREAD

**Issue by jdosti** [Alfresco/alfresco-ng2-components#1592]
1. Go to Tag component.
2. Create a tag with an existing name.

**Expected Results**

User should be notified that the name already exist and can't create tag.

**Actual Results**

User doesn't get notified that the name already exist and can't create tag.

**Comment by hashraf88** [comment]
This still occurs using the same steps as above on all browsers, video of steps and outcome attached.

[tag placeholder.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/796433/tag.placeholder.mp4.zip)

**Comment by eromano** [comment]
you are not tsting against the last version
