### ISSUE TITLE
Pagination component - dropdown doesn't stay visible on screen

### ISSUE THREAD

**Issue by john-knowles** [Alfresco/alfresco-ng2-components#1593]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**
When the pagination is at the bottom of the screen the dropdown for page selection disappears out of the viewable area.

<img width="380" alt="screen shot 2017-02-03 at 15 48 12" src="https://cloud.githubusercontent.com/assets/18680913/22593948/e0da7570-ea18-11e6-8fa6-ccfc0c8ad6b6.png">

**Expected behavior:**
The dropdown should adjust the direction it opens depending on its location - so if it is too close to the bottom of the screen it needs to drop "up".

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by magemello** [comment]
This is a style preference that should be addressed via css or html, example:

```
<div style="padding: 5px 5px">
     <dcoument-list></document-list>
</div>
```
