### ISSUE TITLE
The text of a DocumentList row is not fully visible

### ISSUE THREAD

**Issue by john-knowles** [Alfresco/alfresco-ng2-components#1594]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
Letters p, y, g are cut off.

<img width="160" alt="screen shot 2017-02-03 at 16 30 34" src="https://cloud.githubusercontent.com/assets/18680913/22596119/3681df28-ea22-11e6-9a06-4e245ebcae3c.png">
<img width="165" alt="screen shot 2017-02-03 at 16 30 30" src="https://cloud.githubusercontent.com/assets/18680913/22596118/3674b4f6-ea22-11e6-9d59-8f5f3e1bb0b3.png">
<img width="244" alt="screen shot 2017-02-03 at 16 29 08" src="https://cloud.githubusercontent.com/assets/18680913/22596117/36749ac0-ea22-11e6-936c-33061afa208a.png">

**Expected behaviour:**
Letters are fully displayed

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by john-knowles** [comment]
Note: I can't reproduce this in the demo app.

**Comment by DenisVuyka** [comment]
@john-knowles if it cannot be reproduced should we close this ticket then?
