### ISSUE TITLE
Custom stencil components not getting rendered on a completed task/start form

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1597]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**
Custom stencil components not getting rendered on a completed task/start form.

**Expected behavior:**
Expect the custom stencil components to render correctly on completed task and start form.

**Steps to reproduce the issue:**
create a process start->user task->end. Attach a form created from a custom stencil to both start and user task. The stencil gets rendered correctly on active start form and open task. However once the start/task form is submitted/completed and when you open the completed form, the stencils are not rendered correctly. A similar defect used to be in activiti-app as well which got fixed in 1.5.3.2 (https://issues.alfresco.com/jira/browse/ACTIVITI-486)

**Component name and version:** 
ng2-activiti-form 1.1.0

**Browser and version:** 
Tested in Chrome, possibly in all.

**Comment by VitoAlbano** [comment]
This should be solved by https://issues.alfresco.com/jira/browse/ADF-224.
Closing
