### ISSUE TITLE
Demo shell build problem with Node 5

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#1602]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**

Build has error with node5 : 
```
/Users/eromano/Projects/test/config/webpack.common.js:12
let pattern = '+(alfresco-js-api|ng2-alfresco|ng2-activiti)*';
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/eromano/Projects/test/config/webpack.dev.js:3:20)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Expected behavior:**

The Expected behavior is here  https://github.com/Alfresco/generator-ng2-alfresco-app/issues/63

**Steps to reproduce the issue:**

Reference here  https://github.com/Alfresco/generator-ng2-alfresco-app/issues/63

**Component name and version:** 

demo shell

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
Node 5 is not officially supported, the Long Term Support (LTS) version is 6: https://github.com/nodejs/LTS#lts-schedule. I don't see any reason spending time on that.

**Comment by eromano** [comment]
The prerequisites say Make sure the Node.js version is > 5:
https://github.com/Alfresco/alfresco-ng2-components/blob/master/PREREQUISITES.md

**Comment by DenisVuyka** [comment]
I still don't get what's the problem upgrading to official node version.

We also got this issue: #1539
Official article refers also to 6.x and optional 7.x: https://community.alfresco.com/docs/DOC-6600-adf-101-getting-started-with-alfresco-application-development-framework
