### ISSUE TITLE
License badge never loads

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1604]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**
License badge on main readme.md page never loads:
![screen shot 2017-02-07 at 15 16 24](https://cloud.githubusercontent.com/assets/503991/22697180/97da6ac8-ed48-11e6-97db-133dfb00ed39.png)

**Expected behavior:**
The badge should be fixed or removed.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

all browsers 

**Node version (for build issues):**  

**New feature request:**

**Comment by magemello** [comment]
@DenisVuyka what page, also can you please check from another browser to verify that is not a cache problem?

**Comment by DenisVuyka** [comment]
@magemello This issue can be closed I think. It was Chrome issue and seems to be working fine now.
