### ISSUE TITLE
Server address not configurable

### ISSUE THREAD

**Issue by john-knowles** [Alfresco/alfresco-ng2-components#1605]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [X] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
Webpack bundling is putting the Alfresco API url into a .js file which has to be changed depending on who is deploying is and where they are deploying it.

**Expected behaviour:**
Configuration file is output so that when deploying the application the built code does not have to be manually edited.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
Can you please be more specific? Here's the production configuration file for webpack and there are no Alfresco API urls there: https://github.com/Alfresco/alfresco-ng2-components/blob/master/demo-shell-ng2/config/webpack.prod.js

**Comment by john-knowles** [comment]
We change the API url during webpack bundling and it’s taken from an env.conf file which maps to localhost:8080

**Comment by ohej** [comment]
So essentially the issue here is that once you generate the app you specify the address for the repository and Activiti, which is then put into app.component.ts. 

Once you the make a production build this is transpiled into a big JS file which makes it non-trivial to change the host/port.

Essentially we should figure out a way to externalise the config.

**Comment by DenisVuyka** [comment]
There's a `SettingsService` that keeps those values and that can be used by end applications. All example projects have some code samples on how to use it. Given that ADF has no code behind, it's a 100% client-side application you will still need getting those values in your application. If they are coming from the server or dynamically evaluated - this can be put into TypeScript files somewhere.

**Comment by DenisVuyka** [comment]
Here's an [AlfrescoSettingsService](https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-alfresco-core/src/services/alfresco-settings.service.ts) that can be imported into application code.

**Comment by DenisVuyka** [comment]
@ohej @john-knowles @magemello 

The URLs generated with the App in the [app.component](https://github.com/Alfresco/generator-ng2-alfresco-app/blob/master/app/templates/app/_app.component.ts) file are just default (fallback) values. In its constructor, the component overwrites these settings if there's anything in the local storage. This is just an example implementation and can be tuned to whatever end app developers want actually.

**Comment by DenisVuyka** [comment]
Introduced in the 1.6.0 as part of the AppConfigService (ng2-alfresco-core)
