### ISSUE TITLE
UI does not fallback to english if native browser locale is not available. many labels missing

### ISSUE THREAD

**Issue by romainguinot** [Alfresco/alfresco-ng2-components#1608]
Hi,

If you have a browser with a non-english locale, many (if not all) labels are missing.
You need a browser with just english.

There needs to be a fallback to english if the native language is not available.
Ideally, go through the browser's accept languages to see if there is a potential match, and, if not, fallback to english.

See attached screenshots.

![process](https://cloud.githubusercontent.com/assets/1854212/22739437/f308c08e-ee0b-11e6-964d-4f9f983a8bff.png)
![doclist](https://cloud.githubusercontent.com/assets/1854212/22739438/f3095634-ee0b-11e6-8391-237744062097.png)
![login](https://cloud.githubusercontent.com/assets/1854212/22739439/f30a4d8c-ee0b-11e6-9eec-24a7fb73f89a.png)

**Comment by DenisVuyka** [comment]
Good point, thanks. Translation service does indeed support fallback locales but seems to be not working properly.
