### ISSUE TITLE
User image not shown correctly for invoked user in task details

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1609]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ x ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**
Please find attached image where an involved user image is shown differently to how it is stored in the activiti. In this example, the logged in user is the same as involved user. The logged in user image on top left corner is shown correctly. However the involved user is shown incorrectly.
<img width="1585" alt="screen shot 2017-02-09 at 12 01 00 am" src="https://cloud.githubusercontent.com/assets/2080360/22771332/b9ff62e8-ee5b-11e6-9c5e-c4d7ab4825d2.png">

**Expected behavior:**
Expecting the involved user image to be fetched from activiti

**Steps to reproduce the issue:**
Create a task and involve a user to the task. Add an image to the involved user in activiti.  Check the involved user image in ADF.

**Component name and version:** 
ng2-alfresco-task. v1.1.0

**Browser and version:** 
Tested in chrome.

**Comment by VitoAlbano** [comment]
I think this is a feature request. When we added the MDL chips to the people component for tasklist and processlist we didn't planned to adding the proper activiti user image.

**Comment by DenisVuyka** [comment]
Yes, there's no code to display actual images right now. In addition Angular 1 UI does not show those users inline in the header, one needs to click and see the 'details' content in the main area, like groups, comments, etc. We should rework how this feature looks I think.

**Comment by cijujoseph** [comment]
Denis, regarding the Angular 1 UI, you don't have to go to the main content area. PFA an image where it shows the icon in the header. Btw, if there is no image attached to the user, it just displays the initials.
<img width="1484" alt="screen shot 2017-03-28 at 2 03 25 pm" src="https://cloud.githubusercontent.com/assets/2080360/24422510/6667e6f8-13bf-11e7-89a5-524203005609.png">

**Comment by DenisVuyka** [comment]
@cijujoseph Yes, we need two implementations here, shortened form with initials/avatars and details page.
