### ISSUE TITLE
Add Support to provide styles on each component initialization

### ISSUE THREAD

**Issue by Salaboy** [Alfresco/alfresco-ng2-components#1615]
**Type of issue:**  (check with "[x]")
```
- [ x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**

The current activiti-start-task doesn't allow the user to override the entire (style) class of the component. 
**Expected behavior:**

The user should be provided a way to override the (style) classes of the component
**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

A third party app wants to style ADF components in a custom way, they should be able to override the default components classes.

**Comment by eromano** [comment]
Use the :host pseudo-class selector to target styles in the element that hosts the component. This is the classic way you can customize the style in all the Angular 2 component
