### ISSUE TITLE
WARN: 'Could not find HammerJS.' on every single unit test execution

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1617]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**
When running unit tests nearly on every executed test there's an output: 

```text
WARN: 'Could not find HammerJS. Certain Angular Material components may not work correctly.'
```

There are hundreds of them. This is related to additional angular/material libs (required for some components)

**Expected behavior:**
Additional libs should be configured correctly as per getting started guide: https://material.angular.io/guide/getting-started

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by hacknaked** [comment]
I fix this adding 

`import 'hammerjs';`

in every `*.spec.ts` test file. 
Also, adding the import statement to `polyfills.ts` silences the warning.
