### ISSUE TITLE
Task List / Process List define columns in the HTML and not in the JS

### ISSUE THREAD

**Issue by Salaboy** [Alfresco/alfresco-ng2-components#1624]
**Type of issue:**  (check with "[x]")
```
- [ x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**

For Process and Task Lists you need to define the columns by using JS 
```ts
this.dataTasks = new ObjectDataTableAdapter(
      [],
      [
          {type: 'text', key: 'id', title: 'Id',  sortable: true},
          {type: 'text', key: 'name', title: 'Name', cssClass: 'name-column', sortable: true}
      ]
    );
```

**Expected behavior:**

You should be able to define the columns in the HTML following the Document List approach:
```html
<alfresco-document-list ...>
    <content-columns>
        <content-column key="$thumbnail" type="image"></content-column>
        <content-column 
            title="Name" 
            key="name" 
            sortable="true"
            class="full-width ellipsis-cell">
        </content-column>
```
Which opens the possibility to add custom columns with more data. 

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
We may want to backport this feature to DataTable. It was originally introduced for DocumentList before DataTable was created.

**Comment by Salaboy** [comment]
Yes sounds like a DataTable feature.. it is not specific for the Process/Task List

**Comment by tdonovancsra** [comment]
+1 Please implement

**Comment by DenisVuyka** [comment]
@tdonovancsra it is already implemented and merged with development branch (will be available with the next release), you can see more details within the associated PR (it gives samples of usage): https://github.com/Alfresco/alfresco-ng2-components/pull/1705
