### ISSUE TITLE
Task List doesn't load the correct values for Columns

### ISSUE THREAD

**Issue by Salaboy** [Alfresco/alfresco-ng2-components#1625]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**

If you define a task list with the following columns: 
this.dataTasks = new ObjectDataTableAdapter(
      [],

      [
          {type: 'text', key: 'id', title: 'Id',  sortable: true},
        {type: 'text', key: 'name', title: 'Name', cssClass: 'name-column', sortable: true},
        {type: 'text', key: 'created', title: 'Created',  sortable: true},
          {type: 'text', key: 'assignee.lastName', title: 'Assignee',  sortable: true},
          {type: 'text', key: 'dueDate', title: 'Due Date',  sortable: true}
      ]
    );

Assignee.lastName and dueDate are not correctly displayed. The data is correctly returned by the activiti-rest APIs but the component for some reason is not loading that data into the column. 
**Expected behavior:**

You should be able to load all the available data returned by the activiti-rest API. 

 
**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by mauriziovitale** [comment]
@hashraf88 With the fix I put also some unit test 0d566d23f0dbd3fc96a0839a6e71970e556315df but it would be better add also some integration test.
