### ISSUE TITLE
Material design problem on the user detail

### ISSUE THREAD

**Issue by Vegetam** [Alfresco/alfresco-ng2-components#1626]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**

Since on ADF if you have it with Activiti you must have the username with the @something for example francesco.malagrino@alfresco.com the job title option is not aligned to the value of the job title I have image but I can't add here. For fix this problem I removed align-items: flex ends; inside the css material.orange-blue.min.css line 8 at the following point : 

```css
.mdl-list__item
.mdl-list__item-secondary-content 
{
align-items:flex-end;
-ms-flex-align: end;
-webkit-align-items:flex end;
}
```

It appear as
                                                                   job title :
                     techical account manager

if you remove those option the display will be much better as : 
job title : 
technical
account
manager

**Expected behavior:**

The behaviour should be Job Title : value of the job title in the correct position
**Steps to reproduce the issue:**

Just add an username long as francesco.malagrino@alfresco.com
**Component name and version:** 

Is in the css original-material.css but it can be fixed also user-info-component.html  adding a css line
**Browser and version:** 

 All
**Node version (for build issues):**  

6.9.5
**New feature request:**

Just remove that option in the css under or add it under the user-info-component

**Comment by DenisVuyka** [comment]
Notes: we are not going to change anything in the Google's libraries and themes. As part of the fix there will be a new `user-info__job-title` CSS class enforcing `align-items: flex-start;` for corresponding field, if that's not enough the class can still be extended from the outside.
