### ISSUE TITLE
Tree-view component

### ISSUE THREAD

**Issue by john-knowles** [Alfresco/alfresco-ng2-components#1627]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**

**Expected behaviour:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

Please can we have a tree-view navigation component that allows developers to build a user interface that enables users to traverse through a hierarchical structure, like folders.

There are many use cases for a tree-view component:
- Browse folder structure of the repository, or a site etc
- Select a folder to move, or copy content to

**Acceptance Criteria**

- [ ] Tree-view component's data source is configurable
- [ ] Design utilises Material Design (i.e. http://codepen.io/kasajian/pen/MyWyMo)
- [ ] Configuration for enforcing selection of a single item, or allowing multiple selection
- [ ] Users can select all, unselect all easily (which is configurable)
- [ ] Items containing children can be expanded and collapsed
- [ ] Configuration use as a source or destination component
- [ ] Allow pre-selection of a node(s) (by ID or path) via configuration

**Comment by rgauss** [comment]
Another requirement would be to allow pre-selection of a node(s) (by ID or path) via configuration.

**Comment by john-knowles** [comment]
Thanks @rgauss

**Comment by DenisVuyka** [comment]
What's the benefit of creating a TreeView Component in the scope of ADF compared to end devs taking existing implementations out there and binding to the existing data, i.e. https://github.com/500tech/angular2-tree-component?

**Comment by DenisVuyka** [comment]
Another concern is that Tree View will never ever be compatible with any mobile devices, and navigation paradigms we have in the mobile world, so we are speaking about desktop-only component that pretends to be a Material Design one.

**Comment by DenisVuyka** [comment]
See also: http://www.primefaces.org/primeng/#/tree

**Comment by rgauss** [comment]
> What's the benefit of creating a TreeView Component in the scope of ADF compared to end devs taking existing implementations out there

For one, consistency across teams delivering products.  Even simply wrapping an existing implementation would be better than each team doing their own investigation (which takes time and resources) and choosing different implementations resulting in a disjointed UI/UX for customers.

> Another concern is that Tree View will never ever be compatible with any mobile devices

Why is that?

**Comment by DenisVuyka** [comment]
@rgauss 
re mobile devices, how do you imagine a Tree View with like 10 levels of depth on the iOS/Android device? Google's Material Design spec never included Tree View for instance. Traditionally people use clickable lists for that.

**Comment by DenisVuyka** [comment]
@rgauss If you go to http://www.primefaces.org/primeng for example, they advertise 70+ ready to  use open source components (general purpose). Do you expect ADF to reimplement all of them?

**Comment by rgauss** [comment]
> how do you imagine a Tree View with like 10 levels of depth on the iOS/Android device?

I'd image a responsive design that would switch to a horizontally scrolling presentation to represent depth, but I'm no UX designer.

> Do you expect ADF to reimplement all of them?

No, of course not, but even official recommendations of other frameworks with perhaps examples of how to use them within ADF is better than teams duplicating work and an inconsistent UX.

**Comment by DenisVuyka** [comment]
Closing for now. Can be reopened in the future if needed.
