### ISSUE TITLE
Alfresco  File  and  Folder Multiple  http   Looping  Call

### ISSUE THREAD

**Issue by vikashsingh005** [Alfresco/alfresco-ng2-components#1637]
When  i  Upload  multiple   file  and   folder  to  alfresco  Continuously,  then  when  changing  from Bread com  ,  then  we  have  Multiple  Loop   on  file  and   Folder.

Bred Com will   not behave  properly ,its  like  fast   forward  switch  between   file  and   Folder   continuously 

![capture2](https://cloud.githubusercontent.com/assets/7962189/23016353/3238d3a6-f45c-11e6-8252-8e780d91cdb9.PNG)
   
![image](https://cloud.githubusercontent.com/assets/7962189/23016364/39566ad6-f45c-11e6-90d4-7c662c5b257b.png)

**Comment by vikashsingh005** [comment]
[Untitled 2.zip](https://github.com/Alfresco/alfresco-ng2-components/files/779725/Untitled.2.zip)

**Comment by DenisVuyka** [comment]
Yes, once it in the loop it will be calling that non-stop, we'll try to address this issue.

**Comment by DenisVuyka** [comment]
@magemello @mauriziovitale 
I think there might be a bug related to Upload and way it handles `current folder id`. When the upload is in the progress and user changes folder it - the upload service may start uploading to a new folder instead of the one it was dropped to.
