### ISSUE TITLE
app cannot be accessed from another host

### ISSUE THREAD

**Issue by romainguinot** [Alfresco/alfresco-ng2-components#1639]
Issue that i raised in the healthcare app : https://github.com/Alfresco/health-care-app/issues/33 
seem to be a general framework issue.

Apps cannot be accessed from another host it would seem, which would be a rather severe issue. 
Could be a CORS config issue, but there is nothing in the CORS xml config fragment (by default) that seem to restrict connections to only those coming from the same host. 

Please see the issue mentioned above for all the details about requests etc. 
Please let me know if you would like to duplicate or move over the health app issue to here.

**Comment by DenisVuyka** [comment]
@romainguinot We got Login component working via the "plunker" domain agains the locally installed ECM/BPM instances ( [Login (1.1.0)](http://embed.plnkr.co/PfZytJyHcl3xIsa8pdMo/) ). That involves both SSL bypassing and dealing with CORS.

**Comment by 10SPD** [comment]
We also seem to be running into CORS issues. We have enabled it via web.xml (using SDK 2.2.0) and we can do GET (using jsonp), but POST isn't working properly. We still get the following error, even though the request is being sent, accepted, **and processed**:

`No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3001' is therefore not allowed access.`

Any one run into this?

**Comment by DenisVuyka** [comment]
@romainguinot @10SPD 
These are local configuration issues. I suggest using [Gitter](https://gitter.im/Alfresco/alfresco-ng2-components) chat for diagnosing the problem, as this is not related to ng2-components implementation.
