### ISSUE TITLE
ADD all valid fields that the tasklist can display

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1643]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [ ] Support request
- [ x ] Documentation
```
**Current behavior:**

In the documentation we don't tell what are the fields that the tasklist can display, the only way right now is debugging the call to the process service.
**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
Once the cloud instance of the Process Services is upgraded the link to corresponding REST API and output will be posted to the readme.
