### ISSUE TITLE
Checkboxes have wrong values on completed start form

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1656]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behavior:**
Checkboxes have wrong state when rendered for complete start forms.

**Expected behavior:**
Checkboxes should reflect the state of the form when user completed it.

**Steps to reproduce the issue:**

- Import this application: [Variables.zip](https://github.com/Alfresco/alfresco-ng2-components/files/798973/Variables.zip)
- Start the process
- Fill the text inputs
- Check the checkboxes to the left, and rename unchecked those to the right:
- Complete the form and reopen it via Processes -> Completed -> Your Process -> Start Form

**Expected** (at per the old web UI):

Only checkboxes to the left are `checked`

![screen shot 2017-02-24 at 10 19 10](https://cloud.githubusercontent.com/assets/503991/23300005/9ba34c02-fa7b-11e6-8fc4-e519a85d9359.png)

**Actual**:

All checkboxes are `checked`

![screen shot 2017-02-24 at 10 19 35](https://cloud.githubusercontent.com/assets/503991/23300048/c81faeba-fa7b-11e6-86a8-8978ba1d4f11.png)

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by tzclucian** [comment]
I think I've also encountered something similar but wanted to get more feedback until raising an issue.

I've just tried to use a toggle switch, the same code used in the settings panel from the demo app.

```ts
  <p class="toggle">
    <label for="switch1" class="mdl-switch mdl-js-switch mdl-js-ripple-effect">
      <input type="checkbox" id="switch1" [checked]="isECM" class="mdl-switch__input"
             (click)="toggleECM()">
      <span class="mdl-switch__label">ECM</span>
    </label>
  </p>
```

If using the toggle from the UI/page the changes are correctly recorded/bound in controller.
If the variable that is bound to the input changes its boolean value the UI is not updating correctly.

Am I doing something wrong or is this a bug as well?

**Comment by DenisVuyka** [comment]
@tzclucian thanks for reporting, will investigate that as well

**Comment by hashraf88** [comment]
@tzclucian I believe the issue you reported to be a seperate issue, if your problem still persists please open a seperate issue, thanks.

**Comment by DenisVuyka** [comment]
I suggest using [md-slide-toggle](https://material.angular.io/components/component/slide-toggle) in your code. We will be migrating to this component later on, the generated app should already have references to @angular/material.

**Comment by tzclucian** [comment]
> I suggest using md-slide-toggle in your code. We will be migrating to this component later on, the generated app should already have references to @angular/material.

Thank you @DenisVuyka , much appreciated.

> @tzclucian I believe the issue you reported to be a seperate issue, if your problem still persists please open a seperate issue, thanks.

Do you consider that is worth opening another one?

**Comment by DenisVuyka** [comment]
This particular issue is related to checkbox rendering on a completed or readonly form ('Display Value' widget), so can be closed once testing complete.
