### ISSUE TITLE
Process definition overview: all processes displayed in graph

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1657]
When within a specific app only the processes the tables/graphs should only display those within that specific app not all processes.

**Comment by VitoAlbano** [comment]
@hashraf88  is this problem still happening ? Checking with the latest from development i can see : 

<img width="1403" alt="screen shot 2017-03-29 at 15 02 21" src="https://cloud.githubusercontent.com/assets/7974125/24458408/c0640160-1490-11e7-9b04-b9d546dcabcd.png">
<img width="1398" alt="screen shot 2017-03-29 at 15 02 08" src="https://cloud.githubusercontent.com/assets/7974125/24458406/c01f3b7a-1490-11e7-8dad-dbd2e59f846b.png">
<img width="1403" alt="screen shot 2017-03-29 at 15 01 56" src="https://cloud.githubusercontent.com/assets/7974125/24458407/c02a6ebe-1490-11e7-916f-9452a06bbe3d.png">

**Comment by VitoAlbano** [comment]
checking the activiti behaviour i can spot that "Process definition overview" is only showed via the Analytics App or Task App, never in the specific app. So i'll change the behaviour to match the one in activiti
