### ISSUE TITLE
tooltips are not displayed correctly if longer than a single line

### ISSUE THREAD

**Issue by jdosti** [Alfresco/alfresco-ng2-components#1668]
1. Go to Reports
2. Create a "Task service level agreement" report.

<img width="283" alt="screen shot 2017-02-24 at 15 11 04" src="https://cloud.githubusercontent.com/assets/24432311/23363876/a6243170-fcf4-11e6-8db7-3fc42b5602b9.png">

**Comment by hashraf88** [comment]
Also in process instances overview report

<img width="123" alt="screen shot 2017-02-27 at 14 04 53" src="https://cloud.githubusercontent.com/assets/13200338/23364200/f725bc64-fcf5-11e6-8e7f-c4b37b7ccd3c.png">
