### ISSUE TITLE
"Process definition details" option is not highlighted correctly.

### ISSUE THREAD

**Issue by jdosti** [Alfresco/alfresco-ng2-components#1669]
1. Go to Reports.
2. Create a "Process definition overview" report.

<img width="254" alt="screen shot 2017-02-27 at 13 51 14" src="https://cloud.githubusercontent.com/assets/24432311/23364044/6a39a69e-fcf5-11e6-9db9-abe0c3796588.png">

**Comment by hashraf88** [comment]
Duplicate of #1668
