### ISSUE TITLE
Cannot right-click on DocumentList

### ISSUE THREAD

**Issue by chris-equis** [Alfresco/alfresco-ng2-components#1677]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
Right-clicking in Document List is not available with `[contextMenuActions]="false"`
- right-click is not working on any Document List element, not only on rows

**Expected behavior:**
Right-clicking in Document List should be available with `[contextMenuActions]="false"` or not specified (since the default value is `false`)

**Comment by DenisVuyka** [comment]
@chris-equis good point, right now it is just "always disable":

```ts
@HostListener('contextmenu', ['$event'])
    onShowContextMenu(e?: Event) {
        if (e) {
            e.preventDefault();
        }
    }
```

needs to perform additional check.
