### ISSUE TITLE
Add Edit in MS Office

### ISSUE THREAD

**Issue by lcreswick** [Alfresco/alfresco-ng2-components#1691]
**Type of issue:**  (check with "[x]")
```
- [ x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
When configuring a task form in Activiti Kickstart, user can add a Display Value field that displays a property of type document, and they can choose to "Allow editing documents in Office".

ADF does not include capability to respect the "Allow editing documents in Office" configuration on a form. 

**Expected behavior:**
ADF to respect the "Allow editing documents in Office" configuration on a form.

**Steps to reproduce the issue:**

**Component name and version:** 
/node_modules/ng2-activiti-form/src/components/widgets/display-value

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by lcreswick** [comment]
I have worked around this limitation as follows:
 in /home/vagrant/default-adf-1-1/node_modules/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.html:

`
...
<div *ngSwitchCase="'upload'">
        <div class="upload-widget" valign="top">
            <div title="Edit in MS Word">
                <a *ngIf="hasFile" [href]="editInWordUrl()" target="_blank" class="material-icons upload-widget__icon"><i *ngIf="hasFile" class="material-icons upload-widget__icon">edit</i></a>
				<label *ngIf="hasFile" class="upload-widget__label" [attr.for]="field.id">{{field.name}}</label><br>
				<label *ngIf="hasFile" class="upload-widget__label" [attr.for]="field.id">{{value}}</label>
			</div>
            <div title="Open Document for Viewing">
				<a *ngIf="hasFile" href="http://demo:9090/activiti-app/app/rest/content/{{id}}/rendition/preview">
					<img *ngIf="hasFile" class="upload-widget" border="1" src="http://demo:9090/activiti-app/app/rest/content/{{id}}/rendition/thumbnail">
				</a>
			</div>
        </div>
    </div>
...
`

Because the edit in MS Word url has a "non-standard" protocol, we must whitelist it, i did this as follows in /home/vagrant/default-adf-1-1/node_modules/ng2-activiti-form/src/components/widgets/display-value/display-value.widget.ts:

`
...
editInWordUrl(){
		return this.sanitizer.bypassSecurityTrustUrl('ms-word:ofe|u|http://demo:9090/activiti-app/aos/' + this.id + '/' + this.value);
	}
...
`

**Comment by DenysVuika** [comment]
ACA (https://github.com/Alfresco/alfresco-content-app) already provides extensions to Edit in Office via Alfresco Office Services; the Alfresco Digital Workspace also provides integration with Office 365
