### ISSUE TITLE
Minification is not working because of alfresco-js-api

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1693]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
Right now production build has minification switched off for production builds because of `alfresco-js-api` 1.2.0 is pointing to the ES6 code instead of the compiled bundle (within package.json).

Note: this was fixed for 1.2.1 version of `alfresco-js-api` and needs to be fixed for demo shell and yeoman generators now.

**Expected behavior:**
Production build should have minification fixed enabled by default.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
https://github.com/Alfresco/alfresco-js-api/pull/207 fix this issue
