### ISSUE TITLE
Support for attach folder widget

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#1698]
Newly added widget 'attach folder' added in Process Service 1.6 should be supported

<img width="261" alt="screen shot 2017-03-07 at 14 56 15" src="https://cloud.githubusercontent.com/assets/13200338/23662096/6761b48c-0346-11e7-93d7-81eda737cfe2.png">

**Comment by magemello** [comment]
please use the template

**Comment by VitoAlbano** [comment]
https://issues.alfresco.com/jira/browse/ADF-325 this will be solved with this task
