### ISSUE TITLE
Support row selection when in double-click nav mode

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#170]
When document list component is using 'double-click' navigation mode the single click should select entire row.

The selected row should be visually identified, i.e. changing the text/background colour.

**Comment by DenisVuyka** [comment]
This should also help showing selected Activiti Task when navigating from the Process Details.

**Comment by hashraf88** [comment]
Only in Safari (fine in Chrome and Firefox) the last row is not highlighted correctly, the bottom of a row is not highlighted as other rows are. 

**Last row**
<img width="1395" alt="screen shot 2017-01-17 at 11 19 17" src="https://cloud.githubusercontent.com/assets/13200338/22018569/549abb7a-dca7-11e6-89d4-750b81704b5d.png">

**Other rows**
<img width="1393" alt="screen shot 2017-01-17 at 11 19 28" src="https://cloud.githubusercontent.com/assets/13200338/22018567/547f7702-dca7-11e6-9566-05c3ceb797a3.png">
