### ISSUE TITLE
 Tabs are not rendered when fetched via <activiti-form> component 

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1709]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
 Tabs are not rendered when fetched via <activiti-form> component.Tabs are displayed correctly on a start form <activiti-start-form>, no issues

**Expected behavior:**
Expects the tabs to be rendered correctly when using <activiti-form> component.

**Steps to reproduce the issue:**
My config was 
<activiti-form
            [readOnly]="true"
            [formId]="'3008'"
            [showValidationIcon]="false"
            [data]="claimDetails"
            [showTitle]="false"
            [showSaveButton]="false"
            [showDebugButton]="false"
            [showRefreshButton]="false">
        </activiti-form>

**Component name and version:** 
ng2-activiti-form.

**Browser and version:** 
Chrome, possibly in all

**Comment by DenisVuyka** [comment]
Cannot reproduce this issue with current development branch (1.4.0)
