### ISSUE TITLE
Provide documentation and examples on using custom stencil properties

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1713]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**

**Expected behavior:**
Provide documentation and examples on using custom stencils and accessing stencil properties.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
Article on Alfresco community:

https://community.alfresco.com/docs/DOC-6610-custom-stencils-with-adf

Readme:

https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/docs/stencils.md
