### ISSUE TITLE
Make the applicable input/output on activiti-task-details in activiti-start-form as well

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1718]
**Type of issue:**  (check with "[x]")
```
- [ x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```

**New feature request:**
Features available in activiti-task-details (ng2-activiti-tasklist) (eg: @Output() formLoaded, @Output() onError) are applicable for activiti-start-form (ng2-activiti-form) too. Please make those applicable input/outputs on activiti-start-form component.

**Comment by DenisVuyka** [comment]
@cijujoseph Could you please check whether `FormService` provides what's needed for your scenarios in terms of events? See this [readme section](https://github.com/Alfresco/alfresco-ng2-components/tree/master/ng2-components/ng2-activiti-form#formservice)

**Comment by DenisVuyka** [comment]
Start form is missing "FormLoaded" event wiring with FormService, will be fixed shortly.

**Comment by cijujoseph** [comment]
Thanks Denis. FormService has what I need, I basically need to update form.values with my data.

**Comment by DenisVuyka** [comment]
Is https://github.com/Alfresco/alfresco-ng2-components/issues/1719 still actual of we can close it?

**Comment by cijujoseph** [comment]
yes, #1719 can be closed as it is very much a duplicate of this.

**Comment by cijujoseph** [comment]
I have tried onFormLoaded with an activiti-start-form component and it is not working!

**Comment by cijujoseph** [comment]
Following is my config and no luck!
<activiti-start-form [processDefinitionId]="processDefinitionId"
                              [showRefreshButton]="false"
                              [showOutcomeButtons]="true"
                              (formLoaded)="onFormLoaded($event)"
                              (outcomeClick)="onOutcomeClick($event)">
            </activiti-start-form>

 onFormLoaded(event: any){
     console.log("loaded")
  }

**Comment by DenisVuyka** [comment]
Do we still need this ticket opened?

**Comment by cijujoseph** [comment]
I am able to subscribe to event the following way - formService.formLoaded.subscribe((e: FormEvent) => {});
Happy for it to be closed.
