### ISSUE TITLE
Provide documentation and samples on Form validation

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1721]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
- [x] Documentation
```
**Current behaviour:**

**Expected behavior:**
Provide documentation and examples on Form validation. 

The topics of interest:
- Existing form field validators
- Creating custom validators
- Maintaining default validators (creating own sets, replacing existing, etc.)

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by tdonovancsra** [comment]
+1 Would be very interested in this

**Comment by tdonovancsra** [comment]
+2 ;)

**Comment by DenisVuyka** [comment]
Already implemented.
