### ISSUE TITLE
To be able to inject process level information and format the task details header values

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#1727]
**Type of issue:**  (check with "[x]")
```
- [ X] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
unable to customize the task details header with task specific information

**New feature request:**
To be able to put process level information in the task header for context on the task as a whole.  
to be able to format the date format instead of seeing 'today' for example

**Component name and version:** 
ng2-alfresco-task-list 
    task-details
   task-header

**Comment by fcorti** [comment]
Both the issues should be addressed with the most recent versions of ADF.
Please raise new issues proving more details, in case what exists today is not enough.
Thanks.
