### ISSUE TITLE
Provide support for Angular CLI

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1733]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**

For the moment `demo shell` and `yeoman app generator` are using custom build configuraiton.
The build and configuration process will be greatly simplified if both projects support Angular CLI.

**Expected behavior:**
Provide Angular CLI support for `demo shell` and `yeoman app generator`.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by tdonovancsra** [comment]
+1
