### ISSUE TITLE
Angular application not working for Internet Explorer 11

### ISSUE THREAD

**Issue by silviuMr** [Alfresco/alfresco-ng2-components#1734]
[ ] New feature request
 [x] Bug  
 [ ] Support request
 [ ] Documentation

**Current behaviour:**
The "Loading Demo Shell" message is displayed at the top of the screen in a never-ending loop.

**Expected behavior:**
The login page should appear when accessing the application.

**Steps to reproduce the issue:**
Launch Internet Explorer and go to the address where the the app started (ex: http://localhost:3000). In Firefox, Chrome and Safari this behaviour is not reproduced, everything loads up as it should.

This seems to be a similar issue as [this](https://github.com/Alfresco/alfresco-ng2-components/issues/932#issuecomment-266848336) and [this](https://github.com/Alfresco/alfresco-js-api/issues/121)
![ie11_not_loading](https://cloud.githubusercontent.com/assets/14122022/24037864/df99de84-0b07-11e7-98fa-cbe493a7395d.png)

**Component name and version:** 
Standard ng2-alfresco-app from DOC-4595

**Browser and version:** 
Internet Explorer 11.953.14393.0
 
**Node version (for build issues):**  
6.10.0

**Comment by eromano** [comment]
@silviuMr refer to the https://github.com/Alfresco/generator-ng2-alfresco-app/issues/71 https://github.com/Alfresco/generator-ng2-alfresco-app/commit/6233be97273da8c444abd3abb99dfe0119ed3ec8  to understand how to fix this issue.
