### ISSUE TITLE
Upload Service should provide all APIs needed to build custom UI

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#1735]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
For the moment it is difficult customising the look and feel of existing Upload status dialog.

**Expected behaviour:**
Upload Service should provide enough APIs to build custom build visualisation of the Upload process.

Sample scenario:

- as a developer, I would like to have an embedded panel control on the sidebar showing upload progress, I would like to build my HTML elements to the collection of Files being uploaded, or trigger cancelling of uploads easily.
- there should be numerous events exposed so that my code can react accordingly (file dropped, folder dropped, upload progress, upload cancel, etc.)

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by john-knowles** [comment]
Thinking about all the possible events:

- file dropped
- folder dropped
- upload progress
- upload in progress/not started cancel
- uploaded file delete
- pause/resume upload
- upload error responses

**Comment by DenisVuyka** [comment]
@john-knowles I think 'pause/resume' features deserves a separate issue as it might become a huge effort. In order to properly pause upload server side needs to support upload in chunks and chunk management (I don't now whether public REST APIs support that). We could, however, provide lightweight implementation, where only upcoming (queued) files are paused, while those 'in progress' continue to upload.

**Comment by john-knowles** [comment]
Sounds good to me!  The REST API will support resumable uploads in the next main release (see REPO-329 in JIRA).

**Comment by pionnegru** [comment]
Also, the service needs the interface through which the queue could be cleared manually.
We don't destroy the dialog  since the user needs the visual progress while navigating through the app sections. Once the uploads are done and dialog is closed, on next upload, the queue has the last files uploaded.
