### ISSUE TITLE
Configuration driven datatable for mobile/desktop views

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1739]
**Type of issue:**  (check with "[x]")
```
- [ x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```

**New feature request:**
The current version of data-table is not mobile friendly. It would be great if the input configuration can allow certain fields/columns to be configured with "desktop-only" css to make it look nice on mobile devices

**Comment by DenisVuyka** [comment]
There are embedded styles for document list already to hide columns on mobile devices: https://github.com/Alfresco/alfresco-ng2-components/blob/master/demo-shell-ng2/app/components/files/files.component.html have you tried that with data table?

**Comment by cijujoseph** [comment]
Yeah, trying that option now on my <alfresco-datatable> component which I am using to show a list of records. This is a forward looking feature request which I thought would be useful for a developer to specify desktop/mobile when defining the SchemaColumn!

**Comment by cijujoseph** [comment]
closing the issue. The feature already exist - cssClass: 'desktop-only' in datatable!
