### ISSUE TITLE
Demo shell is not working in Safari and IE11

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#1742]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by pionnegru** [comment]
seems to be https://github.com/Alfresco/alfresco-ng2-components/issues/1693

**Comment by magemello** [comment]
closing duplicate of #1734
