### ISSUE TITLE
Missing documentation for custom columns and custom action in datatable Readme

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#1752]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [ ] Support request
- [ x ] Documentation
```
**Current behaviour:**

Missing documentation for custom columns and custom action in datatable Readme
**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
@magemello all docs are in the readme.md (development branch)

- https://github.com/Alfresco/alfresco-ng2-components/tree/development/ng2-components/ng2-alfresco-datatable#datacolumn-properties (and example of html above that section)
- https://github.com/Alfresco/alfresco-ng2-components/tree/development/ng2-components/ng2-alfresco-datatable#showrowactionsmenu-event
