### ISSUE TITLE
Office docs support ng2 viewer

### ISSUE THREAD

**Issue by anikets43** [Alfresco/alfresco-ng2-components#1825]
Greetings!! 

Does ng2-viewer supports MS office files like ppt, pptx to view in the browser.

Cheers,
Aniket

**Comment by eromano** [comment]
Hi @anikets43 ,

no the viewer doesn't support those files extensions. The list of the extensions supported is here:

https://github.com/Alfresco/alfresco-ng2-components/tree/master/ng2-components/ng2-alfresco-viewer

The viewer has some extension point where you can add your custom viewer extension you can find how to do it : 

https://github.com/Alfresco/alfresco-ng2-components/tree/master/ng2-components/ng2-alfresco-viewer

https://www.slideshare.net/EugenioRomano/adf-in-action-12

For other questions about the framework and his components please use the gitter cahnnel:

https://gitter.im/Alfresco/alfresco-ng2-components
