### ISSUE TITLE
Ability to remove the debug button from Task Details Component

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1826]
**Type of issue:**  (check with "[x]")
```
- [ x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```

**New feature request:**
Currently activiti-task-details.component shows the "Debug" button all the time. Please add an input to keep/remove the debug button. Please add an input "showDebugButton" to align with the form component

**Comment by eromano** [comment]
duplicate https://github.com/Alfresco/alfresco-ng2-components/issues/1655
