### ISSUE TITLE
Ability to add content to a Task (ng2-activiti-tasklist component)

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/alfresco-ng2-components#1828]
**Type of issue:**  (check with "[x]")
```
- [ x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```

**New feature request:**
APS OOTB UI allows you to add content to a task (outside of the form). Please see attached screenshot.
<img width="1386" alt="screen shot 2017-04-19 at 4 29 03 pm" src="https://cloud.githubusercontent.com/assets/2080360/25203139/aed6d092-251d-11e7-867a-5c78674b6f58.png">
Please add this component to ng2-activiti-tasklist

**Comment by eromano** [comment]
Hi @cijujoseph ,

we already are working on it https://issues.alfresco.com/jira/browse/ADF-491
