### ISSUE TITLE
Even   in  the  Service   for   Document  Action  LifeCycle

### ISSUE THREAD

**Issue by vikashsingh005** [Alfresco/alfresco-ng2-components#1830]
Currently  I have  a  situation  where  i  want  to   use  Event   Like  File  Deleted ,Folder  Deleted ,Folder  Created, Folder  Deleted .So   that  we  will  use   this   features to  Perform  Other  Operation  especially we  want  to   Call  some  API  Over  It

**Comment by eromano** [comment]
@vikashsingh005 please use the template
