### ISSUE TITLE
Blank page after running the demo of a component

### ISSUE THREAD

**Issue by methanome** [Alfresco/alfresco-ng2-components#1870]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [ ] Bug  
- [X] Support request
- [ ] Documentation
```
**Current behaviour:**

I followed the instructions in this page to run the demo: https://github.com/Alfresco/alfresco-ng2-components/tree/master/ng2-components
But when I execute the demo I get a blank page with the following error in the console:

Error: @http://localhost:34541/node_modules/ng2-alfresco-documentlist/index.js:29:27
	@http://localhost:34541/node_modules/ng2-alfresco-documentlist/index.js:1:31
	@http://localhost:34541/node_modules/ng2-alfresco-documentlist/index.js:1:2
	@http://localhost:34541/src/main.js:31:35
	@http://localhost:34541/src/main.js:1:31
	@http://localhost:34541/src/main.js:1:2
	ZoneDelegate.prototype.invoke@http://localhost:34541/node_modules/zone.js/dist/zone.js:232:17
	Zone.prototype.run@http://localhost:34541/node_modules/zone.js/dist/zone.js:114:24
	scheduleResolveOrReject/<@http://localhost:34541/node_modules/zone.js/dist/zone.js:502:52
	ZoneDelegate.prototype.invokeTask@http://localhost:34541/node_modules/zone.js/dist/zone.js:265:21
	Zone.prototype.runTask@http://localhost:34541/node_modules/zone.js/dist/zone.js:154:28
	drainMicroTaskQueue@http://localhost:34541/node_modules/zone.js/dist/zone.js:401:25
	ZoneTask/this.invoke@http://localhost:34541/node_modules/zone.js/dist/zone.js:339:25
	
	Evaluating http://localhost:34541/node_modules/ng2-alfresco-core/index.js
	Evaluating http://localhost:34541/node_modules/ng2-alfresco-documentlist/index.js
	Evaluating http://localhost:34541/src/main.js
	Error loading http://localhost:34541/src/main.js

**Expected behavior:**

After using npm run start, the demo of the component should start correctly. 
**Steps to reproduce the issue:**

cd ng2-alfresco-documentlist
npm install
npm link
npm run build:w
--from another terminal--
cd ng2-alfresco-documentlist
cd demo
npm install
npm link ng2-alfresco-documentlist
npm run start
Result: a blankpage with a console error @http://localhost:34541/
I tested with ng2-alfresco-login, same behaviour.
**Component name and version:** 

I'm trying to test the component ng2-alfresco-documentlist. I downloaded all the components from the repository:  https://github.com/Alfresco/alfresco-ng2-components.git
**Browser and version:** 

 Firefox 53.0 (64-bit)
Ubuntu 16.04
**Node version (for build issues):**  

node v5.12.0
npm v3.8.6
**New feature request:**

**Comment by eromano** [comment]
I tested all the demo before the 1.5.0 release and are working
