### ISSUE TITLE
Expose a Claim Task event on activiti-task-details.component 

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#1883]
**Type of issue:**  (check with "[x]")
```
- [x ] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```

**New feature request:**
Would it be possible for the activiti-task-details.component.ts to expose an event on the onClaim Task event?  This would enable some external actions when the user does this action

**Comment by eromano** [comment]
I thinks is possible ? would be possible for you create a PR?

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-645
