### ISSUE TITLE
Partial conversion of the private api calls to the public api 

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#1884]
**Type of issue:**  (check with "[x]")
```
- [x ] New feature request
- [ x] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
The private api is still being called because of #729.  Version 1.4.0 rolled back the changes that were put in to call the public api because of #729 but I don't think it was necessary to completely roll all that back. Specifically we need the call for form variables to at minimum to be put back in to public calls. 

GET /activiti-app/app/rest/tasks/${taskId}/variables

in 1.3.0 the api call is set to this which works just fine for us
activiti-app/api/enterprise/tasks/${taskId}/variables

This is a big issue for use because we cannot use the private api in production because we use a different authentication scheme.  Is it possible to fold this call in and work on the rest later?  We are anticipating fixes in the 1.5.0 release but we are stuck having to use the 1.3.0 version of the alfresco-js-api because of the issues above.  

Is there a solution we can come to until the actual full api on the backend gets fixed?

**New feature request:**
 Partial roll out of the public calls that work.

**Comment by tdonovancsra** [comment]
+10 . We need some sort of path forward for this

**Comment by VitoAlbano** [comment]
We have changed to the new enterprise api task-forms/{task-id}/variables.
This has already been released on js-api, https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-activiti-rest-api/src/api/TaskFormsApi.js.

I'll close this issue as it is fixed.
