### ISSUE TITLE
ng2-alfresco-core breaks from @angular/material": "2.0.0-beta.4" onwards

### ISSUE THREAD

**Issue by tom-vandepoele** [Alfresco/alfresco-ng2-components#1926]
**Type of issue:**  (check with "[x]")
```
- [ ] New feature request
- [X] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
 alfresco-ng2-components uses @angular/material 2.0.0-beta.1

**Expected behavior:**
As alfresco-ng2-components started to use Angular 4, I'd expect it to use the latest version of @angular/material (which is currently 2.0.0-beta.6, not 2.0.0-beta.1)

However, when switching, ng2-alfresco-core breaks

**Steps to reproduce the issue:**
I've tried replacing "@angular/material": "2.0.0-beta.1" with "@angular/material": "2.0.0-beta.6" due to some fixes required.

From "@angular/material": "2.0.0-beta.4" onwards they have removed the forroot:

> The forRoot method on all Angular Material modules has been removed. It was previously deprecated and a no-op. Importing the modules directly will have the same effect.

Info on https://github.com/angular/material2/releases

This breaks ng2-alfresco-core.

Just thought I'd mention it so it can be addressed.

**Comment by DenisVuyka** [comment]
This is already addressed for the 1.6.0 release
