### ISSUE TITLE
No official method to get form values which later on can be passed to *data* property in <activiti-form>

### ISSUE THREAD

**Issue by zielinskikamil** [Alfresco/alfresco-ng2-components#2005]
**Type of issue:**  (check with "[x]")
```
- [x] New feature request
- [ ] Bug  
- [ ] Support request
- [ ] Documentation
```
**Current behaviour:**
There is no offical exposed method to get form data (of type FormValues) which can be latter on be passed again to ``` @Input() data: FormValues;```. Current work around is activiti-form.form.values. 

The similar issue is when a user saves a form. From the passed event only way to get form values is by using ```event.values```.

Please also notice an inconsistency in naming. To pass form values to <activiti-form> component, ```[data]``` property is used, but to get this data object, form.values property is used.

**Expected behavior:**
New method/updated doc to get form values. Possibly fix naming inconsistency.

**Steps to reproduce the issue:**
1. Go to documentation. Notice that there is no information about how to get form values, which later on can be passed again via [data] property.

**Component name and version:** 
ng2-activiti-form: 1.5.0

**Browser and version:** 
all

**New feature request:**
We would like to use ADF in offline mode. Where user can save his changes as a draft and come back to it later on. According to the documentation, it is possible to pass *data* but there is no information how to get this data.

**Comment by eromano** [comment]
Hi @zielinskikamil you can listen the events raised from the form where we pass also inside the form values. You can see the documentation [here](https://github.com/Alfresco/alfresco-ng2-components/tree/development/ng2-components/ng2-activiti-form#events)
### Events

| Name |  Return Type | Description |
| --- | --- | --- | 
| formLoaded | [FormModel](https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts) | Invoked when form is loaded or reloaded. |
| formSaved | [FormModel](https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts)  | Invoked when form is submitted with `Save` or custom outcomes.  |
| formCompleted | [FormModel](https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts)  | Invoked when form is submitted with `Complete` outcome.  |
| formDataRefreshed | [FormModel](https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/src/components/widgets/core/form.model.ts) | Invoked when form values are refreshed due a data property change  |
| executeOutcome | [FormOutcomeEvent](https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/src/components/widgets/core/form-outcome-event.model.ts) | Invoked when any outcome is executed, default behaviour can be prevented via `event.preventDefault()` |
| onError | any | Invoked at any error |

**Comment by DenisVuyka** [comment]
The Form component behaviour is based on the underlying model class instance, so accessing 'component.form.something' is a valid approach, and there are many other APIs you can get from FormModel and FormService types.

The `@Input() data` property is an initial set of form field values you want to use when loading/rendering form definition. Once this data is applied it is FormModel that is responsible for the rest. Don't treat this property as 1:1 mapping of the FormModel.values.

Every `FormEvent` instance contains a reference to the `FormModel` from where you can access to many other stuff, so there's no naming inconsistency here, it is always the `form.something`.

**Comment by zielinskikamil** [comment]
Hey @DenisVuyka, thanks for a response. Your response clears things a bit. I think we can close this issue.
