### ISSUE TITLE
is it possible to show collapsing row data while onclick on a row using ng2-datatable

### ISSUE THREAD

**Issue by dhrn** [Alfresco/alfresco-ng2-components#2058]
how  to **create collapsing row data while onclick on a table row.**(http://materializecss.com/collapsible.html)   
Is it possible with ng2-alfresco-datatable?
**please reply here is it possible or not?**

**Comment by eromano** [comment]
@dhrn we don't have this capability at the moment. Feel free to use the gitter channel for questions: https://gitter.im/Alfresco/alfresco-ng2-components
