### ISSUE TITLE
can't start the ng2-activiti-tasklist demo

### ISSUE THREAD

**Issue by SourenaSahraian** [Alfresco/alfresco-ng2-components#2094]
Getting the below error when doing : npm start

ERROR in /Users/ssahraian/Downloads/alfresco-ng2-components/alfresco-ng2-components/ng2-components/ng2-activiti-tasklist/demo/node_modules/ng2-activiti-tasklist/src/components/activiti-task-details.component.ts
(155,30): error TS2339: Property 'taskId' does not exist on type 'SimpleChanges'.

ERROR in /Users/ssahraian/Downloads/alfresco-ng2-components/alfresco-ng2-components/ng2-components/ng2-activiti-tasklist/demo/node_modules/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
(136,21): error TS2339: Property 'selectionMode' does not exist on type 'SimpleChanges'.

ERROR in /Users/ssahraian/Downloads/alfresco-ng2-components/alfresco-ng2-components/ng2-components/ng2-activiti-tasklist/demo/node_modules/ng2-alfresco-datatable/src/components/datatable/datatable.component.ts
(136,47): error TS2339: Property 'selectionMode' does not exist on type 'SimpleChanges'.

ERROR in /Users/ssahraian/Downloads/alfresco-ng2-components/alfresco-ng2-components/ng2-components/ng2-activiti-tasklist/demo/node_modules/ng2-alfresco-core/src/utils/file-utils.ts
(19,13): error TS2304: Cannot find name 'WebKitFileEntry'.

ERROR in /Users/ssahraian/Downloads/alfresco-ng2-components/alfresco-ng2-components/ng2-components/ng2-activiti-tasklist/demo/node_modules/ng2-alfresco-core/src/directives/upload.directive.ts
(191,45): error TS2339: Property 'webkitGetAsEntry' does not exist on type 'DataTransferItem'.

ERROR in /Users/ssahraian/Downloads/alfresco-ng2-components/alfresco-ng2-components/ng2-components/ng2-activiti-tasklist/demo/node_modules/ng2-alfresco-core/src/directives/upload.directive.ts
(192,49): error TS2339: Property 'webkitGetAsEntry' does not exist on type 'DataTransferItem'.

**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
Hi @SourenaSahraian  we moved the demo out of the project to better maintain them. Since the next version will not be anymore in this repo. You can find the working example here https://github.com/Alfresco/adf-examples/tree/master/ADF_1.6.1/process-list-tasklist-demo thanks
