### ISSUE TITLE
Cannot run "npm run build"

### ISSUE THREAD

**Issue by Fengjun-Wang** [Alfresco/alfresco-ng2-components#2160]
After I did "npm install ng2-activiti-diagrams", I went into the folder, and run "npm install", everything works well except for some warnings. Then I tried to run "npm build", or "npm run build", and there are many errors.
Who has some ideas?

>>>>>ERROR MESSAGE:
.\ng2-activiti-diagrams\node_modules\webpack\bin\webpack.js:315
                throw e;
                ^

Error: Cannot find .\node_modules\ng2-activiti-diagrams\tsconfig.json" file. Please check webpack and ForkTsCheckerWebpackPlugin configuration.

**Comment by eromano** [comment]
Hi @Fengjun-Wang  
What are you trying to do?
did you modify something in the component? Usually the build is used when you directly modify the component.
If you are using it only in your project you don't need to build it. The build is already in the bundles folder

**Comment by eromano** [comment]
close issue
