### ISSUE TITLE
isLoggedIn method of EcmAuth client is returning "true" when ticket expires

### ISSUE THREAD

**Issue by ConstantinMatheis** [Alfresco/alfresco-ng2-components#2178]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
This issue has already been addressed: https://issues.alfresco.com/jira/browse/ADF-451
Unfortunately, isLoggedIn still returns true when the ticket has expired, so when a user navigates to the app it can happen that the app thinks he is logged in and tries to show him the document-list. Because the app is unauthorized to get the nodes from the Alfresco server it just displays the loading screen. Only when the user clicks on any other menu item after seeing the loading screen he gets redirected to the login page. 

**Expected behavior:**
isLoggedIn returns true if the ticket is invalid or at least an error is thrown that can be caught with a custom implementation of ErrorHandler so that the user doesn't see the loading screen of the document list and is immediately redirected to the login page.

**Browser and version:** 
ADF: 1.7.0
Browsers: all

**Steps to reproduce the issue:**
Invalidate the ticket, e.g.

1. log into the ADF app
2. open a new browser tab and again navigate to the app (now you should be logged in automatically)
3. in the just opened tab click on "logout" (or whatever it is called in your specific app)
4. switch back to the previous tab and try to navigate to a component that uses a document-list
5. now you see the document-list loading screen

**Comment by eromano** [comment]
I am not able to replicate it are you using the demo shell?

**Comment by ConstantinMatheis** [comment]
I replicated it in the demo shell and in our own application. I saw that you have added a [commit](https://github.com/Alfresco/alfresco-js-api/commit/4c6a9a4c914d58c318f6a6e8d6111f854c94caf7) that invalidates the ticket when the application receives a 401. Unfortunately, the user isn't redirected to the login page immediately but sees this:
![unauthorized](https://user-images.githubusercontent.com/26505965/29349778-e1e018e0-825b-11e7-9863-c9e6027deafa.PNG).
I've written a custom implementation of ErrorHandler that redirects the user to the login page on every error it receives but the error doesn't get to the handler.

**Comment by DenisVuyka** [comment]
Is this issue still valid with the [AuthGuardEcm](https://alfresco.github.io/adf-component-catalog/injectables/AuthGuardEcm.html) route guard from 2.0.0 ?

**Comment by eromano** [comment]
no update I am closing the issue , please feel free to reopen if this bug is still presenti in 2.0.1>

**Comment by ariksidney** [comment]
Hi all,

I have the same issue (with ADF 2.4.0). When I'm logged in, delete the ticket via the API and then try to navigate to a different folder, I just see the loader forever.
![image](https://user-images.githubusercontent.com/15780097/46477684-7c36ac80-c7eb-11e8-97a4-9a8a34af5986.png)
Does somebody else has this issue or is there a solution?

**Comment by DenysVuika** [comment]
@ariksidney it's your application responsibility to detect 401 and redirect to login, the Document List is not responsible for that. You can use this approach to handle all JS-API errors: https://github.com/Alfresco/alfresco-content-app/blob/master/src/app/app.component.ts#L66

**Comment by ariksidney** [comment]
@DenysVuika Awesome thanks, I tried it with an Interceptor to detect 401 errors, but it's not working. I try your approach.

**Comment by DenysVuika** [comment]
JS API is not based on Angular, so Angular interceptor won’t work in this case.
