### ISSUE TITLE
document-list only sorts the nodes that are currently displayed

### ISSUE THREAD

**Issue by ConstantinMatheis** [Alfresco/alfresco-ng2-components#2184]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
when sorting the document-list (with pagination enabled) it only sorts the nodes that are currently displayed on a page

**Expected behavior:**
nodes that are in the current folder but not displayed due to the row limit should also be sorted

**Steps to reproduce the issue:**
1. using the document-list component view a folder that contains more nodes than rows per page
2. sort the document-list by clicking on a header, e.g. name
3. the nodes that did not fit on the page are not affected by the sorting

**Component name and version:** 
ng2-alfresco-documentlist 1.7.0

**Browser and version:** 
all

**Comment by fcorti** [comment]
This is possible since ADF 4.0.
Please note that due to an enhanced REST endpoint, this feature will be possible only since ACS 7th version.
