### ISSUE TITLE
alfresco-search-control input field isn't cleared

### ISSUE THREAD

**Issue by ConstantinMatheis** [Alfresco/alfresco-ng2-components#2193]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
As long as the application isn't reloaded any text in the search input field stays there even if a user logs out and another one logs in.

**Expected behavior:**
The search input field should be emptied when a user logs out so that the next user that logs in can't see what the previous user has typed.

**Steps to reproduce the issue:**
1. log in
2. type something in the search field
3. log out
4. log in as another user
5. now you can still see the previously typed text in the input field

**Component name and version:** 
ng2-alfresco-search 1.7.0

**Browser and version:** 
Chrome 59, Firefox 54, IE 11

**Comment by eromano** [comment]
Hi @ConstantinMatheis are you sure is not saved somewhere in your browser ?

**Comment by ConstantinMatheis** [comment]
It also happens with the [example app](https://github.com/Alfresco/generator-ng2-alfresco-app) so it's not because some custom code broke it but maybe it's a weird default browser setting... Were you able to recreate the issue?

**Comment by eromano** [comment]
@ConstantinMatheis no from my environment

**Comment by ConstantinMatheis** [comment]
oh ok, then the reason could be some browser settings.
