### ISSUE TITLE
Catalog website available on a public URL

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#221]
http://devproducts.alfresco.me is a great website to discover and look at our widgets. We need to make sure this is available externally

**Comment by enzor** [comment]
Changed to https://devproducts.alfresco.com .

**Comment by binduwavell** [comment]
This is not working on iOS

**Comment by magemello** [comment]
Hi Bindu, can you explain us more about your issue?

**Comment by binduwavell** [comment]
It's working way better than it was this morning. Autocomplete was broken. Still has issues with "narrow" screen width (I am testing on an iPhone 6s Plus) where a bunch of text and images are truncated.
