### ISSUE TITLE
npm start or build error

### ISSUE THREAD

**Issue by Iamguy84** [Alfresco/alfresco-ng2-components#2244]
Hi folks,
I am using angular 4 with systemjs config.

**In app.module.ts**
```
import { CoreModule } from 'ng2-alfresco-core';
import { ViewerModule } from 'ng2-alfresco-viewer';
@NgModule({
  imports:[
    BrowserModule,
    CoreModule.forRoot(),
    ViewerModule.forRoot(),
    BrowserAnimationsModule,
    HttpModule,
    CommonModule,
    FormsModule,

    ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ]
})
export class AppModule { }
```
**In systemjs.config.js**
```
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/router/upgrade': 'npm:@angular/router/bundles/router-upgrade.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
      '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
      '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
      'primeng':                   'npm:primeng',

	  'ng2-alfresco-viewer': 'npm:ng2-alfresco-viewer',
	  'ng2-alfresco-core': 'npm:ng2-alfresco-core'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      },
      primeng: {
          defaultExtension: 'js'
      }
    }
  });
})(this);
```
I run npm start in command prompt and I am getting error message and it say:

> node_modules/@angular/material/typings/button-toggle/button-toggle.d.ts(32,22): error TS2420: Class 'MdButtonToggleGroup' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdButtonToggleGroup'.
> node_modules/@angular/material/typings/button-toggle/button-toggle.d.ts(32,50): error TS2507: Type '(new (...args: any[]) => CanDisable) & typeof MdButtonToggleGroupBase' is not a constructor function type.
> node_modules/@angular/material/typings/button-toggle/button-toggle.d.ts(91,22): error TS2420: Class 'MdButtonToggleGroupMultiple' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdButtonToggleGroupMultiple'.
> node_modules/@angular/material/typings/button-toggle/button-toggle.d.ts(91,58): error TS2507: Type '(new (...args: any[]) => CanDisable) & typeof MdButtonToggleGroupBase' is not a constructor function type.
> node_modules/@angular/material/typings/button/button.d.ts(55,22): error TS2420: Class 'MdButton' incorrectly implements interface 'CanColor'.
>   Property 'color' is missing in type 'MdButton'.
> node_modules/@angular/material/typings/button/button.d.ts(55,22): error TS2420: Class 'MdButton' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdButton'.
> node_modules/@angular/material/typings/button/button.d.ts(55,39): error TS2507: Type '(new (...args: any[]) => CanColor) & (new (...args: any[]) => CanDisable) & typeof MdButtonBase' is not a constructor function type.
> node_modules/@angular/material/typings/checkbox/checkbox.d.ts(55,22): error TS2420: Class 'MdCheckbox' incorrectly implements interface 'CanColor'.
>   Property 'color' is missing in type 'MdCheckbox'.
> node_modules/@angular/material/typings/checkbox/checkbox.d.ts(55,22): error TS2420: Class 'MdCheckbox' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdCheckbox'.
> node_modules/@angular/material/typings/checkbox/checkbox.d.ts(55,41): error TS2507: Type '(new (...args: any[]) => CanColor) & (new (...args: any[]) => CanDisable) & typeof MdCheckboxBase' is not a constructor function type.
> node_modules/@angular/material/typings/chips/chip.d.ts(31,22): error TS2420: Class 'MdChip' incorrectly implements interface 'CanColor'.
>   Property 'color' is missing in type 'MdChip'.
> node_modules/@angular/material/typings/chips/chip.d.ts(31,22): error TS2420: Class 'MdChip' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdChip'.
> node_modules/@angular/material/typings/chips/chip.d.ts(31,37): error TS2507: Type '(new (...args: any[]) => CanColor) & (new (...args: any[]) => CanDisable) & typeof MdChipBase' is not a constructor function type.
> node_modules/@angular/material/typings/core/option/optgroup.d.ts(9,22): error TS2420: Class 'MdOptgroup' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdOptgroup'.
> node_modules/@angular/material/typings/core/option/optgroup.d.ts(9,41): error TS2507: Type '(new (...args: any[]) => CanDisable) & typeof MdOptgroupBase' is not a constructor function type.
> node_modules/@angular/material/typings/core/selection/pseudo-checkbox/pseudo-checkbox.d.ts(29,22): error TS2420: Class 'MdPseudoCheckbox' incorrectly implements interface 'CanColor'.
>   Property 'color' is missing in type 'MdPseudoCheckbox'.
> node_modules/@angular/material/typings/core/selection/pseudo-checkbox/pseudo-checkbox.d.ts(29,47): error TS2507: Type '(new (...args: any[]) => CanColor) & typeof MdPseudoCheckboxBase' is not a constructor function type.
> node_modules/@angular/material/typings/icon/icon.d.ts(51,22): error TS2420: Class 'MdIcon' incorrectly implements interface 'CanColor'.
>   Property 'color' is missing in type 'MdIcon'.
> node_modules/@angular/material/typings/icon/icon.d.ts(51,37): error TS2507: Type '(new (...args: any[]) => CanColor) & typeof MdIconBase' is not a constructor function type.
> node_modules/@angular/material/typings/menu/menu-item.d.ts(19,22): error TS2420: Class 'MdMenuItem' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdMenuItem'.
> node_modules/@angular/material/typings/menu/menu-item.d.ts(19,41): error TS2507: Type '(new (...args: any[]) => CanDisable) & typeof MdMenuItemBase' is not a constructor function type.
> node_modules/@angular/material/typings/progress-spinner/progress-spinner.d.ts(29,22): error TS2420: Class 'MdProgressSpinner' incorrectly implements interface 'CanColor'.
>   Property 'color' is missing in type 'MdProgressSpinner'.
> node_modules/@angular/material/typings/progress-spinner/progress-spinner.d.ts(29,48): error TS2507: Type '(new (...args: any[]) => CanColor) & typeof MdProgressSpinnerBase' is not a constructor function type.
> node_modules/@angular/material/typings/radio/radio.d.ts(33,43): error TS2507: Type '(new (...args: any[]) => CanDisable) & typeof MdRadioGroupBase' is not a constructor function type.
> node_modules/@angular/material/typings/radio/radio.d.ts(133,22): error TS2420: Class 'MdRadioButton' incorrectly implements interface 'CanColor'.
>   Property 'color' is missing in type 'MdRadioButton'.
> node_modules/@angular/material/typings/radio/radio.d.ts(133,44): error TS2507: Type '(new (...args: any[]) => CanColor) & typeof MdRadioButtonBase' is not a constructor function type.
> node_modules/@angular/material/typings/select/select.d.ts(75,22): error TS2420: Class 'MdSelect' incorrectly implements interface 'CanColor'.
>   Property 'color' is missing in type 'MdSelect'.
> node_modules/@angular/material/typings/select/select.d.ts(75,22): error TS2420: Class 'MdSelect' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdSelect'.
> node_modules/@angular/material/typings/select/select.d.ts(75,39): error TS2507: Type '(new (...args: any[]) => CanColor) & (new (...args: any[]) => CanDisable) & typeof MdSelectBase' is not a constructor function type.
> node_modules/@angular/material/typings/slide-toggle/slide-toggle.d.ts(26,22): error TS2420: Class 'MdSlideToggle' incorrectly implements interface 'CanColor'.
>   Property 'color' is missing in type 'MdSlideToggle'.
> node_modules/@angular/material/typings/slide-toggle/slide-toggle.d.ts(26,22): error TS2420: Class 'MdSlideToggle' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdSlideToggle'.
> node_modules/@angular/material/typings/slide-toggle/slide-toggle.d.ts(26,44): error TS2507: Type '(new (...args: any[]) => CanColor) & (new (...args: any[]) => CanDisable) & typeof MdSlideToggleB...' is not a constructor function type.
> node_modules/@angular/material/typings/slider/slider.d.ts(34,22): error TS2420: Class 'MdSlider' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdSlider'.
> node_modules/@angular/material/typings/slider/slider.d.ts(34,39): error TS2507: Type '(new (...args: any[]) => CanDisable) & typeof MdSliderBase' is not a constructor function type.
> node_modules/@angular/material/typings/tabs/tab-label-wrapper.d.ts(18,22): error TS2420: Class 'MdTabLabelWrapper' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdTabLabelWrapper'.
> node_modules/@angular/material/typings/tabs/tab-label-wrapper.d.ts(18,48): error TS2507: Type '(new (...args: any[]) => CanDisable) & typeof MdTabLabelWrapperBase' is not a constructor function type.
> node_modules/@angular/material/typings/tabs/tab-nav-bar/tab-nav-bar.d.ts(43,22): error TS2420: Class 'MdTabLink' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdTabLink'.
> node_modules/@angular/material/typings/tabs/tab-nav-bar/tab-nav-bar.d.ts(43,40): error TS2507: Type '(new (...args: any[]) => CanDisable) & typeof MdTabLinkBase' is not a constructor function type.
> node_modules/@angular/material/typings/tabs/tab.d.ts(16,22): error TS2420: Class 'MdTab' incorrectly implements interface 'CanDisable'.
>   Property 'disabled' is missing in type 'MdTab'.
> node_modules/@angular/material/typings/tabs/tab.d.ts(16,36): error TS2507: Type '(new (...args: any[]) => CanDisable) & typeof MdTabBase' is not a constructor function type.
> node_modules/@angular/material/typings/toolbar/toolbar.d.ts(19,22): error TS2420: Class 'MdToolbar' incorrectly implements interface 'CanColor'.
>   Property 'color' is missing in type 'MdToolbar'.
> node_modules/@angular/material/typings/toolbar/toolbar.d.ts(19,40): error TS2507: Type '(new (...args: any[]) => CanColor) & typeof MdToolbarBase' is not a constructor function type.
> node_modules/alfresco-js-api/index.d.ts(3,25): error TS2304: Cannot find name 'AlfrescoApiConfig'.
> node_modules/alfresco-js-api/index.d.ts(3,45): error TS1093: Type annotation cannot appear on a constructor declaration.
> node_modules/alfresco-js-api/index.d.ts(29,13): error TS2304: Cannot find name 'AlfrescoApiConfig'.
> node_modules/alfresco-js-api/index.d.ts(31,15): error TS2304: Cannot find name 'Activiti'.
> node_modules/alfresco-js-api/index.d.ts(32,11): error TS2304: Cannot find name 'Auth'.
> node_modules/alfresco-js-api/index.d.ts(33,11): error TS2304: Cannot find name 'Core'.
> node_modules/alfresco-js-api/index.d.ts(34,16): error TS2304: Cannot find name 'Discovery'.
> node_modules/alfresco-js-api/index.d.ts(36,14): error TS2304: Cannot find name 'BpmAuthApi'.
> node_modules/alfresco-js-api/index.d.ts(37,14): error TS2304: Cannot find name 'EcmAuthApi'.
> node_modules/alfresco-js-api/index.d.ts(38,17): error TS2304: Cannot find name 'OauthApi'.
> node_modules/alfresco-js-api/index.d.ts(40,15): error TS2304: Cannot find name 'Activiti'.
> node_modules/alfresco-js-api/index.d.ts(41,11): error TS2304: Cannot find name 'Core'.
> node_modules/alfresco-js-api/index.d.ts(42,16): error TS2304: Cannot find name 'Discovery'.
> node_modules/alfresco-js-api/index.d.ts(43,13): error TS2304: Cannot find name 'AlfrescoUpload'.
> node_modules/alfresco-js-api/index.d.ts(47,12): error TS2304: Cannot find name 'NodesApi'.
> node_modules/alfresco-js-api/index.d.ts(48,14): error TS2304: Cannot find name 'ContentApi'.
> node_modules/alfresco-js-api/index.d.ts(49,5): error TS2300: Duplicate identifier 'upload'.
> node_modules/alfresco-js-api/index.d.ts(49,13): error TS2304: Cannot find name 'UploadApi'.
> node_modules/alfresco-js-api/index.d.ts(50,16): error TS2304: Cannot find name 'WebscriptApi'.
> node_modules/alfresco-js-api/index.d.ts(52,16): error TS2304: Cannot find name 'EcmClient'.
> node_modules/alfresco-js-api/index.d.ts(53,16): error TS2304: Cannot find name 'BpmClient'.
> node_modules/alfresco-js-api/index.d.ts(54,19): error TS2304: Cannot find name 'SearchClient'.
> node_modules/alfresco-js-api/index.d.ts(55,23): error TS2304: Cannot find name 'EcmPrivateClient'.
> node_modules/alfresco-js-api/index.d.ts(159,9): error TS2687: All declarations of 'list' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(167,9): error TS2687: All declarations of 'pagination' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(168,9): error TS2687: All declarations of 'entries' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(178,9): error TS2687: All declarations of 'count' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(179,9): error TS2687: All declarations of 'hasMoreItems' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(180,9): error TS2687: All declarations of 'totalItems' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(181,9): error TS2687: All declarations of 'skipCount' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(182,9): error TS2687: All declarations of 'maxItems' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(281,9): error TS2687: All declarations of 'displayName' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(282,9): error TS2687: All declarations of 'id' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(286,9): error TS2687: All declarations of 'mimeType' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(287,9): error TS2687: All declarations of 'mimeTypeName' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(288,9): error TS2687: All declarations of 'sizeInBytes' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(289,9): error TS2687: All declarations of 'encoding' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(325,84): error TS7006: Parameter 'opts' implicitly has an 'any' type.
> node_modules/alfresco-js-api/index.d.ts(365,9): error TS2687: All declarations of 'briefSummary' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(366,9): error TS2687: All declarations of 'descriptionURL' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(368,9): error TS2687: All declarations of 'stackTrace' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(369,9): error TS2687: All declarations of 'statusCode' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(744,9): error TS2687: All declarations of 'mimeType' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(745,9): error TS2687: All declarations of 'mimeTypeName' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(746,9): error TS2687: All declarations of 'sizeInBytes' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(747,9): error TS2687: All declarations of 'encoding' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(774,9): error TS2687: All declarations of 'briefSummary' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(775,9): error TS2687: All declarations of 'descriptionURL' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(777,9): error TS2687: All declarations of 'stackTrace' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(778,9): error TS2687: All declarations of 'statusCode' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(909,9): error TS2687: All declarations of 'list' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(913,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'entries' must be of type 'MinimalNodeEntity[]', but here has type 'NodeEntry[]'.
> node_modules/alfresco-js-api/index.d.ts(913,9): error TS2687: All declarations of 'entries' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(914,9): error TS2687: All declarations of 'pagination' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(915,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'source' must be of type 'Source', but here has type 'Node'.
> node_modules/alfresco-js-api/index.d.ts(919,9): error TS2687: All declarations of 'count' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(920,9): error TS2687: All declarations of 'hasMoreItems' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(921,9): error TS2687: All declarations of 'totalItems' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(922,9): error TS2687: All declarations of 'skipCount' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(923,9): error TS2687: All declarations of 'maxItems' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(1443,9): error TS2687: All declarations of 'displayName' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(1444,9): error TS2687: All declarations of 'id' must have identical modifiers.
> node_modules/alfresco-js-api/index.d.ts(1749,79): error TS7006: Parameter 'title' implicitly has an 'any' type.
> node_modules/alfresco-js-api/index.d.ts(1750,81): error TS7006: Parameter 'title' implicitly has an 'any' type.
> node_modules/alfresco-js-api/index.d.ts(1755,46): error TS7006: Parameter 'updateCustomModel' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/components/context-menu/context-menu-holder.component.ts(66,5): error TS7008: Member 'links' implicitly has an 'any[]' type.
> node_modules/ng2-alfresco-core/src/components/context-menu/context-menu-holder.component.ts(97,14): error TS7006: Parameter 'e' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/components/context-menu/context-menu-holder.component.ts(97,17): error TS7006: Parameter 'links' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/components/material/mdl-menu.directive.ts(20,13): error TS7005: Variable 'componentHandler' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/components/material/mdl-textfield.directive.ts(20,13): error TS7005: Variable 'componentHandler' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/components/material/mdl-upgrade-element.directive.ts(19,13): error TS7005: Variable 'componentHandler' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/components/view/card-view-dateitem.component.ts(48,17): error TS7006: Parameter 'changed' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/components/view/card-view-item-dispatcher.component.ts(46,5): error TS7008: Member 'ngOnInit' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/components/view/card-view-item-dispatcher.component.ts(47,5): error TS7008: Member 'ngDoCheck' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/components/view/card-view-item-dispatcher.component.ts(65,17): error TS7019: Rest parameter 'args' implicitly has an 'any[]' type.
> node_modules/ng2-alfresco-core/src/components/view/card-view-item-dispatcher.component.ts(92,19): error TS7006: Parameter 'methodName' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/components/view/card-view-item-dispatcher.component.ts(92,31): error TS7019: Rest parameter 'args' implicitly has an 'any[]' type.
> node_modules/ng2-alfresco-core/src/directives/upload.directive.ts(115,17): error TS7006: Parameter 'event' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/directives/upload.directive.ts(191,45): error TS2339: Property 'webkitGetAsEntry' does not exist on type 'DataTransferItem'.
> node_modules/ng2-alfresco-core/src/directives/upload.directive.ts(192,49): error TS2339: Property 'webkitGetAsEntry' does not exist on type 'DataTransferItem'.
> node_modules/ng2-alfresco-core/src/directives/upload.directive.ts(229,51): error TS2339: Property 'concat' does not exist on type '{}'.
> node_modules/ng2-alfresco-core/src/models/product-version.model.ts(50,55): error TS7006: Parameter 'module' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/models/site.model.ts(44,64): error TS7006: Parameter 'content' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/models/site.model.ts(50,61): error TS7006: Parameter 'member' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/alfresco-content.service.ts(116,63): error TS7006: Parameter 'currentPermission' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/alfresco-content.service.ts(118,63): error TS7006: Parameter 'currentPermission' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/content.service.ts(32,30): error TS7006: Parameter 'data' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/content.service.ts(32,36): error TS7006: Parameter 'format' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/content.service.ts(32,44): error TS7006: Parameter 'fileName' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/content.service.ts(88,29): error TS7006: Parameter 'fileName' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/discovery-api.service.ts(42,25): error TS7006: Parameter 'error' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/favorites-api.service.ts(85,25): error TS7006: Parameter 'error' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/people-api.service.ts(44,25): error TS7006: Parameter 'error' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/renditions.service.ts(37,35): error TS7006: Parameter 'observer' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/renditions.service.ts(53,35): error TS7006: Parameter 'observer' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/search-api.service.ts(43,25): error TS7006: Parameter 'error' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/translate-loader.service.ts(26,14): error TS2420: Class 'AlfrescoTranslateLoader' incorrectly implements interface 'TranslateLoader'.
>   Types of property 'getTranslation' are incompatible.
>     Type '(lang: string) => Observable<any>' is not assignable to type '(lang: string) => Observable<any>'. Two different types with this name exist, but they are unrelated.
>       Type 'Observable<any>' is not assignable to type 'Observable<any>'. Two different types with this name exist, but they are unrelated.
>         Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
> node_modules/ng2-alfresco-core/src/services/translate-loader.service.ts(46,13): error TS7034: Variable 'observableBatch' implicitly has type 'any[]' in some locations where its type cannot be determined.
> node_modules/ng2-alfresco-core/src/services/translate-loader.service.ts(53,17): error TS7005: Variable 'observableBatch' implicitly has an 'any[]' type.
> node_modules/ng2-alfresco-core/src/services/translate-loader.service.ts(63,16): error TS7005: Variable 'observableBatch' implicitly has an 'any[]' type.
> node_modules/ng2-alfresco-core/src/services/translate-loader.service.ts(73,46): error TS7006: Parameter 'x' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/translate-loader.service.ts(92,34): error TS7006: Parameter 'observer' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/translation.service.ts(32,29): error TS2352: Type 'TranslateLoader' cannot be converted to type 'AlfrescoTranslateLoader'.
>   Property 'prefix' is missing in type 'TranslateLoader'.
> node_modules/ng2-alfresco-core/src/services/translation.service.ts(59,16): error TS90010: Type 'Observable<any>' is not assignable to type 'Observable<any>'. Two different types with this name exist, but they are unrelated.
>   Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.
> node_modules/ng2-alfresco-core/src/services/translation.service.ts(63,16): error TS90010: Type 'Observable<any>' is not assignable to type 'Observable<any>'. Two different types with this name exist, but they are unrelated.
> node_modules/ng2-alfresco-core/src/services/upload.service.ts(19,28): error TS7016: Could not find a declaration file for module 'minimatch'. 'C:/Users/asalahuddin/Desktop/PrimeNG Demo Layout/node_modules/minimatch/minimatch.js' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/upload.service.ts(177,22): error TS7006: Parameter 'err' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/upload.service.ts(181,24): error TS7006: Parameter 'data' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/services/upload.service.ts(185,16): error TS7006: Parameter 'err' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/utils/file-utils.ts(19,13): error TS2304: Cannot find name 'WebKitFileEntry'.
> node_modules/ng2-alfresco-core/src/utils/file-utils.ts(30,17): error TS7034: Variable 'iterations' implicitly has type 'any[]' in some locations where its type cannot be determined.
> node_modules/ng2-alfresco-core/src/utils/file-utils.ts(32,37): error TS7006: Parameter 'entries' implicitly has an 'any' type.
> node_modules/ng2-alfresco-core/src/utils/file-utils.ts(34,37): error TS7005: Variable 'iterations' implicitly has an 'any[]' type.
> node_modules/ng2-alfresco-core/src/utils/file-utils.ts(36,25): error TS7005: Variable 'iterations' implicitly has an 'any[]' type.
> node_modules/ng2-alfresco-core/src/utils/file-utils.ts(36,65): error TS7006: Parameter 'entry' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(64,17): error TS7006: Parameter 'changes' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(84,16): error TS7006: Parameter 'src' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(84,21): error TS7006: Parameter 'resolve' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(84,30): error TS7006: Parameter 'reject' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(87,35): error TS7006: Parameter 'progressData' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(92,27): error TS7006: Parameter 'pdfDocument' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(102,17): error TS7006: Parameter 'error' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(106,13): error TS7006: Parameter 'error' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(147,15): error TS7006: Parameter 'scaleMode' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(215,53): error TS7006: Parameter 'currentPage' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(343,17): error TS7006: Parameter 'target' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(359,23): error TS7006: Parameter 'target' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/pdfViewer.component.ts(360,44): error TS7006: Parameter 'page' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/viewer.component.ts(69,17): error TS7006: Parameter 'document' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/components/viewer.component.ts(73,17): error TS7006: Parameter 'changes' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/directives/extension-viewer.directive.ts(54,57): error TS7006: Parameter 'fileExtension' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/directives/extension-viewer.directive.ts(70,15): error TS7006: Parameter 'fileExtension' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/services/rendering-queue.services.ts(48,15): error TS7006: Parameter 'pdfViewer' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/services/rendering-queue.services.ts(55,24): error TS7006: Parameter 'pdfThumbnailViewer' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/services/rendering-queue.services.ts(67,27): error TS7006: Parameter 'currentlyVisiblePages' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/services/rendering-queue.services.ts(94,24): error TS7006: Parameter 'visible' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/services/rendering-queue.services.ts(94,33): error TS7006: Parameter 'views' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/services/rendering-queue.services.ts(94,40): error TS7006: Parameter 'scrolledDown' implicitly has an 'any' type.
> node_modules/ng2-alfresco-viewer/src/services/rendering-queue.services.ts(135,20): error TS7006: Parameter 'view' implicitly has an 'any' type.

Waiting for your response.
Thanks in advance

**Comment by DenisVuyka** [comment]
We are not supporting system.js for a long time already. Please use webpack configurations provided with the generators or demo apps.
