### ISSUE TITLE
IE 11 problems with upload and downloading 

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#2280]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When using IE 11 in the ADF demo you cannot download documents.  When running on windows 7-10 you get Access Denied on any action to download.  On server 2012 you get a dialog:

Do you want to allow this website to open an app on your computer?  
click allow
then you get
"No apps are installed to open this type of link (blob)"

I tried with .txt, .pdf, .docx . 

This works in chrome of course

**Expected behavior:**
Downloads the file

**Steps to reproduce the issue:**
Install demo on windows machine. 
Upload document anywhere in the application 
Try to download it.

**Component name and version:** 
ADF 1.7 all

**Browser and version:** 
IE 11

**Node version (for build issues):**  
node 8.4.0 
npm 5.3.0

as an fyi we had a similiar behavior in another application and fixed it doing this if it helps
slightly different but may work

public openPdf(url: String) {
        let ua: string = window.navigator.userAgent;
        let windowsBrowserRegex = /Trident|MSIE|Edge/;
        let isIE = ua.match(windowsBrowserRegex);
        let newWindow: Window = null;

        if (!isIE) {
            newWindow = window.open('about:blank', '_blank');
        }

        let requestOptions: RequestOptions = new RequestOptions({
            responseType: ResponseContentType.ArrayBuffer
        });

        this.http.get(url.toString(), requestOptions).subscribe(response => {
            let file = new Blob([response['_body']], { type: 'application/pdf' });

            let fileURL = URL.createObjectURL(file);
            if (isIE) {
                window.navigator.msSaveOrOpenBlob(file, 'download.pdf');
            } else {
                newWindow.location.href = fileURL;
            }
        }, (error: any) => Observable.throw(error.json().error || 'Error getting document'));
    }

**Comment by tdonovancsra** [comment]
Also uploading on the new process and task attachment list only works if you drag and drop it.  The plus sign does't work

**Comment by DenisVuyka** [comment]
Notes for developers: might require polyfills for IE 11, as angular no longer supports it by default. Details on polyfills can be found in any Angular CLI generated project, i.e. https://github.com/Alfresco/angular-cli-adf-app/blob/master/src/polyfills.ts

**Comment by tdonovancsra** [comment]
Are you guys pulling support for IE11?

**Comment by DenisVuyka** [comment]
No, just put the links for whoever picks the task.

**Comment by tdonovancsra** [comment]
Tried your version of the polyfills above and get the same problem.  It looks for an application to open a blob.  I think you just need to send the correct content type

**Comment by tdonovancsra** [comment]
Any update on this?

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-1568
