### ISSUE TITLE
JS API - Document use of other APIs available in the v1 REST API

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#231]
Currently we have only documented how to use the thumbnail, addChildren and login APIs that we are using for the components.

We need to ensure that the JS API still exposes all other methods that are available in the public REST API and document how to access these capabilities.

**Comment by montgolfiere** [comment]
Just a heads up, the next Community EA 2016 (hopefully July or August) should hopefully also include additional REST API features, such as initial version history support.
