### ISSUE TITLE
People control is referencing the rest api instead of enterprise for pictures

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#2314]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When using the people control requests are being made to the rest api instead of the enterprise apit

http://localhost:9999/activiti-app/app/rest/users/2004/picture

**Expected behavior:**
either this call should not be made or it should target the enterprise api

**Steps to reproduce the issue:**
put a people control on the page and search for users

**Component name and version:** 
1.8

**Comment by tdonovancsra** [comment]
this.getUserProfilePictureUrl = function(userId) {
       return this.apiClient.basePath + '/app/rest/users/'+userId+'/picture';
    }

from the afresco-js-api 

This needs to be changed

**Comment by tdonovancsra** [comment]
this is still happening in beta7

**Comment by DenisVuyka** [comment]
I’m afraid yes.

**Comment by tdonovancsra** [comment]
will this be fixed for 1.9?
