### ISSUE TITLE
Breadcrumb issue on ADF 1.8

### ISSUE THREAD

**Issue by fsforna** [Alfresco/alfresco-ng2-components#2326]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Dear ADF developers, after upgrading the ADF framework from 1.7 to 1.8 we noticed various changes on breadcrumb behavior.
Now the breadcrumb root parameter can be used only to change the root name, instead by using the 1.7 release the root parameter sets the base folder as expected.

**Expected behavior:**
Configuring the root folder breadcrumb parameter, the breadcrumb tree should start from the folder that I specified before.

**Steps to reproduce the issue:**
By using the demo application, you can set the breadcrumb root parameter by editing the files.component.html.

<adf-breadcrumb
            #documentBreadCrumb
            [target]="documentList"
            [root]="YOUR ROOT NAME"
            [folderNode]="documentList.folderNode">
</adf-breadcrumb>

**Component name and version:** 
ADF 1.8
alfresco-document-list

**Browser and version:** 

 
Tested on Chrome and Firefox lastest versions.

**Node version (for build issues):**  
6.11.2

**New feature request:**

**Comment by DenisVuyka** [comment]
The updated component will allow setting both the custom name of the root element (including i18n resource keys as values) and the node id. You can test this feature once 1.9.0-beta2 is out.
