### ISSUE TITLE
Remove widget event writing to log

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#2330]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Looks like some debug code snuck in

Please take out line 

 protected event(event: Event): void {
        _**console.log(event);**_
        this.formService.formEvents.next(event);
    }

from WidgetComponent

widget.component.ts

**Expected behavior:**
doesn't log

**Steps to reproduce the issue:**
Look at the console when running application

**Component name and version:** 
1.9 beta 1

**Comment by eromano** [comment]
Had been removed in this PR https://github.com/Alfresco/alfresco-ng2-components/pull/2358/files
