### ISSUE TITLE
Created Service is not getting resolved in a Component

### ISSUE THREAD

**Issue by patelvikash** [Alfresco/alfresco-ng2-components#2364]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**
Getting compilation error

ERROR in ./app/components/mycomponents/myfirstpage.component.ts
Module not found: Error: Can't resolve 'app/my-services/test.service' in 'C:\Users\kintu.barot.c2\my-ADF\my-adf\app\components\myc
omponents'
 @ ./app/components/mycomponents/myfirstpage.component.ts 13:21-60
 @ ./app/components/index.ts
 @ ./app/app.module.ts
 @ ./app/main.ts
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 ./app/main.ts 

**Expected behavior:**
Should able to resolve created service in a component

**Steps to reproduce the issue:**
1. Create a folder in 'app' folder.
2. Create a service inside above created folder.
3. Create a new component.
4. Use created service in a component.

One can also refer project in a attached zip

**Component name and version:** 
Using adf 1.8.0

**Browser and version:** 
 
**Node version (for build issues):**  
v6.10.3

[my-adf.zip](https://github.com/Alfresco/alfresco-ng2-components/files/1320750/my-adf.zip)

**Comment by DenisVuyka** [comment]
The issue is related to how the service is imported. It should always be the relative path based on the component that performs import:

```ts
import { TestService } from '../../my-services/test.service';
```

**Comment by DenisVuyka** [comment]
I would also recommend declaring the service in `providers` section of the Module, not the Component one:

**app.module.ts**
```ts
import { TestService } from './my-services/test.service';

@NgModule({
  providers: [
    ...,
    TestService
  ]
})
export class AppModule { }
```

**Comment by vikash09** [comment]
Thank **DenisVuyka**, This worked for me.
