### ISSUE TITLE
Translation override file is not overriding translation labels

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#2412]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
We want to use our own verbiage for the claim label under task detail.   We've added the provider in the app.modules.ts

{
            provide: TRANSLATION_PROVIDER,
            multi: true,
            useValue: {
                name: 'app',
                source: 'resources'
            }
        }

and in the config files are copying the resources/i18n/en.json   

{
                context: 'resources/i18n',
                from: '**/*.json',
                to: 'resources/i18n'
            },

This file is being copied and loaded but the values are not overriding the labels

**Expected behavior:**
Our text changes are not overriding the built in

**Steps to reproduce the issue:**
add a resources/i18n/en.json file

in the file change the values for claim task from 
 "CLAIM": "To work on this task click Claim."
To 
"CLAIM": "To work on this task, you need to claim it first. You can do that by pressing the Claim button above."

**Component name and version:** 

ng2-activiti-tasklist

**Browser and version:** 
all
 
**Node version (for build issues):**  
node 8.1.4
npm 5.3.0

**Comment by tdonovancsra** [comment]
<img width="740" alt="screen shot 2017-10-03 at 10 31 41 am" src="https://user-images.githubusercontent.com/16578748/31130736-37da681e-a826-11e7-9940-12cc553e2f51.png">

<img width="766" alt="screen shot 2017-10-03 at 10 33 20 am" src="https://user-images.githubusercontent.com/16578748/31130777-542cece4-a826-11e7-9878-e16cfcef052a.png">

Here you can see both files get loaded

**Comment by tdonovancsra** [comment]
and they reliably load in that order.  At least the resources/918n/en.json is loaded last

**Comment by tdonovancsra** [comment]
if I change to this in app.module.ts
{
            provide: TRANSLATION_PROVIDER,
            multi: true,
            useValue: {
                name: 'ng2-activiti-tasklist',
                source: 'resources'
            }
        },

my file doesn't get referenced at all and is not pulled down.  If I give it any other name it gets referenced and pulled down but not used

**Comment by DenisVuyka** [comment]
Should be fixed in 1.9.0 release or upcoming betas. The 'app' resource will get top priority and will allow changing any ADF resource string/object.
