### ISSUE TITLE
Translation not working in sharedModule or more than one module

### ISSUE THREAD

**Issue by dhrn** [Alfresco/alfresco-ng2-components#2544]
Translation is working if project contains only one module(appModule).I am having more than one module.In my SharedModule, translation is not working.i am getting the following error.
```
Template parse errors:
The pipe 'translate' could not be found ("
      </td>
      <td>
          <i class="material-icons" md[ERROR ->]-tooltip="{{'BUTTON_LABEL.ADVANCE'  | translate}}"
             mdTooltipPosition="left"): ng:///SharedModule/SharedSearchComponent.html@9:70
```

**Comment by DenisVuyka** [comment]
I use use shared module across all the components in your application then you can try importing CoreModule in the common one.

**Comment by dhrn** [comment]
app Module
```
@NgModule({
  imports: [
    BrowserModule,
    routing,
    LoginModule,
    ActivitiProcessListModule,
    AnalyticsModule,
    HttpModule,
    MuraaiModule,
    MaterialModuleCustom
  ],
  declarations: [
    AppComponent
  ],
  exports: [
    MaterialModuleCustom
  ] ,
  providers: [
    MuraaiHttpCoreServices,
    { provide: AppConfigService, useClass: DebugAppConfigService },
    {
      provide: TRANSLATION_PROVIDER,
      multi: true,
      useValue: {
        name: 'app',
        source: 'resources'
      }
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

SharedModule:

```
@NgModule({
  imports: [
    CommonModule,
    CoreModule,
    FormsModule,
    ReactiveFormsModule,
    MaterialModuleCustom,
    DataTableModule,
    ChartsModule
  ],
  declarations: [
  SharedComponent
  ],
  schemas: [
    CUSTOM_ELEMENTS_SCHEMA
  ],
  exports: [
    FormsModule,
    ReactiveFormsModule,
    MaterialModuleCustom,
    DataTableModule,
    ChartsModule
  ]
})
export class SharedModule { }

```
i am using translation in all the components.Still i am getting the error

**Comment by DenisVuyka** [comment]
The 'app.module' still needs to have a 'CoreModule' import. Modules in Angular have tree hierarchy, for the Root, ChildA and ChildB, if you import the CoreModule in the Root, both child modules will get it automatically. But if you import only to ChildA, then ChildB and its own tree of modules/components won't get that.

**Comment by dhrn** [comment]
i have tried that also, but it is not working

**Comment by dhrn** [comment]
can you share any sample code?

**Comment by dhrn** [comment]
can you  share any sample code?

**Comment by DenisVuyka** [comment]
Your SharedModule needs to re-export all the modules for others. Try having "imports" and "exports" section the same. At least it needs to re-export the CoreModule.

**Comment by dhrn** [comment]
hi  @DenisVuyka,  when i import adf module  in my shared module, i am getting the following error.

> 
**browsermodule has already been loaded. if you need access to common directives such as ngif and ngfor from a lazy loaded module, import commonmodule instead.**

i think [this line](https://github.com/Alfresco/alfresco-ng2-components/blob/master/lib/core/core.module.ts#L64) causes the issue.Is it correct?.

**Comment by DenisVuyka** [comment]
@dhrn all generators for 2.0 are proved to be working fine, we even got a Travis running unit and e2e tests for each blueprint. Please create a simple project to reproduce the issue and attach to this issue. If you are using some custom setup, I would recommend generating a new 2.0 app into some empty folder and comparing its setup with your current one.

**Comment by dhrn** [comment]
here i have added [demo app](https://github.com/dhrn/adf-lazy-load.git). please suggest a solution

**Comment by DenisVuyka** [comment]
thanks, I am able to reproduce the issue and we are investigating possible solutions.

**Comment by DenisVuyka** [comment]
I have logged a Jira ticket: [ADF-2064](https://issues.alfresco.com/jira/browse/ADF-2064). Meanwhile, I suggest using the regular routing to unblock the development and returning to lazy loading at later stages.

**Comment by dhrn** [comment]
thanks @DenisVuyka !.

**Comment by tanup** [comment]
@DenisVuyka : Is there any other way than using regular routing, because our project architecture quite complex and regular routing in this case is not efficient or recommended.

**Comment by DenisVuyka** [comment]
@tanup you can try importing required modules manually into the lazy loaded routes, without CoreModule. Here's what the core module imports: https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/core.module.ts#L55

**Comment by DenisVuyka** [comment]
Working on the fix, should be available with upcoming 2.1 release

**Comment by tanup** [comment]
@DenisVuyka : Thanks for the update.

**Comment by dhrn** [comment]
Hi @DenisVuyka ,i am using latest beta.i have followed the demo-shell. i think, i am missing some thing. please suggest a solution for this.

i want to create 10  datatable. so i have customized adf-datatable  called dhrn-table(inside dhrn-table i am using adf-datatable). Now i want  add 2 table in App Module and remaining 8 in lazy-loading Modules.

```
@NgModule({
  imports: [
    CommonModule,
    ...imports() // CoreModule
  ],
  declarations: [
    ...components()
  ],
  entryComponents: [
    ...entryComponents()
  ],
  exports: [
   CommonModule,
   ...components()
  ]
})
export class xxxSharedModule {}

@NgModule({
  imports: [
    CommonModule,
    ...lazyImports() // CoreModule.forChild
  ],
  declarations: [
    ...components()
  ],
  exports: [
   CommonModule,
   ...components()
  ]
})
export class xxxSharedModuleLazy {}

@NgModule({
  imports: [
    xxSharedModuleLazy
  ],
  exports: [
    xxxSharedModuleLazy
  ]
})
export class xxxModuleLazy {}

@NgModule({
  imports: [
    xxxSharedModule
  ],
  exports: [
    xxxSharedModule
  ]
})
export class xxxModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: xxxModule
    };
  }

  static forChild(): ModuleWithProviders {
    return {
      ngModule: xxxModuleLazy
    };
  }
}
```

In app.module.ts
```
import:[
xxxModule.forRoot()  // for 2 dhrn-table
]
```


In lazy module
```
import:[
xxxModule.forChild()   // lazy load Module  (8 dhrn-table)
]
```

iam getting the following error:

> dhrn-table Component is part of the declarations of 2 modules: xxxSharedModule and xxxSharedModuleLazy!

**Comment by dhrn** [comment]
Hi @DenisVuyka, @eromano , i am working on latest beta(2). i am not able to access the values in app.config.json by using AppConfigService. i mean i am getting undefined for all the values.

**Comment by dhrn** [comment]
Hi @DenisVuyka, @eromano , i am working on latest beta(2). In lazy-module i am not able to access value which is defined in app.config.json. ie i am getting **undefined** for all key in the Json

**Comment by dhrn** [comment]
i am getting correct value only if i import required module.if i import Content Module instead of UploadModule, then  it is not working.

**Comment by DenisVuyka** [comment]
@dhrn Are you importing only via "forChild" in your lazy module?

**Comment by dhrn** [comment]
i solved this.i have imported wrongly. thanks @DenisVuyka .
