### ISSUE TITLE
demo shell build is not working with tomcat

### ISSUE THREAD

**Issue by dhrn** [Alfresco/alfresco-ng2-components#2577]
![screenshot from 2017-10-31 18-06-06](https://user-images.githubusercontent.com/14145706/32224824-00f2315c-be69-11e7-9d01-b1b672001315.png)
i have deployed this build with tomcat. but i am getting 404 for all includeed files

**Comment by DenisVuyka** [comment]
I believe for the Tomcat your "index.html" page should have: `<base href="./">` (note the dot)

**Comment by DenisVuyka** [comment]
The Tomcat might also need settings for SPA (single page application), to return index.html for all 404 requests. I doubt this is the "demo shell build" problem as issue title says.
