### ISSUE TITLE
Small mistake in documentation

### ISSUE THREAD

**Issue by wernernaehle** [Alfresco/alfresco-ng2-components#2635]
Note: there is this PR https://github.com/Alfresco/alfresco-ng2-components/pull/2636 to fix it
 I think there is a small mistake in the documentation of this link: https://github.com/Alfresco/alfresco-ng2-components/blob/ee5fe6dab93152711424639a6d1f55e846390e26/docs/document-list.component.md#navigation-mode. In the chapter "Custom columns" there is an example how to use "data-columns". This sample uses the property "sortable" without "[]" and I think it should be "[sortable]" instead of "sortable".

**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [X] Documentation

**Current behaviour:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 
ng2-alfresco-documentlist

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
Closing as your PR is already merged to 2.0. Thanks for the contribution.
