### ISSUE TITLE
Cannot import ViewerModule in Angular 4.2.4

### ISSUE THREAD

**Issue by manumqln** [Alfresco/alfresco-ng2-components#2652]
I am not able to import ViewerModule in Angular 4.2.4. It shows an error "Unexpected value 'ViewerModule' imported by the module 'AppModule'" when running. Could anyone please help?

Thanks in advance

**Comment by eromano** [comment]
hi @manumqln is really difficult help you like can you create an example project where this problem occurs?

**Comment by manumqln** [comment]
I have imported `ViewerModule` in app.module.ts and added the following code in html
`<alfresco-viewer [showViewer]="true" [overlayMode]="true" [urlFile]="'assets/test.pdf'">
  <div class="mdl-spinner mdl-js-spinner is-active"></div>
</alfresco-viewer>`
But I am getting below error when doing ng serve.

<img width="1278" alt="screen shot 2017-11-16 at 5 42 06 pm" src="https://user-images.githubusercontent.com/1004008/32890633-a75f9b5e-caf5-11e7-86a0-dc1c4c2734e6.png">

**Comment by DenisVuyka** [comment]
What version of ADF are you using?

The ADF 1.9.0 requires Angular 4.3.6 and certain versions of other components. All that is documented in the "how to upgrade" articles we ship with every release.

**Comment by manumqln** [comment]
I am using ADF 1.9.0 and upgraded Angular to 4.4.6. The issue still persists.

**Comment by eromano** [comment]
did you start your app with the generator?

**Comment by manumqln** [comment]
Yes, I am using angular-cli. I start it with `ng serve` command.

**Comment by DenisVuyka** [comment]
Are you sure you are running with Angular 4.3.6 as I've mentioned yesterday (not  4.2.4. and not 4.4.6)  ? have you tried to remove the node_modules and package lock file?

**Comment by DenisVuyka** [comment]
Please create a project to reproduce the problem, remove node_modules form it, zip and attach to this issue so that someone can reproduce and see where the issue is. Thanks in advance.

**Comment by manumqln** [comment]
I have tried removing node_modules and package-lock.json. I am currently using angular 4.4.6. Do I need to try 4.3.6 as well?

**Comment by DenisVuyka** [comment]
1.9.0 is based on 4.3.6, you MUST use the same version to build an application based on 1.9.0.
