### ISSUE TITLE
ADF Unable to login with APS

### ISSUE THREAD

**Issue by amrutawandakar** [Alfresco/alfresco-ng2-components#2728]
Hello,

I am trying to use ADF(using angular CLI) with APS(1.7) I have referred the link "https://community.alfresco.com/community/application-development-framework/blog/2017/10/16/generating-an-angular-cli-project-and-preparing-it-for-use-with-adf-190" for ADF installation I am getting login page of ADF but unable to login it gives message " You've entered an unknown username or password" even though they are correct.

Kindly help me to resolve this issue. Here I have attached my zip file.

Thanks
[adf-workbench.zip](https://github.com/Alfresco/alfresco-ng2-components/files/1501927/adf-workbench.zip)

**Comment by DenisVuyka** [comment]
You have `[providers]="'ALL'"` in the `app.component.html`. That means component requires both ACS and APS at the same time with same credentials (username + password). If you use only APS please change to `[providers]="'BPM'"`
