### ISSUE TITLE
Add hashing to translation JSON files to stop browser caching

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#2755]
**Type of issue:**  (check with "[x]")

> - [ X] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Currently the translation files (en.json etc) are being cached on the client browser.  When new versions of the text are deployed the cached version is being shown.

**New feature request:**
Add cache busting scheme for these files similar to the hash that is put on vendor, app and polyfil deployment files.  When the namespace for the messages changes in 1.10 we had a lot of caching problems and had to instruct people to manually clear caches to see new values

**Comment by DenisVuyka** [comment]
fixed and will be available with 2.1 release
