### ISSUE TITLE
Custom theming issue in 2.0

### ISSUE THREAD

**Issue by dhrn** [Alfresco/alfresco-ng2-components#2765]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**

After Migration to 2.0 i am getting Custom theming error 
i am having theming option for my app.so i have added one script file in project.  Script will take all custom defined theme's(scss) and convert it into corresponding css. In Adf 2.0 i am not able to produce custom theme.
I found node-sass not able to import[ this](https://github.com/Alfresco/alfresco-ng2-components/blob/master/lib/core/styles/_theming.scss#L1) 
Assume my one one of custom theme:
Dark-theme.scss 
@import '../node_modules/@alfresco/adf-content-services/styles/index';
@import '../node_modules/@alfresco/adf-process-services/styles/index';
@import '../node_modules/@alfresco/adf-insights/styles/index';
@import '../node_modules/@alfresco/adf-core/styles/index'
@import './app/app-theme';
@include mat-core($typography);
// Define the dark theme.
$primary: mat-palette($mat-pink);
$accent:  mat-palette($mat-blue-grey, A200, A100, A400);
$theme: mat-dark-theme($primary, $accent);
ap-theme($theme) {
  @include angular-material-theme($theme);
  @include adf-content-services-theme($theme);
  @include adf-process-services-theme($theme);
  @include adf-insights-theme($theme);
[  @include adf-core-theme($theme);
](https://github.com/Alfresco/alfresco-ng2-components/blob/master/lib/core/styles/_index.scss#L3)  @include app-theme($theme);
}
 Script Logic:
 all scss(themes) > css file
i run the script with ng serve and ng build .

**Expected behavior:**

**Steps to reproduce the issue:**

In 1.9 theming [this line](https://github.com/Alfresco/alfresco-ng2-components/blob/master/lib/core/styles/_theming.scss#L1) is not available

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

Node: 8.9.1
npm: 5.5.1
Angular-Cli: 1.5.2
Adf: 2.0
**New feature request:**

**Comment by eromano** [comment]
Did you try to follow the new theming  doc? https://github.com/Alfresco/alfresco-ng2-components/blob/master/docs/theming.md

**Comment by eromano** [comment]
In the last version or the scss file are concatenated in the theming scss file of any package, as good practices suggest

**Comment by dhrn** [comment]
hi @eromano , [This Document](https://github.com/Alfresco/alfresco-ng2-components/blob/master/docs/theming.md)  is working fine for ng serve or ng build. But it is not working for this $(npm bin)/node-sass $file > $file.css

**Comment by dhrn** [comment]
@eromano i am having adf-components and custom components. so for theming, i am generating my own theme which includes both adf-componets and own custom-components. so i have created one script file which build themes for my app.

**Comment by DenisVuyka** [comment]
Is the ticket about supporting your custom script, or improvement to the ADF styling/theming? You can create a PR if you see something is missing or can be improved.

**Comment by eromano** [comment]
@dhrn give a look here https://github.com/Alfresco/alfresco-ng2-components/blob/master/demo-shell/src/custom-style.scss this is how we did it in our test shell app. 
The 

'''
@include adf-app-layout-theme
'''

This is the custom theme of the test app

**Comment by dhrn** [comment]
hi @eromano ,
we can able to produce only one custom theme(inbuilt) from above [url](https://github.com/Alfresco/alfresco-ng2-components/blob/master/demo-shell/src/custom-style.scss).
we are not able to provide more than one theme.i want to create more than one theme for my app (which will be dynamically switched). so i have create one script file which will take all custom scss and convert it into css(each css file is a theme).For that i am using  this command in script `$(npm bin)/node-sass $file > $file.css`. Here i am getting error because this line`(@import '~@angular/material/theming';(lineno:65 at 'node_modules/@alfresco/adf-core/theming';))` causes the issue.Because node - sass trying to import line` @import '~@angular/material/theming';` . so i am getting error. i hope you understood the problem.

**Comment by dhrn** [comment]
hi @eromano @DenisVuyka 
i am building theme's with help of one bash script file.
In 1.9, themes are configured with separate files
![screenshot from 2017-12-05 19-58-55](https://user-images.githubusercontent.com/14145706/33612180-c902dfae-d9f6-11e7-9b2f-8a47bd8ab4d2.png)
But in 2.0 everything is converted into single file.
here i am not able exclude what  i don't want.

**Comment by dhrn** [comment]
hi @eromano , here i have [reproduced](https://github.com/dhrn/adf-custom-theme) my issue.

**Comment by eromano** [comment]
@dhrn thanks for the example project I'll give a look on it

**Comment by eromano** [comment]
i think the tool that you are using is not able to solve the relative import you could try create a webpack script as this one:

https://github.com/Alfresco/alfresco-ng2-components/blob/master/lib/config/webpack.style.js

**Comment by dhrn** [comment]
Thanks @eromano
