### ISSUE TITLE
User and Password

### ISSUE THREAD

**Issue by anakin59490** [Alfresco/alfresco-ng2-components#2766]
Hi,
Sorry but what are user and password to use ?
Thx

**Comment by DenisVuyka** [comment]
Can you please clarify the question? For ACS you use default ACS admin account or any user account you've created. For APS you use APS account. When authentication is set to "ALL" in Login component - you use a single credentials that are present in both services.

**Comment by anakin59490** [comment]
I have installed ACS in local : http://127.0.0.1:8080/share/page/
![image](https://user-images.githubusercontent.com/16132965/33604397-228df14e-d9b6-11e7-9591-ac91290da21b.png)
 But when i use the same user/password, it doesn't work (http://localhost:3000/login) :
![image](https://user-images.githubusercontent.com/16132965/33604519-89f75b72-d9b6-11e7-9b3c-1647321bbdd4.png)

**Comment by eromano** [comment]
How did you configured your login component? Is it only provider settled to ECM ? Maybe you have the provider settled to all

**Comment by anakin59490** [comment]
This is the original code, i didn't change anything.
![image](https://user-images.githubusercontent.com/16132965/33609063-ecf2d9f8-d9c6-11e7-9440-bd74c1830d70.png)

**Comment by anakin59490** [comment]
code from LoginComponent.ts

**Comment by eromano** [comment]
Can you check the network tab which call performs when you press login?

**Comment by anakin59490** [comment]
So i have 2 request URL : 
![image](https://user-images.githubusercontent.com/16132965/33611266-0c8a6824-d9ce-11e7-9262-4b788b5f65ac.png)

and 

![image](https://user-images.githubusercontent.com/16132965/33611273-12e4fbc6-d9ce-11e7-9191-9ce268de6322.png)

I have both installed ACE and ACS . i will unsintall the 2 sotware. Then i will install only ACS

**Comment by anakin59490** [comment]
Ok i have installed only ACS, and this is the tomcat/webapps folder: 
![image](https://user-images.githubusercontent.com/16132965/33612791-02d97fe0-d9d3-11e7-93db-51bc4f82b9bd.png)

 i can acces the app : 

![image](https://user-images.githubusercontent.com/16132965/33612879-47de7820-d9d3-11e7-9b9d-75f31f8eba50.png)

Then npm start : 

![image](https://user-images.githubusercontent.com/16132965/33612919-6d913b5c-d9d3-11e7-9d60-89564c12b743.png)

but i still get the same issue : 

![image](https://user-images.githubusercontent.com/16132965/33613011-aed8ca80-d9d3-11e7-81e0-836beb2dec96.png)

I must have done something wrong .... but what ?

**Comment by DenisVuyka** [comment]
All your errors have 404 code. That means the URLs are not available for your setup. Try generating a new 2.0.0 application without Tomcat first. Most probably you have misconfigured the Tomcat, or miss some of the settings.

**Comment by anakin59490** [comment]
Ok i'm going to do it. 
But what i don't understand is that is work with the other projects founded in tuto and retrieved on GitHub... (https://community.alfresco.com/community/application-development-framework/pages/get-started) like adf-workbench-content, etc...
To test the different projects, i use eclipse and a embedded Tomcat to launch my All-in-one project.
an i use WebStorm for ADF projects. All of it run on port 4200.
