### ISSUE TITLE
Yeoman generated app can only preview one time

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-ng2-components#2777]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

With an uncustomized yeoman generated 2.0 app I preview a file which works. I then attempt to preview a second file and nothing happens.

**Expected behavior:**

I am able to preview more than one document without having to refresh the browser (which loses context and I have to renavigate.)

**Steps to reproduce the issue:**

I have a vanilla 5.2 repo, I navigated to Personal Files > Data Dictionary > Email Templates > activities, double clicked activities-email_de.ftl, clicked the in page back button and then double clicked activities-email_es.ftl and nothing happens.

**Component name and version:** 

generator-ng2-alfresco-app 2.0.0

**Browser and version:** 

Chrome
 
**Node version (for build issues):**  

8.0.0

**Comment by eromano** [comment]
thanks @binduwavell we will try to fix it in the next version of the generator
