### ISSUE TITLE
ng-packagr question

### ISSUE THREAD

**Issue by rmeshksar** [Alfresco/alfresco-ng2-components#2781]
**Type of issue:**  (check with "[x]")

> - [ x] Question

I am learning about ng-packagr and noticed that it is getting used in your amazing library as well. Wondering if you can help me with my question.

I noticed that in the following file:
https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/index.ts

First all modules are exported followed by other elements of the components like directives, components, ... .
My question is to understand why modules are not exported as part of components separately. 

For example for the 'form' module in the above file there two lines:

export * from './form/form.module';
export * from './form';

Can form.module be exported as part of the following file:
https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/form/public-api.ts

And only have
export * from './form';
In the main index file.

I appreciate your clarification on this.

**Comment by eromano** [comment]
HI @rmeshksar It should be possible and valid do it in both way
