### ISSUE TITLE
ng2-activiti-tasklist extension to include process variables

### ISSUE THREAD

**Issue by sanonlymail** [Alfresco/alfresco-ng2-components#2783]
**Type of issue:**  (check with "[x]")

> - [x ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

adf-tasklist component currently retrieves and renders task level attributes e.g. created date, task name, due date, assignee etc. 

**Expected behavior:**

We would like to have a task list behavior to be extended to display process level variables as well. 

**Steps to reproduce the issue:**

**Component name and version:** 

ng2-activiti-tasklist 1.9.0

**Browser and version:** 

ALL
 
**Node version (for build issues):**  

**New feature request:**

We would like to have task list behavior to be extended to display process level variables as well. This is required to provide more details for the task in a business scenario. e.g. If we are creating task in one step capturing indexing information, then some of the captured indexing information needs to be made available through out the process. This is achieved by making the indexing information available at process level. So when execution goes through multiple tasks, the task list should be able to display process level variables to provide more information to the users.

**Comment by DenisVuyka** [comment]
You are using ADF 1.9 based on the ticket. Can you try the same issue with the latest 2.4?
