### ISSUE TITLE
508 Issue on upload widget

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#2785]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
In version 1.10.0.beta 6 if you tab to the upload button and hit enter the upload dialog doesn't appear.  For Section 508 this fails.

**Expected behavior:**
hitting the enter button displays upload dialog

**Steps to reproduce the issue:**
This is happening because of a material overlay getting the focus that is for the behind the scenes input type="file" control. Hitting enter doesn't activate the input control.  While it's true that tabbing again will activate that control this is confusing to the user and will not pass 508 testing

having a keyup.enter handler should fix this we think

**Component name and version:** 
ng2-activiti-form 1.10.0 beta 6

**Browser and version:** 
All

**Comment by eromano** [comment]
@tdonovancsra fo you know if it is still a problem in 2.0.0?

**Comment by tdonovancsra** [comment]
I haven't had a chance to install the demo to see but if there hasn't been any changes to that component I'm betting it still occurs

**Comment by eromano** [comment]
Please feel free to reopen if this bug is still presenti in 2.0.1>
