### ISSUE TITLE
Broken link on theming documentation page

### ISSUE THREAD

**Issue by fcorti** [Alfresco/alfresco-ng2-components#2789]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [x] Documentation

**Current behaviour:**
In the following page, the last link at "See also, Theming" is broken.
https://alfresco.github.io/adf-component-catalog/additional-documentation/angular-material-design.html

**Expected behavior:**
The link should link the following page.
https://github.com/Alfresco/alfresco-ng2-components/blob/master/docs/theming.md

**Steps to reproduce the issue:**
Click the link. ;-)

**Component name and version:** 
N/A

**Browser and version:** 
Firefox 57.00 on Ubuntu
 
**Node version (for build issues):**  
N/A

**New feature request:**
N/A

**Comment by therealandeeee** [comment]
The link was actually to the Theming page in the Component Catalog (which is equivalent to theming.md on GitHub). The error was that the pre-processor script was not changing the .md suffix to .html. Both the script and the link are now fixed.
