### ISSUE TITLE
ADF is not working with SSO enabled process services

### ISSUE THREAD

**Issue by muhmadtabrez** [Alfresco/alfresco-ng2-components#2802]
Hi,
   I am using ADF 2 following example https://community.alfresco.com/community/application-development-framework/blog/2017/11/29/taking-adf-20-out-for-a-spin and creating simple app. I am uisng alfresco process services for the this example and i had enabled sso in the alfresco process services.
    with help of https://docs.alfresco.com/process-services1.7/concepts/ps-app-config-OAuth-client.html link i had configured sso with github. i am able to login successfully on APS.
    With same user credentials when i am trying to use with ADF 2 login component i am  unable to login to APS.

    I am getting the following error in console 
![image](https://user-images.githubusercontent.com/5879103/34610558-b7c7a6fc-f247-11e7-8d1b-ab117bf39754.png)

**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

ADF 2 login component 
**Browser and version:** 

 chrome Version 63.0.3239.108
**Node version (for build issues):**  
Node version: 8.4.0
Angular CLI: 1.6.1

**New feature request:**

**Comment by eromano** [comment]
I close this issue to old please check against to the new version and if is still present feel free to reopen it
