### ISSUE TITLE
Visibility of items dependent on a radio button list not showing on completed tasks

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#2833]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When you have a form that has a radio button list of items and based on what is selected another set of items is visible.  When the task is completed and you open the completed task in ADF you don't see the dependent fields with their values.

**Expected behavior:**
You should see the dependent values.

**Steps to reproduce the issue:**
create radio button list with three options
add dropdown to the form and set the visibility or the field if == to option_3
add a text box to the form and set the visibility or the field if == to option_3
add a text box to the form and don't set any visibility condition

start the process and select option 3 
enter values in all fields 
complete the task.   
open completed task.  you don't see the first two fields but you do see the third text box and option 3 is still selected on the main radio button list
 
**Component name and version:** 
activiti/core

**Browser and version:** 
all
 
**Node version (for build issues):**  
8.9.0

**Comment by tdonovancsra** [comment]
[Test App.zip](https://github.com/Alfresco/alfresco-ng2-components/files/1633148/Test.App.zip)
Here is a test application to illustrate

**Comment by tdonovancsra** [comment]
note: the values appear if you just save the task

**Comment by tdonovancsra** [comment]
any news on this?

**Comment by eromano** [comment]
@tdonovancsra will be fixed in 2.2.0

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2199
