### ISSUE TITLE
Provide a best practice / sample implementation for cross-app routing

### ISSUE THREAD

**Issue by binduwavell** [Alfresco/alfresco-ng2-components#2871]
**Type of issue:**  (check with "[x]")

> - [X] New feature request

**New feature request:**

As ADF starts being used we expect implementors to create and share many types of components. Additionally it is likely that some special purpose apps will be created. I believe it will be very useful for such apps link to each other, passing context and credentials and possible a return path.

I realize that this is likely more of an Alfresco Content/Process App type issue. However I believe it will affect bespoke apps as well built with ADF. As such, I think that providing some guidelines on how to perform app linking (and return) will be beneficial for folks creating ADF solutions.

Imagine we are creating an ADF application for a large company. Realistically we may want to create apps for each department or possible for each role/use-case. Imagine a sales rep is in the Sales App and they find some documentation related to a product that is in development. It would be ideal if the Sales App could route to the Engineering App passing along the context of the product the sales rep located and also any credentials that were used to log into the Sales App. This way, the sales rep will enter the Engineering App without having to provide credentials again and they will be navigated to the appropriate user experience for the product they are interested in. Ideally the routing mechanism would understand that the user came from the Sales App and would in the case provide a button in the toolbar to go back to where they were in the Sales App when they entered the Engineering App.

**Comment by binduwavell** [comment]
There is some discussion about extension mechanisms on the community here: https://community.alfresco.com/message/827340-alfresco-contentprocess-app-moduleextension-mechanism

**Comment by eromano** [comment]
@binduwavell As you said what I see here is more a BE job that in big part it sounds already possible with the current implementation. 
We should just check the permission part if it works correctly in this scenario and give some guidance with an example app as you said.

**Comment by binduwavell** [comment]
@eromano any progress on this?

**Comment by DenisVuyka** [comment]
I'm not sure it is responsibility of component library to define the routing. it should be handled by the end-app developers or admins that maintain nginx or any other proxies if multiple isolated apps needed.

**Comment by DenysVuika** [comment]
Closing as this is not in the scope of the component library but an end application architecture
