### ISSUE TITLE
adf-content-metadata-card configuration driven by node-type instead of aspect-type.

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-ng2-components#2893]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Currently, all the new metadata component's configuration is driven by aspects.
When you configure an aspect and its properties to be presented, the component shows a different box for each aspect, each one with a expand/collapse link.

**Expected behavior:**
In cases where there are lots of custom aspect, with 1 property per aspect (for reusability reasons), having a custom type, like "contract" with list of, lets say, 10 mandatory-aspects, it would be nice if it was possible to define the component configuratio for node, like, for the type "contract", show the following "10 properties", without differentiating from what aspects define them.

**Steps to reproduce the issue:**
Just follow the documentation on the component to setup a project

**Component name and version:** 
adf-content-metadata-card version 2.0.1

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2232

**Comment by popovicsandras** [comment]
Hi Douglas,

I'd like to learn a bit more about how you would like to group and organise the layout around the properties. Please find our proposal about the new aspect/property organising schema below.

```javascript
{
    "content-metadata": {
        "presets": {
            "kittens": [
                {
                    "title": "GROUP-TITLE1-TRANSLATION-KEY",
                    "properties":  [
                        // We would like to show every property from the exif:exif aspect
                        { 
                            "aspect": "exif:exif",
                            "properties": "*"
                        },
                        // We would like to show the two properties (kitten:custom1, kitten:custom3) from the kitten:vet-records aspect
                        { 
                            "aspect": "kitten:vet-records", 
                            "properties": [ "kitten:custom1", "kitten:custom3" ]
                        },
                        // We would like to show the owner:name property from the owner:parameters aspect
                        { 
                            "aspect": "owner:parameters", 
                            "properties": [ "owner:name" ]
                        }
                    ]
                } ,
                {
                    "title": "GROUP-TITLE2-TRANSLATION-KEY",
                    "properties":  [
                        // We would like to show the two properties (kitten:favourite-food, kitten:recommended-food) from the kitten:food aspect
                        {
                            "aspect": "kitten:food", 
                            "properties": [ "kitten:favourite-food", "kitten:recommended-food" ] 
                        }
                    ]
                }
            ]
        }
    }
}
```

The end result of this config would be two accordion groups with the properties like this:


| + GROUP-TITLE1-TRANSLATION-KEY |
| ------------------------------------ |
| exif:param1 |
| exif:param2 |
| ... |
| exif:paramN |
| kitten:custom1 |
| kitten:custom3 |
| owner:name |

| + GROUP-TITLE2-TRANSLATION-KEY |
| ------------------------------------ |
| kitten:favourite-food |
| kitten:recommended-food |

Is it something what could be useful for you guys? Feel free to add any further suggestions for improving this schema to add more freedom for developers, depending on your needs and how you want to use this component.

**Comment by douglascrp** [comment]
It looks good enough for me.
Usually, I do not group different sets of properties like that. What I do is to show all the properties I need as a single "block", but if I understand what you are proposing, that should be doable, as the array could have, for the situation I described, a single item, with all the especific properties for all the aspects.

But please, remember that properties are not exclusively defined inside aspects. Types can also have their own sets os properties.

So, it would be something like:

```
{
    "content-metadata": {
        "presets": {
            "kittens": [
                {
                    "title": "GROUP-TITLE1-TRANSLATION-KEY",
                    "properties":  [
                        // We would like to show every property from the exif:exif aspect
                        { 
                            "aspect": "exif:exif",
                            "properties": "*"
                        },
                        // We would like to show the two properties (kitten:custom1, kitten:custom3) from the kitten:vet-records aspect
                        { 
                            "aspect": "kitten:vet-records", 
                            "properties": [ "kitten:custom1", "kitten:custom3" ]
                        },
                        // We would like to show the owner:name property from the owner:parameters aspect
                        { 
                            "aspect": "owner:parameters", 
                            "properties": [ "owner:name" ]
                        },
                        // We would like to show all the properties from the type kitten:kitten
                        { 
                            "type": "kitten:kitten", 
                            "properties": [ "kitten:name", "kitten:color", "kitten:weight" ]
                        }
                    ]
                } ,
                {
                    "title": "GROUP-TITLE2-TRANSLATION-KEY",
                    "properties":  [
                        // We would like to show the two properties (kitten:favourite-food, kitten:recommended-food) from the kitten:food aspect
                        {
                            "aspect": "kitten:food", 
                            "properties": [ "kitten:favourite-food", "kitten:recommended-food" ] 
                        }
                    ]
                }
            ]
        }
    }
}
```

**Comment by eromano** [comment]
It sounds like we have a plan , thanks @douglascrp and @popovicsandras  :)
