### ISSUE TITLE
webscript.component.md post method needed

### ISSUE THREAD

**Issue by shazada** [Alfresco/alfresco-ng2-components#2909]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

At this moment the adf-webscript-get only supports get
**Expected behavior:**

Expected there should be a adf-webscript-post
**Steps to reproduce the issue:**

Include the webscript.component.md
Use the component to get data and it works.
Try and include POST method
**Component name and version:** 

webscript.component.md 2.1.0
**Browser and version:** 

 all
**Node version (for build issues):**  

?
**New feature request:**

Only implementing a get won't cut it.
Other methods should be available as well.
Like POST, PUT, DELETE, etc.

There are 100 scenario's needed for these methods :) I guess this is too obvious to post.

**Comment by DenisVuyka** [comment]
@shazada https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-core-rest-api/src/api/WebscriptApi.js#L50

**Comment by eromano** [comment]
@shazada if you want use other method I suggest you to use the webscript service by its own:  

```  
  constructor(private apiService: AlfrescoApiService) {}
this.apiService.getInstance().webScript.executeWebScript('post', this.scriptPath, this.scriptArgs, this.contextRoot, this.servicePath).then((webScriptdata) => {

```

you can pass all the supported verb you want. For more information about this method in the alfresco-js-api:

https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-core-rest-api/docs/WebscriptApi.md

**Comment by shazada** [comment]
@eromano I understand both of you.  But this is a feature request for:
https://alfresco.github.io/adf-component-catalog/components/WebscriptComponent.html#readme

`<adf-webscript-get 
    [scriptPath]="string"
    [scriptArgs]="Object"
    [contextRoot]="string"
    [servicePath]="string"
    [showData]="boolean"
    [contentType]="JSON | HTML | DATATABLE | TEXT"
    (success)= "logData($event)">
 </adf-webscript-get>`

So instead I suggest the following default component:

`<adf-webscript
    [scriptPath]="string"
    [scriptArgs]="Object"
    [contextRoot]="string"
    [servicePath]="string"
    [showData]="boolean"
    [httpMethod]="GET | POST | PUT | DELETE"
    [contentType]="JSON | HTML | DATATABLE | TEXT"
    (success)= "logData($event)">
 </adf-webscript>`

I hope this is clear :)

**Comment by eromano** [comment]
@shazada  because the async call and the return value that maybe you don't want always inject in your html I think in the : post, delete and put senario is a better approach use the service and handle the result in your component.

**Comment by shazada** [comment]
@eromano Maybe not direct in the HTML, but a default popup with succes/false/response text is mostly the case.

So in the showData we could add: DIALOG | NONE.
Sorry I'm no Angluar expert :) So I could be speaking Rubbish.

**Comment by eromano** [comment]
@shazada is perfectly fine :). I want only understand the use case.  can you give me an example scenario?

**Comment by shazada** [comment]
@eromano Sure.

For example you've got a simple form, for example:
![image](https://user-images.githubusercontent.com/1477763/35806750-e4d1198e-0a80-11e8-9267-80c2af5fef74.png)

This a replacement for the calendar item in Share but then in ADF.
So this form has been properly rendered.
Now we want to send the response to our custom webscript as a POST.

So in case it's successful. We want to present it within a simple popup message like in share:
- Successfully created calendar item
- Failed to create the calendar item.

So similar to the Share use-case:
```
Alfresco.util.PopupManager.displayMessage({
	text : Alfresco.util.message("success.calendar")
});
```
