### ISSUE TITLE
ADF Form - Freeze tabs panel at the top for long forms

### ISSUE THREAD

**Issue by miguel-galan** [Alfresco/alfresco-ng2-components#2919]
**Type of issue:**  (check with "[x]")

> - [x ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**New feature request:**

*Current behaviour:*
The tabs in a long form are not visible when Scrolling down. It makes it difficult to switch among tabs at any point. To select another tab the user has to scroll up to the top to click on the new tab.

*New feature expected behavior*
It would be very useful and user-friendly to keep tabs visible all the time while scrolling down through long forms, so the users could switch tabs at any time.

**Comment by eromano** [comment]
Hi @miguel-galan  I did a simple try I think you can accomplish it with just css style adding this style:

```css
.adf-form-container .mat-tab-body-content {
    height: 200px;
    overflow: scroll;
}
```

You can modify the height has better fit in your scenario

**Comment by miguel-galan** [comment]
Great!
Thanks for the help @eromano!
