### ISSUE TITLE
A simpler way to show the index of a row in the datatable component.

### ISSUE THREAD

**Issue by akolybelnikov** [Alfresco/alfresco-ng2-components#2923]
**Type of issue:**  (check with "[x]")

> - [X] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

Momentarily you would need to access the underlying data-object from your template like so:
```
<ng-template let-entry="$implicit">
        {{entry.data.getRows().indexOf(entry.row) + 1}}
 </ng-template>
```

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

DataTableComponent / [adf-datatable]

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

There might be a need for an easier / more intuitive way to access row indexes in a datatable. In fact, this is a default feature in most frameworks.

![image](https://user-images.githubusercontent.com/18685675/35966009-e7374282-0cbc-11e8-980a-3237bdcb7300.png)

**Comment by DenysVuika** [comment]
You can use custom column templates to achieve the desired behaviour.
