### ISSUE TITLE
event.preventDefault() is not a function on rowClick($event) in the datatable component

### ISSUE THREAD

**Issue by akolybelnikov** [Alfresco/alfresco-ng2-components#2928]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [X] Documentation

**Current behaviour:**

If passed like so in the template:
```
(rowClick)="onRowClick($event)"
```
a call throws the TypeError: preventDefault() is not a function, if used like so:
```
onRowClick(e) {
    e.preventDefault();
  }
```
**Expected behavior:**

`defaultPrevented` should have value 'true'

**Steps to reproduce the issue:**

If called like so:
```
onRowClick(e) {
    e.event.preventDefault();
  }
```
no error is thrown.

**Component name and version:** 

adf-datatable, @alfresco/adf-core 2.1.0

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2301
