### ISSUE TITLE
upload.widget.ts is downloading preview of file instead of the raw content

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#2936]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When a user uploads a Word document in the upload.widget.  and saves the form. 
The user comes back and see the proper word icon and file.
clicks on the file but in the background it's is opening a pdf rendition but not changing the file extension.  (shouldn't be doing this at all) . 
The user gets a message from Word that the file is corrupted
Inspecting the file shows it's a pdf

**Expected behavior:**
don't send preview back send the raw document 

**Steps to reproduce the issue:**
Upload word document to a form upload widget
click on the file to download

1.9.0 code 
fileClicked(file: ContentLinkModel): void {
        this.formService.getFileRawContent(file.id).subscribe(
            (blob: Blob) => {
                file.contentBlob = blob;
                this.formService.formContentClicked.next(file);
            },
            (error) => {
                this.logService.error('Unable to send evento for file ' + file.name);
            }
        );
    }

2.0.0 code introduced the error

fileClicked(obj: any): void {
        const file = new ContentLinkModel(obj);
        **let fetch = this.processContentService.getContentPreview(file.id);
        if (file.isTypeImage() || file.isTypePdf()) {
            fetch = this.processContentService.getFileRawContent(file.id);
        }**
        fetch.subscribe(
            (blob: Blob) => {
                file.contentBlob = blob;
                this.formService.formContentClicked.next(file);
            },
            (error) => {
                this.logService.error('Unable to send event for file ' + file.name);
            }
        );
    }

**Component name and version:** 
2.0.0 and greater 
alfresco-core

**Browser and version:** 
all

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2300
