### ISSUE TITLE
[New Feature] Lock and Unlock documents

### ISSUE THREAD

**Issue by a4rado** [Alfresco/alfresco-ng2-components#2947]
**Type of issue:**  (check with "[x]")

> - [X] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

**Expected behavior:**
The user can lock and unlock selected documents.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**
1. User selects a document to be locked.
2. A lock/unlock component is added in the content-menu.
3. Depending on the permission, user can execute lock/unlock

Note: refer to alfresco/share lock and unlock feature.

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2306

**Comment by DenisVuyka** [comment]
Implemented and will be available with the corresponding milestone.
