### ISSUE TITLE
Broken link into the documentation at DataColumn Component

### ISSUE THREAD

**Issue by fcorti** [Alfresco/alfresco-ng2-components#2983]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [X] Documentation

**Current behaviour:**
Broken link in the "See also" paragraph, linking to the DataTableAdapter.

**Expected behavior:**
Remove or update the link.

**Steps to reproduce the issue:**
Access to https://alfresco.github.io/adf-component-catalog/components/DataColumnComponent.html
Scroll the page at the end.
Find the See also paragraph.
Click on Datatable component.

**Component name and version:** 
Not relevant

**Browser and version:** 
Not relevant
 
**Node version (for build issues):**  
Not relevant

**New feature request:**
Not relevant

**Comment by therealandeeee** [comment]
Both issues are now fixed:
https://alfresco.github.io/adf-component-catalog/components/DataColumnComponent.html
