### ISSUE TITLE
Validate folder name on change in content-metadata-card component

### ISSUE THREAD

**Issue by akolybelnikov** [Alfresco/alfresco-ng2-components#3043]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
If assigned a duplicate (an existing) folder name, no user notification is given. The component lets user finish the process but does not save the new name silently. A 409 (Conflict) error is thrown in the developer console.

**Expected behavior:**
As in the create-folder-directive the user should be notified explicitly about the duplicate folder name.

**Steps to reproduce the issue:**
Call a node in a content-metadata-card component and adjust the folder name to match an existing.

**Component name and version:** 
adf-content-metadata-card 2.2.0

**Browser and version:** 
all
 
**Node version (for build issues):**  
8.9.4

**New feature request:**

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2483
