### ISSUE TITLE
Provide a mechanism to resolve and render custom container widgets (i.e TabsWidgetComponent)

### ISSUE THREAD

**Issue by miguel-galan** [Alfresco/alfresco-ng2-components#3048]
**Type of issue:**  (check with "[x]")

> - [X] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**New feature request:**
Right now it's possible to customize form field widgets and resolve the rendering using FormRenderingService.setComponentTypeResolver. It would be very useful to be able to render custom container widgets in the same way. 
(For example TabsWidgetComponent, in order to add tooltips and change the label when the tap is selected)

**Comment by fcorti** [comment]
I think the guide below answers this to request.
https://www.alfresco.com/abn/adf/docs/user-guide/aps-extensions/
