### ISSUE TITLE
Build of components lib fails

### ISSUE THREAD

**Issue by sanderPostma** [Alfresco/alfresco-ng2-components#3099]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

When I try to do this on the master or development branch compiler errors are shown. Also the same when on the 2.0.0 tag. Only with 2.1.0 I get one step further, npm run build completes successfuly, but npm run test does not.
When I ignore the tests and go ahead and link the locally buildt lib modules, the demo shell application won't start. First error:
ERROR in node_modules/@alfresco/adf-core/card-view/components/card-view-dateitem/card-view-dateitem.component.ts(71,13): error TS90010: Type 'moment.Moment' is not assignable to type 'moment.Moment'. Two different types with this name exist, but they are unrelated.

**Expected behavior:**

The lib modules to succusfully build and the tests working. These libs should work with demo-shell. Maybe I need a specific nodejs version, the prerequisite age says >5 so I used the current release.

**Steps to reproduce the issue:**

As described in the readme page, the components should be build by the following command:
npm install
npm run build

Then I run
npm run test

Then
cd ..\demo-shell
npm link ..\lib\core
npm link ..\lib\content-services
npm link ..\lib\process-services
npm link ..\lib\insights
npm install
npm start

**Component name and version:** 

alfresco-ng2-components\lib

**Browser and version:** 

Chrome 64
 
**Node version (for build issues):**  

Tried node 8.10.0 8.7.0 & 7.10.1

**New feature request:**

**Comment by eromano** [comment]
Hi @sanderPostma where do you get the guide on how to build?

**Comment by sanderPostma** [comment]
On the main page in the readme:
https://github.com/Alfresco/alfresco-ng2-components
I clicked "components"
Then under section "Build from sources" it only says
npm install
npm run build

**Comment by eromano** [comment]
Yep this is fine should work but the link part is not going to work, you can not use it in the demo shell using the link. Why are you tryng to build the library do you need to modify something inside? Because otherwise you can get it from NPM. Instead if you want work with the development lib in the demo shell you need to execute the script:

./start.sh -dev -gitjsapi development

as described in the wiki:

https://github.com/Alfresco/alfresco-ng2-components/wiki/Working-with-the-development-branch#start-the-demo-shell

**Comment by sanderPostma** [comment]
Thanks for the reference.
I am trying to add I component of my own to the demo project, initially for demo purposes and learning the ecosystem of this platform.
I was following the instructions from the components page by just running npm install and npm run build from a Windows DOS shell and I'm getting loads of compile errors.
This looks like there is something wrong with my typescript environment, but now I ran the npm-build-all.sh script from a MINGW shell and that's working much better.
Am I better off in a Linux machine? Recommended nodejs version?

**Comment by eromano** [comment]
node-v8.10. that is the LTS.
Linux like OS are the preferred env in our core team

**Comment by sanderPostma** [comment]
Hi again,
I now have an Ubuntu env.  When reading the scripts/README.md it looks like the following two lines should work:
./npm-build-all.sh -c -gitjsapi development
./start.sh -dev -t -gitjsapi development
Both execute successfully, when Firefox opens log login screen doesn't show and Firefox chokes up. Teh console gives the following error message
```
Error: Template parse errors:
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: MatSlideToggle,MatSlideToggle ("
<div class="settings">
    <p class="toggle">
        [ERROR ->]<mat-slide-toggle
            id="switch1"
            [color]="'primary'"
"): ng:///AppModule/LoginComponent.html@4:8
More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: MatSlideToggle,MatSlideToggle ("
    </p>
    <p class="toggle">
        [ERROR ->]<mat-slide-toggle
            id="switch2"
            [color]="'primary'"
```
This is in the development branch. The master branch doesn't build here:
```
selector/content-node-selector.service.spec.ts
(72,54): Argument of type '"100"' is not assignable to parameter of type 'Expected<number>'.

```
Am I missing anything?
Thanks in advance

**Comment by DenisVuyka** [comment]
@sanderPostma why not taking the Alfresco Content Application as a basement for your experiments? https://alfresco.github.io/alfresco-content-app/#/ This is much easier that trying to build the project that is meant for internal purposes and not supported for production use.

**Comment by sanderPostma** [comment]
Thanks I will give that a try. [This page ](https://community.alfresco.com/community/application-development-framework/pages/sample-code) sent me to this project as being "the sample code" so it made sense to start with this.
