### ISSUE TITLE
When searching for 'Uploader' no component is returned

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#311]
Please see video for steps to reproduce

[uploader.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/341016/uploader.mp4.zip)

**Comment by mauriziovitale** [comment]
Add the possibility to find the component using the keywords inside the package.json of the component
Example of the component keywords 
"keywords": [
    "ng2",
    "angular",
    "angular2",
    "upload",
    "alfresco"
  ],

**Comment by binduwavell** [comment]
Would be good to also allow search by directive. Imagine I see a directive in code and I'm not sure which component has published it.
