### ISSUE TITLE
Content actions not correctly disabled

### ISSUE THREAD

**Issue by kaspereden** [Alfresco/alfresco-ng2-components#3112]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Guys question, i am having an issue with permission checks. I am currently checking permissions on content-actions like this:
```
<content-action target="folder"
        [permission]="'delete'"
        [disableWithNoPermission]="true"
        [handler]="'delete'"
        title="delete me">
</content-action>
```

When a user has the Site-Collaborator role it works perfect. However when a user has the Site-Consumer role the button does not get disabled, the user does however not have the rights to do this action. 

I figured that there is one mayor difference in the code and that is when a user has a "Site-Consumer" role the getNodeChildren api does not provide an allowableOperations object. This seems to be part of the problem. Is this known? Is there a workaround? Or is it fixable?

**Expected behavior:**
When for a specific user there is no "allowableOperations" in the node entry the content actions that require a certain permission should be greyed out.

**Steps to reproduce the issue:**

1. Create a site and add a consumer and a collaborator.
2. Create a folder in the site 
3. Create an ADF app with the following component:
```
<adf-document-list
  #documentList
  currentFolderId="-root-"
  [contextMenuActions]="true"
  [contentActions]="true">
  <content-actions>
    <content-action target="folder"
                    permission="delete"
                    [disableWithNoPermission]="true"
                    [handler]="'delete'"
                    title="delete">
    </content-action>
  </content-actions>
</adf-document-list>
```
4. login with the consumer and see which action is enabled, login with the collaborator and see the same
Consumer: ![screenshot from 2018-03-22 09-31-20](https://user-images.githubusercontent.com/3147896/37759423-dfe272b4-2db3-11e8-9c14-739fc01ea01d.png)
Collaborator: ![screenshot from 2018-03-22 09-31-40](https://user-images.githubusercontent.com/3147896/37759426-e1f4f9c8-2db3-11e8-957c-b861770f3984.png)

Both should not be able to delete.

**Component name and version:** 
I tried digging into components and somewhere between the content-action and the data-table-row component it seems to go wrong.

**Browser and version:** 
all

**Node version (for build issues):**  
v9.4.0

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2551
