### ISSUE TITLE
how can i Translate the software i want to add Arabic to the dashboard how ?

### ISSUE THREAD

**Issue by OmarAllouzi95** [Alfresco/alfresco-ng2-components#3122]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
Hi https://github.com/Alfresco/alfresco-ng2-components/blob/development/docs/user-guide/internationalization.md maybe this document can help you
