### ISSUE TITLE
Update repo and issue paths in package.json files

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#313]
Update 'repo' and 'bugs' entries to point to public repository.

**Comment by magemello** [comment]
can you fix also these properties for all the components? 

 "repository": {
    "type": "git",
    "url": "https://github.com/alfresco/ng2-alfresco-viewer.git"
  },
  "bugs": {
    "url": "https://github.com/alfresco/ng2-alfresco-viewer/issues"
  },
