### ISSUE TITLE
Document list/ Data columns ngIf dosn't work

### ISSUE THREAD

**Issue by batmansk** [Alfresco/alfresco-ng2-components#3130]
**Type of issue:**  (check with "[x]")

> - [ x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
ngIf for data-columns in adf-document-list doesn't work.
Works only first time, but it is not updated when navigation down/up folders.

**Expected behavior:**

**Steps to reproduce the issue:**
in ts file create function onFolderChange {
this.condition = !this.condition;
}
<adf-document-list
  #documentList
  [currentFolderId]="rootFolder"
  [showHeader]="true"
  (folderChange)="onFolderChange($event)">

  <data-columns *ngIf="condition">
    <data-column key="$thumbnail" type="image" [sortable]="false"></data-column>
    <data-column key="name" title="Title" class="full-width name-column"></data-column>
  </data-columns>

  <data-columns *ngIf="!condition">
    <data-column key="id" [title]="FolderName"></data-column>
    <data-column key="createdAt" title="Created"></data-column>
  </data-columns>
</adf-document-list>

**Component name and version:** 
adf-document-list/data-columns

**New feature request:**
To have option to define columns in adf-document-list component for folder based on a condition(e.g. folder type).

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2589

**Comment by kaspereden** [comment]
I am not quite sure that the ngIf here is the best soldution. Neither is the one below but this is a workaround in the current environment :) I would just opt to use documentlist presets, like for example this: https://github.com/Alfresco/alfresco-ng2-components/issues/3049  

*workaround*
You can show/hide columns by setting a class and then show/hide it via css. (do not forget to ::ng-deep the styles if they don't seem to work properly) 

```
[ngClass]="{classname: condition}"
```
