### ISSUE TITLE
Travis badge on catalog is not visible for any component

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#314]
<img width="548" alt="screen shot 2016-06-30 at 10 10 38" src="https://cloud.githubusercontent.com/assets/7974125/16483136/f1322108-3eaa-11e6-9b30-6a6e8f3dd01d.png">
<img width="807" alt="screen shot 2016-06-30 at 10 10 46" src="https://cloud.githubusercontent.com/assets/7974125/16483135/f1312ece-3eaa-11e6-9484-ee0e3682313e.png">

**Comment by magemello** [comment]
The badge is still pointing to the private instance of travis, at the next publish will go away. No actions needed.

**Comment by VitoAlbano** [comment]
Re checked and now it's fine.
Closing.
