### ISSUE TITLE
[urlFile] in <adf-viewer> won't load preview of files with remote URLs

### ISSUE THREAD

**Issue by akolybelnikov** [Alfresco/alfresco-ng2-components#3182]
> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
The component won't load the preview of a file from a remote URL.

The plunkr linked in the documentation does not load the preview either:
https://embed.plnkr.co/iTuG1lFIXfsP95l6bDW6/

**Expected behavior:**
`[urlFile]` should load a preview of a file with a remote URL like so
`[urlFile]="'https://cntz06.contezza.nl/alfresco/service/api/internal/shared/node/WWDg_afiTU6lHEgr4fAbQA/content'"`
or like so
`[urlFile]="urlFile"`
with `urlFile: string = 'https://cntz06.contezza.nl/alfresco/service/api/internal/shared/node/WWDg_afiTU6lHEgr4fAbQA/content'` in the `.ts` file.

**Steps to reproduce the issue:**
Please try
`[urlFile]="'https://cntz06.contezza.nl/alfresco/service/api/internal/shared/node/WWDg_afiTU6lHEgr4fAbQA/content'"`

**Component name and version:** 
adf-viewer v2.2.0

**Browser and version:** 
all
 
**Node version (for build issues):**  
8.9.4

**Comment by DenisVuyka** [comment]
You are trying to preview a shared link? there's a "sharedLinkId" property for that purpose. Can you try `sharedLinkId="WWDg_afiTU6lHEgr4fAbQA"` ?

**Comment by akolybelnikov** [comment]
The sharedLinkId works well. The urlFile however dosn't.

**Comment by eromano** [comment]
yep I see from the example
