### ISSUE TITLE
Missing reference to the server side documentation

### ISSUE THREAD

**Issue by akolybelnikov** [Alfresco/alfresco-ng2-components#3216]
> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [X] Documentation

**Current behaviour:**
In the documentation to the [emailSharedLink](https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-core-rest-api/docs/SharedlinksApi.md#emailsharedlink) the reference to `"client"` isn't clear and the link to [server documentation](https://docs.alfresco.com/5.2/concepts/email-templates-intro.html) doesn't work.

**Expected behavior:**
A basic example of a client would be a good idea. For example:
`"client": "share"`

**Component name and version:** 
**alfresco-js-api --> sharedLinksApi**

**Comment by DenisVuyka** [comment]
this is an auto-generated docs and link is missing in the original swagger definition: https://api-explorer.alfresco.com/api-explorer/#!/shared-links/emailSharedLink
