### ISSUE TITLE
Generated app issues

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#322]
Generating an app with the yeoman generator seems not to be giving the same experience as the demoshell.

I tried on a fresh Ubuntu VM to ensure that I didn't have any local environment stuff in the way. I installed generator-ng2-alfresco-app generated a project, said yes to include all the components, ran `npm install` and `npm start`. 

Logging in works perfect and the page renderes. Clicking a few times in the document list and then it becomes unresponsive. From the javascript console I see this error:

``zone.js:461 Unhandled Promise rejection: EXCEPTION: Error in http://localhost:3000/node_modules/ng2-alfresco-search/dist/src/components/alfresco-search-control.component.html:13:0
ORIGINAL EXCEPTION: No provider for AlfrescoThumbnailService!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:4383:27)``

The error points towards the search component, so I tried updating the version in `package.json` to the latest version available on npmjs.com but the same error persists (even after deleting `node_modules` and rerunning `npm install`). 

I tried generating a new project and did not include the search component and now the navigation seems better, however breadcrumbs seems to be 50/50 and the navigation buttons below ("Go to root" etc.) now gives errors. 

I have had reports from developers trying it out and not being successful so it is not just an isolated issue with my machine.

Running the demoshell works great though, no issues. I tried copying the dependencies to get the exact same versions as the demoshell but still got errors.

**Comment by eromano** [comment]
I am going to fix it in the version 0.0.19
