### ISSUE TITLE
content-actions do not get disabled in context-menu-holder

### ISSUE THREAD

**Issue by kaspereden** [Alfresco/alfresco-ng2-components#3220]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

When using content-actions and a context-menu-holder the content actions do not get disabled correctly. The default content-actions do however get disabled correctly.
![image](https://user-images.githubusercontent.com/3147896/39046457-923d02fa-4496-11e8-86b6-d66a90cdb45b.png)
![image](https://user-images.githubusercontent.com/3147896/39046511-bdb911ee-4496-11e8-9ae6-d749601757e8.png)

**Expected behavior:**
Expected is that they both have the exact same behaviour.

**Steps to reproduce the issue:**
Create a content-action like this 
```
  <content-action target="document"
                                permission="create"
                                [permission]="'delete'"
                                [disableWithNoPermission]="true"
                                [disabled]="!hasPermission('delete')"
                                title="DOCUMENT_LIST.ACTIONS.DOCUMENT.VERSION_HISTORY"
                                (execute)="showVersionsDialog($event)">
                </content-action>
```

And also a ```<context-menu-holder></context-menu-holder>```

**Component name and version:** 
context-menu-holder
content-action

**Browser and version:** 
all
 
**Node version (for build issues):**

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2859

**Comment by DenisVuyka** [comment]
Notes: you have permission property declared 2 times:
```
permission="create"
[permission]="'delete'"
```
