### ISSUE TITLE
Multiple upload loses files on save of form (not complete)

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#3241]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When uploading multiple files to the upload control in a form when the user hits save the first and last file doesn't get uploaded and saved with the form

**Expected behavior:**
all files saved with the form

**Steps to reproduce the issue:**
Create form with upload component with multiple files option set
Upload 3 files and click save
first and last file doesn't get saved.

sample process included

**Component name and version:** 
activiti 1.6.4
ADF 2.2
adf-core/form
adf-core/form/components/widgets

**Browser and version:** 
all

**Node version (for build issues):**  
npm 5.7.1
node 8.9.4
[Attach Documents.zip](https://github.com/Alfresco/alfresco-ng2-components/files/1951383/Attach.Documents.zip)

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2858

**Comment by VitoAlbano** [comment]
Hi @tdonovancsra this was a bug related to APS that has been solved in the version 1.8.1 . 
Here it is the bug solved for APS : https://issues.alfresco.com/jira/browse/ACTIVITI-1249
