### ISSUE TITLE
The TimeAgoPipe is not translating correctly into Portuguese

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/alfresco-ng2-components#3274]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When using the content-app with Brazilian Portuguese language selected, everything is ok, except for the "X minutes ago" text, that is not translated.

**Expected behavior:**
The text should be shown as "X minutos atrás".

**Steps to reproduce the issue:**
Select Brazilian Portuguese as the language for the content-app.
Change any document property.
Check in the file list the text in English.

**Component name and version:** 
TimeAgoPipe version 2.3.1

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenisVuyka** [comment]
We have started working on this bug recently https://issues.alfresco.com/jira/browse/ADF-2699. Hopefully will arrive with new ADF version.
