### ISSUE TITLE
Form validation icon is not displayed when showValidationIcon option is enabled

### ISSUE THREAD

**Issue by miguel-galan** [Alfresco/alfresco-ng2-components#3276]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
ADF form doesn't display the validation icon when showValidationIcon option is enabled

**Expected behavior:**
Validation icon should be displayed when showValidationIcon option is enabled

**Steps to reproduce the issue:**
1. Using the adf-form component, add [showValidationIcon]= "true"
<adf-form 
   ...
    [showValidationIcon]="true"
   ...
</adf-form>

2. The form doesn't display the validation icon

**Component name and version:** 
Component: adf-form
Version: 2.3.0, 2.4.0-beta3

**Browser and version:** 
all

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-2999
