### ISSUE TITLE
Login Component logo not properly centered

### ISSUE THREAD

**Issue by witchedwiz** [Alfresco/alfresco-ng2-components#3289]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Login component has the logo not being centered (this is an aftereffect of a missing width)
When using the Login Component inside another component I've tried enforcing some behavior at no avail.. The only working workaround to affect html code delcared in adf core components, is using the "global" custom.css, but as the target element ( `<div class="mat-card-header-text">` ) lacks an id or a unique class and since the :has clause selector is not yet supported in any browser ( expressions like div.mat-card-header-text:has(> mat-card-title:has(> div.adf-alfresco-logo) are not properly supported by browser as you can see here https://caniuse.com/#feat=css-has ) 
, "addressing" the issue this way would introduce additional problems as it would effectively modify the behavior of all div mat-card-header-text globally.
hierarchy is:
```
<mat-card-header class="mat-card-header">
	<div class="mat-card-header-text">
		<mat-card-title class="mat-card-title">
            <div class="adf-alfresco-logo">
```
a simple width:100% has to be applied at the relevant `<div class="mat-card-header-text">`
the other alternative is to add the style with `ng::deep` in the importing component, but i still feel that while a bandain works, this is not the correct approach

![container_mat_card](https://user-images.githubusercontent.com/15959908/39807251-1e07176e-537c-11e8-9df2-a222aec07dcc.png)

**Expected behavior:**
Logos provided to the login component should fit the rest of the mat card design correctly

**Steps to reproduce the issue:**
Simply provide an external logo to the  component and the issue is there

**Component name and version:** 
 ng2-alfresco-login 2.2.0
checked and it seems no similar issue has been opend//closed for versions after the 2.2.0

**Browser and version:** 
Firefox 59, but I've also seen this in my safari browser through ipad and iphone. 
 
**Node version (for build issues):**  
9.9.0

**Comment by eromano** [comment]
this problem has been already fixed in 2.3.0 please update your components thanks.
