### ISSUE TITLE
Minimise button for upload dialog is on the wrong level

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#330]
Minimise button should be aligned with a Close one.

<img width="710" alt="screen shot 2016-07-01 at 13 45 52" src="https://cloud.githubusercontent.com/assets/503991/16522692/3b7adbaa-3f97-11e6-94fb-2fc903a547be.png">

**Comment by VitoAlbano** [comment]
Fixed.

![screen shot 2016-07-11 at 18 13 43](https://cloud.githubusercontent.com/assets/7974125/16739687/4873780e-4793-11e6-9e93-5b520b4efb86.png)
