### ISSUE TITLE
Events on 'LOCK' handler does not trigger

### ISSUE THREAD

**Issue by anshukumar2311** [Alfresco/alfresco-ng2-components#3377]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Events of content actions such as (permissionEvent) and (success) does not trigger on **LOCK** handler.

**Expected behavior:**
Events should trigger on **LOCK** handler as it works for other handlers such as **MOVE**, **COPY**, **DELETE**

**Steps to reproduce the issue:**
Add below code in **content-actions** of **adf-document-list** component

<content-action
        title="{{'DOCUMENT_LIST.ACTIONS.DOCUMENT.LOCK' | translate}}"
        [icon]="'lock'"
        [target]="'document'"
        [handler]="'lock'"
        [disableWithNoPermission]="true"
        (permissionEvent)="onLockActionPermissionError($event)"
        (success)="onLockActionSuccess($event)">
</content-action>

Implement event functions in corresponding script file and add alerts to it.

**Component name and version:** 
ADF 2.3.0

**Browser and version:** 
Chrome 66.0
 
**Node version (for build issues):**  
node v8.9.4

**New feature request:**

**Comment by eromano** [comment]
Hi as for documentation 
https://github.com/Alfresco/alfresco-ng2-components/blob/master/docs/content-services/content-action.component.md

Emitted when the action succeeds with the success string message. Applies to copy, move and delete actions.
