### ISSUE TITLE
Configure cross-origin calls to activiti

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#342]
Test CORS working via Tomcat servlet filter and publish a Docker container with this enabled

**Comment by wabson** [comment]
Docker image has been pushed to `docker-internal.alfresco.com/wabson/activiti-app-tomcat`. A `docker-compose` file is available in this [gist](https://gist.github.com/wabson/664134b3ff285744b3fd0cb7ffe13bc9#file-docker-compose-yml) which references this and starts up an environment with MySQL as the DB.
