### ISSUE TITLE
Error not found ~@mat-datetimepicker

### ISSUE THREAD

**Issue by kremmer** [Alfresco/alfresco-ng2-components#3425]
With the new version 2.2.0 i have this error : 
File to import not found or unreadable: ~@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss

**Comment by DenisVuyka** [comment]
@kremmer the latest version is 2.3.0. have you checked if you have the following libs installed?

```json
"@mat-datetimepicker/core": "1.0.1",
"@mat-datetimepicker/moment": "1.0.1",
```

**Comment by DenisVuyka** [comment]
@kremmer please do not remove the issue template next time.

**Comment by kremmer** [comment]
thanks @DenisVuyka 
 but I have "@mat-datetimepicker/core": "1.0.4",
and I followed the config of https://community.alfresco.com/docs/DOC-7318-adf-220-release-note#jive_content_id_New_package_versions
{
  "name": "adf-cli-acs-template",
  "version": "2.0.0",
  "blueprint": "Content Services",
  "description": "ACS ADF Application with Angular CLI",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --open",
    "build": "ng build",
    "clean": "npm run clean-build  && rimraf dist node_modules typings dist",
    "clean-build": "rimraf 'app/{,**/}**.js' 'app/{,**/}**.js.map' 'app/{,**/}**.d.ts'",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "publishConfig": {
    "registry": "https://nexus.mtpl.bs.fr.atos.net/repository/npm-private/"
  },
  "private": true,
  "dependencies": {
    "@alfresco/adf-content-services": "2.2.0",
    "@alfresco/adf-core": "2.2.0",
    "@angular/animations": "5.0.0",
    "@angular/cdk": "5.0.0-rc0",
    "@angular/common": "5.0.0",
    "@angular/compiler": "5.0.0",
    "@angular/core": "5.0.0",
    "@angular/flex-layout": "5.0.0-beta.13",
    "@angular/forms": "5.0.0",
    "@angular/http": "5.0.0",
    "@angular/material": "5.0.0-rc0",
    "@angular/platform-browser": "5.0.0",
    "@angular/platform-browser-dynamic": "5.0.0",
    "@angular/router": "5.0.0",
    "@mat-datetimepicker/core": "1.0.4",
    "@ngx-translate/core": "9.1.1",
    "@xyezir/mat-datetimepicker-core": "0.0.3",
    "alfresco-js-api": "2.2.0",
    "angular-2-multiple-selection": "*",
    "body-parser": "^1.18.3",
    "chart.js": "2.5.0",
    "classlist.js": "1.1.20150312",
    "core-js": "2.4.1",
    "custom-event-polyfill": "0.3.0",
    "dragula": "^3.7.2",
    "express": "^4.16.3",
    "hammerjs": "2.0.8",
    "intl": "1.2.5",
    "minimatch": "3.0.4",
    "moment": "2.15.2",
    "moment-es6": "^1.0.0",
    "mysql": "^2.15.0",
    "ng2-accordion": "0.0.15",
    "ng2-charts": "1.6.0",
    "ng2-dnd": "^5.0.2",
    "ng2-dragula": "^1.5.0",
    "ng2-file-upload": "^1.3.0",
    "ngx-perfect-scrollbar": "^5.3.5",
    "pdfjs-dist": "1.5.404",
    "raphael": "2.2.7",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.2",
    "web-animations-js": "2.3.1",
    "zone.js": "0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.5.0",
    "@angular/compiler-cli": "5.0.0",
    "@angular/language-service": "5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^6.0.111",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.3",
    "karma-jasmine": "^1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "rimraf": "^2.6.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "~2.4.2"
  }
}

I followed the config of https://community.alfresco.com/docs/DOC-7318-adf-220-release-note#jive_content_id_New_package_versions

**Comment by DenisVuyka** [comment]
ADF 2.3.0 is built with 1.0.1. What guide said it should be 1.0.4 ?
