### ISSUE TITLE
Auth guards are not working with query parameters

### ISSUE THREAD

**Issue by dhrn** [Alfresco/alfresco-ng2-components#3437]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**  AuthGauds is seems to be not working

https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/services/auth-guard-bpm.service.ts#L49

https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/services/auth-guard-ecm.service.ts#L62

/route/:id?queryparameter=value

when session is availabe, then it is working.
if session is not available, authgauds are preventing are not working as expected.
i mean, the both id and query parameter taking as id
new redirect url is -> 
**Expected behavior:**

when session is not available, authguads needs to be redirected to same url(after logged in).
https://stackoverflow.com/questions/45035660/angular-routing-canactivate-authguard-transmit-query-params

**Steps to reproduce the issue:**
```
 export const appRoutes: Routes = [
     { path: 'login', component: LoginDemoComponent },
     {
        path: 'app',
        component: AppContainerComponent,
        canActivate: [ AuthGuardBpm ],
        children: [
          { path: 'task-detail/:taskId', component: TaskDetailComponent, canActivate: [ AuthGuardBpm ] }
        ]
     }
];

```
/app/task-detail/pending-task?status=done
 try to access url in incognito window(new session)

**Service name and version:** 
 1. AuthGuardBpm
2. AuthGuardEcm

**Browser and version:** 
all

**Node version (for build issues):**  
All

**Comment by DenisVuyka** [comment]
@dhrn I've updated the title because it seems to be related to BPM guards

**Comment by pionnegru** [comment]
@dhrn why not use `canActivateChildren`?

```javascript
 export const appRoutes: Routes = [
     { path: 'login', component: LoginDemoComponent },
     {
        path: 'app',
        component: AppContainerComponent,
        canActivate: [ AuthGuardBpm ],
        canActivateChildren: [ AuthGuardBpm ],
        children: [
          { path: 'task-detail/:taskId', component: TaskDetailComponent }
        ]
     }
];
```

**Comment by pionnegru** [comment]
ok, I see the problem. We already try to build original url with query params [here](https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/services/auth-guard-bpm.service.ts#L60), but queries with `?` seem to get lost

**Comment by dhrn** [comment]
@pionnegru is it a bug or not?

**Comment by DenisVuyka** [comment]
@dhrn We will try to address that scenario

**Comment by dhrn** [comment]
thanks @DenisVuyka

**Comment by eromano** [comment]
@dhrn maybe this can help you

```javascript

        this.alfrescoApiService.getInstance().on('error', (error) => {
            if (error.status === 401) {
                if (!this.authenticationService.isLoggedIn()) {
                    this.router.navigate(['/login']);
                }
            }
        });
```
