### ISSUE TITLE
Comma in file name causes problems in Chrome browser

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#3458]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [√] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When a user uploads a file that contains a comma in its name, Google Chrome allows the upload. However, when someone tries to download that same file,
Chrome thinks that the action is trying to send one header with 2 Content-Disposition, asking for 2 separate files due to the comma in the filename. Because
 of this behavior, Chrome block the download to prevent splitting attack. 

**Expected behavior:**
Users should be able to download a file that contains comma in it or at least prevent them from uploading such file in the first place. 

**Steps to reproduce the issue:**
Step 1: Navigate to any widget or module that allows you to upload a file 
     Step 2: Use any file that its name has a comma in it.
     Step 3: Upload said file
     Step 4: Try to download the file, and you should get an error that looks like this in your browser's inspection view
      (only broken in Chrome): ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

**Component name and version:** 
ADF 2.2.0
APS 1.6.2

**Browser and version:** 
Chrome 66
Note: doesn't happen in IE
 
**Node version (for build issues):**  
Angular CLI: 1.5.0
Node: 8.9.4
OS: darwin x64
Angular: 5.1.1
... animations, common, compiler, core, forms, http
... platform-browser, platform-browser-dynamic, router

```
@angular/cdk: 5.0.1
@angular/cli: 1.5.0
@angular/compiler-cli: 5.2.11
@angular/flex-layout: 2.0.0-beta.12
@angular/language-service: 5.2.11
@angular/material-moment-adapter: 5.0.1
@angular/material: 5.0.1
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.7.0-beta.1
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.8.1
```

**Comment by tdonovancsra** [comment]
https://github.com/Alfresco/alfresco-ng2-components/issues/3458

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-3157

**Comment by tdonovancsra** [comment]
@eromano why is this being pushed to 2.5.0.  From the internal ticket the @VitoAlbano claims he does not see it.  We have upgraded to ADF 2.4.0 and APS 1.9.0 and it's still a problem.   Is there an ADF fix for this as well?  Having our testers hit it again to be sure

**Comment by tdonovancsra** [comment]
Ok so testers confirm issue still there.  And just to be clear.  The file can be uploaded but errors on the **download**

**Comment by tdonovancsra** [comment]
We are just using APS 1.9.0 and ADF 2.4.0.  @DenisVuyka

**Comment by DenisVuyka** [comment]
@tdonovancsra Yes, my bad, was thinking of ACA.

**Comment by DenisVuyka** [comment]
My guess: might be related to APS as we just let the browser download the content without loading it into the application for security reasons (i.e. if you download scripts or insecure content).

**Comment by tdonovancsra** [comment]
Yeah wouldn't be surprised.  Just making sure the issue gets to the right place.  Is there something we can do?  Say override one of the beans in the meantime?

**Comment by tdonovancsra** [comment]
Just to update this also happens on:
ADF 2.4.0
APS 1.9.0

**Comment by tdonovancsra** [comment]
any progress on this? @DenisVuyka
