### ISSUE TITLE
Test saucelabs tool https://saucelabs.com/features

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#350]

**Comment by hashraf88** [comment]
I am in contact with broserstack to see if they provide readme badges and matrices, similar to that which Saucelab offer and also with regards to free plans for open source projects. 

![screen shot 2016-07-05 at 12 00 33](https://cloud.githubusercontent.com/assets/13200338/16582653/1993af76-42a8-11e6-86c3-6f64d272fec6.png)

**Comment by VitoAlbano** [comment]
I got the answer from browserstack team : 
"Hello Vito,
Thanks for the email. We are happy to offer you a free subscription. In return, we ask for a mention of BrowserStack on your project page & website. I hope this works for you?
I’m afraid we do not offer badges to display a matrix of browsers on your Readme. But we’ll keep you posted as this is made available.
Regards, 
Adithya Chadalawada 
www.browserstack.com"

So browser stack doesn't provide the badge
