### ISSUE TITLE
NotificationService additional styling options addition

### ISSUE THREAD

**Issue by witchedwiz** [Alfresco/alfresco-ng2-components#3527]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
NotificationService currently supports just snackMessage and snackMessage with action.. Theming is flat black, and positioning cannot be arranged

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 
ng2-NotificationService 

**Browser and version:** 
not applicable
 
**Node version (for build issues):**  
not applicable

**New feature request:**
I think that the notificationservice is a step in the right direction into offering a consistent user experience with notification instead of stale "messages" displayed in the form, but as is the service feels still too "small" in scope.
I'd suggest that you switch from:
openSnackMessage(message: string, millisecondsDuration?: number): MatSnackBarRef<any>;
to
/**
position -> center, bottom, top
textcolor -> color hex for text
backcolor -> color hex for background of the box
*/
openSnackMessage(message: string, millisecondsDuration?: number, position?: string, textcolor?: string, backcolor?: string): MatSnackBarRef<any>;

or
/**
position -> center, bottom, top
messageLevel -> info, warn, error (applying apt coloring on the background, for example info green, warning orange, error red )
*/
openSnackMessage(message: string, millisecondsDuration?: number, position?: string, messageLevel?: string): MatSnackBarRef<any>;

clearly the same signature modification should be applied to openSnackMessageAction

**Comment by DenisVuyka** [comment]
We can add support for custom css class names passed to the notification component. In that case you can provide necessary positioning

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-3286
