### ISSUE TITLE
Doubleclick event in datatable has cyclic dependency

### ISSUE THREAD

**Issue by witchedwiz** [Alfresco/alfresco-ng2-components#3528]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
in the datatable component the event triggered by the "doubleclick" is structured in a way that has a property that reference the object itself..
as evidence, you cannot JSON.stringify it
.html file

<adf-datatable [data]="data"
(rowDblClick)="rowDblClickEvent($event)"
..
..

.ts file
rowDblClickEvent(event: any)
{
console.log(JSON.stringify(event);
}

will raise a cyclical dependency issue
which is due to JSON stringify encountering in the object a property that in turn refers to another property of the same object which CONTAINS the property that is currently being "stringified"
e.g.
event [ prop1, prop2, prop3]
prop2 [ prop21, prop22, prop23]
prop22[ prop221, prop2, prop 223]
prop22.prop2 is effectively pointing to its parent prop2
hence it will raise the cyclical dependency issue when JSON.stringify will try to resolve it

**Expected behavior:**
this is a tricky one, as normally one would just JSON.stringify when doing some debugging so it's not a glaring bug per se, it's just that it's not clear if the cyclical reference inside the object is required or was an oversight.

**Steps to reproduce the issue:**
simply trap a doubleclick event from the datatable component and try to JSON.stringify the object.

**Component name and version:** 
2.3.0

**Browser and version:** 
all
 
**Node version (for build issues):**  
9.9.0

**Comment by DenisVuyka** [comment]
The event implementation is as following:

```
export class DataRowEvent extends BaseUIEvent<DataRow> {

    sender: any;

    constructor(value: DataRow, domEvent: Event, sender?: any) {
        super();
        this.value = value;
        this.event = domEvent;
        this.sender = sender;
    }
}
```

The event carries `sender` and `event` (original DOM event) to aid in app-level subscriptions. You can stringify `event.value` if needed, but it's difficult to imagine why developers will need `console.log` and `JSON.stringify` for these events in production. 

Closing for now until there's a business value in removing class members.
