### ISSUE TITLE
Disable native menu for context menu component

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#353]
It should not be possible displaying native browser context menu for the dropdown component displayed by context menu component.

Actual behaviour:
<img width="279" alt="screen shot 2016-07-05 at 10 59 30" src="https://cloud.githubusercontent.com/assets/503991/16581109/af905154-429f-11e6-8abc-c549633bdd02.png">

**Comment by VitoAlbano** [comment]
Checked.
Solved.
