### ISSUE TITLE
Need the ability to override default date format

### ISSUE THREAD

**Issue by alex4u2nv** [Alfresco/alfresco-ng2-components#3539]
Currently, when you try to override the format of dates used in adf-document-library where timeAgo formatting was applied, the new format defaults to 'MMM d, y, h:mm:ss a'
<img width="224" alt="oea_repository" src="https://user-images.githubusercontent.com/40564/41990581-cd7601aa-7a10-11e8-9789-e23c57af8b89.png">

**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Overriding the date format on components does not render dates and time in the expected format.

**Expected behavior:**
use a materials date format, and have dates render in those formats
https://docs.angularjs.org/api/ng/filter/date

**Steps to reproduce the issue:**
Change format='timeAgo' to format='short' 
Rendered date does not follow expected format 'short': equivalent to 'M/d/yy h:mm a' for en_US locale (e.g. 9/3/10 12:05 PM)

**Component name and version:** 
"@alfresco/adf-content-services": "2.4.0",
"@alfresco/adf-core": "2.4.0",

**Browser and version:** 
 all
 

**New feature request:**
Time Ago should take an optional format parameter that will render dates based on that format, if document is older than time ago thresholds.

**Comment by DenysVuika** [comment]
I has been fixed and should work fine with 2.6.0
