### ISSUE TITLE
Fast deploy buttons

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#354]
Would be nice make our application easy to depoly. To do so @eromano found the following set of buttons on the parse repository. Let's investigate how to implements the same set of buttons :

https://elements.heroku.com/buttons/parseplatform/parse-server-example?data%5Btrackable%5D%5Baction%5D=Clicked&data%5Btrackable%5D%5Bcategory%5D=Heroku+Button&data%5Btrackable%5D%5Blabel%5D=View+Details

**Comment by jsotiro** [comment]
Great idea. I would most certainly do AWS
