### ISSUE TITLE
Add drop-down list option to edit metadata/properties, which are constrained with a discrete list of values 

### ISSUE THREAD

**Issue by syankov** [Alfresco/alfresco-ng2-components#3540]
**Type of issue:**  (check with "[x]")

> - [x ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

I am working with the alfresco-content-app starter project. 
I am modifying the <adf-content-metadata-card> (ContentMetadataComponent) in the side panel to display properties from a particular aspect. The pulled-in properties are configured through a custom preset in app.config.json->content-metadata, as described [here](https://alfresco.github.io/adf-component-catalog/additional-documentation/tutorials/content-metadata-component.html) . This works well and I can see and edit the properties. However, one of my properties has a list constraint and can only accept values that are defined in a list in the aspect. Currently the ContentMetadataComponent displays only text inputs or date picker inputs for editable properties. It should allow configuration and display of option inputs where the user can select from a discrete set of values.

**Expected behavior:**

For an editable property whose value is constrained by a list of values configuration should be possible to present this property as a drop-down select input with pre-defined selection options.

**Steps to reproduce the issue:**

**Component name and version:** 

ContentMetadataComponent ADF 2.4.0

**Browser and version:** 
all

 
**Node version (for build issues):**  

**New feature request:**

For an editable property whose value is constrained by a list of values configuration should be possible to present this property as a drop-down select input with pre-defined selection options.

**Comment by eromano** [comment]
duplicated of https://github.com/Alfresco/alfresco-ng2-components/issues/3709
