### ISSUE TITLE
Header bar in document-list-component doesn't auto-scroll

### ISSUE THREAD

**Issue by kevingroen** [Alfresco/alfresco-ng2-components#3545]
**Type of issue:**  (check with "[x]")

> - [X ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
The ADF document-list component contains multiple rows. Therefore we need to scroll to see content at the bottom. If we scroll to the bottom, the header bar doesn't scroll down.

**Expected behavior:**
The ADF document-list component contains multiple rows. Therefore we need to scroll to see content at the bottom. If we scroll we want the header bar to auto scroll down.

**Steps to reproduce the issue:**
Fill a documentlist with enough rows so that a scrollbar appears. Scroll down to see that the header stays in place.

**Component name and version:** 
document-list.component

**Browser and version:** 

 
**Node version (for build issues):**  
v6.11.4

**New feature request:**
User experience

**Comment by eromano** [comment]
Could you provide a screenshot/video of your problem?
