### ISSUE TITLE
EcmUserService.getInstance() returns undefined

### ISSUE THREAD

**Issue by gpaucot** [Alfresco/alfresco-ng2-components#3552]
The application is basically a searchscreen. It has its own implementation of SearchQueryBuilder that uses the username in some queries. An error arises on (most) reloads, it seems that EcmUserService.getInstance() returns undefined.

**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
SavedSearchComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property 'core' of undefined
    at EcmUserService.getUserInfo (adf-core.js:5840)
    at EcmUserService.getCurrentUserInfo (adf-core.js:5845)
    at new EageSearchQueryBuilderService (eage-search-query-builder.service.ts:18)
    at createClass (core.js:12480)
    at _createProviderInstance (core.js:12447)
    at createProviderInstance (core.js:12288)
    at createViewNodes (core.js:13763)
    at createRootView (core.js:13665)
    at callWithDebugContext (core.js:15090)
    at Object.debugCreateRootView [as createRootView] (core.js:14373)

**Steps to reproduce the issue:**
A clean flow works: login, search, navigate, etc. but when already logged in, if we refresh then we get that error.

**Component name and version:** 
EcmUserService
v2.4.0

**Browser and version:** 
Google Chrome Version 67.0.3396.99 64bits Windows 10

**Comment by DenisVuyka** [comment]
@gpaucot You raise a bug for the code that is not the part of ADF. What is the way to reproduce the issue with ADF given that Search Query Builder is not using EcmUserService

**Comment by DenisVuyka** [comment]
`getCurrentUserInfo` is not an event. It is just a method that returns an Observable. You cannot subscribe to it in the constructor of a singleton service and expect it to be fired when app starts.

**Comment by DenisVuyka** [comment]
Just use the method when it is really needed, not in the constructor.

**Comment by gpaucot** [comment]
Yes it is what we did and that works fine. It was just not obvious to me why calling getCurrentUserInfo() without subscribe triggered an error. 
But again, it is not blocking anymore ;-)

**Comment by DenisVuyka** [comment]
Ok, then closing this ticket for now. Thanks.
