### ISSUE TITLE
ADF: search filter component doesn't resolve user names

### ISSUE THREAD

**Issue by HansDeBal** [Alfresco/alfresco-ng2-components#3559]
**Type of issue:**  (check with "[x]")

> - [*] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**New feature request:**
We are using ADF 2.4 and defined a filter on a custom property containing usernames. Is it possible to resolve these usernames to full names in the facet values?

**Comment by DenisVuyka** [comment]
@HansDeBal do you know if the Search API (https://api-explorer.alfresco.com/api-explorer/#!/search/search) allows doing that?

**Comment by HansDeBal** [comment]
Yes it does,

When providing this request-body:
`{
  "query": {
    "query": "*",
    "language": "afts"
  },
  "facetFields": {"facets": [{"field": "creator", "mincount": 1}, {"field": "modifier", "mincount": 1}]}
}`

I get a response containing a display-key which contains the full name of the user:
`{
              "label": "mjackson",
              "filterQuery": "creator:\"mjackson\"",
              "count": 55,
              "display": "Mike Jackson"
            }`

**Comment by DenisVuyka** [comment]
@HansDeBal So what is the issue then? for 2.4.0 we already show display names for "Creator" and "Modifier" fields. You can check ACA.

**Comment by DenisVuyka** [comment]
![screen shot 2018-07-31 at 10 12 38](https://user-images.githubusercontent.com/503991/43450275-47800320-94aa-11e8-8453-30d7b2571aef.png)

**Comment by HansDeBal** [comment]
@DenisVuyka This only seems to work on Alfresco properties. We have a custom property which contains the username and this doesn't get resolved:
`"facetsFields": [{
				"label": "FACETS.CLAIMANT",
				"buckets": [{
					"label": "JohnDoe",
					"filterQuery": "ea:claimant:\"JohnDoe\"",
					"count": 1
				}]
			}`

**Comment by HansDeBal** [comment]
![image](https://user-images.githubusercontent.com/10340138/43450686-8cdd8e2a-94b3-11e8-9c42-8cf0cdf2a7ac.png)

**Comment by HansDeBal** [comment]
Fixed issue by extending publicapi.personPropertyLookup-bean
