### ISSUE TITLE
ADF accordion-group not opening

### ISSUE THREAD

**Issue by MisterPro93** [Alfresco/alfresco-ng2-components#3571]
**Type of issue:**

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
The accordion-group attribute [isOpen]="false" results in a closed accordion-group that CANNOT be opened, [isOpen]="true" results in an open accordion-group that CAN be closed and opened.

**Expected behavior:**
The accordion-group attribute [isOpen]="false" should provide the same behaviour as [isOpen]="true", just with a "closed" starting state.

**Steps to reproduce the issue:**
Set the accordion-group attribute [isOpen]="false" and try to open the accordion-group. Repeat the same with  [isOpen]="true", now closing and opening the accordion-group does work.

**Component name and version:** 
accordion-group.component with ADF 2.4.0

**Browser and version:** 
Chrome 67.0.3396.99

**Comment by DenysVuika** [comment]
Closing as this component no longer exists in 3.x, use mat-accordion instead.
