### ISSUE TITLE
Support for multiline content for datatable component (in gallery mode)

### ISSUE THREAD

**Issue by dmoeyersons** [Alfresco/alfresco-ng2-components#3606]
**Type of issue:**  (check with "[x]")

> - [X] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
The datatable component show it's content on one line in list display mode as well as in gallery display mode. If the content is getting larger, the datatable reacts differently depending on the display mode:
- in the list display mode you get a horizontal scrollbar making you scroll left and right to see all the content (not responsive!)
- in gallery mode the content is broken of at the right side of the card view and you see only a part of the full content. There actually isn't a lot of space for the content. In gallery mode, the cards also seem to have a fixed width, so that the width of the screen isn't always used well (not fully responsive, only partly).

**Expected behavior:**
Because content can be important and responsive apps are desired, the behavior described above is not always desired. Especially because the developer doesn't always control the size of the content of the datatable.
Gallery display mode could be an answer to have responsive datatables that fit on smaller (smartphones) screens. (for example: list mode on computer & tablet screens, gallery mode on mobile devices).
Maybe we could have a property to allow the content to be multiline & responsive. ([multiline]="true")
The multiline option would give the following behaviour:
- list mode: the datatable is stretched to the width of the screen and the content is displayed over multiple lines if needed. (i already achieved this by setting the rowStyle to "{'word-wrap': 'break-spaces', 'white-space': 'initial'}")
- gallery mode: the cards fill the width of the screen and the content is displayed over multiple lines instead of being broken of (i have found no simple solution for this).

**Steps to reproduce the issue:**
Create a standard datatable with a few (5 or more) columns, put a short sentense in each column, enough to make it overflow. Set the datatable display mode in list mode and see the results, set the datatable display mode in gallery mode and see the results

**Component name and version:** 
adf-datatable ADF v2.4.0

**Browser and version:** 
all
 
**Node version (for build issues):**  
8.11.1

**New feature request:**
I would like this change to be able to offer more responsive datatables that show the full content on as computer screens, tablets and mobile devices.
I am currently working on a front end design for a task list (data list), where every item in the task list has several properties. The content of the task list is important to understand the task, so it isn't useful when specific data is not visible, also users complain when they need to scroll left & right, because they lose the overview of each task. Because the task list has 9 columns i would want to switch to gallery mode on mobile devices, but in that mode my task list is completely useless, because most of the content disappears.

**Comment by eromano** [comment]
Hi @dmoeyersons you can modify the style of the datable or document list from your app if you don't like the default behaviour

**Comment by dmoeyersons** [comment]
hi @eromano , I have solved it without using adf-datatable. Thanks.
