### ISSUE TITLE
Unable to run npm install command 

### ISSUE THREAD

**Issue by sai401** [Alfresco/alfresco-ng2-components#3621]
> - [x] Support request

**Current behaviour:**
After cloning the trough git i am trying to  install node modules by typing command npm install but it is throwing one message called 
"up to date in 1.906s
found 0 vulnerabilities"
what should i do 

**Expected behavior:**
i didnt understand how to run the application can anyone help with this .I want to run this application,

**Comment by DenisVuyka** [comment]
Please use issue tracker to raise bugs for the framework. For all the non-issue related activities please use [Gitter](https://gitter.im/Alfresco/alfresco-ng2-components) or [Community Portal](https://community.alfresco.com/community/application-development-framework)
