### ISSUE TITLE
TranslationService in lazy-loaded modules

### ISSUE THREAD

**Issue by HansDeBal** [Alfresco/alfresco-ng2-components#3652]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Steps to reproduce the issue:**
We get 2 different intances of the TranslationService: 1 for the AppModule and 1 for the LazyModule. As a result:
- the language is not shared thus a translationService.use() only affects part of the application.
- the translations are loaded multiple times, once for the AppModule and once for the LazyModule.

How to reproduce:
In the AppModule, import the AdfModule.
In the LazyModule, import
CoreModule.forChild() and ContentModule.
Configure the language on AppModule with translationService.userLang = 'xx' and dump both instances. Notice that the userLangs are different.

Most of our modules are lazy-loaded, is there a know way to solve this ? If so, could you provide a simple example of code ?

**Comment by HansDeBal** [comment]
FYI: also created a ticket on the support site, 00969844

**Comment by DenisVuyka** [comment]
@HansDeBal Yes, we already have a PR in progress that addresses the Lazy Loading concerns.

**Comment by HansDeBal** [comment]
ok, great. So we can expect this fix in 2.5?

**Comment by DenisVuyka** [comment]
Hopefully yes. You can watch #3609 PR for the progress.
