### ISSUE TITLE
Document list icons could be better named

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#366]
When using a screen reader certain options within a document list column could be better named so when read have more relevance 
more_vert to more
account_circle to account
cloud_download to download

![screen shot 2016-07-06 at 11 30 00](https://cloud.githubusercontent.com/assets/13200338/16615258/44ccd2ec-436d-11e6-8b4a-b6d2f9ac5aa2.png)
![download](https://cloud.githubusercontent.com/assets/13200338/16616156/53898144-4373-11e6-8117-a90397656575.png)
![account](https://cloud.githubusercontent.com/assets/13200338/16616157/538b38e0-4373-11e6-8d92-b1bd0807f3ba.png)

**Comment by DenisVuyka** [comment]
These names are based on this icon set: https://design.google.com/icons/
