### ISSUE TITLE
'cm:lockOwner' field contains literal string value '[object Object]' when requesting it via the nodesApi

### ISSUE THREAD

**Issue by m-gv** [Alfresco/alfresco-ng2-components#3661]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

When using the nodesApi.getNode(id) call to retrieve node data, the 'cm:lockOwner' property is returned as cm:lockOwner: "[object Object]"

The same behaviour is also present for the lockNode and unlockNode calls.

**Expected behavior:**

The lockOwner object should be parsed and added to the properties as such, so that the information is accessible.

Should be patched for all calls where the lockOwner object is made available.

**Steps to reproduce the issue:**

1. Fetch a locked file using the Nodes API: nodesApi.getNode(id)
2. View the object returned by the getNode call: 
* Under properties, the field 'cm:lockOwner' gets returned as string value '[object Object]'

**Component name and version:** 

ADF 2.4.0

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-3495
