### ISSUE TITLE
Visibility rule based on Checkbox's unchecked value does not work in ADF

### ISSUE THREAD

**Issue by dkochubei-clgx** [Alfresco/alfresco-ng2-components#3678]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Visibility rule that displays a field when a checkbox is not checked does not work in ADF

**Expected behavior:**
A field should be visible when a checkbox is not checked

**Steps to reproduce the issue:**
Place Textfield and Checkbox on the form. Configure Textfield to be visible when the checkbox is not checked.

**Component name and version:** 
Possibly WidgetVisibilityService

**Browser and version:** 
Chrome 68.0.3440.84
 
**Node version (for build issues):**  

**New feature request:**
Checkbox's default value is 'null' for unchecked state, but the rule which is configured in App Designer expects it to be 'false'.

**Comment by eromano** [comment]
Hi @dkochubei-clgx can you please tell me which version are you using of ADF?

**Comment by dkochubei-clgx** [comment]
Hi, @eromano. ADF 2.4.0

**Comment by eromano** [comment]
Could you try to update to 2.5.0?

**Comment by eromano** [comment]
just checked in 2.5.0 is working please feel free to reopen if you see something different
