### ISSUE TITLE
Global configure "appearance" for Material 6 form fields

### ISSUE THREAD

**Issue by ManuelEssmeister** [Alfresco/alfresco-ng2-components#3682]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
The only way of customizing the look and feel of OOTB form fields is with CSS (SCSS)

**Component name and version:** 
FormComponent / Widgets...

**New feature request:**
Angular Material 6 supports a new configuration property called "appearance". This allows modifying the look and feel of mat-form-field elements. Check out this example (taken from the angular material documentation) https://stackblitz.com/angular/nnkyqlmyqod?file=app%2Fform-field-appearance-example.html
I understand the ADF version 2.5.x will use Angular/Material 6. Therefore being able to configure all OOTB fields with an appearance would be a huge benefit (especially because of the "outline" appearance).

**Comment by eromano** [comment]
Hi @ManuelEssmeister nice idea. The only maybe little problem that i see if we expose an appearance option it will affect the whole Form . So the whole form will have appearance : 'legacy' | 'standard' | 'fill' | 'outline'

**Comment by fcorti** [comment]
Not valid anymore.
