### ISSUE TITLE
ADF 2.5 issue with intl polyfill

### ISSUE THREAD

**Issue by kaspereden** [Alfresco/alfresco-ng2-components#3710]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
In the browser console I am getting the following message: 
```
Uncaught ReferenceError: global is not defined
at Object../node_modules/intl/index.js (index.js:2)
at webpack_require (bootstrap:81)
at Object../src/polyfills.ts (zone.js:3060)
at webpack_require (bootstrap:81)
at Object.4 (polyfills.ts:77)
at webpack_require (bootstrap:81)
at checkDeferredModules (bootstrap:43)
at Array.webpackJsonpCallback [as push] (bootstrap:30)
at polyfills.js:1
```
It is gone after I've disabled the intl polyfill. But that is probably not the way to go...

**Expected behavior:**
no messages

**Steps to reproduce the issue:**
I've upgraded from adf 2.4 to 2.5

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  
v10.8.0

**New feature request:**

**Comment by DenisVuyka** [comment]
@kaspereden according to this thread, this one is not needed anymore with 6.x: https://github.com/angular/angular-cli/issues/9920

**Comment by kaspereden** [comment]
@DenisVuyka cool, we also do not face extra problems by this. So it only needs to be removed from the generator

**Comment by DenisVuyka** [comment]
@kaspereden already updated generators, thanks 👍

**Comment by kaspereden** [comment]
cool lets close this
