### ISSUE TITLE
ADF 2.5 issue with task details

### ISSUE THREAD

**Issue by kaspereden** [Alfresco/alfresco-ng2-components#3715]
**Type of issue:**  (check with "[x]")

> - [X] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
The task details component ignores the "showHeader" boolean and lets the end user decide whether or not it actually shows  the header. Also the label has not been translated.

![image](https://user-images.githubusercontent.com/3147896/44447502-b0159400-a5e8-11e8-88c7-6560ed6c0a75.png)

**Expected behavior:**
At least an option to disable the button. 

Also a translated label

**Steps to reproduce the issue:**
Create a page with a task details component.
```
<adf-task-details
  [taskId]="taskId"
  [showChecklist]="false"
  [showComments]="false"
  [showFormCompleteButton]="true"
  [showFormRefreshButton]="false"
  [showFormSaveButton]="false"
  [showFormTitle]="false"
  [showHeader]="false"
  [showHeaderContent]="false"
  [showInvolvePeople]="false"
  [showNextTask]="false">
</adf-task-details>
```

**Component name and version:** 
ADF 2.5
Task detail component

**Browser and version:** 
all
 
**Node version (for build issues):**  
10.8.0

**New feature request:**
Option to disable  this toggle

**Comment by eromano** [comment]
Thanks to highlight this problem seems that we moved the e2e switch in the wrong place 👍

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-3513
