### ISSUE TITLE
SearchFilterComponent: allow searches which contain the entered search-value and not only start with the search-value

### ISSUE THREAD

**Issue by HansDeBal** [Alfresco/alfresco-ng2-components#3716]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Component name and version:** 
SearchFilterComponent <adf-search-filter #settings></adf-search-filter>

**New feature request:**
When we're on the search-result component which contains facets, there us an option to filter on facet-values in a facet (input-field called "Filter category"). When using this input-field, the component shows the facet-values which start with the entered string. See https://github.com/Alfresco/alfresco-ng2-components/blob/54fbe61c08d0e005d72ff15d83c6cde2ede190ee/lib/content-services/search/components/search-filter/models/response-facet-query-list.model.ts#L35

We would like to have an configuration option that not only the facet-values are kept which **start with** the entered string, but which **contain** the entered string.
Eg: The created by facet which contains Administrator and Alice Beecher. When looking for "eec", it should show "Alice Beecher". Now, it doesn't show any match.

**Comment by HansDeBal** [comment]
Use case:
our model contains a property for which the value always starts with the same string ("Working Party: "). So it contains values such as "Working Party: blabla" or "Working Party: "Lorem ipsum" This property is also used as a facet. But when filtering in the facetvalues, theuser of course doesn't want to type "Working Party" first, he wants to find relevant facetvalues when typing "bla".

**Comment by HansDeBal** [comment]
@eromano 
Any target release version for this? Our customer again requested this feature explicitely. Would like to give them a target date.

**Comment by DenysVuika** [comment]
@HansDeBal Seems like a simple feature. You could create a PR ;)

**Comment by eromano** [comment]
for more details about this feature please look the documentation :
https://github.com/Alfresco/alfresco-ng2-components/blob/e5c7ffb3145887494e935185756107ef9e36b877/docs/content-services/components/search-filter.component.md
