### ISSUE TITLE
Success event not fired when upload file is paused and resume

### ISSUE THREAD

**Issue by dGodinho** [Alfresco/alfresco-ng2-components#3721]
**Type of issue:**
> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
If pause and resume upload the success event from "adf-upload-button" will not be fired, after the file is uploaded, 

**Expected behavior:**
If you set success event and need to pause and resume, after the file is uploaded the success event need to be fired anyway

**Steps to reproduce the issue:**
- Add success event to "adf-upload-button"
<adf-upload-button ...... (beginUpload)="onBeginUpload($event)" (success)="onSuccess($event)">
- Set simple alert at onSuccess function
onSuccess(event) {
    alert('success');
  }
- Pause and resume uploadt in onBeginUpload function
  onBeginUpload(event: UploadFilesEvent) {
    event.pauseUpload();
    event.resumeUpload();
}
- File will be uploaded properly but success event will not be fired

**Component name and version:** 
- "adf-upload-button" component with ADF 2.4.0
- Demo-shell of dev branch in FilesComponent 

**Browser and version:** 
Google Chrome - 68.0.3440.106

**Comment by eromano** [comment]
@dGodinho did you try it on 2.5.0?

**Comment by dGodinho** [comment]
I think so

**Comment by magemello** [comment]
@eromano Comparing:

- upload-files.event.ts 
- upload-base.ts

Both call "this.uploadService.uploadFilesInTheQueue()"

in one case we pass the event inside “upload-base.ts"
and another we don’t "upload-files.event.ts"

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-3580
