### ISSUE TITLE
Hide default save button but display custom outcome save button

### ISSUE THREAD

**Issue by amrutawandakar** [Alfresco/alfresco-ng2-components#3730]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

i have custom outcome as Save(which saves present task and moves back to previous task), in adf it displays default save button as well as my custom outcome save button, so i tried to use the [showFormSaveButton]="false" property which hides my custom outcome save button also with default one.
[https://files.gitter.im/Alfresco/alfresco-ng2-components/VUP3/image.png](url)
**Expected behavior:**

If form contains custom outcome save button hide default save button.
**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by mauriziovitale** [comment]
The property you mention (showFormSaveButton) seems to be wrong. Could you please try 
[showSaveButton]="false"

**Comment by DenisVuyka** [comment]
@mauriziovitale `showFormSaveButton` is the property for Task Details that maps to the `showSaveButton` of the Form.

**Comment by mauriziovitale** [comment]
It looks like is working fine
```javascript
<adf-task-details 
    [taskId]="currentTaskId"
    [showFormSaveButton]="true">
```
The save button is present
<img width="532" alt="screen shot 2018-08-29 at 14 26 40" src="https://user-images.githubusercontent.com/14923305/44790573-956a8e80-ab97-11e8-8b22-f909dcac459e.png">

```javascript
<adf-task-details 
    [taskId]="currentTaskId"
    [showFormSaveButton]="false">
```
Save button is not present
<img width="528" alt="screen shot 2018-08-29 at 14 27 33" src="https://user-images.githubusercontent.com/14923305/44790642-b632e400-ab97-11e8-8243-9ff66b2c4bff.png">

**Comment by amrutawandakar** [comment]
@mauriziovitale thanks for reply.
[https://files.gitter.im/Alfresco/alfresco-ng2-components/VUP3/image.png](url)
in the image you can check how i got.

**Comment by eromano** [comment]
not reproducible
