### ISSUE TITLE
empty thumbnails showing in adf document list gallery view 

### ISSUE THREAD

**Issue by sai401** [Alfresco/alfresco-ng2-components#3743]
> - [*] Bug  

**Current behaviour:**
 empty thumbnails showing in adf document list gallery view after binding the data list 

**Expected behavior:**
hide unnecessary empty thumbnails 

**Component name and version:** 
adf-document-list 2.5 
![issue](https://user-images.githubusercontent.com/20453732/45032740-32ce3280-b070-11e8-8f31-a582bda5197b.PNG)

**Comment by eromano** [comment]
Hi can you try with the last alpha version  "2.6.0-9322cf07f7e6667273fc4b41ac6bcd3f0cb96c4c" ?

**Comment by eromano** [comment]
Please feel free to reopen if you provide more context thanks
