### ISSUE TITLE
Hidden items based on visibility don't align correctly because of hidden placeholder containers

### ISSUE THREAD

**Issue by tdonovancsra** [Alfresco/alfresco-ng2-components#3794]
**Type of issue:**  (check with "[x]")

> - [X ] New feature request
> - [ X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When designing forms that have controls that get hidden based on a radio button list the controls are hidden but the container they are in still visually remains so the control currently showing get pushed down on the page and appear to be floating.

**Expected behavior:**
that the controls that are visible align with the controls on the left. shift up etc.   If we had a css class on the container that holds the hidden elements we could handle this ourselves too.  

**Steps to reproduce the issue:**
create a form that has a container with two columns.  Put radio button list on the left and then stack controls on the right that show/hide based on the selection

**Component name and version:** 
forms / all versions

**Browser and version:** 
all

**Comment by eromano** [comment]
@tdonovancsra could be possible have a video or some screenshot to better understand the problem?

**Comment by eromano** [comment]
I close this issue. Please check it against to the new version and if is still present feel free to reopen it

**Comment by uclaeamsavino** [comment]
We have this exact issue. There are three hidden fields pushing down the content on the right. This is set on APS using visibility rules.

![image](https://user-images.githubusercontent.com/43759901/81877768-d3117580-953a-11ea-99e2-89fceb397432.png)

Here's what it looks like directly on APS, the hidden fields are not pushing the content down:

![image](https://user-images.githubusercontent.com/43759901/81877834-0b18b880-953b-11ea-9896-8a4e1fdbf96d.png)

It seems like hiding only works on ADF when the thing being hidden takes up the width of the form - like a section. Hiding fields within a section doesn't work - as they still hold the same amount of space as if they were visible.
