### ISSUE TITLE
Translations not loaded properly

### ISSUE THREAD

**Issue by gpaucot** [Alfresco/alfresco-ng2-components#3796]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Some translations are missing, for example the labels of the login page, the facets and the pager.
The application we are writing is at the moment EN only and heavily uses lazy-loaded modules. 
My browser is FR.
In AppConponent.ngOnInit() we have a call to translationService.use('en').

Here are the requests made:
- /assets/adf-content-services/i18n/en.json?v=1537174447860
- /resources/i18n/en.json?v=1537174447879
- /assets/adf-content-services/i18n/fr.json?v=1537174447881
- /resources/i18n/fr.json?v=1537174447882
- /assets/adf-core/i18n/fr.json?v=1537174447890

It seems an en.json file is missing, in our case we miss /assets/adf-core/i18n/en.json

When the browser language is EN, is works perfectly however.

**Expected behavior:**
Same but with the missing file so that all labels are shown properly.

**Steps to reproduce the issue:**
Change you browser language to something else than EN. Then do a translationService.use('en') in the init.

**Component name and version:** 
N/A : Transversal

**Browser and version:** 
all

Thanks !

**Comment by DenisVuyka** [comment]
@gpaucot do you configure resource folders as API requires? also do you have correct rules in `angular.json` to copy assets to the corresponding folders?

**Comment by gpaucot** [comment]
@DenysVuika I beleive so: when doing a build, all files are present even the not-loaded /assets/adf-core/i18n/en.json

**Comment by DenysVuika** [comment]
@gpaucot what version of ADF are you using? we recently moved ACA to lazy loaded modules (upcoming 1.5) and had zero problems with language files with ADF 2.5.0 that has a lot of improvements. You also need to use lazy modules properly of course (forRoot, forChild)

**Comment by mauriziovitale** [comment]
@gpaucot you should have a dist folder like this one 
<img width="336" alt="screen shot 2018-09-19 at 10 11 57" src="https://user-images.githubusercontent.com/14923305/45743702-9457da80-bbf4-11e8-806a-3afc88a3f494.png">

**Comment by gpaucot** [comment]
@DenysVuika We use 2.5.0 and all lazy-loaded modules do the imports like this: 

```
@NgModule({
  imports: [
    ...,
    CoreModule.forChild(),
    ContentModule.forChild()
  ],
...
})
```
@mauriziovitale Indeed I have ;-)

I checked the ACA and the bug is there as well, here is a GIF on how to reproduce (my Browser is in FR):

![connexion - alfresco](https://user-images.githubusercontent.com/4678416/45745088-4943c480-bc00-11e8-905a-a67613d7e6ce.gif)

**Comment by DenysVuika** [comment]
@gpaucot oh, I didn't realise you had non-English browser defaults. Currently we have an issue related to the 3rd party library related to fallback languages. Could you try the same with "en-US" settings for your browser?

**Comment by DenysVuika** [comment]
There's an open bug in ngx-translate library, that causes translation issues even without lazy loading. You can just switch your browser to one of the languages not supported by the app, and you may get same issue even without lazy loading.

**Comment by gpaucot** [comment]
@DenysVuika When the browser is in EN, everything is fine. Ho ok, do you the ticket reference by any chance ?

**Comment by DenysVuika** [comment]
@gpaucot please see https://issues.alfresco.com/jira/browse/ADF-3575, you can watch the issue to get notified on changes to the ticket.

**Comment by gpaucot** [comment]
Thanks !
