### ISSUE TITLE
Single required dropdown column dynamicgrid aps-form row editor not saving

### ISSUE THREAD

**Issue by ethanpilot** [Alfresco/alfresco-ng2-components#3804]
**Type of issue:** 

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
In APS, I have a Dynamic Grid component with 1 required dropdown column.  This functions as expected in the APS interface.  However, when I try to fill out this form in ADF in the out of the box "start process" or the "task details" screens (which leverage the form component) or a custom component using the adf form, after I choose an option in the dropdown in the row editor, it will not let me save, saying "Field XYZ is required".

**Expected behavior:**
When I choose an option from the dropdown in the row editor and click save, it should save and add a row to the grid.

**Steps to reproduce the issue:**

1. Create form on APS with optional dynamic grid component requiring one required dropdown column.
2. Use this form in a form component in ADF.
3. Attempt to add a column to this grid, choosing a selection from the dropdown and clicking save.
4. Column will not save properly, instead displaying "Field XYZ is required"

**Component name and version:** 
adf-form v2.5.0

**Browser and version:** 
[all]

**Comment by ethanpilot** [comment]
Did some more investigating, seems like onValueChanged is not being called in the DropdownEditorComponent at any point, including in other grids with multiple columns and non-required dropdowns, resulting in them saving  with empty values in those columns.
Is this a bug that is larger in scope or perhaps just a configuration issue on my side?

**Comment by DenisVuyka** [comment]
Seems like a bug.

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-3576

**Comment by eromano** [comment]
I can replicate the same bug we are investigating it
