### ISSUE TITLE
Tabs only render on adf-form when form is retrieved by task ID and not form ID

### ISSUE THREAD

**Issue by ethanpilot** [Alfresco/alfresco-ng2-components#3826]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
A form is created in APS with tabs.  When displaying this form via the adf-form component, the tabs render and function properly when retrieved via task id.  However, the form appears as one long page without tabs when retrieved via form id.

**Expected behavior:**
Tabs should always render and behave consistently no matter how the form is retrieved in the adf-form component.

**Steps to reproduce the issue:**
1. Create Form with tabs in APS
2. Create component with adf-form referencing this form by its form ID
3. View page and note lack of tabs

**Component name and version:** 
Component: FormComponent (adf-form)
ADF Version: 2.5.0

**Browser and version:** 
all

**Comment by fcorti** [comment]
I'm closing this because the ADF version is too old.
Please check this with the newest ADF version and reopen if still valid.
Thanks.
