### ISSUE TITLE
It is not possible upload an empty folder via button

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#385]
1.Login into demo App
2.Click on Upload Button
3.Choose an Empty folder
4.Notice that nothing happen - NOT EXPECTED.

**Comment by mauriziovitale** [comment]
At the moment it is not possible to upload an empty folder using the chrome folder upload API. As the workaround, we can add a button Create Folder.
I'm waiting for more detail from @ohej @jsotiro @magemello

**Comment by magemello** [comment]
#384
