### ISSUE TITLE
Upload an empty folder via D&D does not immediately show the folder

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#386]
1.Login into Demo App
2.Drag and Drop an empty folder
3.Notice that the folder is not visible - NOT EXPECTEd
4.Perform some action on the demo shell
5.Notice that the folder is now visible

**Comment by mauriziovitale** [comment]
It is the same problem of #385

**Comment by VitoAlbano** [comment]
retested with latest version and now is working.
Closing.
