### ISSUE TITLE
Task header component doesn't expose the end date for a task

### ISSUE THREAD

**Issue by yregaieg** [Alfresco/alfresco-ng2-components#3878]
**Type of issue:**  (check with "[x]")

> - [X] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

TaskHeaderComponent doesn't expose the possibility to the developer for showing task end date

**Expected behavior:**

TaskHeaderComponent should expose the possibility to the developer for showing task end date

**New feature request:**

When user access historic/completed tasks, it is quite useful to have the possibility of showing the date of completion in the header information

**Comment by mauriziovitale** [comment]
Issue raised
https://issues.alfresco.com/jira/browse/ADF-3676
