### ISSUE TITLE
npm ERR! peer dep missing while npm install

### ISSUE THREAD

**Issue by metalbreeze** [Alfresco/alfresco-ng2-components#3885]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
npm ERR! peer dep missing: @mat-datetimepicker/core@2.0.1, required by @alfresco/adf-core@2.7.0-beta2
npm ERR! peer dep missing: @mat-datetimepicker/core@2.0.0, required by @mat-datetimepicker/moment@2.0.1-beta.1
npm ERR! peer dep missing: @mat-datetimepicker/moment@2.0.1, required by @alfresco/adf-core@2.7.0-beta2
npm ERR! peer dep missing: core-js@2.4.1, required by @alfresco/adf-core@2.7.0-beta2
npm ERR! peer dep missing: core-js@2.4.1, required by @alfresco/adf-insights@2.7.0-beta2
npm ERR! peer dep missing: core-js@2.4.1, required by @alfresco/adf-process-services@2.7.0-beta2
npm ERR! peer dep missing: pdfjs-dist@2.0.303, required by @alfresco/adf-core@2.7.0-beta2
npm ERR! peer dep missing: reflect-metadata@^0.1.12, required by @alfresco/adf-core@2.7.0-beta2
npm ERR! peer dep missing: webpack@^2.0.0 || ^3.0.0, required by pdfjs-dist@2.0.489
npm ERR! peer dep missing: webpack@^2.0.0, required by sass-loader@6.0.5
npm ERR! missing: codelyzer@3.1.2, required by adf-tslint-rules@0.0.4

**Expected behavior:**

**Steps to reproduce the issue:**
git clone https://github.com/Alfresco/alfresco-ng2-components.git
cd alfresco-ng2-components
npm install
npm start

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  
node --version
v8.10.0

**New feature request:**

**Comment by DenysVuika** [comment]
First of all, we don't support demo shell as an official application. Please refer to Content Application or Process Workspace for better examples.  

Second, those are peer dependency warnings/errors and should not affect the resulting application.
