### ISSUE TITLE
peer dependency glitches

### ISSUE THREAD

**Issue by derflocki** [Alfresco/alfresco-ng2-components#3900]
I have just begun to play with the adf-components and I am by no means a node/angular expert but here are a few things I have noticed making my first steps with adf:
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**
When installing `@alfresco/adf-core@2.6.0` and `@alfresco/adf-content-services@2.6.0` a warning about incorrect peer dependencies is shown. The actual peer dependencies from the packages are below are incompatible:
* `@alfresco/adf-core@2.6.0` -> `reflect-metadata@^0.1.12`
* `@alfresco/adf-content-services@2.6.0` ->`reflect-metadata@0.1.10`

Second,  [the `package.json` documentation](https://docs.npmjs.com/files/package.json#peerdependencies) and the [npm blogpost on peer dependencies](https://nodejs.org/en/blog/npm/peer-dependencies/) suggest using versions as broad as possible versions for peer dependencies. Here however some fixed versions are used:
* adf-core:
  * "@mat-datetimepicker/core": "2.0.1",
  * "@mat-datetimepicker/moment": "2.0.1",
  * "alfresco-js-api": "2.6.0",
  * "core-js": "2.4.1",
  * "hammerjs": "2.0.8",
  * "minimatch-browser": "1.0.0",
  * "pdfjs-dist": "2.0.303",

* adf-content-services:
  * "alfresco-js-api": "2.6.0",
  * "@alfresco/adf-core": "2.6.0",
  * "hammerjs": "2.0.8",
  * "reflect-metadata": "0.1.10",

**Expected behavior:**
Installing `@alfresco/adf-core@2.6.0` and `@alfresco/adf-content-services@2.6.0` and the required peer dependencies should not produce errors/warnings.

**Comment by DenysVuika** [comment]
For now you can keep using the application regardless of these warnings.
