### ISSUE TITLE
An amount field in APS 1.9 form with a "£" currency symbol is rendered as "$"  in ADF

### ISSUE THREAD

**Issue by sharmap-pt** [Alfresco/alfresco-ng2-components#3922]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
An amount field in an APS form with "£" set as currency gets rendered as "$" when implemented in ADF app.

**Expected behavior:**
The amount field should display the currency as "£" as set in APS

**Steps to reproduce the issue:**
Configure a form with amount field and change the the currency to "£" and check the difference in Activiti-app and ADF app.

**Component name and version:** 
ng2-form

**Browser and version:** 
Chrome, Firefox, Microsoft edge
 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-3727

**Comment by sharmap-pt** [comment]
We are using ADF 2.5. The error happens when you create a form in the workflow and set the currency as £ in an amount field. Later in the workflow, when another form is created which uses the 'display value' for the amount field, the second form in ADF displays a $ sign instead of £.  Example would be a 'Expense review' workflow where a user submits the amount and a reviewer views the same amount.

**Comment by eromano** [comment]
Not sure I completely got your problem would be possible to attach for you an example BPM app that has this problem?

**Comment by sharmap-pt** [comment]
Sure, please find attached the BPMN for the app.
The 'Submit expense' form has £ sign against the amount field. The 'Review expense' form reads values from the 'Submit expense' form. However, when 'Review expense' form is rendered in ADF 2.5, it has $ sign against the amount field.
[Expense Review.bpmn20.zip](https://github.com/Alfresco/alfresco-ng2-components/files/2576744/Expense.Review.bpmn20.zip)

**Comment by sharmap-pt** [comment]
![image](https://user-images.githubusercontent.com/44469243/48421802-1ed03c80-e755-11e8-8ab5-26bb422d3e99.png)

**Comment by sharmap-pt** [comment]
![image](https://user-images.githubusercontent.com/44469243/48421848-3a3b4780-e755-11e8-8fa5-cd085933b6b4.png)

**Comment by eromano** [comment]
I just tried it and I am not able to reproduce it, are you sure is the same form?

**Comment by sharmap-pt** [comment]
Yes, it is the "Review expense" form in the app.

**Comment by eromano** [comment]
The example that you sent it only contain the process it doesn't contain any form. If you could export the app with also the form maybe could be better. I tried to replicate it creating those form and is not happening .

**Comment by kaspereden** [comment]
could it be that this happens because of  i18n and browser settings?

**Comment by eromano** [comment]
not sure if is browser setting why is it working in one form? I guess if @sharmap-pt  will provide a working app will be easier to debug

**Comment by sharmap-pt** [comment]
Please find attached the app with forms. It is the Submit expense and Review expense forms we are after. The process is called Expense Review. Thanks a lot for your help!

[Human Resource.zip](https://github.com/Alfresco/alfresco-ng2-components/files/2656865/Human.Resource.zip)

**Comment by eromano** [comment]
@sharmap-pt if you try the same app in the activiti-app the labels are correct?

**Comment by sharmap-pt** [comment]
That’s correct Eugenio. In the activiti-app, the labels are all fine.

**Comment by eromano** [comment]
close for the missing update, feel free to reopen if you have more info to share with us
