### ISSUE TITLE
An APS form rendered in ADF displays PS-TAB.TASK-SHOW-HEADER in the header

### ISSUE THREAD

**Issue by sharmap-pt** [Alfresco/alfresco-ng2-components#3940]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When an editable form is created in APS and as part of the workflow this form is read further down as a readonly form, in ADF PS-TAB.TASK-SHOW-HEADER is displayed in the header.

**Expected behavior:**
TASK-SHOW_HEADER should not be displayed on the form in ADF.

**Steps to reproduce the issue:**
Configure an editable form in APS and ensure that this form is read as a read only form as part of the workflow. The header is displayed on the form in ADF.

**Component name and version:** 
ng2 form

**Browser and version:** 
Chrome, Firefox, Microsoft edge
 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-3736

**Comment by eromano** [comment]
which version are you using? this problem should have been already fixed in 2.6.0
