### ISSUE TITLE
Support row template for datatable

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#400]

**Comment by davidcognite** [comment]
This should be expanded to include more flexibility in the content column. Aikau (and indeed YUI) support the concept of pluggable cell renderers, which adds a huge amount of flexibility, but an ng-content option using transclusion would be useful too.

**Comment by DenisVuyka** [comment]
@davidcognite It is much easier taking enterprise-grade datatable component and wrap it with the angular application than implementing it from the scratch. Complete datatable implementation will require huge amount of resources (human and financial) with little to no output. We have paused on raw templates because there are too many moving parts there - sorting, column reordering, cell types, context menus, etc. Technically it is much cheaper for end-developers implementing own table rather than customizing ours.

**Comment by magemello** [comment]
@DenysVuyka speaking with @davidcognite the two features that he would like to see in the datatable and then reflected in the document list are:
1. Ability to define custom type for a column
2. Ability to define custom template for a column

This 2 functionality in general make sense also for me.

@davidcognite next time to avoid misunderstandings please provide more specific use cases. Most of us don't know enough Aikau to understand what is a pluggable cell render.

**Comment by DenisVuyka** [comment]
We can try implementing support for cell templates, something like this:

```html
<document-list>
    <columns>
        <column key="name">
            <column-template>
                <template>
                    <h1>hello world</ht>
                    <div>{{node.id}}</div>
                </template>
            </column-template>
        </columns>
    </columns>
</document-list>
```

**Comment by magemello** [comment]
@DenisVuyka, is it possible make it less verbose? entry.data.getValue(entry.row, entry.col)} removing entry.row and entry.col...also can we make available all properties of the node inside the cell?

example:
```html
<content-column
        title="{{'DOCUMENT_LIST.COLUMNS.DISPLAY_NAME' | translate}}"
        sortable="true"
        class="full-width ellipsis-cell">
    <template let-entry="$implicit">
        <span>Id: {{entry.data.getNode().id)}}</span>
        <span>Name: {{entry.data.getNode().id)}}</span>
    </template>
</content-column>
```

**Comment by DenisVuyka** [comment]
That may require huge refactoring of DataTable and DataAdapter.

**Comment by magemello** [comment]
To consider the task done we need at least be able to access all the node information from the cell..

**Comment by DenisVuyka** [comment]
DataRow holds the Node and provides access to all node properties:

```ts
export interface DataRow {
    isSelected: boolean;
    hasValue(key: string): boolean;
    getValue(key: string): any;
}
```

It supports also property paths, so you can use `entry.row.getValue('user.firstName')` for example

**Comment by DenisVuyka** [comment]
Another note - `entry` object is defined by developers via `let-entry="<binding>"`. You can have it 

```ts
<template let-myvariable="$implicit">
     <span>{{myvariable.data...}}</span>
</template>
```

**Comment by magemello** [comment]
Can we document both things please?

**Comment by DenisVuyka** [comment]
@magemello Yes, that will make more sense. You can get everything you need from those 3 properties available, we just need documenting and giving examples.

**Comment by magemello** [comment]
cool...please pr it as part of this issue
