### ISSUE TITLE
Add parameter to the login component to easily change the background image

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#407]
example:
```html
<alfresco-login bckimg="/img/background.jpg"></alfresco-login>
```

**Comment by ohej** [comment]
Being able to put in a custom logo would be a good thing as well as this is a feature we see often.

**Comment by DenisVuyka** [comment]
I suggest having more meaningful attribute name, like "background-image" (similar to CSS naming)

**Comment by DenisVuyka** [comment]
closing as duplicate of  #534
