### ISSUE TITLE
nodejs version higher than 10 cannot fetch npm package "deasync 0.1.12"

### ISSUE THREAD

**Issue by deadmeats** [Alfresco/alfresco-ng2-components#4074]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [X ] Support request
> - [ ] Documentation

**Current behaviour:**
Seems to me that "npm install -g generator-alfresco-adf-app@latest" command fails on the latest version of the nodejs (10.14.1 LTS) but then works with previous version 8.x. The error comes from npm package deasync version 0.1.12.  NPM could not install the deasync version 0.1.12. From node 10.x, I could install higher version of deasync (0.1.13 or 0.1.14 current) but not the version of 0.1.12

there is thread discussing deasync 0.1.12's failure in node v10.  Hope this helps https://github.com/abbr/deasync/issues/97

**Expected behavior:**
(this is done in node v8.14 npm v6.4.1 and yoamen v2.0.5)
>npm install -g generator-alfresco-adf-app@latest
> node ./build.js
`win32-x64-node-8` exists; testing
Binary is fine; exiting
+ generator-alfresco-adf-app@2.6.3
added 391 packages from 251 contributors in 18.699s

**Steps to reproduce the issue:**
I just followed all of the prerequisite in the "Creating your first ADF application" and error is shown after executing "npm install -g generator-alfresco-adf-app@latest"

npm ERR! deasync@0.1.12 install: `node ./build.js`
npm ERR! Exit status 1

**Component name and version:** 
generator-alfresco-adf-app@latest

**Browser and version:** 
node v10.14.1 LTS
 
**Node version (for build issues):**  
node v10.14.1 LTS Failed.
node v8.14 Success

**New feature request:**
Please update the dependency of deasync? or let me know how to fix this problem with latest node.

**Comment by DenysVuika** [comment]
Every time you change major versions of Node you need to clean node_modules and install again. Try with `npm ci` command (clean install), or remove "node_modules" and "package-lock.json" and run "npm i" again

**Comment by eromano** [comment]
For now my suggestion is to use node 9

**Comment by eromano** [comment]
the generator version 3.0.2 fix this bug. Please update your generator
