### ISSUE TITLE
Integration with AppVeyor (CI for Windows)

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#409]
Let's investigate if it's possible to test our app also on a windows ci.

https://www.appveyor.com/

for the badge:

https://www.appveyor.com/docs/status-badges

**Comment by magemello** [comment]
The build of this tool is quite slow. So for now we are building only master and development with it.

**Comment by DenisVuyka** [comment]
Can we consider any other options like having a local image with windows for test builds when needed? We have sacrificed Travis for all commits already and team got zero performance improvements with AppVayour
