### ISSUE TITLE
  No event for chekbox in adf-document-list while click and dblclick

### ISSUE THREAD

**Issue by sai401** [Alfresco/alfresco-ng2-components#4091]
**Type of issue:**  (check with "[x]")

> - [x ] Support request

**Current behaviour:**
I am using gallery view for adf-document-list and multi select to true i can see checkbox to select and un select.No events for click and dbl click event for checkbox.

**Expected behavior:**
I am using gallery view for adf-document-list and multi select to true i can see checkbox to select and un select. But i want a click and dbl click event while select and un select the checkbox and in that event i want selected data item also. 

**Component name and version:** 
adf-document-list

**Comment by DenysVuika** [comment]
Document List already exposes various selection events that you can listen to, i.e. `node-select`, `node-unselect`, etc. You can use events instead of accessing the checkboxes
