### ISSUE TITLE
Select all checkbox in document list in gallery view not visible

### ISSUE THREAD

**Issue by sai401** [Alfresco/alfresco-ng2-components#4102]
> - [x ] Support request

**Current behaviour:**
while using adf document list and i set display=gallery working fine but no select all checkbox.

**Expected behavior:**
is there select all checkbox for adf-document-list in gallery view also in adf 2.4. Currently for gallery view select all check box is not having. or any event i have to fire from my component. in gallery view also select all checkbox need to work

**Comment by eromano** [comment]
Hi @sai401 , I guess got missing in the hiding of the header.do you want to contribute in the project adding it?
