### ISSUE TITLE
How to allow folder to upload ?

### ISSUE THREAD

**Issue by Dharmraj12** [Alfresco/alfresco-ng2-components#4143]
i am using adf upload button  to upload folder . But In onSuccess its returning  files detail from folder . Can i get folder detail  in onSuccess or when folder is upload any event is there ?

<adf-upload-button
   [rootFolderId]="projectDocument"
     uploadFolders="true"
  (success)="onSuccess($event)"
(createFolder)="onFolder($event)"
(beginUpload)="onBeginUpload($event)"
></adf-upload-button>

**Comment by DenysVuika** [comment]
We do not upload folders, we upload files and ACS constructs full paths on the fly.

**Comment by Dharmraj12** [comment]
there is any way to find this file belongs to folder during upload time in success()

**Comment by DenysVuika** [comment]
There's a rich set of events on the Upload Service, you can check the API and access some info via FileModel, including the whole node via `data` I believe: https://github.com/Alfresco/alfresco-ng2-components/blob/development/docs/core/upload.service.md
