### ISSUE TITLE
Uploading and downloading a document in tasks detais component using the attach document control results in the downloaded file being corrupt

### ISSUE THREAD

**Issue by yregaieg** [Alfresco/alfresco-ng2-components#4220]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

When the user tries to download an attached document on a tasks details page/component before that task being saved/executed, the downloaded documents always gets corrupted (when opened in Notepad it shows "[object Object]" as the only content)

**Expected behavior:**

Even when the task hasn't been executed/saved yet, user should be still able to download the uploaded document, or the option to download it should be removed.
**Steps to reproduce the issue:**

- Create a process app with ADF having a tasks details page (based on tasks details component).
- Create an APS process and APP having at least one single user task with at least one single "Attach document control"
- Initiate an instance of the previously designed/published process
- in the user task having the "Attach document" Control, try uploading a pdf and downloading it again.
- Open the downloaded file and note that it is corrupt
- Open the downloaded file in notepad and observe the content.

**Component name and version:** 

ADF 2.5
**Browser and version:** 

 All browsers
**Node version (for build issues):**  

N/A
**New feature request:**

N/A

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-3974
