### ISSUE TITLE
Configurable operators in SearchQueryBuilderService

### ISSUE THREAD

**Issue by tomvansambeek** [Alfresco/alfresco-ng2-components#4235]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Currently the operator which combines the query with the userQuery, userFacetBucket, userFacetQuery and so on is the hardcoded AND operator. There is no way to intercept the final query which goes to the backend. It is always with the AND operator.

**Expected behavior:**
I expected the operator to be configurable, so that I can choose when I want to use the AND or the OR operator. The expected behavior is to tell the SearchQueryBuilderService which join operator I want to use.

**Steps to reproduce the issue:**
Create a userQuery and add it to the SearchQueryBuilderService, then add a userFacetQuery to the service. The two parts automatically get combined with the AND operator in the final query which gets send to the backend.

**Component name and version:** 
ng2-alfresco-search-query-builder-service
ADF version 2.6.1.

**Browser and version:** 
N/A
 
**Node version (for build issues):**  
v10.12.0

**New feature request:**
The requested feature is the configuration of the operator which combines the userQuery and the other query objects into the final query which goes to the backend. The feature is now hardcoded in the ' AND ' operator. I have to use the OR operator in my situation. I suspect that there are different cases for the use of the OR operator and the AND operator, so it would be nice if I can choose which operator I want to use.

**Comment by eromano** [comment]
Hi you can create your own SearchQueryBuilderService and inject it with use

```
     providers: [
            { provide: SearchQueryBuilderService, useClass: MySpecialSearchQueryBuilderService }
        ]
```
