### ISSUE TITLE
Providing Arabic support for ADF

### ISSUE THREAD

**Issue by ShivaniNR** [Alfresco/alfresco-ng2-components#4264]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Currently, no Arabic support is provided for ADF componenets.

**Expected behavior:**
ADF would support Arabic for its components.

**Component name and version:** 
ar.json file.
ADF 2.6.1

**Comment by eromano** [comment]
Hi @ShivaniNR at the moment we don't translate ADF in this language but we know it works with the Arabic language. you can add the ar.json file in the resource folder next to the other and reference it in the app.config.json it will works

**Comment by yregaieg** [comment]
@eromano it will probably need more than that since Arabic has an RTL script...

**Comment by eromano** [comment]
https://github.com/Alfresco/alfresco-ng2-components/blob/development/docs/user-guide/rtl-support.md this guide should allow you to enable RTL .
We also added some fix around the components. Feel free to open new RTL bugs if you find any strange behavior
