### ISSUE TITLE
NotificationService: Snackbar without auto closing

### ISSUE THREAD

**Issue by ariksidney** [Alfresco/alfresco-ng2-components#4308]
**Type of issue:** 

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Component name and version:** 
Notification Service, every version
 
**New feature request:**
Currently, the Notification Service can only open a snackbar message for a specific time (either as parameter or default value which is set to 5000ms). I think it would be good to have an option to open it until it is manually dismissed with the dismissSnackMessageAction() function. 
Motivation: We have some custom Webscripts which takes some time to complete so it would be nice to show the snackbar to the user until we get an answer from the webscript and then hide it.

One way I could think of is that if the duration is set to 0, it won't automatically disappear.

If you think this would be a good addition I could create a PR for this.

**Comment by DenysVuika** [comment]
If you check the Material Snackbar, the only way to prevent it close is to set the duration to 0. With the ADF Notification Service, you can already provide a duration as a parameter, see: https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/services/notification.service.ts#L39

**Comment by eromano** [comment]
@ariksidney if the documentation is not clear enough and you like this example you can also contribute to the documentation and add it for the next people with a problem like yours. We reward all the people that contribute to the project with a t-shirt

**Comment by ariksidney** [comment]
@DenysVuika Oh you are right, I think the documentation on material is not that good, because it's also possible to just leave out the duration parameter for the config. 

@eromano Thanks I think I will do it to clarify that a duration of 0 will prevent the notification from auto closing.
