### ISSUE TITLE
Table sorting for all node elements

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-ng2-components#4313]
**Type of issue:**  (check with "[x]")

> - [X] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

(Could be also a Bug, but I added it as a feature request)

**Current behaviour:**

Currently the DocumentList and the DataTable only sort the elements on the current page. For example I go into the DocumentList and have pagination enabled. I have multiple pages with results. 

When I click on the column header to sort the table it will only sort the elements in the current view/on the current page of the pagination. When I click on "Created at" for example it will sort the elements on the current page. But the user could think it will sort all elements of all three pages. So he might think the top result sorted by creation date will be the newest entry. But on the other pages there are newer ones. 

**Expected behavior:**

When the user clicks a table column header it should sort all the elements in the current folder, not only the ones on the current page.

**Steps to reproduce the issue:**

1. Fill a folder with so many documents/nodes to have multiple pages of results
2. Sort the table by a column.
3. The table is sorted but only the elements on the current page. The results on the other pages are ingored 

**Component name and version:** 
DocumentListComponent/DataTableComponent

**Browser and version:** 
all

**New feature request:**
We had some customers with multiple pages of results. When they sorted the list they said the couldn't find their documents, because the expectation always was, the whole folder gets sorted

**Comment by DenysVuika** [comment]
Yeah, we have server-side sorting enabled for the Search Results and Node Selector (Copy/Move) from what I know. Definitely needs some fixes for the rest of the Views.

**Comment by fcorti** [comment]
Solved in ADF 4
