### ISSUE TITLE
Save and Complete Outcome not translateable

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-ng2-components#4340]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Using Process Services the Save and Complete Button are not translated. This issue was raised some time ago and closed: https://issues.alfresco.com/jira/browse/ADF-3561 however it is still happening. Someone in the Jira ticket also claims it's not fixed yet.

**Expected behavior:**
Like everything else they should be translated and not english only

**Component name and version:** 
FormComponent

**Browser and version:** 
all

**Comment by eromano** [comment]
Hi @MariusGrunenberg they should be translatable please see this PR: https://github.com/Alfresco/alfresco-ng2-components/commit/b630869f6cdbbb0ae65a75e2b8e1580f6dfcfef0

```json
  "SAVE": "SAVE",
  "COMPLETE": "COMPLETE",
  "START PROCESS": "START PROCESS",
```

are present in the core/i18n/*.json translation files.

**Comment by MariusGrunenberg** [comment]
@eromano Ok I am really sorry, I guess this can be closed now. Just tried it again, somehow Chrome behaved weird and cached the wrong translations. And going into the Jira ticket, seeing the last comment I thought it wasn't fixed, yet. 

Sorry

**Comment by eromano** [comment]
no problem
