### ISSUE TITLE
Text Viewer Component not passing the withCredentials parameter

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-ng2-components#4345]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

When we use kerberos (using withCredentials), we are not able to view the text file content
**Expected behavior:**

It should display the content of text files
**Steps to reproduce the issue:**
use withCredentials true and point to ACS with Kerberos enabled. Try to view the text files and the content will not be displayed
**Component name and version:** 
adf-core

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-4148
