### ISSUE TITLE
After clicking undo the upload still continues  

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#436]
1. Upload a file
2. Click undo
3. Notice file upload continues

![screen shot 2016-07-15 at 10 51 54](https://cloud.githubusercontent.com/assets/13200338/16870598/4bbcdac0-4a7a-11e6-94e4-329172c63d61.png)

[undoupload.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/365674/undoupload.mp4.zip)

**Comment by VitoAlbano** [comment]
It seems that the pull request wasn't merged, the problem is still happening.

**Comment by VitoAlbano** [comment]
Same problem still happen on Firefox.
Fixed on Chrome.

**Comment by VitoAlbano** [comment]
Retested on Firefox and working fine.
Closing.
