### ISSUE TITLE
Activiti forms rendered for ng2

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#440]
As a developer I want to be able to render bpm forms as an alfresco ng-2 component with its own tag activiti-form and all parameters needed passed as attributes.

This ticket is for a basic renderer with no support for conditional visibility or stencils. These will follow as a separate ticket.

The ability to provide a custom look and feel to fit in with application and material design is an important requirement.

### Status
_Below is the status for basic renderer implementation, more complex widget behaviour and details to be part of separate upcoming tickets._

#### Features

- [x] Load task and corresponding form
- [x] Display form with Material Design Lite elements
- [x] Save form via `Save` action
- [x] Complete form via `Complete` action
- [x] Render custom form outcomes as action buttons
- [x] Execute custom form outcomes
- [ ] Display form header with details
- [ ] Form Validation
  * [ ] Required fields

#### Widgets (system)

- [x] Tabs
- [x] Text
- [x] Multiline Text
- [x] Number
- [x] Checkbox
- [ ] Date
- Dropdown
  * [x] Manual
  * [x] REST service
  * [ ] Data source
- [ ] Typeahead
- [ ] Amount
- [ ] Radio buttons
- [ ] People
- [ ] Group of People
- [ ] Dynamic Table
- [ ] Hyperlink
- [ ] Header
- [ ] Attach
- [ ] Display value
- [ ] Display text

**Comment by magemello** [comment]
I'm closing this issue, I moved all the above in this epic #468
