### ISSUE TITLE
Expecting "-" symbol when any one node is unselected in adf-document-list multi select mode

### ISSUE THREAD

**Issue by sai401** [Alfresco/alfresco-ng2-components#4422]
> - [x ] New feature request

**Current behaviour:**
in adf-document-list for example if 5 items are selected by clicking select all checkbox. i want to unselect the select all checkbox when 5 out of one node checkbox is unselected like below example link.

[](https://stackblitz.com/angular/kgykeojjrpd?file=app%2Ftable-selection-example.ts)

**Expected behavior:**
if i unselect any one node atleast select all checkbox need to show "-" symbol that is fine or select all checkbox need to uncheck .

**Steps to reproduce the issue:**
check select all checkbox and now unselect any one node then select all checkbox need to unselect or it has to show "-" symbol but still select all checkbox is in checked state.

**Component name and version:** 
 adf 2.6.1, adf-document-list

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-5102
