### ISSUE TITLE
Issue with the pagination

### ISSUE THREAD

**Issue by yregaieg** [Alfresco/alfresco-ng2-components#4443]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When I open the task list page inside my ADF app, I get an this error message : `Cannot find a differ supporting object '[5,10,15,20]' of type 'string'. NgFor only supports binding to Iterables such as Arrays.` and the pagination under my task-list looks messed up.

**Expected behavior:**
To not have the error, and to have the correct display

**Steps to reproduce the issue:**
Check current behavior.

**Component name and version:** 
PaginationComponent, ADF 3.0

**Analysis**

When pagination component is not configured to use a specific `supportedPageSizes` it defaults to the user preferences : https://github.com/Alfresco/alfresco-ng2-components/blame/development/lib/core/pagination/pagination.component.ts#L95
User preferences read that value from local storage : https://github.com/Alfresco/alfresco-ng2-components/blame/development/lib/core/services/user-preferences.service.ts#L89
Even though the value is indeed present in my storage as a valid array, it is read as a string : https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/services/storage.service.ts#L37

**Comment by eromano** [comment]
I don't see this error anymore, feel free to close it if you are still able to reproduce it
