### ISSUE TITLE
Upload file rename  

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#446]
There are two issue around this thing

1)Could be useful add inside the uploader an option to configure the auto rename.
2)Now  if you upload a file/folder with the same name the upload fail without a clear error. We should say that is failing for a name clashing if autorename is false

autorename propertie If true, then a name clash will cause an attempt to auto rename by finding a unique name using an integer suffix.

```javascript
this.alfrescoJsApi.upload.uploadFile(fileToUpload, null, null, null, {autoRename: true})

this.alfrescoJsApi.nodes.createFolderAutoRename('newFolderName').then(function (data) {
```

**Comment by magemello** [comment]
duplicated of #526
