### ISSUE TITLE
Read-only property configuration for adf-content-metadata-card 

### ISSUE THREAD

**Issue by connexas** [Alfresco/alfresco-ng2-components#4468]
**Type of issue:**  (check with "[x]")

> [ x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**New feature request:**
The customization of the current adf-metadata-card component does not allow to mark particular properties as read-only. It's only possible to set all properties to read-only by the ```readOnly``` flag, but not selected ones. It should be possible to set particular properties to read-only. 
Follow this documentation: https://www.alfresco.com/abn/adf/docs/content-services/content-metadata-card.component/.

Example: 
```
	"content-metadata-presets": [
	  {
		"id": "app.content.metadata.myproductaspect",
		"custom": [
		  {
			"id": "app.content.metadata.myproductaspect",
			"title": "Connection Details",
			"items": [
			  {
				"id": "app.content.metadata.myproductaspect",
				"aspect": "myproductprefix:myproductaspect",
				"properties": [
				          "myproductprefix:uniqueid",
				          "myproductprefix:name",
				          "myproductprefix:version"
        ]
			  }]
		  }]
	  } ]
```
With that code ```myproductprefix:uniqueid```, ```myproductprefix:name``` and ```myproductprefix:version``` are available below the aspect header "Connection Details" at the card view. But all can be edited by the user. While this might be fine - and is requested - for ```myproductprefix:name``` for instance, it might be never the case for ```myproductprefix:uniqueid```. Because if someone changes a generated id, it will break the underlying business logic. Therefore, it should be possible to prevent any changes for particular properties, like for ```myproductprefix:uniqueid```.

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-4276
