### ISSUE TITLE
provide data column type as number as an option

### ISSUE THREAD

**Issue by Abdul-Quadar-Quazi** [Alfresco/alfresco-ng2-components#4627]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
currently, the data column is taking numbers as a text and sorting as a string. which is causing an issue in sorting the number based column 

**Expected behavior:**
the data column should sort correctly for numeric values.

**New feature request:**
the column should provide a type = number and sort accordingly based on numeric sorting,
and please provide a custom sorting option so that we can use the sorting based on the requirement.

**Comment by tomgny** [comment]
I think these PRs should solve the problem:

- https://github.com/Alfresco/alfresco-ng2-components/pull/8984
- https://github.com/Alfresco/alfresco-ng2-components/pull/9013
