### ISSUE TITLE
404 errors on ADF 3.1 app launch looking for locale based on browser setting 

### ISSUE THREAD

**Issue by wichmannd** [Alfresco/alfresco-ng2-components#4652]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [X ] Support request
> - [ ] Documentation

**Current behaviour:**
When our application launches we see 404 errors in the browser DevTools console e.g. 
http://localhost:8150/assets/adf-content-services/i18n/en-GB.json?v=1556201997563 404 (Not Found)
http://localhost:8150/assets/adf-core/i18n/en-GB.json?v=1556201997563 404 (Not Found)

We have tried adding a "locale" setting in app.config.json specifying a value of "en" (i.e. "locale" : "en") expecting this to over-ride browser setting as per the documentation here: https://www.alfresco.com/abn/adf/docs/user-guide/internationalization/
However we still see the 404 errors which indicate a look-up based on the browser settings only

**Expected behavior:**
No 404 errors in console; locale look-ups to use locale as specified in app.config.json

**Steps to reproduce the issue:**
Launch ADF application e.g. http://localhost:8150

**Component name and version:** 
Using ADF 3.1, Angular 7.0.3

**Browser and version:** 
Chrome 73.0.3683.103
 
**Node version (for build issues):**  
10.14.0 (we have the same issue when deployed)

**Comment by DenysVuika** [comment]
@wichmannd we are probing various locales, the errors just mean there is no such file. Why do you consider that a problem?

**Comment by wichmannd** [comment]
thanks @DenysVuika

We asked because we recently upgraded our app from ADF 2.5 where we did not see any such 404 errors in our browser consoles. It was also our understanding that if we specify a locale in app.config.json then the browser locale is ignored, so we were surprised to see attempts to access locale files for the browser's settings.

**Comment by DenysVuika** [comment]
@wichmannd should not be an issue as users should not be using browser consoles anyway. feel free to suggest a way to improve or PR

**Comment by DenysVuika** [comment]
You can check more details here: https://github.com/Alfresco/alfresco-ng2-components/blob/development/docs/user-guide/internationalization.md#how-the-display-language-is-selected. First we try "en-GB", then "en". Same with "pt-BR" and "zh-CH" for instance.
