### ISSUE TITLE
SSO Authentication server unreachable

### ISSUE THREAD

**Issue by LeoQuote** [Alfresco/alfresco-ng2-components#4659]
I set up an activiti cloud and tried to build an ui for it , using adf , but the login page keep saying "SSO Authentication server unreachable"

I've set the app.config.json to my activiti cloud , all the network request seems to be fine , not 4XX or 5XX . where could be the problem?
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**

login page says ``SSO Authentication server unreachable``
**Expected behavior:**

login success and operate well
**Steps to reproduce the issue:**

**Component name and version:** 

ng2-alfresco-login
**Browser and version:** 

 
**Node version (for build issues):**  

v11.10.0
**New feature request:**

**Comment by DenysVuika** [comment]
Please use the issue tracker to raise issues or feature requests. For your local configuration troubleshooting please contact support.
