### ISSUE TITLE
CSS for document list component

### ISSUE THREAD

**Issue by ShivaniNR** [Alfresco/alfresco-ng2-components#4771]
After upgrading ADF from 3.0.0 to 3.1.0, the CSS of the document list component is changed. Any suggestions on how to fix this?

**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**
 After upgrade, the component looks like as shown in the screenshot
![image](https://user-images.githubusercontent.com/47320667/58257537-b8c11380-7d8e-11e9-9981-9844f5bfd9d4.png)
 

**Expected behavior:**
The component should look like,
![image](https://user-images.githubusercontent.com/47320667/58257591-d3938800-7d8e-11e9-9d0c-e4c717a25506.png)

**Comment by eromano** [comment]
@ShivaniNR do you have any CSS that overrides the ADF CSS?

**Comment by ShivaniNR** [comment]
Actually, we build our ADF app on Alfresco Content App. So, there is _alfresco-document-list.scss file from which the CSS for datatable gets applied. Other than that we have not added any CSS.

**Comment by eromano** [comment]
In the next releases, ADF and ACS will converge those styles
