### ISSUE TITLE
Total number of rows is incorrect for a second when navigtating between pages

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#478]
1. Change rows per page to 15
2. Notice 15-30 is displayed for a second then updates 

N.b. Does not seem to occur when rows per page is set to 5, 10 or 20
[total number of uploads.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/384251/total.number.of.uploads.mp4.zip)

**Comment by DenisVuyka** [comment]
This happens because UI is updated twice - before fetching the data from the server and after. If there's not enough items returned by server we additionally update paging numbers.
