### ISSUE TITLE
Document list does not work with Alfresco installed in other language than English

### ISSUE THREAD

**Issue by angelborroy-ks** [Alfresco/alfresco-ng2-components#479]
Alfresco creates systems folders (Sites, Repository...) with different names according to OS language. For Spanish systems we have "Sitios", "Repositorio"... 

In my local tests Document Library component is not working because of this issue.

When using CMIS, always is better using primary path expressions like `/app:company_home/st:sites`, which are not changing from one system to another.

**Comment by AFaust** [comment]
Primary path expression CAN be different. There are configuration properties which you can set in the alfresco-global.properties to have a different child name than app:company_home for example... I have had at least one customer that didn't want to see Company Home anywhere (even in primary path), so he changed it. Of course then other parts of Alfresco that are ignorant of configurable/localizable values may break, but technically this is a valid configuration option.
