### ISSUE TITLE
Cannot use custom component for upload form field in ADF 3.2.1

### ISSUE THREAD

**Issue by JStoef** [Alfresco/alfresco-ng2-components#4797]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
We currently have a dialog that displays the start form of a process, with the use of the 'StartFormComponent'. This start form contains an 'Attach file' form field. In the constructor of the dialog we use: this.formRenderingService.setComponentTypeResolver('upload', () => CustomUploadWidgetComponent, true); . The upload form field is rendered as an AttachFileWidgetComponent.  

**Expected behavior:**
The 'Attach file' form field (of type 'upload') is rendered as an CustomUploadWidgetComponent. 

**Steps to reproduce the issue:**
1. Create a process and have a start form of this process that contains an 'Attach file' component. 
2. Create an ADF component that displays the startform of this process with the 'StartFormComponent'. 
3. Override the DefaultComponent by a custom component with this.formRenderingService.setComponentTypeResolver('upload', () => CustomComponent, true); 
4. See that the 'Attach file' field is still displayed with the DefaultComponent. 

**Component name and version:** 
StartFormComponent, version 3.2.1
In version 3.1.0 this works perfectly. 

**Browser and version:** 
All

**Comment by tdonovancsra** [comment]
This is affecting me as well.  There is an override in form.component.ts that is registering this and overriding us looks like

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-5106
