### ISSUE TITLE
List separator configuration in multi-value metadata from 3.2.0 release does not work with Content Metadata Card component for the properties whose type is d:mltext.

### ISSUE THREAD

**Issue by rohit9637** [Alfresco/alfresco-ng2-components#4798]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
![multivaleud-seperator-issue](https://user-images.githubusercontent.com/34914213/58704571-26da8b80-83ca-11e9-9ace-c3be4a3f4888.png)

**Expected behavior:**
As per the above config, the multivalued properties should be separated by ";"

**Steps to reproduce the issue:**
Add the configuration same as following
![image](https://user-images.githubusercontent.com/34914213/58704740-a700f100-83ca-11e9-92a7-3364c22c342d.png)

Watch for multivalued properties in adf-content-metadata-card component.

**Component name and version:** 
ADF 3.2.1 adf-card-view-textitem component

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by davidcanonieto** [comment]
Hi @rohit9637 
Currently,  the `multi-value-pipe-separator` is only compatible with models of time  `d:text`. In the hand, `d:mltext` will give you a multi-line text metadata property that is not multivalue. 

I suggest you use `d:text` model if you want to make use of this new feature introduced in ADF 3.2.0.

**Comment by rohit9637** [comment]
@davidcanonieto `d:mltext` properties allows store multilingual values, not multi-line text metadata property. This property can be Multivalued. 

My requirement is to store multivalued properties for English and Arabic Locale. How could I use the `d:text `property?

**Comment by rohit9637** [comment]
@davidcanonieto why the issue is closed?
@DenysVuika, please comment.
