### ISSUE TITLE
Demo shell not linking reliably

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#480]

**Comment by DenisVuyka** [comment]
Should be related to how 'webscript' dependency is declared:

<img width="522" alt="screen shot 2016-07-27 at 14 21 23" src="https://cloud.githubusercontent.com/assets/503991/17176623/74514a72-5405-11e6-9bcb-77b86670e939.png">

**Comment by DenisVuyka** [comment]
@wabson Is this issue still actual or can be closed already?

**Comment by wabson** [comment]
We said we would leave this in the backlog as a placeholder until we reviewed if the changes in the commits above (4dbf21d, 1a7d018), which were rolled back during the hackathon, could be incorporated into the scripts. I'll take a look at this.
