### ISSUE TITLE
Investigate jira integration with github 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#481]
https://github.com/integrations/jira-software

**Comment by hashraf88** [comment]
https://help.github.com/articles/integrating-jira-with-your-projects/

**Comment by hashraf88** [comment]
admin access required to jira project https://issues.alfresco.com/jira/projects/DPR/summary

**Comment by ohej** [comment]
Question, how does this work when we have multiple Github repositories?

**Comment by hashraf88** [comment]
Will take a look but unsure if it is possible with multiple repositories.

**Comment by hashraf88** [comment]
Require admin access to jira https://issues.alfresco.com/jira/servicedesk/customer/portal/1/ITSD-4236

**Comment by hashraf88** [comment]
https://issues.alfresco.com/jira/servicedesk/customer/portal/1/ITSD-4266

**Comment by hashraf88** [comment]
Sample smart commit DPR-1 #comment testing 
Discussion required with team if Jira integration is the correct move forward.
