### ISSUE TITLE
Custom Tasklist Date incorrect

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-ng2-components#4811]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Defining custom columns for the tasklist like this: 
`
<adf-tasklist
        [state]="state"
        [assignment]="assignment"
        (rowClick)="onRowClick($event)"
      >
        <data-columns>
          <data-column
            key="name"
            title="Name"
            class="full-width name-column"
          ></data-column>
          <data-column
            [key]="'created'"
            [type]="'date'"
            [format]="'timeAgo'"
            title="Created"
          >
          </data-column>
        </data-columns>
      </adf-tasklist>
`

leads to the Date not displaying the correct time:

https://drive.google.com/open?id=1Cv3bxF5tZhOKPJxio5un7n0q-HDOQEHQ

The time is always "00:00". In addition the sorting doesn't work correctly when using type date. 

Somehow the DocumentListComponent displays everything correct, but I saw in the code it handles the columns a bit differently.

**Expected behavior:**
Display the correct date and time and ensure the sorting is correct

**Steps to reproduce the issue:**
Create a custom Tasklist

**Component name and version:** 
TaskListComponent

**Comment by eromano** [comment]
@MariusGrunenberg could you test it with ADF 3.3.0 ?

**Comment by DenysVuika** [comment]
closing due to no response
