### ISSUE TITLE
Component availability based on ADF version

### ISSUE THREAD

**Issue by Abbaskarara52** [Alfresco/alfresco-ng2-components#4818]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [x] Documentation

**Current behaviour:**
The components info in the documentation does not indicate in which adf version it was introduced. Example the TreeViewComponent was introduced in adf-3.0.0 then it should be tagged (or provided info) with "Since adf-3.0.0"

**Expected behavior:**
The documentation (also in the code) should include the specific version of ADF in which the component was introduced/deprecated/removed to allow better clarity on components available in the current and previous versions.

**Comment by eromano** [comment]
we have it  in the documentation:  

https://github.com/Alfresco/alfresco-ng2-components/blob/development/docs/content-services/components/tree-view.component.md

is the first thing in the top.
We prefer to keep the other info in the history of GIT for the code.
