### ISSUE TITLE
Demo the Doc Lib interaction with Activiti

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#484]
A typical use case would be to invoke a process and create a task from a doc. It would be great to
- [x] List the processes as custom actions for a doc or a folder. When clicking on it initially it could just have an alert saying "Placeholder for invoking process "+process name
- [ ] Next step would be to replace the alert with bringing up the form associated with the starting of the process and allow the user to fillit in. This should use our Activity Forms component. We need to decide how we pass the node context, when that is needed (not all the cases would be required) 
- [ ] Cancel or Submit the form which then creates an activity task/process instance that can be seen in the Task List component or activiti itself

This will show developers how to create a BPM-driven process inititation (for instance start the review of a doc)

**Comment by jsotiro** [comment]
This supersedes #482

**Comment by DenisVuyka** [comment]
@jsotiro Do we still need this task or can close it?

**Comment by jsotiro** [comment]
@DenisVuyka we still need this
