### ISSUE TITLE
When on last page and changing rows per page list is not updated

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#485]
1. Upload 20 files
2. Change rows per page to 15
3. Go to last/next page
4. Change rows per page to 10 
5. Notice document list is not updated with latest row per page set
6. Notice '15-20 of 20' is still displayed
7. Click previous page
8. Notice document list is still not updated correctly displaying '5-15 of 20' (should be 1-10 of 10)
9. Click previous page
10. Notice first page is correct

N.b. this only seems to occur when changing ros per page from 15 to 10

**Comment by hashraf88** [comment]
This also occurs using the opposite scenario i.e. 
1. Ensure rows per page is set to 5
2. Go to last page 
3. Change rows per page to 20
4. Notice list is not updated

**Comment by DenisVuyka** [comment]
Regarding last comment - you are already on the last page, so from the beginning of the page it does not matter whether it is 5 or 20, the beginning will be fixed.

**Comment by hashraf88** [comment]
Uploaded a video which may help explain better
[pagination.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/386510/pagination.mp4.zip)

**Comment by DenisVuyka** [comment]
Still not sure there's any problem there.

1. Create 7 files and change to 5 rows per page. You should get 2 pages, 5 and 2
2. Move to next page - you should see items 6 and 7
3. Whatever you choose for page numbers - 5, 10, 20, etc you should always see 6 and 7, because page starts with 6
4. On page 2 change to 10 per page (nothing happens and it's ok)
5. Move to page 1
6. You should see all 7 pages there

**Comment by hashraf88** [comment]
I may be expecting different behaviour such as the list to update against the **total** number of rows not what is visible on the page at the change of number of rows.

If the amount of items on display is not more than to the rows per page set no action is performed until a navigation to a previous page is done. 

1. 24 rows
2. Change number of rows per page to 5
3. Go to last page (displays items 20-24)
4. Change numbers of rows per page to 15
**5. At this point the list refreshes and displays items 16-24 (Expected)** 
6. Go to first page and items 1-15 are displayed **(current and expected)**

However this may be expected behaviour.

**Comment by hashraf88** [comment]
Expected behaviour.
