### ISSUE TITLE
Closing StartformDialog currently closes all dialogs

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-ng2-components#4864]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
In the ProcessDetailsComponent I have the possibility to open the StartForm with a dialog. However when I click the close button it closes per default all open dialogs: 

https://github.com/Alfresco/alfresco-ng2-components/blob/09c62d50465d24f16b1f6859f01bc82437123806/lib/process-services/process-list/components/process-instance-tasks.component.ts#L174

When I have the ProcessDetailsComponent already inside a dialog it will close all dialogs, which leads to bad usability.

**Expected behavior:**
Closing the StartFormDialog only closes itself.

**Comment by eromano** [comment]
@MariusGrunenberg are you so using a dialog in a dialog?

**Comment by MariusGrunenberg** [comment]
@eromano  Yes, that's why it's currently closing all

**Comment by eromano** [comment]
I am closing it @MariusGrunenberg using a dialog in a dialog is an antipattern thanks for the issue
