### ISSUE TITLE
Server side sorting of Lists

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-ng2-components#4938]
**Type of issue:**  (check with "[x]")

> - [X] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
In any list (for example DocumentListComponent, TaskListComponent, ...), there's currently only the possibility to sort clientside. Meaning when having pagination only the results of the current page are sorted.

This keeps confusing people, because they sort the list for the most recent document, but can't find it, since it's on Page 2 for example.

The DocumentListComponent already has a parameter "sortingMode", which differentiates between "client" and "server", but the "server" option currently does nothing..

**Expected behavior:**
All lists should have the possibility to get sorted server side.

**Comment by MariusGrunenberg** [comment]
I will provide a PR for: https://github.com/Alfresco/alfresco-ng2-components/issues/4959 which includes the DocumentListComponent.

**Comment by eromano** [comment]
ADF 4.0.0 has this capability
