### ISSUE TITLE
Server Side Sorting for DocumentList

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-ng2-components#4959]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
The Documentlist doesn't provide the possibility to sort on server side. Currently it's only possible to sort all the items, which are currently loaded (e.g in a folder are 50 nodes, but you only see 25, which will be sorted. The others are left out).

**Expected behavior:**
The flag "sortingMode" which already exists on the DocumentList should sort the DocumentList with a Rest Call, when it is set to "server".

**Comment by mail2hemant** [comment]
This is critical feature for building a good ADF Content App, hopefully can be included in Ver 3.5.

**Comment by pathakarvind** [comment]
Any alternate to achieve this?

**Comment by eromano** [comment]
ADF 4.0.0 has this capability now
