### ISSUE TITLE
Angular v8 support - DOCUMENT must be imported from `@angular/common`

### ISSUE THREAD

**Issue by petebacondarwin** [Alfresco/alfresco-ng2-components#4961]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Various component are importing `DOCUMENT` from `@angular/platform-browser` but this was removed in v8.

https://github.com/Alfresco/alfresco-ng2-components/blob/5e0f715bac7d46f6a1822a217815e640e228ab82/lib/core/clipboard/clipboard.service.ts#L19

**Expected behavior:**
Import `DOCUMENT` from `@angular/common`.

**Component name and version:** 
@alfresco/adf-core@3.3.0"

**Comment by DenysVuika** [comment]
Angular 8 is not yet supported

**Comment by petebacondarwin** [comment]
Clearly :-)
