### ISSUE TITLE
Multiple Attachments to APS form failing

### ISSUE THREAD

**Issue by mail2hemant** [Alfresco/alfresco-ng2-components#5019]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
1. APS form has multiple attachments allowed option checked for "Attach file" component.
2. User is able to add multiple attachments from ACS into an APS form at run-time while using activiti-app.
3. User switches to ADF component for the same form, attaches 1 document from ACS and 1 document from local storage, then moves on to select and add 1 more document from ACS and it removes existing attachments and only newly selected document is displayed on form.

**Expected behavior:**
APS form should allow attaching multiple documents from ACS and local storage at the same time.

**Steps to reproduce the issue:**
Described above.

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by dhrn** [comment]
fixed in this PR => #5058

**Comment by dhrn** [comment]
please reopen if it is still there
