### ISSUE TITLE
How to pass format in adfTimeAgo

### ISSUE THREAD

**Issue by Dharmraj12** [Alfresco/alfresco-ng2-components#5031]
i do not want to show time only date in YYYY-MM-DD'

**Comment by DenysVuika** [comment]
@Dharmraj12 then why do you need the adfTimeAgo pipe? you can use Angular date pipe instead

**Comment by Dharmraj12** [comment]
AdfTimeAgo will show like 1 day ago , till 7 days after it will show date .  In that date i don't want time

**Comment by DenysVuika** [comment]
You can refer to the source code and try setting the corresponding config value via the app.config.json: https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/pipes/time-ago.pipe.ts#L47

**Comment by Dharmraj12** [comment]
Thanks @DenysVuika
