### ISSUE TITLE
The Documentlist component is not displayed correctly.

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-ng2-components#5039]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

Table rows didn't display correctly.
![ACS_ADF_Application_current_behavior](https://user-images.githubusercontent.com/3609003/64058503-2dee8100-cbe7-11e9-834e-721a7430e640.png)

and appeared errors below in browser console.
```
Angular is running in the development mode. Call enableProdMode() to enable the production mode. core.js:13689
Login done adf-core.js:1065
ERROR Error: "InvalidPipeArgument: 'Missing locale data for the locale "ja".' for pipe 'DatePipe'"
    Angular 2
    transform adf-core.js:5376
    View_DataTableComponent_26 DataTableComponent.html:124
    Angular 60
    RxJS 5
    Angular 11
DataTableComponent.html:123:28
ERROR CONTEXT 
Object { view: {…}, nodeIndex: 0, nodeDef: {…}, elDef: {…}, elView: {…} }
DataTableComponent.html:123:28
ERROR Error: "InvalidPipeArgument: 'Missing locale data for the locale "ja".' for pipe 'DatePipe'"
    Angular 2
    transform adf-core.js:5376
    View_DataTableComponent_26 DataTableComponent.html:124
    Angular 60
    RxJS 5
    Angular 9
DataTableComponent.html:123:28
ERROR CONTEXT 
Object { view: {…}, nodeIndex: 0, nodeDef: {…}, elDef: {…}, elView: {…} }
DataTableComponent.html:123:28
ERROR Error: "InvalidPipeArgument: 'Missing locale data for the locale "ja".' for pipe 'DatePipe'"
    Angular 2
    transform adf-core.js:5376
    View_DataTableComponent_26 DataTableComponent.html:124
    Angular 60
    RxJS 5
    Angular 9
DataTableComponent.html:123:28
ERROR CONTEXT 
Object { view: {…}, nodeIndex: 0, nodeDef: {…}, elDef: {…}, elView: {…} }
DataTableComponent.html:123:28
ERROR Error: "InvalidPipeArgument: 'Missing locale data for the locale "ja".' for pipe 'DatePipe'"
    Angular 2
    transform adf-core.js:5376
    View_DataTableComponent_26 DataTableComponent.html:124
    Angular 60
    RxJS 5
    Angular 9
DataTableComponent.html:123:28
ERROR CONTEXT 
Object { view: {…}, nodeIndex: 0, nodeDef: {…}, elDef: {…}, elView: {…} }
DataTableComponent.html:123:28
```

**Expected behavior:**

Table rows displayed correctly.

**Steps to reproduce the issue:**

1. Change Browser Language setting to Japanese.
2. Generate template ADF app using Yeoman Generator
```
$ yo alfresco-adf-app --install
```
3. Generate repo app using `mvn` command.
```
$ mvn archetype:generate -Dfilter=org.alfresco:
```
4. Start repo app using Docker Compose.
```
$ ./run.sh build_start
```
5. Start ADF app via npm
```
$ npm start
```
6. Access `http://localhost:4200` via Browser.

**Component name and version:** 

`adf-document-list` component

**Browser and version:** 

all
 
**Node version (for build issues):**  

```
$ node -v
v10.16.3
```

**New feature request:**

This is because the display format `medium` in the DataPipe for the date specified in the DataTable cell is not defined in the Japanese locale. This setting was added from `[ADF-2699] added localisation for time ago pipe` #3298.
I believe that this may happen not only in **Japanese** locale but also **in locales where the `medium` display format is not defined**.
Consider specifying the display format in DataPipe as a variable, or specifying it in advance in the `app.config.json` file.

**Comment by arditdomi** [comment]
@silverskyvicto Can you provide more information on how did you find this problem? Or can you check again if the problem still exists? Because for me it looks like it's working fine. Thanks. 
<img width="1680" alt="Screenshot 2019-09-04 at 11 30 19 am" src="https://user-images.githubusercontent.com/32884230/64247875-a9ae3d80-cf07-11e9-942c-6dadeaec90ca.png">

**Comment by pionnegru** [comment]
the error is 'ERROR Error: "InvalidPipeArgument: 'Missing locale data for the locale "ja".' for pipe 'DatePipe'"'

**Comment by DenysVuika** [comment]
we may need to check if the yeoman template import the "ja" locale @pionnegru @arditdomi

**Comment by unibravo** [comment]
Same Issue for Turkish:
Versiyon: ADW 2.1.0
Error: InvalidPipeArgument: 'Missing locale data for the locale **"tr"**.' for pipe 'e'
