### ISSUE TITLE
Document List should deal with node ID rather than path

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#505]
For now Document List deals with node path when performing rendering, navigation and events. It should be using node IDs instead because of the following reasons:
- most of the `js api` deal with node IDs rather than relative paths
- less i18n problems when dealing with IDs, text can be anything
- it should be possible reacting on Document List events and receiving node ID rather than evaluating it based on path
- together with `path` fetching greatly simplifies `breadcrumb` implementation

**Comment by hashraf88** [comment]
Issues reported in #1446
