### ISSUE TITLE
Enhanced libraries component with search filter

### ISSUE THREAD

**Issue by rohit9637** [Alfresco/alfresco-ng2-components#5074]
Current ACA/ADF version does not support Search, filtering at Library level. This will help to find documents with ease and speed.
Let's consider a folder has thousands of documents and with the current implementation, it will be difficult to find and locate the file, when user increase the pagination size(100 or more).

The solution description

Libraries component can be enhanced by adding the filters on the top of it.

There would be the following filters:

Name: Basically a search box which will search only in the library. Ignore checklist from mockups
File Type: A search box with typeahead/autocomplete field, which will show checklist on search. User should be able to select multiple checklist items. The data for typeahead/autocomplete could be taken from document list data.
File Size: Checklist showing size range same as the categories from the search component.
Author: Typeahead/autocomplete text box with a checklist same as Filter Type
Date: This will have date range for date created and date modified.
Filter to be excluded from below provided mockups.

Content-Type
All the search filter will be on the library level, which will be applied to library data. No Solr query should be used.
The search will be on documents on the same page, from pagination.

Following are the screenshots from the mockup

![libraries](https://user-images.githubusercontent.com/34914213/63944324-f10f7680-ca8e-11e9-9c37-529fbddaa2ec.png)
![libraries-filter](https://user-images.githubusercontent.com/34914213/63944322-f10f7680-ca8e-11e9-92ab-5399d3c6a94d.png)
![name-filter](https://user-images.githubusercontent.com/34914213/63944457-2916b980-ca8f-11e9-9b85-0097e2863e7c.png)
![file-type-filter](https://user-images.githubusercontent.com/34914213/63944320-f076e000-ca8e-11e9-8df0-c2d46eae15ac.png)
![size-filter](https://user-images.githubusercontent.com/34914213/63944318-f076e000-ca8e-11e9-8189-bd1d4a8d49f1.png)
![author-filter](https://user-images.githubusercontent.com/34914213/63944317-efde4980-ca8e-11e9-8f3d-2b6b4cbf03a8.png)
![date-filter](https://user-images.githubusercontent.com/34914213/63944326-f1a80d00-ca8e-11e9-8605-ac5bf393ec8b.png)

For previous on this conversation please refer: https://github.com/Alfresco/alfresco-content-app/issues/1191

**Comment by eromano** [comment]
@rohit9637 I like this design did you already do some work around it?

**Comment by eromano** [comment]
we now have filters on column similar to this idea thanks @rohit9637 for the inspiration
