### ISSUE TITLE
Upload should not be restricted to Button

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#510]
The upload should be also implemented as a `directive` to be able attaching to any HTML element and not only a button. As a developer, I want invoking upload dialogue via menu or other element clicks.

Additional scenarios:

- Attaching upload behaviour to the icons and Document List cells (to be able dragging content on a folder to upload)

**Comment by eromano** [comment]
Could be nice have an attribute like the for of the context menu to say which element of dom attaches the uploader

**Comment by john-knowles** [comment]
Being able to drag and drop to upload files/folders into folders is a requirement we have, so this would unblock that.

What about Dragging and Dropping to move a file into a folder?  Is that a separate request?

**Comment by DenisVuyka** [comment]
@john-knowles I think that should be part of the same directive, some sort of option to control behaviour, i.e. click vs drop vs etc

**Comment by DenisVuyka** [comment]
Created issues to track separately:
- Support for moving/copying content in Document List by drag and drop #1731
