### ISSUE TITLE
Select a date in the future with the search date range component

### ISSUE THREAD

**Issue by JunHog** [Alfresco/alfresco-ng2-components#5122]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ X ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
In the search date-range widget, we can't search for dates in the future (because at the end of the NgOnInit, there is a MaxDate set up to today)

**Expected behavior:**
It should be possible to select a date in the future in the search date-range widget. So maybe make this maxDate a parameter with a default value set as today

**Steps to reproduce the issue:**
Implement a search date range widget, and try to select a date in the future

**Component name and version:** 
Search date range component, latest version

**Browser and version:** 
all
 
**Node version (for build issues):**  
10.13.0

**New feature request:**

**Comment by eromano** [comment]
@JunHog can you provide an example when you need the widget set in the future?

**Comment by JunHog** [comment]
Yes, for example we need to filter on a date concerning the next meeting, which is obviously set in the future.

**Comment by eromano** [comment]
probably we need to add more configuration to this widget to make more flexible. Do you want to contribute on the code?

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-5085

**Comment by eromano** [comment]
https://github.com/Alfresco/alfresco-ng2-components/pull/5525
