### ISSUE TITLE
How to update Task variable using alfresco js api ?

### ISSUE THREAD

**Issue by Dharmraj12** [Alfresco/alfresco-ng2-components#5144]
In Angular with ADF  i want to use alfresco js api to perform operation  Process and task

**Comment by DenysVuika** [comment]
The https://github.com/Alfresco/alfresco-js-api project contains readme with links to corresponding docs. Please use this issue tracker to raise issues and bugs, and use [Alfresco Hub](https://hub.alfresco.com/t5/application-development/ct-p/developing) or [Gitter](https://gitter.im/Alfresco/alfresco-ng2-components) for other types of questions.
