### ISSUE TITLE
Add support for translation of values in ContentMetadataCardComponent

### ISSUE THREAD

**Issue by FilipLabe** [Alfresco/alfresco-ng2-components#5180]
**Type of issue:**  (check with "[x]")

> - [X ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

Values are displayed in their raw form in the ContentMetadataCardComponent. This may cause issues when values are displayed that means little to the user.

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

ContentMetadataCardComponent 3.3.0

**Node version (for build issues):**  

**New feature request:**

Support translation of values, where the value itself should not be displayed directly to the user.

Example:
A property which contains an errorcode.
The code itself may not say mean anything to the user, but a message in plain text may be desired.

This feature is desired at least for properties with constraints, where the options for values are limited. Compare with how values can be translated in Alfresco Share, where it is possible to configure in a .property file how each value should be translated.

Example solution configuration:
configure in a i18 file 

{
...
"PROPERTIES":{
   ......
  "example:errorCode":{
        "1":"Example error translation",
         .....
        "500":"Example error code 500" 
    },
    ...
}
...
}

**Comment by eromano** [comment]
@FilipLabe are you proposing to translate the value of the property?

**Comment by FilipLabe** [comment]
@eromano Yes, exactly.

**Comment by eromano** [comment]
not sure is going to be a good idea, is really difficult to be sure about what a field will contain and when apply it

**Comment by DenysVuika** [comment]
@eromano we could just add the `| translate` pipe when rendering values, and let developers put whatever they want in resource files. That however may impact the performance of the Card View component, so if going the auto-translate way, I would at least have a flag to enable/disable this behavior

**Comment by eromano** [comment]
I am not sure should be a Front End concern and yes @DenysVuika for sure is a good idea having at least an option to eanble/disable it

**Comment by FilipLabe** [comment]
Isn't there already support for translating values in the backend?
So when you get the properties of a node, you automatically get the translated values from the api.
I think thats how i worked with Share, does ADF use another api to get node information?

**Comment by eromano** [comment]
should be the same backend

**Comment by FilipLabe** [comment]
Is there some flag you have to provide to the api when retrieving metadata to get translated values perhaps?

**Comment by DenysVuika** [comment]
You can introduce your own metadata card property component that takes the number and provides whatever modifications needed, i.e. translations, see https://github.com/Alfresco/alfresco-ng2-components/blob/develop/docs/core/components/card-view.component.md
