### ISSUE TITLE
Regression in latest release (Angular 9)

### ISSUE THREAD

**Issue by mgechev** [Alfresco/alfresco-ng2-components#5185]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

The app does not compile with Angular version 9. As @alxhub mentioned, the problem comes from compiling the library with Angular version 7. Currently, there's a deep import which fails, since we flatten the `d.ts` files.

It should be relatively straightforward to fix the bug - update to the latest stable Angular and republish.

**Expected behavior:**

The app should work with version 9.

**Steps to reproduce the issue:**

Create a new app and build it with version 9. You can find reproducible demo [here](https://circleci.com/gh/angular/ngcc-validation/1150#tests/containers/2).

**Component name and version:** 

3.6.0-e667ec4f2f1428ab0998bc801500fc966d1512c4 (we're on the edge)

**Comment by eromano** [comment]
we are planning to update to Angular 9 in the next version

**Comment by mgechev** [comment]
@eromano when are you planning to push the next version?

**Comment by eromano** [comment]
@mgechev we have a PR with the update to Angular8 done. We are just waiting the release of 9 to complete it

**Comment by mgechev** [comment]
Sounds good. Let us know if we can support you somehow.

**Comment by eromano** [comment]
thanks @mgechev

**Comment by asotog** [comment]
hi @eromano any update regarding this ?

**Comment by eromano** [comment]
is in or TODO There is a PR open with all the modfiy

**Comment by ManuelEssmeister** [comment]
Hello,
any update regarding angular 9?

Thx!

**Comment by eromano** [comment]
We are on angular 10 now thanks all
