### ISSUE TITLE
how to call a custom api Using this.alfrescoApiService.getInstance().bpmClient.callCustomApi() ?

### ISSUE THREAD

**Issue by Dharmraj12** [Alfresco/alfresco-ng2-components#5249]
I used this.alfrescoApiService.getInstance().bpmClient.callCustomApi() to call custom api. Its working in local system. When i deployed angular app  in APS . Its taking folder name  in url . 
Example  Build name is dist  then its taking http://hostName:port/dist/ then append url whater i have send on callCustomApi().  But i don;t want folder in url

Or  there any other way to pass complete url Including host name ?

**Comment by DenysVuika** [comment]
Please give more details on how to reproduce the issue
