### ISSUE TITLE
HTTP_PROVIDERS  dependency

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#525]
The HTTP_PROVIDERS is everywhere in the code, do we still need it? The alfresco JS API should make this dependency unnecessary.
We should sanitize the code from this dependency after the integration of the JS-API also for the BPM part is we don't need it as I suppose

**Comment by DenisVuyka** [comment]
Let's park this issue until upgrading to angular 2 RC.5. The RC.5 introduces ngModule concept that may greatly reduce our current references.

**Comment by eromano** [comment]
Yep I agree in RC 5 there are many change around this things

**Comment by DenisVuyka** [comment]
Closing this ticket as the issue will be automatically fixed once we upgrade Angular to RC.5 or later.
