### ISSUE TITLE
how to upload a file using this.alfrescoApiService.getInstance().bpmClient.callApi() ?

### ISSUE THREAD

**Issue by Dharmraj12** [Alfresco/alfresco-ng2-components#5258]
In custom jar i have method to upload a file in ACS .Its content type is multipart but when **i passed multipart its not supporting** 

**this.alfrescoApiService.getInstance().bpmClient.callApi(url, 'POST', {}, {}, {}, data, null, ['multipart/form-data'], ['application/json'])**

**Comment by DenysVuika** [comment]
Missing steps to reproduce the issue without your custom jar.
