### ISSUE TITLE
how to upload a file using this.alfrescoApiService.getInstance().bpmClient.callApi() ?

### ISSUE THREAD

**Issue by Dharmraj12** [Alfresco/alfresco-ng2-components#5259]
Hi @DenysVuika  without solving issue directly u are closing issue. i will explain

I have created  java method to upload a file in ACS  with consume type multipart/form-data.
when i call api  using this.alfrescoApiService.getInstance().bpmClient.callApi().
**its not supporting contenttype multipart/form-data**. 

isJsonMime(contentType: string): boolean {
        return Boolean(contentType !== null && contentType.match(/^application\/json(;.*)?$/i));
}
its throwing error inside buildUrl method in alfrescoApiClient.js.

**Comment by DenysVuika** [comment]
@Dharmraj12 next time please give all the details to reproduce the issue otherwise it is going to be closed as incomplete or unclear.

**Comment by Dharmraj12** [comment]
@DenysVuika  now its cleared  or i need to share more detail

**Comment by DenysVuika** [comment]
@Dharmraj12 what are the steps for an engineer to reproduce this issue and confirm it is a bug?

**Comment by DenysVuika** [comment]
@Dharmraj12 please use the issue template we have configured and fill all the fields in that template

**Comment by Dharmraj12** [comment]
Step 1: we need java method upload a file with consume type  multipart/form-data. ( rest API custom jar)
step 2. from angular with ADF UI  we need to call  that api using 

this.alfrescoApiService.getInstance().bpmClient.callApi()  content type we need to pass   multipart/form-data so it will throw there from alfrescoApiClient.js  because 

**isJsonMime(contentType: string): boolean {
return Boolean(contentType !== null && contentType.match(/^application/json(;.*)?$/i));
}** 
its supporting only application/* content type  no there type

**Comment by Dharmraj12** [comment]
public uploadToACS(uploadObj: any, processObj, contentRequest): Observable<any> {
    const url = 'rest/services/uploadToAcs';
    const body = new FormData();
    body.append('siteid', uploadObj.siteId);
    body.append('containerid', uploadObj.containerId);
    body.append('filedata', uploadObj.file);
    body.append('status', uploadObj.status);
    body.append('overwrite', uploadObj.overwrite);
   return this.alfrescoApiService.getInstance().bpmClient.callApi( url, 'POST', {}, {}, {}, body, null, ['multipart/form-data'], [' application/json']);

}
