### ISSUE TITLE
Autorename option for upload-component

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#526]
this.alfrescoJsApi.upload.uploadFile(fileToUpload, null, null, null, {autoRename: true})

**Comment by eromano** [comment]
This API method supports different properties:
Use ***overwrite*** to overwrite an existing file, matched by name. If the file is versionable, the existing content is replaced.
When you overwrite existing content, you can set the ***majorVersion*** boolean field to true to indicate a major version should be created. The default for majorVersion is false. Setting majorVersion enables versioning of the node, if it is not already versioned.
When you overwrite existing content, you can use the comment field to add a version comment that appears in the version history. This also enables versioning of this node, if it is not already versioned.
You can set the ***autoRename*** boolean field to automatically resolve name clashes. If there is a name clash, then the API method tries to create a unique name using an integer suffix.

**Comment by eromano** [comment]
I added as auto rename as default behaviour and the possibility to use the versioning as further behaviour
