### ISSUE TITLE
Move and polish the tag component made for the appfest

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#529]
For the appfest I did a tags component we can move it in the main components list with some work

**Comment by hashraf88** [comment]
After clicking add tag the tag is not listed and an error occurs in console
`zone.js:101 POST http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/nodes/74cd8a96-8a21-47e5-9b3b-a1b3e296787d/tags 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM735:3Request.end @ alfresco-js-api.js:35719(anonymous function) @ alfresco-js-api.js:73273ZoneAwarePromise @ zone.js:584callApi @ alfresco-js-api.js:73272addTag @ alfresco-js-api.js:63062TagService.addTag @ tag.service.ts:52TagActionsComponent.addTag @ tag-actions.component.ts:74_View_TagActionsComponent3._handle_click_11_0 @ TagActionsComponent.template.js:587(anonymous function) @ core.umd.js:12008(anonymous function) @ platform-browser.umd.js:1240(anonymous function) @ platform-browser.umd.js:1317ZoneDelegate.invoke @ zone.js:323onInvoke @ core.umd.js:9004ZoneDelegate.invoke @ zone.js:322Zone.runGuarded @ zone.js:230NgZoneImpl.runInnerGuarded @ core.umd.js:9037NgZone.runGuarded @ core.umd.js:9269outsideHandler @ platform-browser.umd.js:1317ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
tag.service.ts:62 Error: {"error":{"errorKey":"framework.exception.EntityNotFound","statusCode":404,"briefSummary":"08080193 The entity with id: 74cd8a96-8a21-47e5-9b3b-a1b3e296787d was not found","stackTrace":"For security reasons the stack trace is no longer displayed, but the property is kept for previous versions.","descriptionURL":"https://api-explorer.alfresco.com"}}(…)`

![screen shot 2016-09-08 at 11 25 41](https://cloud.githubusercontent.com/assets/13200338/18346236/1ecda5d6-75b7-11e6-8224-56d33d259285.png)
