### ISSUE TITLE
Setting allowSyntheticDefaultImports breaks linking against the js-api

### ISSUE THREAD

**Issue by danchr** [Alfresco/alfresco-ng2-components#5309]
This isn't so much a bug report, as just a friendly notice about an issue that I ran into, and that took me quite a while to debug. It took quite a while to isolate, so I figured I'd describe what happened and put it somewhere reasonably searchable.

I tried to update the Alfresco components to 3.5 and 3.6, but when compiling our ADF application, we got the following error:

> ERROR in node_modules/@alfresco/js-api/src/authentication/oauth2Auth.ts(264,57): error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof M' has no compatible call signatures.

After some digging, and quite a few failed attempts, I managed to isolate this to us having set the `allowSyntheticDefaultImports` setting for the TypeScript compiler. Once I disabled that setting, everything worked.

I'll leave it up to you whether you want to fix this, or just close this issue. Thanks!

**Comment by eromano** [comment]
Hi @danchr we have  "allowSyntheticDefaultImports": true in demo shell and all looks ok can you try with 3.7.0?
