### ISSUE TITLE
How to search user based on parameter?

### ISSUE THREAD

**Issue by Dharmraj12** [Alfresco/alfresco-ng2-components#5319]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**
I want to search a user  based on user Id   from APS User  in ADF
this.peopleProcessService.getWorkflowUsers this is not working with id  its wokring with name 

**Expected behavior:**
I want to search a user  based on user Id from APS User  in ADF.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
Is not possible with the currentAPI
