### ISSUE TITLE
How to make ADF Data Table In Edit mode ?

### ISSUE THREAD

**Issue by Dharmraj12** [Alfresco/alfresco-ng2-components#5323]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**
 IN ADF Table I am using  <data-columns>   i have defined text box  when i try to edit text from text box  its not editing 
![ADF Table not edit mode](https://user-images.githubusercontent.com/29793162/70594546-e96f7a00-1c06-11ea-89cc-73bed6a6cf93.png)

**Expected behavior:**
 IN ADF Table I am using  <data-columns>   i have defined text box  so i can Edit detail .first column is text box 

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
Not sure what you are asking @Dharmraj12 can you give more details?

**Comment by eromano** [comment]
no more details have been added from @Dharmraj12 . I will close this issue, for now, please feel free to reopen it with more details as requested. Thanks
