### ISSUE TITLE
Wrong french translation for CREATE_FOLDER_TITLE

### ISSUE THREAD

**Issue by asauvez** [Alfresco/alfresco-ng2-components#5349]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

Translation for CREATE_FOLDER_TITLE in https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/i18n/fr.json is "Créer un nouveau filtre", which means "Create a new filter".

**Expected behavior:**

Translation should be "Créer un nouveau dossier"

**Component name and version:** 

Last current version of /lib/core/i18n/fr.json

**Comment by eromano** [comment]
Hi @asauvez thanks we will fix it in 3.7.0
