### ISSUE TITLE
Pagination broken when totalItems is undefined

### ISSUE THREAD

**Issue by ariksidney** [Alfresco/alfresco-ng2-components#5352]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Currently the range and total items section of the pagination is broken when totalItems in the pagination object is undefined and when there are more items available.

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/15780097/71666443-1c69e100-2d61-11ea-855f-1ab7528de573.png">

**Expected behavior:**
Must be defined, an idea would be to just show the range and not the total number of elements.

**Steps to reproduce the issue:**
Create a document-list and pagination with the results from a custom afts search query. The query should go to the DB and not to Solr because only then the totalItems property is missing.
My query looks something like this: (PARENT:"nodeIdOfParent") AND (TYPE:"customType")

**Component name and version:** 
adf-pagination (problem exists in every version)

**Browser and version:** 
all

**Comment by eromano** [comment]
@ariksidney would you like to contribute with the fix? Seems you have investigated it enough to add a possible solution

**Comment by ariksidney** [comment]
@eromano sure, I will do it as soon as I have time for it :)

**Comment by eromano** [comment]
@ariksidney thanks
