### ISSUE TITLE
Ambiguous German translation for search-filter action

### ISSUE THREAD

**Issue by georg-un** [Alfresco/alfresco-ng2-components#5379]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Summary:**
In the German translation for the search-filter, the action _Clear all_ is translated to _Alle löschen_. However, in German, this is ambiguous since it also means _Delete all_. We had some confusion about this button with users fearing it would delete all their files... :)

A more unambiguous translation would be _Auswahl zurücksetzen_ which translates to _Reset selection_.

If wished, I can create a PR that replaces 
- _Alle löschen_ in line 215 and 222 with _Auswahl zurücksetzen_ and
- _Löschen_ in line 213 with _Zurücksetzen_.

**Component name and version:** 
search-check-list.component - 3.7.0-beta6

https://github.com/Alfresco/alfresco-ng2-components/blob/91abe87ccce67e5bedd60653df22d39d8affbc9f/lib/content-services/src/lib/i18n/de.json#L211-L229

**Browser and version:** 
all

**Comment by eromano** [comment]
Hi I will assign this task to the translation team thanks

**Comment by gbroadbent** [comment]
Hello georg-un, thank you so much for the observations and suggestions to fix the German strings. Stefan Kopz also validated your suggestions internally. PR has been requested with the changes.
