### ISSUE TITLE
Current user info, js api

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#541]
We need a way to get the info about the current logged in user trough the javascript api. This method should return info for the ECM and the BPM.

**Comment by eromano** [comment]
For the ECM there is an API that return the [recent activiti](https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-core-rest-api/docs/PeopleApi.md#getActivities)

**Comment by magemello** [comment]
#727
