### ISSUE TITLE
Add permission user for folder in Alfresco Content App, user search problem

### ISSUE THREAD

**Issue by mhmmderen3** [Alfresco/alfresco-ng2-components#5419]
I want to give the user access to any folder. The user is calling but as a result only the first name comes. I want the first and last name to appear.   
![image](https://user-images.githubusercontent.com/45883661/73338398-8b1a5b80-4287-11ea-93d9-4bd87ca1b625.png)

https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/content-services/src/lib/permission-manager/components/add-permission/add-permission-panel.component.html#L59

**Comment by MrMercure** [comment]
A fix will be provided in the next release and the first and last name will appear for users.

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-5072

**Comment by eromano** [comment]
It will be released in 3.8.0
