### ISSUE TITLE
Properties can't display right way if value too long. 

### ISSUE THREAD

**Issue by asokolov-flex** [Alfresco/alfresco-ng2-components#5435]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
 By default, it will apply ellipsis if the value its too long

**Expected behavior:**
Perhaps, something like tooltip where I can copy all value. Or scrolling

**Steps to reproduce the issue:**
Go in Edit Properties. And write too long value for any prop

**Component name and version:** 
card-view-textitem.component

**Node version (for build issues):**  
v10.15.3

**Comment by BaptisteMahe** [comment]
Alright, so currently when the value of a card-view-textitem component is too long ellipsis is applied to the value. But if you **triple-click** on that value and **copy it**, it will copy **the whole value**, not only the part that is displayed. 

Does it answer your question?
Do you still think a tooltip or button is needed?

**Comment by Zverbigboy** [comment]
@BaptisteMahe Okay, I also found it. It works. But I meant that it is unclear and not obvious for users who use ACA interface. I think would be better to see all value at once, perhaps user doesn't need to copy this value he just wanna see it whole. What are you thinking about it?

**Comment by BaptisteMahe** [comment]
Some kind of tooltip displaying the whole value when the mouse is over the value?

**Comment by Zverbigboy** [comment]
@BaptisteMahe Yeah, It would be very cool! Or at least rescheduling this for below the line.
![Selection_384](https://user-images.githubusercontent.com/35262502/74447510-2c0d3700-4e82-11ea-93e9-e3994c0b9ea9.png)

**Comment by BaptisteMahe** [comment]
So we opted for a **scrollable** component for non-multiline text item and we now display the **whole value** for multiline ones.

Here is a GIF showing the result :
![Screen Recording 2020-02-14 at 10 05 20](https://user-images.githubusercontent.com/41227846/74522764-bea9e680-4f13-11ea-8126-977484a9a8a7.gif)

Does this suit you?

**Comment by BaptisteMahe** [comment]
So we opted for a scrollable component for non-multiline text item and we now display the whole value for multiline ones.

Here is a GIF showing the result :

![Screen Recording 2020-02-14 at 10 23 45](https://user-images.githubusercontent.com/41227846/74523149-7a6b1600-4f14-11ea-9706-5929b881036f.gif)

Does this suit you?

**Comment by asokolov-flex** [comment]
@BaptisteMahe Certainly, it's up to you. Let it be as you wish. But for me, it seems a little strange. If it will be built for the production it's not the best view. This is just my opinion :)

**Comment by BaptisteMahe** [comment]
The design of the scrollbar was reviewed :

![Screen Recording 2020-02-17 at 10 46 10](https://user-images.githubusercontent.com/41227846/74647034-d9c66180-5172-11ea-906d-ae330aa92ca4.gif)

It is by far the simplest way to implement easy accessibility to the whole value of text item components.  Displaying on several lines or using a tooltip would disrupt the layout of components like card view list.

**Comment by asokolov-flex** [comment]
@BaptisteMahe Well, let it be. I think It will be better. I appreciate it.
