### ISSUE TITLE
extract-text-webpack-plugin repository is deprecated

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-ng2-components#5460]
Hi.

The `extract-text-webpack-plugin` and `extract-text-webpack-plugin-last` libraries seem to be deprecated.

https://github.com/Alfresco/alfresco-ng2-components/blob/f54bc243179f14510731894f0ae4016276ff025e/package.json#L151

Both are based on the same GitHub repository, and that repository's page states that.

- [webpack-contrib/extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin)

It has been announced to use `mini-css-extract-plugin` instead, and it seems that it is recommended to use `css-loader` when using this.

- [mini-css-extract-plugin](https://www.npmjs.com/package/mini-css-extract-plugin)
- [css-loader](https://www.npmjs.com/package/css-loader)

What about using these two libraries?

**Comment by eromano** [comment]
We actually use it only to create the perbuilt CSS in webpack.style.js and actually is quite old. It will be interessing explore if there is a more integrated way to do the same with Angular
