### ISSUE TITLE
Unable to extend ViewerComponent when sharedLinkId of the document is passed

### ISSUE THREAD

**Issue by DeveloperDeepak92** [Alfresco/alfresco-ng2-components#5482]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

We have a custom viewer to render our proprietary files. The custom viewer is plugged in as an adf-viewer extension and it works fine.

We need to use the same custom viewer when a file is opened with the shared link feature(public link), but we are unable to plug the custom viewer when the file is previewed with the shared link as there is no hook available to do so.

Unable to extend ViewerComponent when _sharedLinkId_ of the document is passed
https://github.com/Alfresco/alfresco-ng2-components/blob/development/demo-shell/src/app/components/shared-link-view/shared-link-view.component.html#L4

**Expected behavior:**
Should be able to extend viewerComponent with the sharedLink as well.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
@DeveloperDeepak92 can you add more information on this ticket? is not really helpful your description

**Comment by DeveloperDeepak92** [comment]
@eromano The description is updated with more details, please check.

**Comment by dhrn** [comment]
Hi @eromano yesterday investigated this,

Currently, we are not supporting the viewer extensions when we pass `sharedLinkId` input to **adf-viewer** as mentioned above

https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/viewer/components/viewer.component.ts#L394

These lines are not allowing the extensions

        this.viewerType = this.getViewerTypeByMimeType(this.mimeType);
        if (this.viewerType === 'unknown') {
            this.viewerType = this.getViewerTypeByExtension(this.extension);
        }


we have to modify this as below to support the extension.

        this.viewerType = this.getViewerTypeByExtension(this.extension);
        if (this.viewerType === 'unknown') {
            this.viewerType = this.getViewerTypeByMimeType(this.mimeType);
        }

(just swap the line)

one more line we have to add inside [this](https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/core/viewer/components/viewer.component.ts#L311)

          this.nodeEntry = sharedLinkEntry;

**Comment by adinapitul** [comment]
@DeveloperDeepak92  , can you explain your use case a bit? Why do you want to pass the sharedId to the viewer instead of the nodeId ?

**Comment by DeveloperDeepak92** [comment]
@adinapitul When we share the document (http://localhost/#/preview/s/Nffh2Lv_TGiQCSkQzOaW2Q) for preview we want the document to be render inside our customer viewer instead it renders inside the default adf-viewer.

**Comment by adinapitul** [comment]
@DeveloperDeepak92  , so, your custom viewer works in other places where you pass the nodeId, but doesn't work for shared files where you pass the sharedId ?

**Comment by DeveloperDeepak92** [comment]
@adinapitul yes correct

**Comment by adinapitul** [comment]
not sure if this fixes the problem, but here's what I know:

- for a "normal" file :) , (assuming) you do a call to this:
https://github.com/Alfresco/alfresco-js-api/blob/development/src/api/content-rest-api/docs/NodesApi.md#getNode

this has a return type of [NodeEntry](https://github.com/Alfresco/alfresco-js-api/blob/development/src/api/content-rest-api/docs/NodeEntry.md), so (assuming) you're passing to the viewer the **node.entry.id** property and this works fine

- for a shared file, (assuming) you do a call to this:
https://github.com/Alfresco/alfresco-js-api/blob/development/src/api/content-rest-api/docs/SharedlinksApi.md#getSharedLinkContent

this has a return type of [SharedLinkEntry](https://github.com/Alfresco/alfresco-js-api/blob/development/src/api/content-rest-api/docs/SharedLinkEntry.md), 

so in this case, you need to pass to the viewer the **node.entry.nodeId** and everything should just work

Hope this makes sense.

**Comment by fcorti** [comment]
Closing the issue because answered.
Feel free to reopen it, providing more details.
Thanks.
