### ISSUE TITLE
Activiti components fail on authentication 

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#554]
On http://qa.londonlab.alfresco.me/ and http://staging.londonlab.alfresco.me/  the task and process lists come back empty. 

When i look at the console i see 401 messages (see attached). Some times it will also prompt me to authenticate, although i have logged on. I use admin admin which works when i log on to activiti. 

<img width="1004" alt="screenshot 2016-08-09 15 55 44" src="https://cloud.githubusercontent.com/assets/2410281/17536518/5227c8f0-5e4a-11e6-9d91-241394aba6cb.png">

**Comment by magemello** [comment]
The workaround for now is to open chrome with the follow command:

open -n -a /Applications/Google\ Chrome.app/ --args --user-data-dir=/tmp/chrome_dev_session --disable-web-security --allow-running-insecure-content --new-window

we will fix this problem later

**Comment by magemello** [comment]
we are tracking this issue here #580 , I'm closing this one
