### ISSUE TITLE
"where" clause is not passed to Document List component

### ISSUE THREAD

**Issue by jamilnour** [Alfresco/alfresco-ng2-components#5549]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Where clause is not passed to component

**Expected behavior:**
 [where]=myFilter should pass myFilter to the Get reequest

**Steps to reproduce the issue:**
add  [where]=myFilter

**Component name and version:** 
Document List component (ADF 3.6.0)

**Comment by pionnegru** [comment]
It seems, for custom sources, the `where` clause is not passed [ DocumentListService.loadFolderByNodeId](https://github.com/Alfresco/alfresco-ng2-components/blob/development/lib/content-services/src/lib/document-list/services/document-list.service.ts#L174)
