### ISSUE TITLE
v1 REST API live-search URL change

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#555]
Following https://issues.alfresco.com/jira/browse/REPO-1079 the live-search endpoint will be renamed in the next early access Community Edition release. 

The API itself has not changed, only the endpoint URL. We need to change the search component to incorporate this change

**Comment by hashraf88** [comment]
Error seen when performing a search
<img width="1296" alt="screen shot 2016-11-02 at 12 03 50" src="https://cloud.githubusercontent.com/assets/13200338/19928002/780c21f0-a0f4-11e6-85dc-25282fd2da7d.png">

**Comment by hashraf88** [comment]
Using the latest from the development branch of the alfresco-js-api repo and latest from the development branch of the alfresco-ng-components repo an error occurs when performing a search

<img width="1349" alt="screen shot 2016-11-10 at 12 15 27" src="https://cloud.githubusercontent.com/assets/13200338/20176475/e3b862d2-a73f-11e6-927c-70c0b1b2531a.png">
