### ISSUE TITLE
NotificationService: translate Action value

### ISSUE THREAD

**Issue by ariksidney** [Alfresco/alfresco-ng2-components#5561]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

It's more an enhancement I guess.

**Current behaviour:**
At the moment, when calling notificationService.openSnackMessageAction(message, action) with translation keys only the message is translated.

**Expected behavior:**
For consistency reasons, I would expect that the action value will also be translated if a translation key is passed to the openSnackMessageAction function.

**Steps to reproduce the issue:**
Open a notification with action (openSnackMessageAction()) and pass a translation key as message and action param. Only the message will be translated.

**Component name and version:** 
NotificationService, every version

**New feature request:**
As described in Expected behavior.

I can contribute with a PR if this gets approved :)

**Comment by DenysVuika** [comment]
That's a great suggestion, feel free to raise a PR
