### ISSUE TITLE
ADF Audit Log Directive downloading Blank PDF ( Process already completed)

### ISSUE THREAD

**Issue by Dharmraj12** [Alfresco/alfresco-ng2-components#5582]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**
 <button adf-process-audit *ngIf="showAuditLog"
          [process-id]="processInstanceId"
          [format]="'pdf'"
          [download]="true" 
          mat-icon-button
          [matTooltip]="'Download Process Audit'"
          style="float: right">
    <mat-icon>assignment_ind</mat-icon>
  </button>
i am passing process instance id its downloading Pdf showing correct size but Pdf not having any content. If i download from activiti-app for completed process its coming correct

**Expected behavior:**
PDF size is coming correct but no contnent inside PDF

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by dhrn** [comment]
fixed in this PR -> https://github.com/Alfresco/alfresco-ng2-components/pull/5568.

Try latest alpha version and feel free reopen if it still exists
