### ISSUE TITLE
How to edit data column (textbox) in ADF Data table ?

### ISSUE THREAD

**Issue by Dharmraj12** [Alfresco/alfresco-ng2-components#5625]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**
I am using ADF Data table with custom  \<data-columns> .Inside  \<data-columns> i have defined text box and select box in column level. When  I am trying to edit data from text box . On click Focus came out from text box 

**Expected behavior:**
Text box should be editable 

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

![Text box not editable](https://user-images.githubusercontent.com/29793162/79828789-130f8d80-83bf-11ea-8964-ce14d459e16c.png)

**Comment by dhrn** [comment]
It is quite difficult understand the problem here.
can you share stackblitz or something for better understanding?.

**Comment by eromano** [comment]
I am closing this issue for missing update please feel free to reopen it when you have more info. Thanks
