### ISSUE TITLE
People field displays error message

### ISSUE THREAD

**Issue by amrutawandakar** [Alfresco/alfresco-ng2-components#5636]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ x ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
People field displays error message like **Enter a different value** even after user selection

**Expected behavior:**
Expected behavior is that even after selecting user from people field a error message should not display

**Steps to reproduce the issue:**

- Create Sample process in APS with people field on start form
- In ADF go to hover on process service -> choose app -> click on your app(i.e., sample process)  -> click on process menu -> click on create -> choose new process -> enter process name on start form you have people field search for user and select user -> you will see error message 

**Issue is reproducible when we have first-name and last-name for users.**

**Screen-shot for reference**
![image](https://user-images.githubusercontent.com/29533667/80203926-96421500-8645-11ea-9d7c-e728d2b44c5b.png)

**Component name and version:** 
PeopleWidgetComponent and version is ADF 3.7

**Browser and version:** 
Chrome and Version 81.0.4044.122
 
**Node version (for build issues):**  
Node V8.6.0

Thank you

**Comment by muhmadtabrez** [comment]
This issue is reproduced if user name = first name+lastname (Here APS consist of both first name and last name).
on the other hand this issue is not reproduced if user name=(first name) or username=(lastname) (Here APS will have either first name or lastname)

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-5217

**Comment by dhrn** [comment]
Hello @amrutawandakar  @muhmadtabrez 

are you guys using LDAP sync?

![image](https://user-images.githubusercontent.com/14145706/93316898-65e45880-f82a-11ea-8a0a-3c487788946c.png)

I couldn't see the user name field in the aps.

**Comment by dhrn** [comment]
I couldn't reproduce the problem even with LDAP.

@muhmadtabrez I couldn't find the `username` property in APS. I see only the firstName and lastName. can you please tell me how are you configuring the `username` in APS?

**Comment by amrutawandakar** [comment]
@dhrn i'm not using the LDAP sync.

**Comment by dhrn** [comment]
can you please check gitter chat

**Comment by amrutawandakar** [comment]
@dhrn you can update the issue here

**Comment by dhrn** [comment]
As I said above I couldn't reproduce the problem. 

Give it try with ADF 4.0 and update here if it is still there.

**Comment by amrutawandakar** [comment]
@dhrn thank you i will check and update
