### ISSUE TITLE
Audit Service for Alfresco Content Services

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-ng2-components#5671]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

There is a Service that gets the audit log of Alfresco Process Services, but there is no Service that gets the audit log of Alfresco Content Services.

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

all
 
**Node version (for build issues):**  

**New feature request:**

There is a Service that gets the audit log of Alfresco Process Services, but there is no Service that gets the audit log of Alfresco Content Services.
In front-end development, there are cases that are required by enterprise customers, so I definitely want it.

**Comment by eromano** [comment]
We don't provide it at the moment we are open on contribution happy to help on it

**Comment by eromano** [comment]
Thanks for the contribution we are going to merge it in 4.1.0 we are now in code freeze and we can not merge new functionality until the new release

**Comment by fcorti** [comment]
Thank you for the contribution.
Closing the issue because ADF 4.1 has been released.
