### ISSUE TITLE
Content Metadata Card doesn't list the constraints from Alfresco

### ISSUE THREAD

**Issue by shazada** [Alfresco/alfresco-ng2-components#5679]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

When creating an Alfresco Content Model with a constraint or list of values in the Model Manager
The ADF Meta-Data-Card Component shows a free input text field. 
![Constraint in ADF ACA](https://user-images.githubusercontent.com/1477763/81280031-380b2e00-9058-11ea-87ec-9b04c5d1767a.jpg)
**Expected behavior:**

The ADF Meta-Data-Card should show the constraints of the field in a default Angular Select list
![Constraint in share](https://user-images.githubusercontent.com/1477763/81280066-43f6f000-9058-11ea-88ea-b2ff78638b1d.jpg)
**Steps to reproduce the issue:**

Creata a simple d:text field with a constraint of 2 values
Deploy the model (you could also just creata a model in the Model Manager)
Create a content where this property exist (Upload in Share, or use the JS-Console or CMIS)
Login to Share and see that the constraint is visible and it's been created as a simple select drop-down
Login to the Content App or create a fresh app with Yeoman.
Click on the content you've created and you'll see a free input field
**Component name and version:** 

https://www.alfresco.com/abn/adf/docs/content-services/components/content-metadata-card.component/#
**Browser and version:** 

 all
**Node version (for build issues):**  

v12.16.1
**New feature request:**

**Comment by fcorti** [comment]
Supported since ADF 4.0.
https://www.alfresco.com/abn/adf/docs/release-notes/relnote400/#property-constraint-support-for-acs-7
