### ISSUE TITLE
Cannot run documentlist component demo

### ISSUE THREAD

**Issue by gravitonian** [Alfresco/alfresco-ng2-components#570]
See attached screenshot:
![documentlist-component-bug](https://cloud.githubusercontent.com/assets/2564552/17660022/76e3a47e-62ce-11e6-819d-dd81268e6b63.png)

**Comment by gravitonian** [comment]
Master branch, and the following commands were used to start the demo:

1. sudo npm install 
2. sudo tsc 
3. sudo npm run server

**Comment by magemello** [comment]
Hi Martin,

can you try running the following command:

1. npm install
2. npm start

**Comment by eromano** [comment]
There was some problems in this demo folder now should be ok

**Comment by hashraf88** [comment]
Tested on master using following commands in demo shell and no issues found
1. npm install
2. npm start
