### ISSUE TITLE
Feature request - hide form fields within a column in a 2-column section

### ISSUE THREAD

**Issue by uclaeamsavino** [Alfresco/alfresco-ng2-components#5707]
**Type of issue:**  (check with "[x]")

> - [X ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Currently ADF does not allow us to hide fields within a section. The fields still take up the same amount of space as if they were showing:

![image](https://user-images.githubusercontent.com/43759901/81984257-65705280-95e9-11ea-89e0-7a3d0cf07ca8.png)

**Expected behavior:**
It would be desirable to be able to hide fields within a section in a two column layout, and not have them still take up space, as they do on APS:

![image](https://user-images.githubusercontent.com/43759901/81984350-89cc2f00-95e9-11ea-9d95-48ea6abdf524.png)

**Steps to reproduce the issue:**
Create a two column layout, hide some of the fields on top in either column.

**New feature request:**
The motivation is we have a set of 6 fields which we want to show or hide based on the user's selection in the Gift Type dropdown as shown. If the user selects a one time gift, the form works as expected:

![image](https://user-images.githubusercontent.com/43759901/81984629-f0e9e380-95e9-11ea-8248-f4084a83892b.png)

But if the user selects pledge, the one time gift fields do not properly hide - as shown in the first image above.

**Note:** we did try to hack a bit to see if we could set the parent containers to `display: none`. But it appears that ADF is using flex-layout across the width of the form, whereas APS is displaying the fields for each column in their own container. 

So even if we set the parent containers to not take up any space, the order of the fields is still wrong. This is due to the flex-layout/flex-wrap method of laying fields out in order: 1A, 1B, 2A, 2B, 3A, 3C, etc. Our desired behavior is that the field we have in 4B in the form designer move up to 1B when the other fields are hidden, and 5B move up to 2B, etc.

**Comment by fcorti** [comment]
Fixed in ADF 4.1.
