### ISSUE TITLE
When double clicking on a file viewer is not displayed

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#571]
Env: http://dev.londonlab.alfresco.me/home
Version: 0.2.0

1. Double click on any document in the document list
2. Notice viewer is not displayed

**Comment by hashraf88** [comment]
Also after double clicking on a file the header disappears
<img width="1395" alt="screen shot 2016-08-15 at 11 36 21" src="https://cloud.githubusercontent.com/assets/13200338/17662328/9d92698a-62dc-11e6-914d-88dc2815d211.png">

**Comment by DenisVuyka** [comment]
Error details:
<img width="1246" alt="screen shot 2016-08-18 at 15 25 33" src="https://cloud.githubusercontent.com/assets/503991/17777330/16981e24-6558-11e6-97b3-18d5e599c5f6.png">

**Comment by VitoAlbano** [comment]
It works on my local machine but i've spotted that the code is different.

On Development Branch : 
![screen shot 2016-08-22 at 17 07 53](https://cloud.githubusercontent.com/assets/7974125/17862056/8f57ae8e-688b-11e6-9a2e-14dd2403f486.png)

Now on DEV env : 

![screen shot 2016-08-22 at 17 08 01](https://cloud.githubusercontent.com/assets/7974125/17862057/8f6b1582-688b-11e6-86c5-8fa969b263a5.png)

@enzor could you check when the last successful deploy on dev happened?

![screen shot 2016-08-22 at 17 46 30](https://cloud.githubusercontent.com/assets/7974125/17863134/62fcee1c-6890-11e6-8b5b-4ffaf90fc0f7.png)

**Comment by enzor** [comment]
This is quite strange.
The building system link everything perfectly, but this is not linked properly.
Me and vito went to link manually on the container itself and then it changed.
Waiting for the next trigger and image creation to see if this was just a glitch

**Comment by VitoAlbano** [comment]
It seems that this happens for a problem in the building demo shell script.
Enzo has fixed it, once is everything rebuilded evrything should work fine.

**Comment by hashraf88** [comment]
Issue still present

**Comment by enzor** [comment]
you sure this is present? the right code is there now in the viewer

<img width="707" alt="screen shot 2016-08-24 at 10 19 39" src="https://cloud.githubusercontent.com/assets/73625/17925253/2e13892c-69e4-11e6-90e0-33cfe3ff0f02.png">

**Comment by DenisVuyka** [comment]
Works for `development` branch for me after re-linking ng2-alfresco-viewer

**Comment by eromano** [comment]
Works fine also for me you need to run the build script if you still have  problems

**Comment by enzor** [comment]
is the issue present on dev.londonlab.alfresco.me?

**Comment by hashraf88** [comment]
no

**Comment by enzor** [comment]
awesome! development is sane then!
