### ISSUE TITLE
integrate JS-API activiti in components 

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#574]
- [x] Core
- [x] Login
- [x] Activiti-Tasklist
- [x] Activiti-Processlist
- [x] Activiti-Form

**Comment by hashraf88** [comment]
For the Activiti TaskList the options to add people, comments and tasks seems to be incorrectly displayed.
<img width="738" alt="screen shot 2016-08-25 at 19 05 13" src="https://cloud.githubusercontent.com/assets/13200338/17980380/f6b40844-6af6-11e6-8ffe-f4f731f38b5b.png">

**Comment by DenisVuyka** [comment]
@hashraf88 I think this is the wrong issue, it refers to API only, not UI implementation. In terms of your issue - could you please test the same with Chrome? I suspect there's no dialog polyfill configured for non-Chrome scenarios.

**Comment by hashraf88** [comment]
New issue for comments above #631
