### ISSUE TITLE
Drag-and-Drop from Outlook to ADF deletes the file in Outlook

### ISSUE THREAD

**Issue by syankov** [Alfresco/alfresco-ng2-components#5740]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

When an email is dragged from Outlook to an ADW/ACA document list, the email is deleted from Outlook.

**Expected behavior:**

The file is uploaded to Alfresco as a copy, without deleting it from Outlook.

**Steps to reproduce the issue:**

Open stock ADW 1.4 or current ACA and drag an email from Outlook into the 'Personal Files' document list drag area.

**Component name and version:** 

upload-drag-area

**Browser and version:** 

 Chrome 83.0.4103.61
 MIcrosoft Office Outlook for Office 365 (16.0.11929.20708) 64-bit

**Node version (for build issues):**  

N.A.

**New feature request:**

**Comment by eromano** [comment]
Sorry, but I don't get why this thing is an ADF or ACA bug?

**Comment by syankov** [comment]
Our users are used to copying emails via drag-and-drop from desktop Outlook to Jira in the browser (for example) and we told them that they can do the same with ADF. However, the emails are being deleted which makes drag-and-drop from Outlook to ADF applications unusable. We thought that something can be done in ADF to prevent the deletion as this works with other web applications.

**Comment by DenysVuika** [comment]
@eromano I think the ADF drag and drop can provide the "copy" effect for the drag explicitly to support this scenario. Right now we don't have any effects and rely on browser behavior.

**Comment by eromano** [comment]
ok now make more sense. I will mark it as new funtionality
