### ISSUE TITLE
Multi-selection for the Content Node Selector component

### ISSUE THREAD

**Issue by dylanvdbrink** [Alfresco/alfresco-ng2-components#5788]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When opening the Content Node Selector component it is only possible to select one node and submit the form.

**Expected behavior:**
A property on the component (e.g. `multiSelection`) to allow/disallow multi-selection on the component.

**Steps to reproduce the issue:**
Open the Content Node Selector and try multiple key combinations (cmd + click, shift + click, etc.) to select multiple nodes, which doesn't work.

**Component name and version:** 
alfresco-ng2-components/lib/content-services/src/lib/content-node-selector/content-node-selector-panel.component.html:66 sets `selectionMode` to a hardcoded `single`.

**Browser and version:** 
n/a
 
**Node version (for build issues):**  
n/a

**New feature request:**
A property on the component (e.g. `multiSelection`) to allow/disallow multi-selection on the component. The `select` event already emits an array of Node types, so the impact on existing code _should_ be minimal.

Our workaround for now is to open to popup, select a single node and submitting the popup, adding it to an array, opening the popup again, select a second node, submitting, etc.

**Comment by eromano** [comment]
We are going to review this component behavior soon

**Comment by eromano** [comment]
In 4.0.0. the lib/content-node-selector/content-node-selector.component-data.interface.ts support also the option selectionMode that can be multiple see the content-node-selector.component.md for more details
