### ISSUE TITLE
When uploading multiple documents progress bar in dialogue does not complete for all documents uploaded

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#579]
1. Upload multiple files
2. Notice in upload dialogue progress bar for all documents is not complete, only 1 completes
3. Notice all files are uploaded and displayed in document list though

<img width="1386" alt="screen shot 2016-08-15 at 22 06 19" src="https://cloud.githubusercontent.com/assets/13200338/17679786/e60cb5b4-6334-11e6-94bb-fb948d565b69.png">

**Comment by VitoAlbano** [comment]
Should be fixed now.
Please retest
