### ISSUE TITLE
ADA compliance bug - user cannot tab out of date field

### ISSUE THREAD

**Issue by uclaeamsavino** [Alfresco/alfresco-ng2-components#5795]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
User cannot tab through a date field, tabbing forward just goes back and forth in an endless loop - between the text entry field and the calendar icon.

**Expected behavior:**
Tabbing forward should get the user to the next field in the form.

**Steps to reproduce the issue:**
Create any form with a date field and another field after it. Try to tab through the form.

**Component name and version:** 
3.9beta

**Browser and version:** 
Tested on Chome

**Comment by eromano** [comment]
if you can provide an example of form maybe we can better investigate

**Comment by eromano** [comment]
I am closing this issue, please feel free to reopen wit the enhanced asked information

**Comment by uclaeamsavino** [comment]
Sorry I missed the ask for more information. Unless it's been fixed, this happens in any form with a date field. You can't tab through the date field to the next field, as required for disability rules.

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-5281

**Comment by uclaeamsavino** [comment]
That's great! Thanks Eugenio.

**Comment by fcorti** [comment]
Not reproducible. 
For date/date-time widgets there are two tab steps. 
The first one focuses on the input and the second one on the button to open the calendar dialog.

**Comment by uclaeamsavino** [comment]
@fcorti FYI - the problem is the user cannot tab out of the field. They get in an endless loop where the tab goes back and forth between the calendar icon and the field. Our users have complained about this - they want to be able to tab through fields. Also I believe that is an ADA requirement.

https://campussuite.freshdesk.com/support/solutions/articles/5000721608-ada-handling-forms

> As noted above, all form functions and links should be usable & navigable (using the tab key) through the keyboard. 

https://www.washington.edu/accessibility/checklist/tab-order/

> Try navigating through your web page using keyboard alone. Using the tab key, you should be able to access all links and controls in a predictable order based on their visual position on the page.

Is there another key the users can use to get past the date field? I cannot find a way to get to any other fields using just the keyboard.

**Comment by eromano** [comment]
This issue has ben fixed in th last version of ADF and datetime picker project. It will be part of ADF 4.2.0
