### ISSUE TITLE
Cors call activiti

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#580]
The activiti integration in the demo shell doesn't work unless you open it with the following command:

open -n -a /Applications/Google\ Chrome.app/ --args --user-data-dir=/tmp/chrome_dev_session --disable-web-security --allow-running-insecure-content --new-window

**Comment by wabson** [comment]
Still not working for you @magemello?

**Comment by hashraf88** [comment]
When trying to login to both ECM and BPM I get the following in both Chrome and Firefox

<img width="1243" alt="screen shot 2016-08-24 at 16 26 04" src="https://cloud.githubusercontent.com/assets/13200338/17936691/88fce012-6a17-11e6-8a15-7e4d379ff0f0.png">

Console:
`platform-browser.umd.js:2311 EXCEPTION: Error: Uncaught (in promise): Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.BrowserDomAdapter.logError @ platform-browser.umd.js:2311BrowserDomAdapter.logGroup @ platform-browser.umd.js:2321ExceptionHandler.call @ core.umd.js:4300(anonymous function) @ core.umd.js:9704schedulerFn @ core.umd.js:6651SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ core.umd.js:6639onError @ core.umd.js:9153onHandleError @ core.umd.js:9025ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
platform-browser.umd.js:2311 STACKTRACE:BrowserDomAdapter.logError @ platform-browser.umd.js:2311ExceptionHandler.call @ core.umd.js:4302(anonymous function) @ core.umd.js:9704schedulerFn @ core.umd.js:6651SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ core.umd.js:6639onError @ core.umd.js:9153onHandleError @ core.umd.js:9025ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233_loop_1 @ zone.js:487drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
platform-browser.umd.js:2311 Error: Uncaught (in promise): Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
    at resolvePromise (zone.js:538)
    at resolvePromise (zone.js:523)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.onInvokeTask (core.umd.js:8995)
    at ZoneDelegate.invokeTask (zone.js:355)
    at Zone.runTask (zone.js:256)
    at drainMicroTaskQueue (zone.js:474)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:426)`
