### ISSUE TITLE
Activiti JS API should work across community and enterprise edition

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#582]
Community edition and Enterprise edition have two different URLs for REST APIs. 

The API needs to make this transparent for the user so it will work seamless when switching between community and enterprise. 

If possible, maybe the REST API can tell us if it's community or enterprise and the API can figure this out automatically. If this is not possible it should be configurable.

**Comment by maljac** [comment]
Since I found no information at all about the topic but this issue:
Just wondering if the components also work with activiti community (5.X / 6.X)? Any information about that topic?

**Comment by magemello** [comment]
Hi @maljac ADF support the enterprise edition > 1.5.0

**Comment by maljac** [comment]
Any plans on supporting the community edition too?

**Comment by eromano** [comment]
Activiti 7 CE is now supported
