### ISSUE TITLE
typo exists in Basic Usage of analytics-report-list.component.md

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-ng2-components#5858]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [x] Documentation

**Current behaviour:**

```
<analytics-report-list
    [layoutType]="'LIST'">
</analytics-report-list>
```

**Expected behavior:**

```
<adf-analytics-report-list
    [layoutType]="'LIST'">
</adf-analytics-report-list>
```

**Steps to reproduce the issue:**

**Component name and version:** 

APS Analytics List Component. 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
thanks for the contribution
