### ISSUE TITLE
Un-checked checkboxes appear as checked on completed tasks

### ISSUE THREAD

**Issue by oprepliasko** [Alfresco/alfresco-ng2-components#5867]
Unchecked checkbox appears as checked on a closed task which causes client confusion and defects investigation problems.
The issue was fixed in previous adf version and now appeared again in version 3.9

**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Unchecked checkbox appears as checked on a closed task.

**Expected behavior:**
Unchecked checkbox should appear as un-checked on a closed task.

**Steps to reproduce the issue:**
1. Complete any form with checkbox, but leave it unchecked.
2. Open Completed task. 

**Component name and version:** 
checkbox-widget, adf 3.9

**Browser and version:** 
Chrome 83.0.4103.116

**Comment by eromano** [comment]
https://issues.alfresco.com/jira/browse/ADF-5216

**Comment by eromano** [comment]
Solved in 4.0.0
