### ISSUE TITLE
activiti.../task-forms/{task-id}/variables has not been generated for js-api

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#588]
At the moment the endpoint : ../activiti-app/app/rest/task-forms/{task-id}/variables
needed to retrieve the process variables for a task is not on js-api.

It needs to be added due the fact that it is used by the visibility service.

**Comment by eromano** [comment]
Vito I think you need  to use this.alfrescoJsApi.activiti.editorApi.getForm(formId);
that return a [FormRepresentation](https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-activiti-rest-api/docs/FormRepresentation.md) one of the field of the FormRepresentation is  the [FormDefinitionRepresentation](https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-activiti-rest-api/docs/FormDefinitionRepresentation.md) and here you can find all these parameters in the fields object there is also the visibility condition: 

## FormDefinitionRepresentation

## Properties
Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**className** | **String** |  | [optional] 
**customFieldTemplates** | **{String: String}** |  | [optional] 
**fields** | [**[FormFieldRepresentation]**](FormFieldRepresentation.md) |  | [optional] 
**gridsterForm** | **Boolean** |  | [optional] 
**id** | **Integer** |  | [optional] 
**javascriptEvents** | [**[FormJavascriptEventRepresentation]**](FormJavascriptEventRepresentation.md) |  | [optional] 
**metadata** | **{String: String}** |  | [optional] 
**name** | **String** |  | [optional] 
**outcomeTarget** | **String** |  | [optional] 
**outcomes** | [**[FormOutcomeRepresentation]**](FormOutcomeRepresentation.md) |  | [optional] 
**processDefinitionId** | **String** |  | [optional] 
**processDefinitionKey** | **String** |  | [optional] 
**processDefinitionName** | **String** |  | [optional] 
**selectedOutcome** | **String** |  | [optional] 
**style** | **String** |  | [optional] 
**tabs** | [**[FormTabRepresentation]**](FormTabRepresentation.md) |  | [optional] 
**taskDefinitionKey** | **String** |  | [optional] 
**taskId** | **String** |  | [optional] 
**taskName** | **String** |  | [optional] 



# FormFieldRepresentation

## Properties
Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**className** | **String** |  | [optional] 
**col** | **Integer** |  | [optional] 
**colspan** | **Integer** |  | [optional] 
**hasEmptyValue** | **Boolean** |  | [optional] 
**id** | **String** |  | [optional] 
**layout** | [**LayoutRepresentation**](LayoutRepresentation.md) |  | [optional] 
**maxLength** | **Integer** |  | [optional] 
**maxValue** | **String** |  | [optional] 
**minLength** | **Integer** |  | [optional] 
**minValue** | **String** |  | [optional] 
**name** | **String** |  | [optional] 
**optionType** | **String** |  | [optional] 
**options** | [**[OptionRepresentation]**](OptionRepresentation.md) |  | [optional] 
**overrideId** | **Boolean** |  | [optional] 
**params** | **Object** |  | [optional] 
**placeholder** | **String** |  | [optional] 
**readOnly** | **Boolean** |  | [optional] 
**regexPattern** | **String** |  | [optional] 
**required** | **Boolean** |  | [optional] 
**restIdProperty** | **String** |  | [optional] 
**restLabelProperty** | **String** |  | [optional] 
**restResponsePath** | **String** |  | [optional] 
**restUrl** | **String** |  | [optional] 
**row** | **Integer** |  | [optional] 
**sizeX** | **Integer** |  | [optional] 
**sizeY** | **Integer** |  | [optional] 
**tab** | **String** |  | [optional] 
**type** | **String** |  | [optional] 
**value** | **Object** |  | [optional] 
**visibilityCondition** | [**ConditionRepresentation**](ConditionRepresentation.md) |  | [optional]

**Comment by VitoAlbano** [comment]
Eugenio,

This api returns the process variables that are different from form variables. The form variables are the one you can find where you suggest , the other one are retrieved via this endpoint and are related to the task, even if the name is not clear.

**Comment by eromano** [comment]
I have added the method ``getTaskFormVariables` ``` in the JS-API
https://github.com/Alfresco/alfresco-js-api/issues/65

```javascript

var taskId = "taskId_example"; // String | taskId

this.alfrescoJsApi.activiti.taskFormsApi.getTaskFormVariables(taskId);
```

**Comment by DenisVuyka** [comment]
@eromano This API still uses private REST endpoint, now it is only hidden inside js-api library and is more difficult to detect
