### ISSUE TITLE
Extend Form Validation

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#589]
We need a point where to extend the check of the form. 
The scenario is: as a user, I want to be able to add a custom validation between save/complete button and sending the information to activiti. If my custom function returns true the data are sent to activiti otherwise not.

**Comment by DenisVuyka** [comment]
@magemello We need full form validation support ported, for the moment form widgets do not support Activiti validation settings (required, min/max, etc).
