### ISSUE TITLE
Person is not added in task

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#590]
After adding a person in the tasklist user is not displayed below and counter is not updated

![screen shot 2016-08-19 at 16 07 23](https://cloud.githubusercontent.com/assets/13200338/17814323/412cc6d8-6627-11e6-928b-0d35e83cad29.png)

**Comment by VitoAlbano** [comment]
@hashraf88 @magemello This doesn't seems to be a bug but more a missing feature, if this is the case , wouldn't it be better change it to feature ?

**Comment by magemello** [comment]
agree...for now this thing is there only for demo purpose as placeholder.
