### ISSUE TITLE
Custom stencil Multiple checkbox visibility condition

### ISSUE THREAD

**Issue by ShilpaVKulkarni** [Alfresco/alfresco-ng2-components#5911]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

Visibility condition is working for single checkbox
**Expected behavior:**

Visibility condition should work for multiple check box (custom stencil)

**Steps to reproduce the issue:**

Created the multiple checkbox stencil. On select of checkbox I want to set visibility. On select of single checkbox it is showing and hiding fields properly. And if I select multiple check box at that time it is showing the visible fields of either of check box. 

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

Visibility condition should work for multiple check box (custom stencil)
Created the multiple checkbox stencil. On select of checkbox I want to set visibility. On select of single checkbox it is showing and hiding fields properly. And if I select multiple check box at that time it is showing the visible fields of either of check box.

**Comment by eromano** [comment]
HI @ShilpaVKulkarni what ADF version are you using?

**Comment by eromano** [comment]
@ShilpaVKulkarni if you could share your app will be probably easy for us to debug your problem

**Comment by ShilpaVKulkarni** [comment]
> HI @ShilpaVKulkarni what ADF version are you using?

We are using ADF 3.7.0

**Comment by eromano** [comment]
can you try to replicate with last version?

**Comment by DenysVuika** [comment]
closing as not enough information provided
