### ISSUE TITLE
'development' branch has been renamed and no longer exists.

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-ng2-components#5950]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [x] Documentation

**Current behaviour:**
In `CONTRIBUTING.md`, 'development' branch is listed instead of 'develop' branch.

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**
Fix branch name from `development` to `develop`.

**Comment by DenysVuika** [comment]
Thanks!
