### ISSUE TITLE
Material Datetimepicker for @angular/material 10.x has already released.

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-ng2-components#5958]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
v4 packages below is used.
https://github.com/Alfresco/alfresco-ng2-components/blob/486a1d2c9d1c4101ab6005ca2c01ab74013fcc83/package.json#L87

https://github.com/Alfresco/alfresco-ng2-components/blob/486a1d2c9d1c4101ab6005ca2c01ab74013fcc83/package.json#L88

**Expected behavior:**
Use v5 packages below.
- [@mat-datetimepicker/core](https://www.npmjs.com/package/@mat-datetimepicker/core)
- [@mat-datetimepicker/moment](https://www.npmjs.com/package/@mat-datetimepicker/moment)

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 
all
 
**Node version (for build issues):**  
all

**New feature request:**
Material Datetimepicker for @angular/material 10.x has already released. 

So if you're using Angular 10.x, why not raise the Material Datetimepicker version?

**Comment by DenysVuika** [comment]
Thanks for pointing out. There's no particular reason for using old library, we probably just missed that during the upgrade.

**Comment by eromano** [comment]
Thanks the update has been done
