### ISSUE TITLE
How to test a component in a contribution

### ISSUE THREAD

**Issue by silverskyvicto** [Alfresco/alfresco-ng2-components#5969]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [x] Support request
> - [ ] Documentation

I am considering adding a component for ADF.
I've heard that you need to create and test components to contribute to ADF.

I'm not sure about the test method, so please let me know.

**Current behaviour:**
Commands and information related to test execution are described in README.md and Wiki, but they are not organized.

ex. `README.md`)
```
$ ./start.sh -t
```

ex. `Wiki`)
```
$ ./npm-build-all.sh -t " COMPONENT_NAME " -gitjsapi development
```

ex. `package.json`)
```
"unit-test": "concurrently \"ng test content-services --watch=false\" \"ng test process-services --watch=false\" \"ng test core --watch=false\" \"ng test extensions --watch=false\" \"ng test insights --watch=false\" \"ng test process-services-cloud --watch=false\" ",
"test": "npm run validate-config && ng test demoshell --watch=false",
"e2e": "./scripts/test-e2e-lib.sh -host 'localhost:4200' -dev --folder demo-shell",
"e2e-lib": "ng e2e lib-e2e-test --port=4200",
"lite-server-e2e": "lite-server --baseDir='dist/demo-shell/' -c ./e2e/lite-server-proxy.js",
```

Therefore, "I don't know which command should be executed to check the test result."

**Expected behavior:**
Information about which commands should be used and what tests should be run is contained in `CONTRIBUTING.md`.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenysVuika** [comment]
With the latest codebase, the Angular commands are supported: `ng build <name>` and `ng test <name>`. So, if changing the code in the `core` library, you may want to run:
```
ng build core
// or
ng test core
```
