### ISSUE TITLE
Custom Stencil doesn't work on Start Form

### ISSUE THREAD

**Issue by uvukasinovic** [Alfresco/alfresco-ng2-components#5970]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Custom Stencil doesn't work with 3.9 version (it works with 3.7)

**Expected behavior:**
The stencil should be displayed in the Start Form

**Steps to reproduce the issue:**
Create a new process with a custom stencil field and start it in ADF

**Component name and version:** 
start-process.component.ts

<img width="1291" alt="Screen Shot 2020-08-10 at 12 55 16" src="https://user-images.githubusercontent.com/6500524/89872512-5afa3080-dbb9-11ea-81c9-a9634ac00c82.png">

**Comment by dhrn** [comment]
@uvukasinovic have you tried this https://github.com/Alfresco/alfresco-ng2-components/issues/5678 ?

**Comment by uvukasinovic** [comment]
Thanks @dhrn 

I tried #5678, but it doesn't work.

**Comment by dhrn** [comment]
Raised jira ticket. https://issues.alfresco.com/jira/browse/ADF-5218

Thanks for reporting
