### ISSUE TITLE
file thumbnails not display

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#601]
<img width="1230" alt="screen shot 2016-08-23 at 21 26 25" src="https://cloud.githubusercontent.com/assets/13200338/17908449/6d0f5a64-6978-11e6-8a51-1c323c498181.png">

**Comment by DenisVuyka** [comment]
As we have already discussed - the thumbnails won't be displayed for the files uploaded prior to the recent code updates. For missing thumbnails a mimetype-based icon will be displayed instead.
