### ISSUE TITLE
column width and thumbnail not displayed

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#602]
<img width="1306" alt="screen shot 2016-08-23 at 21 26 45" src="https://cloud.githubusercontent.com/assets/13200338/17908488/99f43aea-6978-11e6-8110-9e64d7fcebd3.png">

**Comment by hashraf88** [comment]
Demo shell not built correctly

**Comment by DenisVuyka** [comment]
It this problem still actual?

**Comment by hashraf88** [comment]
No, issue previously moved to 'done'.
