### ISSUE TITLE
[object Object] is displayed instead of the group name when selecting the same group multiple times

### ISSUE THREAD

**Issue by Hellyks** [Alfresco/alfresco-ng2-components#6081]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behavior:**
When I am on a Task detail page, I have a select user group field in current task form. While I select a user group for the first time, it works fine but if I select it again it displays [object Object] instead of the group name.

**Expected behavior:**
Selecting a same user group multiple times should remain the same value of group name in select user group field.

**Steps to reproduce the issue:**
Create a new APP in APS with a task form having a select user group field.
Create a user group in APS.
Go to Task Detail page of that task in ADF.
Select a user group once.
Click outside the select user group field.
Try to select same user group again.
Check the behavior.

**Component name and version:** 

@alfresco/core -> adf-form -> functional-group-widget  

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
Hi, What version of ADF re you using?

**Comment by eromano** [comment]
I am closing this issue, please feel free to reopen wit the enhanced asked information
