### ISSUE TITLE
Versioning History for ECM nodes

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#610]
<img width="459" alt="screen shot 2016-08-24 at 16 58 35" src="https://cloud.githubusercontent.com/assets/1030050/17938077/683393d0-6a1c-11e6-8c57-38f96f019e2f.png">
Now that we can upload also the files with different version could be nice to have a list with the history of the files versioned

**Comment by DenisVuyka** [comment]
@eromano can we close this ticket already?

**Comment by eromano** [comment]
https://github.com/Alfresco/alfresco-ng2-components/blob/master/docs/version-manager.component.md yep has been added
