### ISSUE TITLE
wrong alfresco-process-services moment implementation

### ISSUE THREAD

**Issue by druckreich** [Alfresco/alfresco-ng2-components#6133]
Within the method getProcessTasks in the class ProcessService a call to moment is made thought the import is called moment$1 

    0008  import moment$1 from 'moment-es6';
    ....
    3083 getProcessTasks(processInstanceId, state) {
    3084     const taskOpts = state ? {
    3085        processInstanceId: processInstanceId,
    3086        state: state
    3087    } : {
    3088        processInstanceId: processInstanceId
    3089    };
    3090    return from(this.alfrescoApiService.getInstance().activiti.taskApi.listTasks(taskOpts))
    3091        .pipe(map(this.extractData), map((tasks) => tasks.map((task) => {
    3092        task.created = moment(task.created, 'YYYY-MM-DD').format();
    3093        return task;
    3094    })), catchError((err) => this.handleProcessError(err)));
    3095 }

**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
The method getProcessTasks is using the function *moment*

**Expected behavior:**
The method getProcessTasks should use the method$1 as importet in line:8

**Component name and version:** 
alfresco-process-services: class ProcessService

**Browser and version:** 
[all]
 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
Hi, What version of ADF are you using?

**Comment by eromano** [comment]
I am closing this issue, please feel free to reopen wit the enhanced asked information
