### ISSUE TITLE
Cursor jumps at the end of the text in the text fields

### ISSUE THREAD

**Issue by oprepliasko** [Alfresco/alfresco-ng2-components#6179]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
When user enters some text into text field, and then puts cursor in the middle of the text and starts editing, cursor is suddenly moved to the end of the text

**Expected behavior:**
Cursor stays in the place where user moved it.

**Steps to reproduce the issue:**
1. Type any text into text field. E.g. word 'Testing'
2. Put cursor between S and T and start typing --> Cursor is moved to the end

**Component name and version:** 
"text-widget"
ADF 4.0

**Browser and version:** 
 Chrome 85.0.4183.121
 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
Hi @oprepliasko we are not able to repliacate the bug can you provide some more context or a sandbox app?

**Comment by Halning** [comment]
> Hi @oprepliasko we are not able to repliacate the bug can you provide some more context or a sandbox app?

Hi @eromano, I am a colleague of @oprepliasko. We have realized that the bug on our application side. We feel sorry that we spent your time.
