### ISSUE TITLE
Partner Day Lab Env

### ISSUE THREAD

**Issue by jsotiro** [Alfresco/alfresco-ng2-components#619]
We need to have a way to give to partners either a pre-setup env of set of instructions so that we can do a 20-30 min class with partner tech track in doing a simple hello world modification of the demo shell to do with us

**Comment by enzor** [comment]
Had a talk with @magemello .

My part is to set up the backend environment (http://partners.londonlab.alfresco.me ? any other idea?) that will have ECM+BPM active and reachable, publicly.

Mario will take care of the frontend part.

**Comment by jsotiro** [comment]
great. can we call it partner-day.londonlab.alfresco.me ?

**Comment by enzor** [comment]
yep! is done! :)
