### ISSUE TITLE
Attach control for linking to respository content from Alfresco

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#621]
To complement the new upload control added by @DenisVuyka we need to be able to select from content items that are already stored in Alfresco when such a source has been configured in the Activiti form instead of the local file source

**Comment by hashraf88** [comment]
File does not display if previously uploaded and cleared
1. Upload a file
2. Save form
3. Navigate away and back to task
4. Clear previously uploaded file
5. Select same file or different file

**Expected results**
File chosen is displayed

**Actual results**
File chosen is not displayed

[upload widget.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/489388/upload.widget.mp4.zip)

**Comment by hashraf88** [comment]
Above reported in #812
