### ISSUE TITLE
Form details not displayed correctly in Firefox

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#631]
**Firefox** 
![screen shot 2016-08-26 at 10 12 32](https://cloud.githubusercontent.com/assets/13200338/18000408/d4add462-6b75-11e6-83d9-8d2ae24afcbe.png)

**Chrome**
<img width="1235" alt="screen shot 2016-08-26 at 10 12 43" src="https://cloud.githubusercontent.com/assets/13200338/18000419/dece445e-6b75-11e6-9768-fe68d189437e.png">

**Comment by DenisVuyka** [comment]
The "Material Design Lite" dialog component does not work for Firefox and Safari at all. There's a [polyfill](https://github.com/GoogleChrome/dialog-polyfill) that is absolutely useless because of [limitations](https://github.com/GoogleChrome/dialog-polyfill#limitations) set.

Dialogs need to be reworked completely.

**Comment by hashraf88** [comment]
Also effects upload widge when configured to use Alfresco source (#621)
**Firefox**
![screen shot 2016-09-22 at 17 03 59](https://cloud.githubusercontent.com/assets/13200338/18756142/ae454f18-80e6-11e6-8c22-a91f555f33fe.png)

**Chrome**
<img width="644" alt="screen shot 2016-09-22 at 17 05 13" src="https://cloud.githubusercontent.com/assets/13200338/18756158/c07aebfc-80e6-11e6-95b8-c1a8fa4f7351.png">

**Comment by hashraf88** [comment]
Also effects start task dialog (#)

![screen shot 2016-09-26 at 12 17 31](https://cloud.githubusercontent.com/assets/13200338/18832441/5327c2a0-83e3-11e6-9bb2-1e76c7ab9634.png)

**Comment by magemello** [comment]
Why in the health care app the dialog get showed correctly even on firefox?

**Comment by magemello** [comment]
with the dialog-polyfill seems to be working, I will try to commit some code with this change

**Comment by DenisVuyka** [comment]
@magemello the problem was initially not in polyfill (it works for Safari and FF) but the way dialogs are created. on non-Chrome browsers they should be child of the `body`.

**Comment by hashraf88** [comment]
In Firefox and Safari only, when I click on the '+' symbol next to people, comment or checklist within a task no dialog appears.

**Comment by magemello** [comment]
are the others dialogs working fine?

**Comment by hashraf88** [comment]
#893 created to address remaining issues
