### ISSUE TITLE
Support for Date widget within Activiti form

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#632]

**Comment by DenisVuyka** [comment]
Suggested component to back the feature: https://puranjayjain.github.io/md-date-time-picker/

**Comment by hashraf88** [comment]
On a completed form the date widget displays the tImestamp I believe unnecessarily and format changes from dd/mm/yyyy to yyyy/mm/dd 

***prior to being completed***
![screen shot 2016-10-03 at 16 45 27](https://cloud.githubusercontent.com/assets/13200338/19043641/e59aac42-8988-11e6-8cf6-08938e030563.png)

***completed***
![screen shot 2016-10-03 at 16 45 38](https://cloud.githubusercontent.com/assets/13200338/19043640/e599fda6-8988-11e6-821f-085822638893.png)

**Comment by magemello** [comment]
@DenisVuyka  the data picker suggest by you seems to be working fine, Maurizio has integrate it already in the Analytics component. Would be great if you could do the same.

**Comment by hashraf88** [comment]
A few things noticed, please let me know if you would like these in seperate issues.

1. If date is manually entered cannot go past year 1995 (21 years exactly) (see image below)
2. If date is manually entered  cannot go past year 2037 (21 years exactly) (see image below)
3. Can override both by entering date manually and completing, if points 1 and 2 are upper and lower limits notifying user with some sort of validation maybe be helpful to avoid confusion 
4. Scrolling through months with navigation options, ‘stop’ symbol displayed for a second
5. For single digit days and month when selecting a date from date picker format is dd-mm-yyyyy (01-01-2000) however on a completed form format is d-m-yyyy (1-1-2000)


**LOWER LIMIT**
![lower](https://cloud.githubusercontent.com/assets/13200338/19431130/0dfa9b0e-944f-11e6-89c9-93d4fa729b02.png)


**UPPER LIMIT**
![upper](https://cloud.githubusercontent.com/assets/13200338/19431129/0df7424c-944f-11e6-870b-549a10e3db12.png)

**Comment by DenisVuyka** [comment]
@hashraf88 re 21 years, in order to setup date picker we have to provide max `future` value, for the moment it is 21 year
```ts
let settings: any = {
    type: 'date',
    future: moment().add(21, 'years')
};
```

**Comment by DenisVuyka** [comment]
@hashraf88 Can you please move last findings to a separate ticket(s)

**Comment by hashraf88** [comment]
1. Not reported as settings not bugs
2. Not reported as settings not bugs
3. Reported in #942
4. Reported in #943
5. Reported in #944
