### ISSUE TITLE
Support for Typeahead widget within Activiti form 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#633]

**Comment by hashraf88** [comment]
When entering text into the text field an unnecessary dialog appears
![screen shot 2016-09-06 at 16 41 41](https://cloud.githubusercontent.com/assets/13200338/18280424/dae0367a-7450-11e6-97d8-d7c0571dc1e0.png)

**Comment by DenisVuyka** [comment]
@hashraf88 Could you please move your comment to a separate ticket and mark as `bug`? I will try replicating Activiti behaviour and hiding empty popup.

**Comment by hashraf88** [comment]
#696 created
