### ISSUE TITLE
Support for Amount widget within Activiti form

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#634]

**Comment by hashraf88** [comment]
On a completed task should the currency be displayed? 
![screen shot 2016-10-10 at 15 52 45](https://cloud.githubusercontent.com/assets/13200338/19240329/d4f6d702-8f01-11e6-9bd7-5f1e0584b266.png)

<img width="409" alt="screen shot 2016-10-10 at 15 52 35" src="https://cloud.githubusercontent.com/assets/13200338/19240310/bba26a8c-8f01-11e6-8d7e-ccfaf7edbb2e.png">

**Comment by DenisVuyka** [comment]
@hashraf88 I will add the currency symbol to the value for the completed form

**Comment by hashraf88** [comment]
Also I have noticed if the amount widget is set to not allow decimal places decimal places are allowed to be entered but when saving or completing the form the deicmal point is not displayed and only the amount before the decimal point is displayed. 

**widget**
![screen shot 2016-10-10 at 16 07 00](https://cloud.githubusercontent.com/assets/13200338/19240810/f62e7252-8f03-11e6-8a82-c2ccd3ca6ed7.png)

**Activiti**
<img width="559" alt="screen shot 2016-10-10 at 16 06 55" src="https://cloud.githubusercontent.com/assets/13200338/19240809/f62ae7b8-8f03-11e6-90af-2ed198d790db.png">


**Completed form**
![screen shot 2016-10-10 at 16 07 22](https://cloud.githubusercontent.com/assets/13200338/19240808/f626fa86-8f03-11e6-9a69-c1de78f91385.png)

**Widget setting**
![screen shot 2016-10-10 at 16 13 18](https://cloud.githubusercontent.com/assets/13200338/19240949/88c6482e-8f04-11e6-85a0-b9c10825ea7b.png)

**Comment by hashraf88** [comment]
Currency rednering on completed form issue resolved. 
Decimal issue addressed in #885
