### ISSUE TITLE
HTTP 500 response in adf-upload-button is emitted as a success event

### ISSUE THREAD

**Issue by tokewf** [Alfresco/alfresco-ng2-components#6352]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

I am running an ADF application where allowed MIME types for file uploads are defined on the backend. The backend returns a HTTP 500 if an illegal MIME type was uploaded. I will need to capture any upload errors and show a snack bar that lets the user know that their upload failed. It is also perfectly conceivable that a file upload may fail for a completely different reason than its MIME type.

With the following in my template:
```html
    <adf-upload-button
      [rootFolderId]="internalAttachmentFolder && internalAttachmentFolder.id"
      [multipleFiles]="true"
      acceptedFilesType=".pdf,.pptx,.xlsx,.docx,.jpg,.jpeg"
      [versioning]="true"
      (success)="onDidUpload($event)"
      (error)="showErrorSnackbar($event)">
```
and in my component class:
```typescript
  onDidUpload(event) {
    console.log('success', event)
    // logic to handle success event
  }

  showErrorSnackbar(event) {
    console.log('error', event)
    // logic to handle error event
  }
```
I am still seeing the success statement logged in the console even though the backend returns a HTTP 500. The value of `event` is
```javascript
{ value: 'Error file uploaded' }
```

**Expected behavior:**

The HTTP 500 response should trigger an emit of the error event.

**Steps to reproduce the issue:**

See above. To reproduce, build an application and use `OnContentUpdatePolicy` to implement a behavior on the Alfresco side that returns a HTTP 500 based on some condition (or, for testing purposes, just returns HTTP 500 all the time).

**Component name and version:** 

ADF 3.7, Angular 7.x

**Browser and version:** 

N/A
 
**Node version (for build issues):**  

10

**New feature request:**

**Comment by eromano** [comment]
https://alfresco.atlassian.net/browse/ADF-5369
