### ISSUE TITLE
Invalid dates when nodes loaded with Safari

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#644]
This is a long-standing issue - when nodes are loaded/displayed with Safari the page crashes with invalid date format exception.

The issue consists of two bugs:
- parsing dates in Safari
- angular 2 referencing Intl api missing in Safari and limited in FF ([ticket](https://github.com/angular/angular/issues/3333))

**Both issues cannot be reproduced with _Safari Technology Preview_, Release 11 (Safari 9.1.2, WebKit 11603.1.2)**

Suggested actions:
- date parsing updates
- [polyfill](https://www.npmjs.com/package/intl) for Safari until fixes not released for desktop and iOS versions.
- [see also](https://github.com/angular/angular/issues/3261)

**Comment by hashraf88** [comment]
Tested on Safari Version 9.1.2
For parsing dates still see "invalid date" in the UI and error in console.

**Comment by DenisVuyka** [comment]
@hashraf88 Have you tried `npm install` before testing? There is a new library and script reference  in the `index.html`

**Comment by hashraf88** [comment]
I hadn't, `npm update` and `npm build` but will try `npm install`
