### ISSUE TITLE
Form Fields should be at the same margin with the others

### ISSUE THREAD

**Issue by trakhmanova-CLGX** [Alfresco/alfresco-ng2-components#6485]
Form Fields should be at the same margin with the others

**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
"City*" is not at the same margin with the other form components on the Authentication Address form.  

**Expected behavior:**
"City*" should be at the same margin with the other form components.
**Steps to reproduce the issue:**
 Create any ticket and observe "City*" on the Authentication Address form.

**Component name and version:** 
"form.component", ADF v4.2

**Browser and version:** 
 Chrome Version 87.0.4280.88 (Official Build) (64-bit)
 
**Node version (for build issues):**  

**New feature request:**

**Comment by trakhmanova-CLGX** [comment]
[FormFields.docx](https://github.com/Alfresco/alfresco-ng2-components/files/5740121/FormFields.docx)

**Comment by trakhmanova-CLGX** [comment]
![image](https://user-images.githubusercontent.com/74369718/103098635-23de6600-4614-11eb-9f7a-bec7b3816582.png)

**Comment by trakhmanova-CLGX** [comment]
![image](https://user-images.githubusercontent.com/74369718/103098642-2fca2800-4614-11eb-986b-76cc93b0e8d5.png)

**Comment by trakhmanova-CLGX** [comment]
![image](https://user-images.githubusercontent.com/74369718/103099251-6739d400-4616-11eb-86e5-ad1212932559.png)

**Comment by trakhmanova-CLGX** [comment]
![image](https://user-images.githubusercontent.com/74369718/103099421-1aa2c880-4617-11eb-9fe9-eaaf1e73d918.png)

**Comment by trakhmanova-CLGX** [comment]
![image](https://user-images.githubusercontent.com/74369718/104034827-114e5a00-51da-11eb-863f-1cd8f13a7680.png)

**Comment by eromano** [comment]
https://alfresco.atlassian.net/browse/ADF-5369

**Comment by eromano** [comment]
Solved in ADF 4.4.0
