### ISSUE TITLE
Wrong display text for file size cell after updating folder name/properties 

### ISSUE THREAD

**Issue by sbakic** [Alfresco/alfresco-ng2-components#6488]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

When you update folder name, file size cell will get some text displayed "NaN CORE".

![103422806-8c44be80-4ba3-11eb-9c73-3b098a43dc6a](https://user-images.githubusercontent.com/6079897/103557543-a805d880-4eb3-11eb-8de0-99f5c439e6e9.png)

**Expected behavior:**

 filesize-cell.component.ts is used to display the size of a file or folder. For the file, it displayed some numbers, for the folder it was empty which is fine. When you want to edit the folder name it will still after the update remain empty.

**Steps to reproduce the issue:**

Run ACA application v1.11+, go to personal-files URL, create new folder, update (edit) folder name. For the "Size" column you will see "NaN CORE".

**Component name and version:** 

filesize.pipe.ts
filesize-cell.component.ts

It happens from 3.9.0 version and it's still there in 4.2.0.
ADDITIONAL INFO
file-size.pipe.ts which is setting the display value gets '' as a value to work with for the folders instead of undefined or null. On update name/propties of the folder in DataTableCellComponent (in datatable-cell.component.ts file) in updateValue method function is called and resolves file size value of folder to '', which latter calls this file-size.pipe.ts.

In previous versions (3.8.0 and below) updateValue() was not called. Why? Because ngOnInit of DataTableCellComponent where it should be call throws exception when getting property "content.sizeInBytes" of node, because in payload folder nodes doesn't have even content property. This is fixed in 3.9.0 to get the actual property. But then updateValue is called which will call file-size.pipe with value ''. And that case is not handled there. And that's why we get display text of file size for folder "NaN CORE".

**Browser and version:** 

 Chrome 87
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
Solved in ADF 4.4.0
