### ISSUE TITLE
ADF 4.2.0 app is reloading infinite times

### ISSUE THREAD

**Issue by groul** [Alfresco/alfresco-ng2-components#6579]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  "[x]"
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

After starting a fresh ADF 4.2.0, the app is just reloading infinite times in browser.
**Expected behavior:**

The login page should reload
**Steps to reproduce the issue:**

Create a fresh app using ADF 4.2.0 and start the app.
**Component name and version:** 

**Browser and version:** 

 Chrome
**Node version (for build issues):**  

node 14.x
**New feature request:**

**Comment by dhrn** [comment]
How are you creating the adf app?

**Comment by Adrian-Glumm-Silbury** [comment]
I have the same issue, regardless of browser (Tested Firefox and Safari, each latest)

I created the adf application with the yeoman generator as described in [this page](https://www.alfresco.com/abn/adf/docs/tutorials/creating-your-first-adf-application/)

**Comment by groul** [comment]
> How are you creating the adf app?

I have created the app by following https://www.alfresco.com/abn/adf/docs/tutorials/creating-your-first-adf-application/

I installed alfresco-adf-app using node 8.x because it was creating problem for other node versions. Then I switch to node 14.x to  run the app.

**Comment by dhrn** [comment]
I remember something that's fixed in the current release.  

can you try with latest alpha and attach the sendbox app here. 

it is hard to help without app.

**Comment by groul** [comment]
Can you please share the link of latest alpha ?

**Comment by dhrn** [comment]
you need to update the package json with following  version

    "@alfresco/adf-content-services": "4.3.0-31279",
    "@alfresco/adf-core": "4.3.0-31279",
    "@alfresco/adf-process-services": "4.3.0-31279",
    "@alfresco/js-api": "4.3.0-3207"

**Comment by chat-du-cheshire** [comment]
Hi, I'm pasted that deps, and it still infinite reload

> you need to update the package json with following version
> 
> ```
> "@alfresco/adf-content-services": "4.3.0-31279",
> "@alfresco/adf-core": "4.3.0-31279",
> "@alfresco/adf-process-services-cloud": "4.3.0-31279",
> "@alfresco/adf-process-services": "4.3.0-31279",
> "@alfresco/js-api": "4.3.0-3207"
> ```
> 
> refer demo shell for the sample configuration

Even more, I've got compilation error node_modules/@alfresco/js-api/src/authentication/oauth2Auth.ts:618:20 - error TS2591: Cannot find name 'Buffer'

**Comment by dhrn** [comment]
@chat-du-cheshire can you add the git hub URL for your referenced application?
I will try to reproduce in mylocal machine

**Comment by chat-du-cheshire** [comment]
Hi, this is it https://github.com/chat-du-cheshire/activiti-test-app. I was following this guide https://www.alfresco.com/abn/adf/docs/tutorials/creating-your-first-adf-application/

**Comment by chat-du-cheshire** [comment]
@dhrn hi, any news ?

**Comment by dhrn** [comment]
@chat-du-cheshire I am able to reproduce this. probably, next week i will have a look on this.

**Comment by chat-du-cheshire** [comment]
@dhrn hi, super, thnx )

**Comment by dhrn** [comment]
Thank you for reporting.It will be released as part 4.3.0 release. please reopen it doesn't fix
