### ISSUE TITLE
Cannot upload file in Safari

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#660]
File is not uploaded and error in console when trying to upload a file in document list

```
[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (children, line 0)
[Log] EXCEPTION: Error: Uncaught (in promise): Error: {"error":{"errorKey":"Required parameters are missing","statusCode":400,"briefSummary":"08010008 Required parameters are missing","stackTrace":"For security reasons the stack trace is no longer displayed, but the property is kept for previous versions.","descriptionURL":"https://api-explorer.alfresco.com"}}
```

**Comment by mauriziovitale** [comment]
We need the new JS API release before test it

**Comment by injrav** [comment]
we are getting the same issue in IE browser.. Same code is working fine in chrome

IE error message - captured from f12 dev tools

{"error":{"errorKey":"Required parameters are missing","statusCode":400,"briefSummary":"050610637 Required parameters are missing","stackTrace":"For security reasons the stack trace is no longer displayed, but the property is kept for previous versions","descriptionURL":"https://api-explorer.alfresco.com"}}

request: body
-----------------------------7e13ac2730c22
Content-Disposition: form-data; name="name"

jun6-am-from-ie.jpg
-----------------------------7e13ac2730c22
Content-Disposition: form-data; name="filedata"

C:\temp\files-to-upload\jun6-am-from-ie.jpg
-----------------------------7e13ac2730c22
Content-Disposition: form-data; name="overwrite"

true
-----------------------------7e13ac2730c22
Content-Disposition: form-data; name="nodeType"

cm:content
-----------------------------7e13ac2730c22--

**Comment by injrav** [comment]
code sample:

var tempHttp: Http = this.http;
    var tempFileData = this.uploadDocumentModel.filedata;
    var tempFileName = this.uploadDocumentModel.filename
   
    let alfrescoUrl: string = ‘alfresco_url';
    let form: FormData = new FormData();
    form.append("name", tempFileName);
//tempfiledata == on debug ,, I am seeing the data into this file object
    form.append('filedata', tempFileData);
    form.append('overwrite', 'true');
form.append('nodeType', 'cm:content')
    var headersData = new Headers();
    headersData.append('Authorization', 'Basic ' + btoa(userid:password));

    tempHttp.post(alfrescoUrl, form,  {headers:headersData} ).map((res: Response) => {

      res.json();
    }).subscribe();
