### ISSUE TITLE
Search Folder

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#666]
We could add also the folder to the search and in case of click open it in the document list

**Comment by eromano** [comment]
```javascript
let opts = {
            include: ['path'],
            rootNodeId: nodeId,
            nodeType: 'cm:content'
        };
```
If you remove  ``` nodeType: 'cm:content' ```  from the option you will search among folder and files.

**Comment by hashraf88** [comment]
Issues found are reported in the below:
#1240 
#1241
