### ISSUE TITLE
Cursor does not change to hand icon on mouseover in Chrome or Safari

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#678]
For component headers 
[mouseover.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/455331/mouseover.mp4.zip)

**Comment by mauriziovitale** [comment]
On my machine, the pointer changes when the mouse is over the link. 
Safari Version 9.1.2
Same behavior with Chrome.
Can some other test it, please ?
[safari-pointer.zip](https://github.com/Alfresco/alfresco-ng2-components/files/461177/safari-pointer.zip)

**Comment by hashraf88** [comment]
Strange, now seems fine. Will close for now but keep an eye on this.
