### ISSUE TITLE
ECM/BPM overlapped by login

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#679]
On Iphones (4s-6plus) below is displayed
Fine on Ipads (Ipad 2 onwards)

![screen shot 2016-09-05 at 17 10 51](https://cloud.githubusercontent.com/assets/13200338/18253406/5d911f1e-738c-11e6-942e-0041ecb886e8.png)

**Comment by DenisVuyka** [comment]
@magemello do we really need changing that? based on my understanding demo shell is an example app, and checkboxes on login screen are for demo purposes only, not for production use on mobile devices.

**Comment by magemello** [comment]
@DenisVuyka What you say is correct, however the deapp still has to be fully working also mobile.
