### ISSUE TITLE
Upload dialog is not brought to front

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#680]
On Iphones (4s-6plus) and Ipads (Ipad 2 onwards)
![screen shot 2016-09-05 at 17 18 45](https://cloud.githubusercontent.com/assets/13200338/18253491/f76a79e6-738c-11e6-973c-a0bcba037d11.png)

**Comment by hashraf88** [comment]
The file upload dialog does now not seem to responsive 
Iphone 5 onwards, no issue on Ipad 
<img width="242" alt="screen shot 2016-10-28 at 15 30 58" src="https://cloud.githubusercontent.com/assets/13200338/19810203/713576a2-9d24-11e6-8390-9650eceddb7d.png">

**Comment by magemello** [comment]
Can you open another issue to track this problem?And close it if the original problem is solved?
