### ISSUE TITLE
Breadcrumb does not work properly with Alfresco installed in other language than English

### ISSUE THREAD

**Issue by RuudGianesini** [Alfresco/alfresco-ng2-components#6813]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**

I've an Alfresco installed in Italian language.
I navigate into a site using Alfresco Content App I see this:
![breadcrumb](https://user-images.githubusercontent.com/18052793/110764291-26d01680-8253-11eb-9396-357912764bd9.png)

**Expected behavior:**

I expect to see "Sample: Web Site Design Project" instead of "swsdp/documentlibrary".

**Steps to reproduce the issue:**

1. Install Alfresco in a different language than English
2. Open ACA
3. Click "My Libraries" on left side menu
4. Click into a site

**Component name and version:** 

breadcrumb.component

**Browser and version:** 

all

**Comment by eromano** [comment]
https://alfresco.atlassian.net/browse/ADF-5371

**Comment by eromano** [comment]
Solved in ADF 4.4.0
