### ISSUE TITLE
Yeoman app alfresco-adf-app produces dependency error

### ISSUE THREAD

**Issue by luiscolorado** [Alfresco/alfresco-ng2-components#6912]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Installing ADF using the yeoman app alfresco-adf-app produces the following error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: adf-cli-acs-aps-template@4.3.0
npm ERR! Found: @angular/compiler@10.0.6
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"10.0.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"^6.0.0 || ^7.0.0 || ^7.2.0-beta.0" from ng-packagr@4.7.1
npm ERR! node_modules/ng-packagr
npm ERR!   peer ng-packagr@"^2.2.0 || ^3.0.0 || ^4.0.0" from @angular-devkit/build-ng-packagr@0.10.7
npm ERR!   node_modules/@angular-devkit/build-ng-packagr
npm ERR!     dev @angular-devkit/build-ng-packagr@"~0.10.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/luis/.npm/eresolve-report.txt for a full report.
```
The instructions imply that the latest version of Angular/CLI (10.x) should work, but it looks like only versions 6 to 7 are supported in the dependencies. 

**Expected behavior:**
The ADF environment should be deployed without errors.

**Steps to reproduce the issue:**
Using Ubuntu 18.0.4

1. Make sure that node has been [completely removed](https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows)
2. Follow the instructions to install the [prerequisites](https://www.alfresco.com/abn/adf/docs/tutorials/creating-your-first-adf-application/#prerequisites)
3. Enter the command 'yo alfresco-adf-app'

**Component name and version:** 
```
npm ERR! While resolving: adf-cli-acs-aps-template@4.3.0
```

**Browser and version:** 
N/A
**Node version (for build issues):**
Output of 'ng v':
```
Angular CLI: 10.0.4
Node: 15.13.0
OS: linux x64

Angular: 10.0.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: <error>

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.8
@angular-devkit/build-angular      0.1000.8
@angular-devkit/build-ng-packagr   0.10.7
@angular-devkit/build-optimizer    0.1000.8
@angular-devkit/build-webpack      0.1000.8
@angular-devkit/core               10.0.8
@angular-devkit/schematics         10.0.4
@angular/cdk                       10.0.2
@angular/cli                       10.0.4
@angular/flex-layout               10.0.0-beta.32
@angular/material                  10.1.0
@angular/material-moment-adapter   10.1.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   10.0.8
@schematics/angular                10.0.4
@schematics/update                 0.1000.4
ng-packagr                         4.7.1
rxjs                               6.6.7
typescript                         3.9.7
webpack                            4.43.0
```

**Comment by davidcanonieto** [comment]
Hi @luiscolorado, is it possible you're using npm version 7 in your machine? If so, please downgrade to npm 6. Many different users have reported compatibility issues with the latest version of npm. Please, let me know.

**Comment by luiscolorado** [comment]
Hi David,

I switched to version 6.14.12, but I get the same error when I run **yo alfresco-adf-app**:

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: adf-cli-acs-aps-template@4.3.0
npm ERR! Found: @angular/compiler@10.0.6
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"10.0.6" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"^6.0.0 || ^7.0.0 || ^7.2.0-beta.0" from ng-packagr@4.7.1
npm ERR! node_modules/ng-packagr
npm ERR!   peer ng-packagr@"^2.2.0 || ^3.0.0 || ^4.0.0" from @angular-devkit/build-ng-packagr@0.10.7
npm ERR!   node_modules/@angular-devkit/build-ng-packagr
npm ERR!     dev @angular-devkit/build-ng-packagr@"~0.10.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/luis/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/luis/.npm/_logs/2021-04-13T19_13_24_496Z-debug.log

I did some more research. I switched angular to version 6.x, and I still got the same error. After reading more carefully the error, I see that I misunderstood the dependencies messages. I think that **the problem is caused by an dependency incompatibility in adf-cli-acs-aps-template**. As far as I can tell, this is not something that can be fixed by the user's environment. Find below the details:
	
The module adf-cli-acs-aps-template@4.3.0 requires @angular/compiler **10.0.6** (see package.json, [line 28](https://github.com/Alfresco/generator-alfresco-adf-app/blob/32729a654ca82883356cd3217e349c8cf2bc14a3/app/templates/adf-cli-acs-aps-template/package.json#L28)). However, another dependency (build-ng-packagr, see [line 59](https://github.com/Alfresco/generator-alfresco-adf-app/blob/32729a654ca82883356cd3217e349c8cf2bc14a3/app/templates/adf-cli-acs-aps-template/package.json#L59)) has sub-dependencies that eventually require @angular/compiler 6, 7, or 7.2.  Below is line 59 of  adf-cli-acs-aps-template:

```
"@angular-devkit/build-ng-packagr": "~0.10.0",	
```
			
The module [@angular-devkit/build-ng-packagr](https://www.npmjs.com/package/@angular-devkit/build-ng-packagr) is deprecated, and the recommendation is to use @angular-devkit/build-angular instead. Nonetheless, let's ignore that for the moment. The dependency above requires build-ng-packagr: ~0.10.0, but that's unavailable. If I understand correctly, npm indicates that  version 0.10.7 is used instead:
	
```
npm ERR!   peer ng-packagr@"^2.2.0 || ^3.0.0 || ^4.0.0" from @angular-devkit/build-ng-packagr@0.10.7
```
	
In turn, npm selects version 4.7.1 of build-ng-packagr:
	
```
npm ERR! peer @angular/compiler@"^6.0.0 || ^7.0.0 || ^7.2.0-beta.0" from ng-packagr@4.7.1 			
```

And, sure enough, [package.json](https://www.npmjs.com/package/@angular-devkit/build-ng-packagr) in ng-packagr@4.7.1 requires a compiler version 6, 7,or 7.2, (see [line 60](https://github.com/ng-packagr/ng-packagr/blob/a72ca3ddb6e3fb8303b1c711af45d563873fa65d/package.json#L60)) which are not compatible with adf-cli-acs-aps-template peer dependency, which requires 10.0.6, that I mentioned above.

`In conclusion,` adf-cli-acs-aps-template should remove the compiler dependency ([line 28](https://github.com/Alfresco/generator-alfresco-adf-app/blob/32729a654ca82883356cd3217e349c8cf2bc14a3/app/templates/adf-cli-acs-aps-template/package.json#L28)) or even better, replace the deprecated dependency [build-ng-packagr](https://www.npmjs.com/package/@angular-devkit/build-ng-packagr).

I hope that makes sense.

**Comment by luiscolorado** [comment]
Are there any comments? As mentioned in my comment, the problem is caused by a conflict in the packaging.

adf-cli-acs-aps-template should remove the compiler dependency ([line 28](https://github.com/Alfresco/generator-alfresco-adf-app/blob/32729a654ca82883356cd3217e349c8cf2bc14a3/app/templates/adf-cli-acs-aps-template/package.json#L28)) or even better, replace the dependency to package [build-ng-packagr](https://www.npmjs.com/package/@angular-devkit/build-ng-packagr). 

[build-ng-packagr](https://www.npmjs.com/package/@angular-devkit/build-ng-packagr) has been deprecated: "This package has been deprecated. Please use the ng-packagr builder from @angular-devkit/build-angular instead."

**Comment by DenysVuika** [comment]
@luiscolorado please raise the yeoman generator issues in the proper repository: https://github.com/Alfresco/generator-alfresco-adf-app.

For the last release, the generator was tested and had no issues. We have even produced some guides on Ubuntu/CentOS installations: https://github.com/Alfresco/generator-alfresco-adf-app#installing-nodejs-and-npm
