### ISSUE TITLE
Compatibility issue for ADF 4.3 with Alfresco 6.2

### ISSUE THREAD

**Issue by kaspereden** [Alfresco/alfresco-ng2-components#6913]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
The content metadata card fails to render when using ADF 4.3 in combination with Alfresco 6.2

What happens is that it uses the Model API, that seems to be new and not working / non existing in ACS 6.x

**Expected behavior:**
It should render

**Steps to reproduce the issue:**
* Server with Alfresco Content Services 6.2
* ADF 4.3 and content metadata card on any node will do

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by dhrn** [comment]
Hello @kaspereden 
it is fixed in this [PR](https://github.com/Alfresco/alfresco-ng2-components/pull/6845) . use latest beta to get it working.

**Comment by kaspereden** [comment]
Cool, thanks :) 

For me the issue is resolved by downgrading 1 version. Since this is only for demo purposes that version is good enough.

**Comment by eromano** [comment]
Solved in ADF 4.4.0
