### ISSUE TITLE
ShareDataTableAdapte getValue performance issue

### ISSUE THREAD

**Issue by eromano** [Alfresco/alfresco-ng2-components#695]
Turned out during the investigation for the viewer performance problem that the main problem is relative to the  `javascript ShareDataTableAdapte.getValue()` method.

Below some screenshot relative the problem:
<img width="1226" alt="screen shot 2016-09-06 at 17 33 39" src="https://cloud.githubusercontent.com/assets/1030050/18280249/b956734a-7458-11e6-9c01-4a1969e1ecab.png">
<img width="847" alt="screen shot 2016-09-06 at 17 34 35" src="https://cloud.githubusercontent.com/assets/1030050/18280251/bb6979de-7458-11e6-92fd-c2ffca984557.png">

For bypass this problem now there is a flag that hides the documentlist when the viewer is on.
To reproduce the problem you need just to remove the flag from the first div of the demo shell int the file files.component.html.

**Comment by DenisVuyka** [comment]
Note: the problem is not in the `getValue` itself but the `date pipe` being called too much times.

**Comment by eromano** [comment]
I tested it with this configuration and the problem is still there. For my understanding seems that when the viewer add a lot of new HTML elements as in the case of long file the change HTML detection of angular 2 is called many times and this tirgger a lot of call to : 

```
detectChangeInternal -> getValue -> datePipe
```

So maybe the question is how to stop this check of getValue inside the ShareDatatable adapter when the HTML relative the documentList is not changed

**Comment by hashraf88** [comment]
Issue relates to @eromano comment above, "For bypass this problem now there is a flag that hides the documentlist when the viewer is on."

When in Chrome and trying to view a picture file (jpg, png etc) the viewer is not displayed correctly. Fine in both Firefox and Safari.

<img width="1373" alt="screen shot 2016-12-05 at 21 06 20" src="https://cloud.githubusercontent.com/assets/13200338/20902513/664dfd4e-bb2f-11e6-9958-d98d077bd6e8.png">

**Comment by DenisVuyka** [comment]
@hashraf88 this is something different. The flag to hide document list has been removed some time ago as no longer needed; performance for this particular ticket was greatly improved and it has nothing to do with Viewer in this case.

**Comment by hashraf88** [comment]
Above reported in #1205
