### ISSUE TITLE
Viewer does not does display in Safari

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#701]
<img width="1264" alt="screen shot 2016-09-07 at 11 51 24" src="https://cloud.githubusercontent.com/assets/13200338/18309477/892577cc-74f1-11e6-80f9-88674f58d0b5.png">

**Comment by eromano** [comment]
Seems to be a problem about the CORS call.  If you open in Safari the developer menu, and select "Disable cross-origin restrictions the problem disappear.
