### ISSUE TITLE
Generated app fails to start if not all components has been selected

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#705]
I created a fresh project using the latest release of `generator-ng2-alfresco-app` and said no to include search and simple dashboard. After the app was generated I did `npm install` followed by `npm start`

```
? Do you want include a navigation bar? Yes
? Do you want include a drawer bar? Yes
? Do you want include a search bar? No
? Do you want include a Document List? Yes
? Do you want include a Tasks List? Yes
? Do you want include a sample dashboard? No
```

I got the following error:
```
app/components/index.ts(2,33): error TS2307: Cannot find module './search/search.component'.
app/components/index.ts(3,36): error TS2307: Cannot find module './search/search-bar.component'.
app/components/index.ts(7,32): error TS2307: Cannot find module './chart/chart.component'.
``` 
If I include all the components everything works as expected.

**Comment by ohej** [comment]
As the list of components grows I think it's good to have this flexibility. It also addresses the use case if you're using BPM or ECM only, in that case you get the possibility to only select what's relevant for you.

The feedback I'm getting says this is a very nice feature because it allows you to get up and running with the features you want quickly. The alternative is that you get everything and have to start pulling individual components out of the setup.

**Comment by DenisVuyka** [comment]
Makes sense, thanks. Then we just need fixing this particular issue.

**Comment by DenisVuyka** [comment]
Moved issue to the corresponding repo. Closing this ticket.
