### ISSUE TITLE
allowedFilesType list is case sensitive (Upload Drag Area + Upload Button)

### ISSUE THREAD

**Issue by ryanchristie** [Alfresco/alfresco-ng2-components#7098]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Supplied value(s) to Upload Drag Area & Upload Button ADF components are case sensitive.

**Expected behavior:**
Supplied value(s) are case insensitive.

**Steps to reproduce the issue:**
Provided [allowedFilesType]=".doc", attempting to upload a .DOC file will not be successful.

**Component name and version:** 
Components: Upload Button, Upload Drag Area
Version: 4.3.0

**Browser and version:** 
All

**Comment by eromano** [comment]
extension are case sensitive
