### ISSUE TITLE
APS form - ADF form does not load dropdown items retrieved from a REST service

### ISSUE THREAD

**Issue by miguel-galan** [Alfresco/alfresco-ng2-components#7102]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

![image](https://user-images.githubusercontent.com/24700924/121785200-6249ec00-cb86-11eb-950b-e2ca3c0125ba.png)

In an APS form, when a dropdown is set to populate the items using a REST service, the ADF form component populates the item list using the manual option. The same task loaded from activiti-app loads the item list as expected using the REST service

**Expected behavior:**

ADF form should load dropdown items using the REST service set, if any.

**Steps to reproduce the issue:**

1. Define a process model in APS (and create a new app with that model)
2. Add a new user task
3. Define a new form for that task
4. Add a dropdown field on the new form
5. Edit the dropdown field options to use a REST Service (set the end point previously)
6. Save and publish the field/form/process/app
7. Start a new instance and open the task from the ADF form component
8. It won't load the list returned from the REST Service

**Note**: APS expects the REST service to return a JSON array with the following format:
[
 {"id" : "value1"}, 
 {"id" : "value2"}, 
 {"id" : "value3"}
]
**Component name and version:** 

Component: adf-form
Version: 4.3.0 (it happens since version 2.4.0, at least)

**Browser and version:** 

Chrome: 91.0.4472.101

**Comment by eromano** [comment]
Hi, @miguel-galan I just tried it using this mock server :  

https://run.mocky.io/v3/f892c0bc-2d5e-4c62-ac83-80304e5f85fc

and all seems to be working fine : 

<img width="775" alt="Screenshot 2021-07-01 at 16 14 43" src="https://user-images.githubusercontent.com/1030050/124139024-8151e480-da87-11eb-933a-15e5b83f2613.png">

**Comment by miguel-galan** [comment]
@eromano you are right. In our case, we selected the rest call but it was failing (due to an issue on the APS side) and we didn't realize that it was falling back to the manual set of options automatically (we thought it was a bug, but it's more like a feature). Thanks
