### ISSUE TITLE
Rows displayed incorrect when changing rows per page on last page

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#716]
1. 20 rows/uploads
2. Change rows per page to 15
3. Go to next page/last page
4. Change rows per page to 10
5. Go to previous page

**Expected results**
List items 1-10 displayed
**Actual results**
List items 5-15 displayed

[pagination2.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/461496/pagination2.mp4.zip)

**Comment by DenisVuyka** [comment]
Mathematically it is correct. Here's the flow you see:

```
Page start: 1 
Page size: 20
Showing: (start - page size|max) => 1 - 20

Change page size to 15

Page start: 1 
Page size: 15
Showing: (start - page size|max) => 1 - 15

Next page
Formula: start = (start + page size)
Result: (1 + 15) = 16

Page start: 16
Page size: 15
Showing: (start - page size|max) => 16 - 20

Change page size to 10

Page start: 16
Page size: 10
Showing: (start - page size|max) => 16 - 20

Prev page
Formula: start = (start - page size)
Result: (16 - 10) = 6

Page start: 6
Page size: 10
Showing: (start - page size|max) => 6 - 16

Prev page
Formula: start = (start|1 - page size|max) => 1 - 10

Page start: 1
Page size: 10
Showing: 1 - 10
```

**Comment by hashraf88** [comment]
1. 20 rows/uploads
2. Change rows per page to 15
3. Go to next page/last page
4. Change rows per page to 10
5. Go to previous page

**Results**
List items 5-15 displayed

This results displayed are correct in a sense that when navigating to previous and next pages the count is taken **from the page come from** instead of the **very first page** i.e. the first item.
