### ISSUE TITLE
Queued tasks are not displayed

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#719]
1. Import following app into Activiti [queued_app.zip](https://github.com/Alfresco/alfresco-ng2-components/files/461707/queued_app.zip)

2. Start a process from 'queued_app' , which includes at least one user task that is not auto assigned

Expected
Task is displayed under queued tasks in demo app
Actual
Task is not displayed under queued tasks in demo app

**Comment by hashraf88** [comment]
#718 
#719

**Comment by mauriziovitale** [comment]
Should be the same problem of the #718

**Comment by hashraf88** [comment]
Unfortunately task does not display when using url pointing at specific app e.g.http://localhost:3000/activiti/appId/1004
