### ISSUE TITLE
Person, group and typeahead values displayed incorrectly on completed tasks

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#723]
![screen shot 2016-09-08 at 16 16 57](https://cloud.githubusercontent.com/assets/13200338/18357696/d9a65128-75e9-11e6-9dbe-a548c732d8ce.png)

**Comment by DenisVuyka** [comment]
In addition the following widgets are displayed incorrectly:

- Checkbox (displays 'False' or 'True')
- Multiline Text (displays text on a single line)
- Upload (displays '[object Object]')

**Comment by DenisVuyka** [comment]
What's interesting - Activiti does not properly display values for `Typeahead` and `Dropdown` (REST-based). Activiti also has problem with `Hyperlink` clicks when value is missing schema (http/https), we got that fixed.

**Activiti**
<img width="917" alt="screen shot 2016-09-09 at 13 35 58" src="https://cloud.githubusercontent.com/assets/503991/18387125/9dfea374-7692-11e6-831f-8fdc7399f317.png">

**Comment by DenisVuyka** [comment]
`ng2-alfresco-form` and original Activiti form component both incorrectly display `Hyperlink` component when form is readonly/complete:

**Open Form**
<img width="567" alt="screen shot 2016-09-09 at 14 44 59" src="https://cloud.githubusercontent.com/assets/503991/18389103/3b9f523c-769c-11e6-981b-185752105ee7.png">

**Complete Form**
<img width="515" alt="screen shot 2016-09-09 at 14 45 10" src="https://cloud.githubusercontent.com/assets/503991/18389115/476bcef6-769c-11e6-8890-37c19e4622dd.png">

**Comment by hashraf88** [comment]
Tested against the below and when completed values are correct (for those widgets supported):

- Tabs
- Text
- Multiline Text
- Number
- Checkbox
- Date (not supported yet)
- Dropdown
- Typeahead
- Amount
- Radio buttons
- People
- Group of people
- Dynamic table (not supported yet)
- Hyperlink
- Upload
- Display value
- Display text

**Comment by DenisVuyka** [comment]
@hashraf88 Should we move issue to done then? We may also want raising tickets for Activiti repo for several widgets having issues with 'complete' form rendering there.

**Comment by hashraf88** [comment]
I think it is already in done, I will raise with Brindusa the issues regarding Activiti.
