### ISSUE TITLE
Asian Language Support

### ISSUE THREAD

**Issue by mail2hemant** [Alfresco/alfresco-ng2-components#7251]
**Type of issue:**  (check with "[x]")

> - [x ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

Currently ADF doesn't support adding more language than already listed.

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenysVuika** [comment]
Right now you can add any more languages you need by putting the translation files in the corresponding folder, also the language picker is based on the configuration file, so you can add/removed language entries where needed.

Can you please elaborate on the issue? What support you think is missing?
