### ISSUE TITLE
Form Validation - Activiti form component

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#726]
Introduce form validation support

- Text
  - [x] Required
  - [x] Min Length
  - [x] Max Length
  - [x] RegEx Pattern
- Multiline Text
  - [x] Required
  - [x] Min Length
  - [x] Max Length
  - [x] RegEx Pattern
- Number
  - [x] Valid Number Value
  - [x] Required
  - [x] Min Value
  - [x] Max Value 
- Dropdown
  - [x] Required
- Typeahead
  - [x] Required
- Radio buttons
  - [x] Required
- People
  - [x] Required
- Group of people
  - [x] Required
- Attach
  - [x] Required

**Comment by hashraf88** [comment]
In Activiti for widgets with max length set no text is allowed to be entered after max length reached.
In the Activiti component once the max length is reached more text is allowed to be entered however a message is displayed 'Should be x characters maximum.'
Is this ok or would Activiti behaviour need to replicated?

**Comment by DenisVuyka** [comment]
We can't replicate full behaviour of Activiti components at this point (styles, input masks, etc.). For now just pure validation.

**Comment by hashraf88** [comment]
Are we introducing validation (required) for the checkbox widget too? Currently it seems we do not

**Comment by DenisVuyka** [comment]
Checkbox cannot have required validation as it has 2 states - checked and unchecked and both states are valid.

**Comment by hashraf88** [comment]
Ah yes true
