### ISSUE TITLE
Not being redirected to login page when Kerberos is enabled

### ISSUE THREAD

**Issue by rderooij** [Alfresco/alfresco-ng2-components#7264]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
A new bug is introduced and maybe it is related to issue [MNT-22334](https://alfresco.atlassian.net/browse/MNT-22334). 

When Kerberos is enabled, and you access the content app within the correct network environment and SSO is applied and works as expected. Both in ACA version 2.5.0 (4.5.0) and ACA 2.6.0 (4.6.0).  

When you access the content app outside the network environment, the credentials do not exist. The current behavior in ACA 2.6.0 (4.6.0) is that you are NOT being redirected to the login page. In ACA 2.5.0 this works as expected, you get the login page and you are able to login. 

The only way you can login outside the network is to set 'withCredentials' configuration parameter with value 'false'. 

**Expected behavior:**
When credentials are not available you will be redirected to the login page.

**Steps to reproduce the issue:**
Works in ACA 2.5.0 and does not work in ACA 2.6.0. 

**Component name and version:** 
See commit: https://github.com/Alfresco/alfresco-ng2-components/commit/4befb779f

**Comment by eromano** [comment]
Hi @rderooij  I have created an internal issue for it
