### ISSUE TITLE
Add Permission Component dosent show LDAP-User, only LDAP-Groups

### ISSUE THREAD

**Issue by archX-S** [Alfresco/alfresco-ng2-components#7268]
> - [ ] New feature request
> - [x] Bug  
> - [x] Support request
> - [ ] Documentation

**Expected behavior:**
Show LDAP users

**Component name and version:** 
Add Permission Component (4.4.0 - 4.6.0)

**Browser and version:** 
all
 
**Node version (for build issues):**  
v12.22.6

**Comment by eromano** [comment]
Are you sure about it? the users and groups are coming always from the content service. What version of Alfresco content services do you have?

**Comment by DenysVuika** [comment]
we use public REST api for all the calls, so if something is not displayed, it is most probably not coming from the Alfresco API response. if you are still having this issue, please check what REST calls involved and why data is not returned. I also suggest testing with latest ADF and ACS 7.x
