### ISSUE TITLE
Demo shell tasklist/processlist should be able to restrict list of tasks to a specific appId

### ISSUE THREAD

**Issue by wabson** [Alfresco/alfresco-ng2-components#732]
Both processlist and tasklist components already support restricting the filters that are rendered, but there is not a single place within the `activiti-demo` local component where a developer can configure a specific `appId` value easily to wire this in.

**Comment by hashraf88** [comment]
1. Cannot switch between apps in firefox, once one app is selected no other app can be selected. Does not occur in Chrome.

2. When accessing an app the first task in the first filter should be displayed (same behaviour as in Activiti)

3. The app options e.g. delete, download etc do not perform an actions, however they may only be place holders for the moment

**Comment by mauriziovitale** [comment]
@hashraf88 
1 - Should be fixed by issue #759 
2 - We can create more issues to improve the activiti apps component.

**Comment by hashraf88** [comment]
2 - reported in #766
