### ISSUE TITLE
Search Page Result is not showed

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#737]
Login as ECM user on demo app
Search the word ppt
Press Enter
Notice that the result page is not showed - NOT EXPECTED

**Comment by VitoAlbano** [comment]
@wabson i've given a look at the code and it seems that we do not support this thing anymore, could you give it a look please?

**Comment by magemello** [comment]
@wabson Have we addressed also the #371 as part of this fix?

**Comment by wabson** [comment]
Yes #371 is fixed as part of this work, and also in hotfix #869

**Comment by magemello** [comment]
@wabson can you move also #371 in test when this task will be moved in test?
