### ISSUE TITLE
After closing viewer navigated back to first page of document list

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#739]
1. Go to second page of document list (ensure more than one page is avaliable)
2. Open viewer
3. Close viewer
4. Notice navigated back to first page of document list, did not remain second page

**Comment by eromano** [comment]
This bug is directly linked to https://github.com/Alfresco/alfresco-ng2-components/issues/695 in order to solve this problem we have to solve before it

**Comment by DenisVuyka** [comment]
I think we should retest this issue with final version of angular and production mode.
