### ISSUE TITLE
Create User Info for User

### ISSUE THREAD

**Issue by VitoAlbano** [Alfresco/alfresco-ng2-components#741]
#727

**Comment by hashraf88** [comment]
**Portrait image** (take no notice of it being upside down)
<img width="451" alt="screen shot 2016-10-07 at 10 31 34" src="https://cloud.githubusercontent.com/assets/13200338/19185696/b7d7c5ca-8c7a-11e6-824d-bd56139d2000.png">

**Landscape image** 
![screen shot 2016-10-07 at 10 45 08](https://cloud.githubusercontent.com/assets/13200338/19185833/46dd145a-8c7b-11e6-8937-5174a4c25253.png)

For the logo on the landing page for a portrait image there are white spaces at the side of the image.

For the logo within the dropdown the grey disc (displayed if no image is present) can be seen on the edges of a portrait image or more prominently on a landscape image.
