### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by RAnouar** [Alfresco/alfresco-ng2-components#7411]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by eromano** [comment]
this ticket doesn't have any valid infotmation
