### ISSUE TITLE
Radio buttons widget does not work with REST settings

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#747]
Radio Buttons widget does not load REST settings and always displays 2 static options instead.

**Comment by hashraf88** [comment]
Only for Radio Buttons widget using REST settings when completed value displayed is incorrect.
Predefined options are displayed correctly. 
**Completed form**
<img width="361" alt="screen shot 2016-09-16 at 15 16 58" src="https://cloud.githubusercontent.com/assets/13200338/18589197/805a474e-7c21-11e6-84d3-1a15e33abead.png">

**Selected option**
<img width="253" alt="screen shot 2016-09-16 at 15 16 22" src="https://cloud.githubusercontent.com/assets/13200338/18589198/805c4fda-7c21-11e6-947c-5f6bd45d3eb2.png">
