### ISSUE TITLE
Attach widget does not trim long names

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#748]
Attach widget should automatically trim long names.

<img width="747" alt="screen shot 2016-09-14 at 20 49 55" src="https://cloud.githubusercontent.com/assets/503991/18527681/a38d6846-7abd-11e6-8692-c6d3956b0142.png">

**Comment by magemello** [comment]
let's use css ellipsis:

.truncate {
  width: 250px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

**Comment by DenisVuyka** [comment]
Activiti shows full text with word wrapping, I will provide the same for ADF.

**Comment by hashraf88** [comment]
Text is wrapped correctly on forms which are not completed but not on completed forms.
Occurs on all browsers. 

**Form, uncompleted (correct)**
<img width="466" alt="screen shot 2016-11-04 at 17 10 16" src="https://cloud.githubusercontent.com/assets/13200338/20015070/a847c66c-a2b1-11e6-924a-853a9a1217b8.png">


**form, completed**
<img width="507" alt="screen shot 2016-11-04 at 17 10 30" src="https://cloud.githubusercontent.com/assets/13200338/20015072/ad0f668c-a2b1-11e6-8513-768e2d009c9d.png">

**Comment by DenisVuyka** [comment]
Should look like following after the fix

![screen shot 2016-11-08 at 13 19 45](https://cloud.githubusercontent.com/assets/503991/20100757/d0e044d4-a5b6-11e6-9da1-50c3a5c785de.png)
