### ISSUE TITLE
Upgrade to Angular 2 RTM

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#749]
Upgrade to Angular 2.0.0 release version

Dependencies:
- [x] ng2-translate (already upgraded to RTM)
- [x] TypeScript 2.0.2 or later

**Comment by DenisVuyka** [comment]
List of unit tests that need to be upgraded/fixed:

## Search
ng2-components/ng2-alfresco-search/src/components/alfresco-search.component.spec.ts
ng2-components/ng2-alfresco-search/src/components/alfresco-search-autocomplete.component.spec.ts
ng2-components/ng2-alfresco-search/src/components/alfresco-search-control.component.spec.ts
ng2-components/ng2-alfresco-search/src/services/alfresco-search.service.spec.ts

## Login
ng2-components/ng2-alfresco-login/src/components/alfresco-login.component.spec.ts

## DocumentList
ng2-components/ng2-alfresco-documentlist/src/services/document-list.service.spec.ts

## Core
ng2-components/ng2-alfresco-core/src/services/renditions.service.spec.ts

## Upload
ng2-components/ng2-alfresco-upload/src/components/file-uploading-dialog.component.spec.ts
ng2-components/ng2-alfresco-upload/src/components/upload-button.component.spec.ts
ng2-components/ng2-alfresco-upload/src/components/upload-drag-area.component.spec.ts
ng2-components/ng2-alfresco-upload/src/services/upload.service.spec.ts

## Tag
ng2-components/ng2-alfresco-tag/src/components/tag-actions.component.spec.ts
ng2-components/ng2-alfresco-tag/src/components/tag-list.component.spec.ts
ng2-components/ng2-alfresco-tag/src/components/tag-node-list.component.spec.ts
ng2-components/ng2-alfresco-tag/src/services/tag.service.spec.ts

## WebScript
ng2-components/ng2-alfresco-webscript/src/webscript.component.spec.ts

## Viewer
ng2-components/ng2-alfresco-viewer/src/componets/pdfViewer.component.spec.ts
ng2-components/ng2-alfresco-viewer/src/componets/imgViewer.component.spec.ts
ng2-components/ng2-alfresco-viewer/src/componets/mediaPlayer.component.spec.ts
ng2-components/ng2-alfresco-viewer/src/componets/notSupportedFormat.component.spec.ts
ng2-components/ng2-alfresco-viewer/src/componets/viewer.component.spec.ts
ng2-components/ng2-alfresco-viewer/src/services/rendering-queue.services.spec.ts

## Activiti Form
ng2-components/ng2-activiti-form/src/services/ecm-model.service.spec.ts
ng2-components/ng2-activiti-form/src/services/widget-visibility.service.spec.ts
ng2-components/ng2-activiti-form/src/services/form.service.spec.ts

## Activiti TaskList
ng2-components/ng2-activiti-tasklist/src/services/activiti-tasklist.service.spec.ts

## Activiti ProcessList
ng2-components/ng2-activiti-processlist/src/services/activiti-process.service.spec.ts

**Comment by DenisVuyka** [comment]
## Broken coverage settings

ng2-components/ng2-alfresco-core/karma.conf.js
ng2-components/ng2-alfresco-search/karma.conf.js
ng2-components/ng2-alfresco-documentlist/karma.conf.js
ng2-components/ng2-activiti-form/karma.conf.js
ng2-components/ng2-activiti-tasklist/karma.conf.js
ng2-components/ng2-alfresco-search/karma.conf.js
ng2-components/ng2-alfresco-upload/karma.conf.js

**Comment by eromano** [comment]
Webscript test fixed
