### ISSUE TITLE
adf viewer is not able to resolve dynamic labels and titles

### ISSUE THREAD

**Issue by bhosalevijay426** [Alfresco/alfresco-ng2-components#7499]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [x] Support request
> - [ ] Documentation

**Current behaviour:**

Instead of getting plain labels for buttons like thumbnails, next previous, I am getting something like - ADF_VIEWER.ARIA.NEXT_PAGE.
I was getting some labels like -  ADF_VIEWER.PAGE_LABEL.SHOWING which I had to handle myself after document load.

**Expected behavior:**

Should get correct labels

**Steps to reproduce the issue:**

My code block is just this - 
<mat-dialog-content class="no-print preview" role="main" aria-label="Document image preview">
   <adf-viewer
      *ngIf="node_Url"
      [urlFile]="node_Url"
      [mimeType]="mime_type"
      [allowDownload]="false"
      [overlayMode]="false"
      [showToolbar]="false"
      [allowThumbnails]="true"
      [allowFullScreen]="false"
      (print)="onPrint($event)"
      tabindex="2"
   >
   </adf-viewer>
   <mat-spinner style="margin-left: 40%;" *ngIf="!node_Url"></mat-spinner>

**Component name and version:** 

I am using adf-viewer which is from adf-content service :  3.9.0 and angular version is 7.2.15

**Browser and version:** 

 latest chrome version

**Node version (for build issues):**  

Node version is - v12.19.0

**Comment by DenysVuika** [comment]
Closing as cannot be reproduced with Angular 14 and latest ADF
