### ISSUE TITLE
Placeholders are not displayed within forms

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#755]
<img width="348" alt="screen shot 2016-09-16 at 12 07 34" src="https://cloud.githubusercontent.com/assets/13200338/18584041/4ba891ec-7c06-11e6-8361-16632aea5020.png">
<img width="432" alt="screen shot 2016-09-16 at 12 07 28" src="https://cloud.githubusercontent.com/assets/13200338/18584042/4bbdce7c-7c06-11e6-99eb-ccc764205366.png">

**Comment by DenisVuyka** [comment]
We use control labels instead of the placeholders. When input gets focus the label floats on the top. The desired look and feel should be discussed with the design team I think.

**Comment by DenisVuyka** [comment]
@magemello I suggest closing this ticket for now.

**Comment by magemello** [comment]
We should avoid to use floating label and use static label + placeholder.
