### ISSUE TITLE
adf-viewer-extension not working with alfresco-enterprise-viewer

### ISSUE THREAD

**Issue by spark66rc** [Alfresco/alfresco-ng2-components#7556]
**Type of issue:** 

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
I want to integrate the "alfresco-enterprise-viewer" component into my ADF application. I have followed the documentation provided with the AEV module. They ask to put the following code inside the adf-viewer component. 

```
   <adf-viewer-extension [supportedExtensions]="['pdf', 'mp4']" #extension > 
       <alfresco-enterprise-viewer [node]="node"></alfresco-enterprise-viewer> 
    </adf-viewer-extension>
```

But nothing happens!
By debugging, I see that we don't fit in the "adf-viewer-extension" directive.

**Expected behavior:**
The AEV module (iframe) must be displayed inside the adf-viewer.

**Steps to reproduce the issue:**
Install Alfresco-enterprise-viewer
Apply the procedure of the documentation "IQ-AlfrecoEnterpriseViewer-ADF-Linux-Alfresco.v1.15.pdf" of module AEV

**Component name and version:** 
adf-viewer, adf-viewer-extension
ADF 4.8.0

**Browser and version:** 
All
 
**Node version (for build issues):**  
v14.19.0

**Comment by spark66rc** [comment]
Hello, I still haven't had an answer

**Comment by DenysVuika** [comment]
@spark66rc contact customer support, as ADF is OSS and does not support Enterprise Viewer in this repository and issue tracker
