### ISSUE TITLE
Activiti apps components custom layout List/Grid

### ISSUE THREAD

**Issue by mauriziovitale** [Alfresco/alfresco-ng2-components#756]
As a developer, I'd like to render the activiti apps list in two different way, as a List or as a Grid.

**Comment by hashraf88** [comment]
If 3 or more rows of apps the task list cannot be accessed

<img width="1394" alt="screen shot 2016-09-17 at 12 51 45" src="https://cloud.githubusercontent.com/assets/13200338/18608104/e47581c4-7cd7-11e6-91d6-6ca0c5770b89.png">

**Comment by hashraf88** [comment]
2. Only in Safari, if a filter is selected the app list is overlapped until an app is selected again.
<img width="1260" alt="screen shot 2016-09-17 at 13 34 32" src="https://cloud.githubusercontent.com/assets/13200338/18608231/c10e8092-7cdb-11e6-9f3f-248070c2e3e0.png">

**Comment by hashraf88** [comment]
Tasklist unable to be accessed #765 (issue only for demo app)
Safari issue reported in #764
