### ISSUE TITLE
moment.js is in maintenance mode

### ISSUE THREAD

**Issue by EugeneHerasymchuk** [Alfresco/alfresco-ng2-components#7571]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
At this point of time, there is only one implementation of DateProvider in the project - it's [MomentDateAdapter](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/lib/core/utils/moment-date-adapter.ts) 
But as per moment.js project status - https://momentjs.com/docs/#/-project-status/ 
"We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done."
The main downside - need to keep moment.js in dependencies because of [peerDependency](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/lib/core/package.json#L33)

**Expected behavior:**
There is at least config for switching between new implementation of provider with Luxon/date-fns... or complete switch from moment.js to a new libraries.

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenysVuika** [comment]
Besides the implementation of the MomentDateAdapter, there's a lot of other cases of using `moment` across the ADF components, quick search shows at least 81 files with 664 references. And there are also ADF-based apps (ACA, ADW, admin, etc) that are using moment besides the data adapter. That makes refactoring of the codebase quite a non-trivial task.

So while I fully agree that the `moment` needs to go, getting rid of it might take several iterations as for me.
