### ISSUE TITLE
If a filter is selected the app list is overlapped until an app is selected again.

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#764]
Only in Safari, if a filter is selected the app list is overlapped until an app is selected again.
<img width="1260" alt="screen shot 2016-09-17 at 13 34 32" src="https://cloud.githubusercontent.com/assets/13200338/18608231/c10e8092-7cdb-11e6-9f3f-248070c2e3e0.png">

**Comment by mauriziovitale** [comment]
Should be fixed by #765

**Comment by hashraf88** [comment]
No actions in Safari now seem to be working, e.g. accessing a task

**Comment by hashraf88** [comment]
Include static 'Task App' app

**Comment by hashraf88** [comment]
Safari issues reported in #778
