### ISSUE TITLE
The app options e.g. delete, download etc do not perform any actions

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#766]
![screen shot 2016-09-19 at 11 31 25](https://cloud.githubusercontent.com/assets/13200338/18629296/94ae1fc6-7e5c-11e6-95f2-529a1c0c7edf.png)

**Comment by hashraf88** [comment]
@magemello have they just been removed?

**Comment by magemello** [comment]
Yes
