### ISSUE TITLE
Alfresco Digital workspace custom extension routing

### ISSUE THREAD

**Issue by GurjarDharmraj** [Alfresco/alfresco-ng2-components#7700]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [X] Support request
> - [ ] Documentation

**Current behaviour:**
{
"routes":[
{
"id":"custom.route",
"parentRoute":"",
"path":"personal-files",
"layout":"app.layout.main",
"component":"your.component.id",
"children":[

]
}
]
}

here want to update only child route   if i am not passing  component id then its throwing error here I want to use default component FilesComponent from Content-ce its not part of 

CoreExtensionsModule.  How i can acchive this 

**Expected behavior:**

**Steps to reproduce the issue:**

**Component name and version:** 

**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenysVuika** [comment]
Please raise the issue in the corresponding repository (`alfresco-content-app`) as this is the ADF repository
