### ISSUE TITLE
Pass process variable without have a form

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#775]

**Comment by DenisVuyka** [comment]
@magemello can you give more details for this task please?

**Comment by wabson** [comment]
As discussed in planning this feature relates to manually setting process variables on a process instance without the use of a form.

Having reviewed the [REST API](https://docs.alfresco.com/activiti/docs/dev-guide/1.4.0/#_activiti_engine_rest_api) docs and JS-API docs I cannot however see any method of doing this. It seems that fetching a [process instance](https://github.com/Alfresco/alfresco-js-api/blob/master/src/alfresco-activiti-rest-api/docs/ProcessInstanceRepresentation.md) details does return information on the variables currently set, but there is no endpoint provided to update existing variables or set new ones on a process.
