### ISSUE TITLE
Automaticaly open next task in the flow - activiti-tasklist-component

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#776]
We want to be able to automatically render the next task when the current one is completed. This behavior must be configurable trough a boolean parameter. 

<activiti-task-details [showNextTaskOnCompleteAction]="true">

**Comment by mauriziovitale** [comment]
@magemello 
When the onFormCompleted is emitted the task list is refreshed and it shows all the tasks (including the newer one) by decrescent date. As a default behavior, the first task is selected and then showed in task detail. This is the same behavior as activiti.
Do you want to make selectFirstTask configurable ?

**Comment by magemello** [comment]
We want to automatically show the next task in the task details area.
