### ISSUE TITLE
Opening a new tab with the mousewheel on adf-breadcrumb item.

### ISSUE THREAD

**Issue by jproennau** [Alfresco/alfresco-ng2-components#7816]
> - [x] New feature request

**Current behaviour:**
Currently the adf-breadcrumb component has it's href hardcoded with '#' as value. Which doesn't support opening a new tab with mousewheel click or with "open in new tab" in the right click context menu.
See: https://github.com/Alfresco/alfresco-ng2-components/blob/2fd10b2fe4663e01380f889d782bdc5ffed432a9/lib/content-services/src/lib/breadcrumb/breadcrumb.component.html#L50.

**Steps to reproduce the issue:**
Use the <adf-breadcrumb> tag with a folderNode/documentList and navigate to a Folder that is a Subfolder.
Now try to open a new tab with the mousewheel or with right click "open in a new tab" on the breadcrumbs parent folder item.

**Component name and version:** 
(https://github.com/Alfresco/alfresco-ng2-components/blob/2fd10b2fe4663e01380f889d782bdc5ffed432a9/lib/content-services/src/lib/breadcrumb/breadcrumb.component.html#L50.)

**Browser and version:** 
I would say all, but only tested it on Chrome: Version 105.0.5195.52

**New feature request:**
We would like to set the href dynamically or get the chance to change the value of it out of our app, so that the above mentioned methods open the right site/folder in a new tab.

**Comment by DenysVuika** [comment]
We handle the clicks to change the document list data, and turning those into hyperlinks is going to break the default functionality. As an alternative, you can implement and use your own breadcrumb implementation that is based on hyperlinks
