### ISSUE TITLE
Sometimes the filterList is shown twice.

### ISSUE THREAD

**Issue by mauriziovitale** [Alfresco/alfresco-ng2-components#784]
<img width="1185" alt="screen shot 2016-09-21 at 11 56 29" src="https://cloud.githubusercontent.com/assets/14923305/18708430/abff755c-7ff2-11e6-85f4-025215e050ee.png">

**Comment by hashraf88** [comment]
steps to replicate

1. Create a new task (Activiti)
2. Refresh task list (activiti component) 
**Expected results** 
Filters remain the same 
**Actual results** 
Filters are duplicated
3. Navigate to processlist
4. Notice filters are not duplicated any longer

**Comment by hashraf88** [comment]
<img width="604" alt="screen shot 2016-09-22 at 16 43 41" src="https://cloud.githubusercontent.com/assets/13200338/18755375/f6747a96-80e3-11e6-85f2-d1d063fced6d.png">

Back but now just for task app, no other app, No steps to reproduce just go to task app and duplicate filters will be displayed
