### ISSUE TITLE
Task overview - Analytics component

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#788]
Reproduce the Task overview graph of Activiti.

**Comment by hashraf88** [comment]
Don't think the timestamp is required for the number of tasks divided by date interval bar chart 
**COMPONENT**
<img width="897" alt="screen shot 2016-10-17 at 16 16 12" src="https://cloud.githubusercontent.com/assets/13200338/19443601/1d113a5e-9485-11e6-8bf7-6a5931aae477.png">

**ACTIVITI**
![screen shot 2016-10-17 at 16 17 24](https://cloud.githubusercontent.com/assets/13200338/19443633/37830354-9485-11e6-9055-f71e291d72ed.png)
