### ISSUE TITLE
 Process instances overview - Analytics component

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#789]
Reproduce the Process instances heat map graph of Activiti.

**Comment by hashraf88** [comment]
The process instance counts section of the report is missing.
![screen shot 2016-10-17 at 15 27 43](https://cloud.githubusercontent.com/assets/13200338/19441936/73109130-947f-11e6-892e-222774dbc75d.png)

**Comment by hashraf88** [comment]
For the process steps total time section if the sum of the activity is 0 is doesnt need to be displayed as a key in on the pie chart. 

**Component**
![screen shot 2016-10-17 at 15 47 43](https://cloud.githubusercontent.com/assets/13200338/19442733/449b1a8e-9482-11e6-8f57-0b8772d84723.png)

**Activiti**
![screen shot 2016-10-17 at 15 47 29](https://cloud.githubusercontent.com/assets/13200338/19442530/7f7c755e-9481-11e6-9f93-680b9a643434.png)

**Comment by magemello** [comment]
It is fine, we can keep it as it is.
