### ISSUE TITLE
 Process definition heat map - Analytics component

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#790]
Reproduce the Process definition heat map graph of Activiti.

**Comment by mauriziovitale** [comment]
### Diagram library
- [ ] Import Raphael js
- [ ] Import Polyline js

### Diagram draw methods
- [ ] _drawStartEvent
- [ ] _drawEndEvent
- [ ] _drawServiceTask
- [ ] _drawCallActivity
- [ ] _drawScriptTask  
- [ ] _drawUserTask 
- [ ] _drawBusinessRuleTask 
- [ ] _drawManualTask 
- [ ] _drawSendTask 
- [ ] _drawReceiveTask 
- [ ] _drawTask 
- [ ] _drawExclusiveGateway 
- [ ] _drawParallelGateway 
- [ ] _drawInclusiveGateway 
- [ ] _drawEventGateway 
- [ ] _drawGateway 
- [ ] _drawBoundaryEvent 
- [ ] _drawIntermediateCatchEvent 
- [ ] _drawThrowEvent 
- [ ] _drawMultilineText 
- [ ] _drawTextAnnotation 
- [ ] _drawFlow 
- [ ] _drawPool 
- [ ] _drawLane 
- [ ] _drawSubProcess 
- [ ] _drawEventSubProcess 
- [ ] _drawAssociation 
- [ ] _drawArrowHead 

### Diagram icons
- [ ] _drawUserTaskIcon 
- [ ] _drawServiceTaskIcon 
- [ ] _drawScriptTaskIcon 
- [ ] _drawBusinessRuleTaskIcon 
- [ ] _drawSendTaskIcon 
- [ ] _drawManualTaskIcon 
- [ ] _drawReceiveTaskIcon 
- [ ] _drawCamelTaskIcon 
- [ ] _drawMuleTaskIcon 
- [ ] _drawAlfrescoPublishTaskIcon 
- [ ] _drawBoxPublishTaskIcon 
- [ ] _drawGoogleDrivePublishTaskIcon 
- [ ] _drawRestCallTaskIcon 
- [ ] _drawEventIcon 
- [ ] _drawTimerIcon 
- [ ] _drawErrorIcon 
- [ ] _drawSignalIcon 
- [ ] _drawMessageIcon

### Diagram functions
- [ ] _showTip 
- [ ] _addHoverLogic 
- [ ] _zoom 

### Diagram Color methods
- [ ] _determineCustomFillColor 
- [ ] _bpmnGetColor
