### ISSUE TITLE
Upload widget does not save file uploaded

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#802]
1.  Upload a file
2. Save form
3. Navgiate away and back to task

**Expected results**
File previously uploaded is saved

**Actual results**
File previously uploaded is not saved

N.b. Firefox only and IE11

**Comment by hashraf88** [comment]
Now fine in Firefox but still remains an issue on IE11 (Windows 8.1)
@magemello do we want to fix/start to fix IE issues yet?

**Comment by magemello** [comment]
Yes please, can you describe the issue?

**Comment by DenisVuyka** [comment]
There are two different issues related to the same test. I've fixed uploads for multiple browsers (including FF and IE), tested with IE and FF. However sometimes there's another issue with CSRF settings for the api we use for uploading files to Activiti. If you have problems with the latter you will now see a dialog saying something like "There was an error, see console output for more details".

**Comment by DenisVuyka** [comment]
@hashraf88 as discussed, should be working fine with latest 'alfresco-js-api' and 'development' branch.
