### ISSUE TITLE
File does not display if previously uploaded and cleared

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#812]
1. Upload a file
2. Save form
3. Navigate away and back to task
4. Clear previously uploaded file
5. Select same file or different file

**Expected results**
File chosen is displayed

**Actual results**
File chosen is not displayed

[upload widget.mp4.zip](https://github.com/Alfresco/alfresco-ng2-components/files/489388/upload.widget.mp4.zip)

**Comment by DenisVuyka** [comment]
Notes: this bug relates to Attach control when used with 'linking' mode (#621)
