### ISSUE TITLE
Bump PDFJS to newer version

### ISSUE THREAD

**Issue by shazada** [Alfresco/alfresco-ng2-components#8137]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

Current version is pdfjs 2.5 https://github.com/Alfresco/alfresco-ng2-components/blob/develop/package.json#L88

**Expected behavior:**

That pdfjs is more up to date
![image](https://user-images.githubusercontent.com/1477763/212066724-aee30c8b-1e32-451f-965d-1261cf2d0391.png)

**Steps to reproduce the issue:**

**Component name and version:** 

pdfjs-dist
**Browser and version:** 

 
**Node version (for build issues):**  

**New feature request:**

**Comment by DenysVuika** [comment]
Using 3.3.x now, thanks for reporting
