### ISSUE TITLE
If no due date set for task text should be 'No Due Date' not 'invalid date' 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#817]
<img width="486" alt="screen shot 2016-09-26 at 16 18 20" src="https://cloud.githubusercontent.com/assets/13200338/18840100/5a1881c2-8405-11e6-9c72-299c2e2792dc.png">
![screen shot 2016-09-26 at 16 18 12](https://cloud.githubusercontent.com/assets/13200338/18840101/5a25619e-8405-11e6-8946-b20c893e6013.png)

**Comment by mauriziovitale** [comment]
Should be fixed with the last js api. 
Please retest.
