### ISSUE TITLE
Task name is displayed as form name

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#825]
In this case the task name is 'task started in activiti' and the form name 'test_form'

![screen shot 2016-09-27 at 16 14 14](https://cloud.githubusercontent.com/assets/13200338/18879933/fe80d8a4-84cd-11e6-894b-df5893e15d96.png)

![screen shot 2016-09-27 at 16 14 22](https://cloud.githubusercontent.com/assets/13200338/18879932/fe7f2400-84cd-11e6-904b-bc570a441dda.png)

**Comment by DenisVuyka** [comment]
Both fields are displaying Task Name, it's not a mistake. Task Details provides own Task Name and wraps a Form that does the same. There's an option to hide Task Name within the Form renderer.

**Comment by hashraf88** [comment]
Oh ok, should we be displaying the form name in the task anywhere at all?

**Comment by DenisVuyka** [comment]
That's a missing functionality I think.

**Comment by hashraf88** [comment]
Created #826
