### ISSUE TITLE
'Mario' appears instead of 'sign in'

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#828]
Only appears after initially starting the dmeo shell
1. Npm install in demo shell folder

<img width="574" alt="screen shot 2016-09-28 at 10 22 18" src="https://cloud.githubusercontent.com/assets/13200338/18908187/85f39964-8566-11e6-859d-24f40277421c.png">

**Comment by magemello** [comment]
Doesn't show on my machine, but in effect the en.json file has this string. So this thing let me think that there is something wrong with the internationalization. Must to be checked.
