### ISSUE TITLE
highlighted/selected filter in tasklist 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#834]
To know which filter you are in the tasklist the active filter could be highlighted in some way. As Activiti does 

E.g. 
![screen shot 2016-09-30 at 12 09 07](https://cloud.githubusercontent.com/assets/13200338/18992148/9336f198-8714-11e6-860d-7789c7ac49f1.png)

Activiti
![screen shot 2016-09-30 at 13 47 18](https://cloud.githubusercontent.com/assets/13200338/18992147/93358718-8714-11e6-9451-d54249ac6239.png)

**Comment by magemello** [comment]
let's just change the color of the font when selected...

**Comment by hashraf88** [comment]
Would it be possible to extend this to process list and analytics?

**Comment by DenisVuyka** [comment]
@hashraf88 Yes, I suggest we create another ticket for that to address later.
