### ISSUE TITLE
Search suggestions are not displayed

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#837]
Search suggestions are not displayed

![screen shot 2016-10-03 at 11 10 40](https://cloud.githubusercontent.com/assets/13200338/19034181/0c940caa-895a-11e6-8b73-6be01d17350e.png)

**Comment by magemello** [comment]
@wabson is it fixed in another issue?

**Comment by magemello** [comment]
@wabson is it fixed in another issue?

**Comment by wabson** [comment]
Yes this was fixed as part of #737

**Comment by hashraf88** [comment]
Just retested and is fine.
