### ISSUE TITLE
Column Sort Arrow Doubled

### ISSUE THREAD

**Issue by JCarlos12** [Alfresco/alfresco-ng2-components#8403]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
But after upgrading to version 5.0 with Angular 14 the sort indicator has doubled
![image](https://user-images.githubusercontent.com/11145777/226350998-600a3fa1-8188-4143-b28a-835bae8c36d5.png)

**Expected behavior:**
I was using ADF version 4.9 with Angular 12 before and the adf-datatable when sorted on a column looked like this
![image](https://user-images.githubusercontent.com/11145777/226350875-ee4e6711-35d6-460e-9549-858475eebfe5.png)

**Component name and version:** 
adf-datatable

Is this an intended feature? If so are there any ways to return it to just one indicator

**Comment by eromano** [comment]
@JCarlos12 what do you mean doubled? the arrow is present for each sortable column if an arrow is present means is sortable

**Comment by JCarlos12** [comment]
@eromano before the upgrade to 5.0.0 the arrow only appears on the left side of the header of the sorted column. Is this an intentional change? Or is there a property that can be configured to only display it on the left side

**Comment by DenysVuika** [comment]
Cannot reproduce with any of the 6.x builds. Please reopen and provide steps to reproduce the issue, if it still happens.
