### ISSUE TITLE
Add BaseQueryBuilderService to public api to be able to extend it

### ISSUE THREAD

**Issue by MarcKoester** [Alfresco/alfresco-ng2-components#8647]
**Type of issue:**  (check with "[x]")

> - [x] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**New feature request:**

I want to integrate a second search to our app, which works different then the main search. I want to use the [SearchQueryBuilder](https://github.com/Alfresco/alfresco-ng2-components/blob/e176009be708ffb3c5f44803d5af9ce4ba563190/lib/content-services/src/lib/search/services/search-query-builder.service.ts), but load a different configuration.
So I tried to write my own QueryBuilder which extends the BaseQueryBuilderService, but this isn't possible because the BaseQueryBuilderService isn't publicly exported.

Could you add the [BaseQueryBuilderService](https://github.com/Alfresco/alfresco-ng2-components/blob/e176009be708ffb3c5f44803d5af9ce4ba563190/lib/content-services/src/lib/search/services/base-query-builder.service.ts) to the public export, so we can extend it with our own QueryBuilder?

**Comment by DenysVuika** [comment]
Thanks for raising this. Will be fixed for the upcoming release
