### ISSUE TITLE
Outline icons prevent from moving to Material Symbols

### ISSUE THREAD

**Issue by romainbrochot** [Alfresco/alfresco-ng2-components#8679]
**Type of issue:**  (check with "[x]")

> - [X] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Some icons use the outline "flag". example : info_outline and with Material Symbols they are not displayed properly.

**Expected behavior:**
Use CSS classes instead so we can register our own classes in the module with the MatIconRegistry service.

**Steps to reproduce the issue:**
Remove material icons from custom-styles.scss
Add material symbols instead.
ADF components using "_outline" icons are not displayed properly.

**Component name and version:** 

**Browser and version:** 
 
**Node version (for build issues):**  

**New feature request:**
Add the possibility to use Mat Symbols

**Comment by romainbrochot** [comment]
Sorry I forgot to add we removed MatIcons http resource in index.html and we use npm dependency for material icons and we import it from custom-styles.scss in our projects because of customers not allowing internet access on their servers

**Comment by DenysVuika** [comment]
@romainbrochot can you then please update the expected behaviour for the ADF, not for your custom application?

**Comment by romainbrochot** [comment]
Yes that's how we did it. It's just that, in specific ADF components, outlined icons do not display properly if we use something else than mat icons.
We'll stick to Mat icons until your work is finished.
You can close the case.

**Comment by DenysVuika** [comment]
thanks for confirming. Switching to Material Symbols will be a breaking change in terms of backwards compatibility, but it is possible using outlined icons with Material Icons too. Closing for now and we might get back to that in the future releases if we decide migrating to Symbols
