### ISSUE TITLE
Support Activiti Custom Form Stencils

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#875]
- Support form stencils made with Angular 2
- Can we support form stencils made with Angular 1 ?

**Comment by DenisVuyka** [comment]
This is a very broad topic that needs to be discussed. I suggest moving it to post 1.0.0 release.

**Comment by magemello** [comment]
#967  
#966

**Comment by magemello** [comment]
Link to the documentation:

- Custom Stencil in Adf:
  - https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/docs/stencils.md 
- Support for existing stencil in Activiti:
 - https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/docs/extensibility.md
