### ISSUE TITLE
adf-insights module documentation

### ISSUE THREAD

**Issue by romainbrochot** [Alfresco/alfresco-ng2-components#8768]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [ ] Support request
> - [x] Documentation

**Current behaviour:**
The documentation is not exhaustive for the insights module, especially if you want to use the 'adf-diagram' component.

**Expected behavior:**
The documentation should explain that you need these 2 modules InsightsModule, ChartsModule and ng2-charts, chart.js, raphael ("node_modules/raphael/raphael.min.js") npm dependencies, etc

**Component name and version:** 
'adf-diagram' component / @alfresco/adf-insights module / ADF v6.1.0

**Browser and version:** 
all
 
**Node version (for build issues):**  
v16.20.1

**New feature request:**

**Comment by DenysVuika** [comment]
What is the scenario you still use Insights library for? It's not used by any internal apps and will be marked as deprecated in the future.

**Comment by romainbrochot** [comment]
Hello Denys
Mainly for the integration of the adf-diagram component (APS instance and definition diagrams)
