### ISSUE TITLE
File upload progress blocked by Angular Service-Worker

### ISSUE THREAD

**Issue by bOo-sRi** [Alfresco/alfresco-ng2-components#8836]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
The upload progress counter (file size counter) is missing in [File Upload Dialog Component](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/docs/content-services/components/file-uploading-dialog.component.md) when [Service Worker](https://angular.io/guide/service-worker-intro) is used. 

**Expected behavior:**
The file size counter should display the progress. 
To achieve that the upload request must include the `ngsw-bypass` header. 
https://angular.io/guide/service-worker-devops#bypassing-the-service-worker

**Steps to reproduce the issue:**

1. Serve Alfresco Angular App with Service-Worker
2. Upload a file
3. See the progress counter not counting upwards. Progress displaying 0/0 until upload is finished. 

**Component name and version:** 
adf-file-uploading-dialog

**Browser and version:** 
all

**Comment by DenysVuika** [comment]
This is an external issue, and you can track it here https://github.com/w3c/ServiceWorker/issues/1141 or use some workarounds suggested here https://github.com/angular/angular/issues/21191#issuecomment-484586484

**Comment by Licht-en-Stein** [comment]
Angular already provides a workaround for bypassing the Service worker https://angular.io/guide/service-worker-devops#bypassing-the-service-worker. For upload requests you have to set the ngsw-bypass header or query parameter. However we're unable to set custom header or query parameter for upload requests which would be the easiest way to achieve that. 

Modifying the Service Worker could be a solution although it is hard to maintain.
