### ISSUE TITLE
People, comment and checklist dialogs do not appear

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#893]
In Firefox and Safari only, when I click on the '+' symbol next to people, comment or checklist within a task no dialog appears. 

Related to #631

**Comment by DenisVuyka** [comment]
Was fixed as part of the following PR: #954

**Comment by hashraf88** [comment]
All dialogs now appear correctly, however the people dialog does not display any suggestions.
Comment and checklist functionality is fine.
<img width="399" alt="screen shot 2016-11-02 at 13 19 56" src="https://cloud.githubusercontent.com/assets/13200338/19930300/bb31fb16-a0ff-11e6-8369-d29dbd70e08a.png">

**Comment by VitoAlbano** [comment]
This problem is already reported on : #815  and will be fixed shortly on the PR for that bug.
As for Denys comment this one was fixed with #954 .
