### ISSUE TITLE
Alfresco Viewer Component Bug After Upgrade

### ISSUE THREAD

**Issue by JCarlos12** [Alfresco/alfresco-ng2-components#8962]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Alfresco Viewer Component displays the content twice. Once with the PDF style and the other just a plain string in the back. See attached image

**Expected behavior:**
Alfresco Viewer Component should display correctly

**Steps to reproduce the issue:**
Currently have this code which is used to display a PDF file

<adf-alfresco-viewer  #viewer
	[allowLeftSidebar]="true"
	[allowPrint]="true"
	[nodeId]="nodeId"
	[overlayMode]="false"
	[sidebarLeftTemplate]="leftSidebarTemplate"
	[showLeftSidebar]="true"
></adf-alfresco-viewer>

**Component name and version:** 
adf-alfresco-viewer : ADF 6.2.0
 
**Node version (for build issues):**  
18.17.1
![Viewer Bug](https://github.com/Alfresco/alfresco-ng2-components/assets/11145777/79a0fa7e-6009-47e7-a1bb-193c99e3d082)

**Comment by DenysVuika** [comment]
Please verify which pdfjs version you are using and if it's matching the ADF. I'm testing this with [Alfresco Content Application,](https://github.com/Alfresco/alfresco-content-app) and there are no issues with PDF files:

```
"pdfjs-dist": "3.3.122",
```

![image](https://github.com/Alfresco/alfresco-ng2-components/assets/503991/079bbf57-2974-4351-bfae-eafbb5aeef26)

**Comment by romainbrochot** [comment]
Hi,

had the same issue, maybe you could check if you have :
```
"styles": [
   [...]
   "node_modules/pdfjs-dist/web/pdf_viewer.css"
]
```

in angular.json

**Comment by MichalKinas** [comment]
@JCarlos12 any updates on this? Can we close the issue?
