### ISSUE TITLE
ADF identity user info compenent doesn't work in ADF 6.1.1

### ISSUE THREAD

**Issue by Karek-MA** [Alfresco/alfresco-ng2-components#8996]
I'm using ADF 6.1.1 with APS 2.4. When I use the component  <adf-identity-user-info ></adf-identity-user-info> it shows nothing. I also tried to call the service directly, but it gets all values as undefined, although I successfully log in, and I can see my list of apps.

What could be the problem and how I can fix it?

**Current behaviour:**
The adf-identity-user-info compenent shows nothing at all, even that I'm logged in

**Expected behavior:**
the adf-identity-user-info should show a round icon for the user and will show extra information about the user when clicked

**Steps to reproduce the issue:**
just use the component in a template 6.1.1 <adf-identity-user-info ></adf-identity-user-info> 

**Component name and version:** 
<adf-identity-user-info ></adf-identity-user-info> 
template version 6.1.1
APS 2.4
Node 18
Angular 16

**Browser and version:** 
all
 
**Node version (for build issues):**  
18

**Comment by DenysVuika** [comment]
Already answered this on the Hub, this component requires SSO with Identity Services configured. For APS you need process-user-info, for ACS - content-user-info
