### ISSUE TITLE
Sign in box

### ISSUE THREAD

**Issue by heenav** [Alfresco/alfresco-ng2-components#900]
- [x] The size of the 'Sign in' box should be 450x450px.
- [x] The current build has an interaction not in the current design. 
  In the put feels - The placeholder text transitions into a label on selection.
  Remove this transition to reflect the design.
- [x] Sometimes we have noticed both input field highlighted orange at the same time.
- [x] The copyright information is missing at the bottom of the box.
- [x] The password icon is currently in the wrong order. 
  eye with line = hidden
- [x] There's currently a shadow around the orange sign in button. This needs to be removed to match the design.
- [x] 'NEED HELP' & 'REGISTER' is underlined. The underline needs to be removed to match the design.
- [x] Font colour needs to be 87 transparency once the live text is being entered - to match the design.
  'Remember' also needs to be 87
- [x] The 'Remember' checkbox needs to be preselected.
- [x] Once the user successfully enters his details and clicks 'sign in', the design shows the 'sign in' button transition into a 'welcome button'. Please match the design.
- [x] The inactive 'sign in' button is currently different to the design. The text colour and also the grey box itself needs to match the design.
- [ ] The red colours for the error states need to match the red in the design.
- [x] Warning icon is missing when the top level errors are presented. e.g.. '…invalid username and password'

**Comment by heenav** [comment]
The current build has an interaction not in the current design. 
In the put feels - The placeholder text transitions into a label on selection.
Remove this transition to reflect the design.

**Comment by heenav** [comment]
Sometimes we have noticed both input field highlighted orange at the same time.

**Comment by heenav** [comment]
The copyright information is missing at the bottom of the box.

**Comment by heenav** [comment]
The password icon is currently in the wrong order. 
eye with line = hidden

**Comment by heenav** [comment]
There's currently a shadow around the orange sign in button. This needs to be removed to match the design.

**Comment by heenav** [comment]
'NEED HELP' & 'REGISTER'  is underlined. The underline needs to be removed to match the design.

**Comment by heenav** [comment]
Font colour needs to be 87 transparency once the live text is being entered - to match the design.
'Remember' also needs to be 87

**Comment by heenav** [comment]
The 'Remember' checkbox needs to be preselected.

**Comment by heenav** [comment]
Once the user successfully enters his details and clicks 'sign in', the design shows the 'sign in' button transition into a 'welcome button'. Please match the design.

**Comment by eromano** [comment]
@heenav Hi thanks for the help about the styling issue, can you please continue to add the other issues on the first comment pressing on the edit command? I already modified the firts one reporting all you others comment. Thanks

**Comment by heenav** [comment]
Ahhh ok so shall i create a 'New issue' for each Issue we raise?

**Comment by magemello** [comment]
For now let's keep everything in this issue...a bullets list will be fine

**Comment by heenav** [comment]
Perfect thanks! :-)

**Comment by heenav** [comment]
The inactive 'sign in' button is currently different to the design. The text colour and also the grey box itself needs to match the design.

The red colours for the error states need to match the red in the design.

Warning icon is missing when the top level errors are presented. e.g.. '…invalid username and password'

**Comment by john-knowles** [comment]
Sign in page also displays message saying login successful, this is not required as per the designs.

![login successful](https://cloud.githubusercontent.com/assets/18680913/22807949/92d2fe66-ef21-11e6-8f29-af840d07cfd6.png)
