### ISSUE TITLE
BaseAuthenticationService onLogin ReplaySubject property wrong behavior

### ISSUE THREAD

**Issue by werdy77** [Alfresco/alfresco-ng2-components#9046]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
If Alfresco ticket (_ticket-ECM_) has been invalidated (or timed out), _BaseAuthenticationService_ **onLogin** _ReplaySubject_ property emit value before ADF login screen appears and not emit value after successful login.

**Expected behavior:**
_BaseAuthenticationService_ **onLogin** _ReplaySubject_  should emit value only after successful authentication.

**Steps to reproduce the issue:**
- Find stored Alfresco ticket in the ADF app browser developer tool/local storage under _ticket-ECM_ name.
- Close ADF app.
- Invalidate ticket with authentication API DELETE call:
```
alfresco/api/-default-/public/authentication/versions/1/tickets/-me-?alf_ticket=TICKET_216825fcb1b7a17daa939518b06bc5c49b48c6c2
```
- Open ADF app.

**Component name and version:** 
BaseAuthenticationService, 6.3

**Browser and version:** 
Brave Version 1.57.64 Chromium: 116.0.5845.188 (Official Build) (64-bit)
 
**Node version (for build issues):**  
18.11.11

**New feature request:**
14.2.12

**Comment by DominikIwanek** [comment]
Fixed by: 
https://github.com/Alfresco/alfresco-ng2-components/pull/9244/files
