### ISSUE TITLE
Process Service Down on NPM?

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/alfresco-ng2-components#9048]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [X] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**
Looks like The Process Service Package is down on NPM. When I try to install it with NPM: 

`npm install @alfresco/adf-process-services`

or specifying the latest version or via package.json I always get: 

`npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://registry.npmjs.org/@alfresco%2fadf-process-services - KV GET failed: 401 Unauthorized`

Also seems like on the official NPM page the package is not available: https://www.npmjs.com/package/@alfresco/adf-process-services

**Comment by DenysVuika** [comment]
maybe it was related to NPM services or your local connections, I can see the package on NPM right now fine

**Comment by MariusGrunenberg** [comment]
Yes I just saw, that in fact it is working now. Was weird, because other packages were fine. But then this issue can be closed, since it seems to have been a temporary issue.
