### ISSUE TITLE
Clean scripts cause full npm install for each project

### ISSUE THREAD

**Issue by DenisVuyka** [Alfresco/alfresco-ng2-components#906]
Clean script calls `npm run clean` for each project. The `clean` script looks like following:

``` json
scripts: {
  "clean": "npm install rimraf && rimraf dist node_modules typings",
}
```

this causes full npm install before removing `node_modules` folder.

**Comment by eromano** [comment]
Hi Denys, 
I just tried this script and not seems to install all the modules.

<img width="891" alt="screen shot 2016-10-17 at 09 55 03" src="https://cloud.githubusercontent.com/assets/1030050/19429421/ee3210b2-944f-11e6-9738-26d8723b41ea.png">

This install rimraf  is useful when you try to clean a component where the node_modules folder is not present or compromised but still need to me cleared.
