### ISSUE TITLE
Update to latest docker image from the platform team

### ISSUE THREAD

**Issue by ohej** [Alfresco/alfresco-ng2-components#907]
We are not using the latest Alfresco repository, we need to update to ensure we're compatible with the latest version but also to leverage some of the latest work like versioning and search.

This will give us a docker image that gets updated when all new features gets merged to head, which means we have a quite stable image but also get the latest features.

**Comment by ohej** [comment]
Please note that when this issue is complete search will be broken because the /live-search URL has been changed to /queries. See #555 for more details.

**Comment by ohej** [comment]
Tagging @eromano so he's aware of the comment above ;)

**Comment by enzor** [comment]
This has been done, and the docker-compose has been put in jira for everyone to use
