### ISSUE TITLE
All versions of process definitions are not displayed, only latest 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#911]
Only latest versions of process definitions are displayed not all versions as displayed in Activiti.

Effects process definition heat map, process instance overview, task overview and task service level agreement 

![screen shot 2016-10-17 at 17 16 04](https://cloud.githubusercontent.com/assets/13200338/19445774/9a35ce5c-948d-11e6-86e5-d8eb03ee417b.png)
<img width="905" alt="screen shot 2016-10-17 at 17 15 54" src="https://cloud.githubusercontent.com/assets/13200338/19445775/9a389c0e-948d-11e6-9149-ebb7a08722c2.png">

**Comment by mauriziovitale** [comment]
Hi @hashraf88 can you retest this issue, I think is already fixed.

Without select an app
Activity
<img width="593" alt="screen shot 2016-11-30 at 09 47 58" src="https://cloud.githubusercontent.com/assets/14923305/20747607/9706b3e6-b6e2-11e6-999c-ef9012421070.png">

ADF
<img width="541" alt="screen shot 2016-11-30 at 09 46 36" src="https://cloud.githubusercontent.com/assets/14923305/20747606/970663a0-b6e2-11e6-857c-4046c3d95775.png">


App selected
Activity
<img width="477" alt="screen shot 2016-11-30 at 09 48 10" src="https://cloud.githubusercontent.com/assets/14923305/20747590/82be63de-b6e2-11e6-8501-c237b19018cc.png">

ADF
<img width="483" alt="screen shot 2016-11-30 at 09 48 24" src="https://cloud.githubusercontent.com/assets/14923305/20747589/82a9319e-b6e2-11e6-820c-74b91f2a45d3.png">
