### ISSUE TITLE
Testing IE 9 on Windows 7

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#931]
Demo shell does not load 
<img width="1353" alt="windows 7 ie 9" src="https://cloud.githubusercontent.com/assets/13200338/19746524/b4ecdf68-9bce-11e6-9c49-89fe74b6eed2.png">

```
SCRIPT438: Object doesn't support property or method 'bind' 
livereload.js?snipver=1, line 1106 character 2
EXCEPTION: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: Unable to get value of the property 'split': object is null or undefined 
ORIGINAL EXCEPTION: Unable to get value of the property 'split': object is null or undefined 
ERROR CONTEXT: 
[object Object] 
Unhandled Promise rejection:Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: Unable to get value of the property 'split': object is null or undefined; Zone:<root>; Task:Promise.then; Value:Error: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: Unable to get value of the property 'split': object is null or undefinedundefined 
Error: Uncaught (in promise): Error: Error in ./AppComponent class AppComponent_Host - inline template:0:0 caused by: Unable to get value of the property 'split': object is null or undefined 
```

**Comment by DenisVuyka** [comment]
Notes: this seem to be a problem related to `AlfrescoTranslationService` implementation:
```ts
constructor(private translate: TranslateService) {
        this.userLang = navigator.language.split('-')[0]; // use navigator lang if available
        this.userLang = /(fr|en)/gi.test(this.userLang) ? this.userLang : 'en';
        translate.setDefaultLang(this.userLang);
}
```
No safety check for `navigator.language` present

**Comment by DenisVuyka** [comment]
Notes: `Object doesn't support property or method 'bind' ` is caused by live reload script.  Live reload should not be enabled for regular testing, we may want splitting `npm start` script into `npm start` (no `-l` switch for live reload) and `npm start.dev` (or similar, for development purposes).

**Comment by hashraf88** [comment]
Demo shell does not display correctly. This is the same for each component tried from left hand menu.
This doesnt seem to occur on Windows 8 with IE10.

<img width="1408" alt="screen shot 2016-10-31 at 22 02 18" src="https://cloud.githubusercontent.com/assets/13200338/19873252/e4a812c8-9fb5-11e6-9bfd-e095b8fec66c.png">

**Error in console**
```

EXCEPTION: Error in app/app.component.html:1:0 caused by: Unable to get value of the property 'contains': object is null or undefined 
ORIGINAL EXCEPTION: Unable to get value of the property 'contains': object is null or undefined 
ERROR CONTEXT: 
[object Object] 
Unhandled Promise rejection:Error in app/app.component.html:1:0 caused by: Unable to get value of the property 'contains': object is null or undefined; Zone:<root>; Task:Promise.then; Value:Error: Error in app/app.component.html:1:0 caused by: Unable to get value of the property 'contains': object is null or undefinedundefined 
Error: Uncaught (in promise): Error: Error in app/app.component.html:1:0 caused by: Unable to get value of the property 'contains': object is null or undefined 
```

**Comment by DenisVuyka** [comment]
I don't think we can support IE9 at this point. Angular 2 [declares](https://angular.io/docs/ts/latest/guide/browser-support.html) only basic app support. It seems we need much more support due to Material Design and 3rd party components like date picker.

I've started with the missing [matchMedia](https://github.com/paulirish/matchMedia.js/) polyfill but demo shell still does not render correctly:

- sidebar does not hide (in fact overlaps entire page with blank white space)
- IE9 does not support font ligatures required for `material design icons` library (might require rewriting all icon names to 

<img width="771" alt="screen shot 2016-11-01 at 11 06 58" src="https://cloud.githubusercontent.com/assets/503991/19887947/8602c952-a023-11e6-93e3-93d4ad722e92.png">
