### ISSUE TITLE
For completed form if tab has visibility condition it does not display

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#939]
1. Create an form with tab that has a visibility condition of some sort
2. Adhere to visibility condition to display tab and complete form
3. Go to completed tasks and notice tab with visibility condition is not displayed

**Comment by VitoAlbano** [comment]
I have retried with the attached app and it seems to work now, could you please retest or be more specific? Thanks 
[TEST_APP.zip](https://github.com/Alfresco/alfresco-ng2-components/files/592673/TEST_APP.zip)
![screen shot 2016-11-15 at 17 23 46](https://cloud.githubusercontent.com/assets/7974125/20316096/679535be-ab58-11e6-8183-7730f3d13fa9.png)
