### ISSUE TITLE
Can override min and max values for date picker

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#942]
Can override min and max values by entering date manually and completing the task, the min and max values are 21 years prior and in the future from today 
It may be helpful to notify user with some sort of validation to avoid confusion.

Relates to #632

**Comment by DenisVuyka** [comment]
@hashraf88 if you remember this min/max range was increased to -100/+100 years from now. This range is needed only for UI component to be able drawing year selectors, the field and validation itself adhere to min/max value in the form definition. Should we close this ticket for now?

**Comment by hashraf88** [comment]
Should we also apply this restriction when entering a date manually too? As there is a restriction on the date picker

**Comment by DenisVuyka** [comment]
If we define minValue/maxValue in Activiti, those restrictions will be applied. It's a date picker we use that needs additional min/max range.

**Comment by hashraf88** [comment]
Happy to close, @magemello ?

**Comment by magemello** [comment]
I understand that we validate the date disabling the complete button, If so you can close the issue @hashraf88. Thnaks

**Comment by hashraf88** [comment]
Validation of date occurs by disabling the complete button
