### ISSUE TITLE
Date picker: when scrolling through months with navigation options, ‘stop’ symbol is displayed for a second

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#943]

**Comment by hashraf88** [comment]
Relates to #632

**Comment by DenisVuyka** [comment]
This is a native datepicker component behaviour. While dates are loaded it turns the cursor to 'stop' to indicate buttons cannot be clicked. Not sure we should be doing anything about that.

**Comment by hashraf88** [comment]
@magemello close for now?

**Comment by magemello** [comment]
@hashraf88  yes please
