### ISSUE TITLE
Dynamic table columns are not responsive, as is rest of form and widgets

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#955]
![screen shot 2016-10-31 at 15 23 07](https://cloud.githubusercontent.com/assets/13200338/19859702/217d5ae2-9f7e-11e6-90c0-493b4796d610.png)

**Comment by DenisVuyka** [comment]
I'm afraid we can't do much about that for the moment. Column amount is unlimited and there are no rules in form definition for resizing/hiding particular columns on smaller screens. Dynamic Table in Activiti is not responsive as well (columns just go beyond the screen if you resize the page).

**Comment by hashraf88** [comment]
@magemello should we close for now?

**Comment by magemello** [comment]
can we have a scrollbar to avoid the table going out the form area?

**Comment by hashraf88** [comment]
scrollbar is fine in Firefox and Chrome but unfortunately an overlap occurs in Safari and also cannot interact with the scrollbar

<img width="771" alt="screen shot 2016-11-02 at 20 24 29" src="https://cloud.githubusercontent.com/assets/13200338/19946077/d09198fa-a13a-11e6-8ca4-c1736737d719.png">

**Comment by DenisVuyka** [comment]
@hashraf88 as discussed - there's a known old Safari problem related to horizontal scrolling, so we may want putting that into a separate issue.

**Comment by hashraf88** [comment]
Above issue in Safari will be investigated in #986
