### ISSUE TITLE
Unable to extend FormComponent from @alfresco/adf-process-services as model.service is not exported

### ISSUE THREAD

**Issue by madhurahuja** [Alfresco/alfresco-ng2-components#9609]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

Module not found: Error: Package path ./lib/form/services/model.service is not exported from package node_modules\@alfresco\adf-process-services (see exports field in \node_modules\@alfresco\adf-process-services\package.json)

**Expected behavior:**

Able to extend the FormComponent

**Steps to reproduce the issue:**

Try to create a custom form component by extending the form component and calling super with the following params

```
formService: FormService
taskFormService: TaskFormService
taskService: TaskService
editorService: EditorService
modelService: ModelService
visibilityService: WidgetVisibilityService
ecmModelService: EcmModelService
nodeService: NodesApiService
```

**Component name and version:** 

FormComponent @alfresco/adf-process-services@6.1

**Browser and version:** 

Chrome 124
 
**Node version (for build issues):**  

Node 14 and Angular 14

**New feature request:**

**Comment by DenysVuika** [comment]
Thanks for reporting, will be fixed in the next release

**Comment by madhurahuja** [comment]
@DenysVuika when is the next release tentatively?

**Comment by DenysVuika** [comment]
should already be out with 6.9.0
