### ISSUE TITLE
Boolean value displays as 'true' instead of 'yes' 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#963]
After adding a row to a dynamic table a boolean property type displays as 'true' instead of 'Yes'. Both instances are correct but do we want to match that in Activiti?

**Activiti**
![screen shot 2016-11-01 at 09 49 38](https://cloud.githubusercontent.com/assets/13200338/19885887/034b628a-a019-11e6-8eb7-509bb8c2cd57.png)

**Component**
<img width="143" alt="screen shot 2016-11-01 at 09 49 42" src="https://cloud.githubusercontent.com/assets/13200338/19885880/fb3e7cf8-a018-11e6-91bf-47282d6319d6.png">

**Comment by magemello** [comment]
I think true also explain well the meaning, we can close it...what do you think @DenisVuyka ?

**Comment by DenisVuyka** [comment]
@magemello Agree that `true` better shows `boolean` column. We could provide some angular pipe to covert booleans to yes/no, but that may affect overall performance. I suggest closing for now.
