### ISSUE TITLE
Amount property does not display with currency in dynamic table

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#964]
After adding a row to a dynamic table an amount property type does not display the currency type set.

**Activiti**
![screen shot 2016-11-01 at 09 54 59](https://cloud.githubusercontent.com/assets/13200338/19886084/b269b0c8-a019-11e6-8d16-3da99054b6a1.png)

**Component**
<img width="172" alt="screen shot 2016-11-01 at 09 54 51" src="https://cloud.githubusercontent.com/assets/13200338/19886085/b271495a-a019-11e6-895d-b190cd236c7f.png">

**Comment by hashraf88** [comment]
Unfortunately I cannot see currency still

**Comment by DenisVuyka** [comment]
@hashraf88 fixed for completed forms only, will check the regular mode.

**Comment by DenisVuyka** [comment]
I will also add currency symbol to the label when editing a row, so it will be something like **MyLabel (GBP)**
