### ISSUE TITLE
Add custom fields in a form

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#966]
As a developer, I want to be able to define custom fields in a form which are not defined in activiti, and then take the data from the formLoaded , formSaved, formCompleted events. Suggested structure :
```
        <custom-inputs position="top/bottom" before="activiti-field-id" after="activiti-field-id">
            <input id="custom-field" type="text">
            <input id="custom-field-2" type="text">
        </custom-inputs>
```

**Comment by jsotiro** [comment]
@magemello and @DenisVuyka  Could you describe the use case for this? And how will it relate to stencils and the form designer. Typically developers will define the forms in activiti forms designer. It would be a step back to take it back to not using the form designer. 

There should be a way to register these controls with the forms designer as stencils even if they are just a place holder for external controls

**Comment by DenisVuyka** [comment]
@jsotiro we now support mapping custom stencils to angular 2 components, there's also an api to allow rendering different components based on stencil metadata. We need documenting form widget authoring in details.

**Comment by DenisVuyka** [comment]
We can add custom field into the form definition itself (layout designer and/or custom stencils) without hacking with inserting fields during render time. In this case customers will have form definition still compatible with other custom renders.

**Comment by jsotiro** [comment]
@magemello  what is the use case for this?

**Comment by magemello** [comment]
Often users want a way to define fielsds in a form and  not send this data to activiti but to another system...

**Comment by jsotiro** [comment]
but that would be a custom HTML form. The value of the Activiti form component is that it comes from the designer.  Having hooks to update other systems is great  but dont see the need to mix the designed and custom. would be interested to see the actual use cases this addresses.

**Comment by DenisVuyka** [comment]
@magemello @jsotiro this scenario is still very unclear, I don't see any reason extending a form on each load compared to Form Definition and custom stencils/components we already support.
