### ISSUE TITLE
Replace Form filed with custom field code

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#967]
As a developer, I want to be able to replace an activiti field editor (aka form widget) in a form with my own custom editor. Suggested structure : 

```
        <custom-widgets>
            <custom-widget fieldId="NameFiledId">
                <template>
                  <h1>Hi I'm Custom</h1>
                  <input id="test" type="text" value="one">
                  <input id="test2" type="text" value"[(field.value)]">
                </template>
            </custom-widget>
        </custom-widgets>

data sent to activiti:
{
  "NameFiledId":  "two"
}
```

For the beginning. we want to use only standard html tags.

**Comment by jsotiro** [comment]
@magemello  and @DenisVuyka  As per #966 What is the problem we are trying to solve here and how will the developer experience work? 
Is the case of providing alternative "standard" library of controls? What would be the use case?

**Comment by DenisVuyka** [comment]
Covered by new extensibility api. Not yet possible defining as part of html markup but possible doing that via code.

**Comment by DenisVuyka** [comment]
@magemello as soon as Form gets wrapped we need another layer of components to make this work (1 layer per wrapping). For example right now we don't use <activiti-form> directly in demo shell, it is wrapped by <activiti-task-details> component.

**Comment by magemello** [comment]
Closing this issue, the actual implementation already provides all the necessary, without using the hml templating:

Link to the documentation:
- Custom Stencil in Adf:
   - https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/docs/stencils.md
- Support for existing stencil in Activiti:
   - https://github.com/Alfresco/alfresco-ng2-components/blob/master/ng2-components/ng2-activiti-form/docs/extensibility.md
