### ISSUE TITLE
Non editable fields cannot be edited after a single row has been added 

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#972]
1. Add different columns with different property types to dynamic table, ensure all are set to not be editable (one column is required to be editable)
2. Add form to task
3. Complete a single row in the dynamic table
4. Click on the '+' to add another row

**Expected results**
All fields are able to be edited as a new row is to be added

**Actual results**
All fields are locked apart from single property type field that was set to be editable in step 1

**Comment by DenisVuyka** [comment]
This is expected behaviour. At design time you add "table columns" for dynamic table, so setting 'editable=false' for a column enforces every row to have readonly cell for the given column.
