### ISSUE TITLE
Header bar visible after login

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#973]
Step to reproduce it:
- Login with username and password
- Click on the login option or go on /login

Result:
Header bar still visible

Aspected:
Header bar should always be hidden in the login page

<img width="1437" alt="screen shot 2016-11-02 at 00 38 46" src="https://cloud.githubusercontent.com/assets/688226/19912771/efd9d7a0-a094-11e6-8793-1f0124011501.png">

**Comment by hashraf88** [comment]
When logged in and in the settings page should I see the top banner?
Relates to 
<img width="1333" alt="screen shot 2016-11-02 at 14 29 58" src="https://cloud.githubusercontent.com/assets/13200338/19932715/e9d5f572-a108-11e6-8f73-7c038d7fbfdb.png">

**Comment by magemello** [comment]
Thanks Hussain, It's ok like that
