### ISSUE TITLE
app.config.json contains validation errors is thrown in console while upgrading ADF components from 6.1.0 to 6.9.0  and application is not coming up

### ISSUE THREAD

**Issue by swathytamizharasan** [Alfresco/alfresco-ng2-components#9741]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [ ] Bug  
> - [X] Support request
> - [X ] Documentation

**Current behaviour:**
All compile time errors have been fixed. While trying to load the application getting the runtime error 

**Expected behavior:**
After upgrade from version 6.1.0 to 6.9.0, the application should be up without any runtime errors. 

**Steps to reproduce the issue:**
Upgrade from version 6.1.0 to 6.9.0. 
Fix all compile time errors. 
Try to load the application in the browser

In browser console getting the below error:
app.config.json contains validation errors.
Have validated the schema and getting the below errors
strict mode: "items is 1-tuple, but minItems or maxItems or maxItems/additionalItems are not specified or different path at "#/definitions/content-metadata-layout-group"
strict mode: use allowUnionTypes to allow union type keyword at https://github.com/Alfresco/alfresco-ng2-components/tree/master/lib/core/app-config/schema.json#/properties/oauth/properties/outh2/properties/codeFlow

**Component name and version:** 
@alfresco/adf-core - 6.9.0

**Browser and version:** 
Chrome 124
 
**Node version (for build issues):**  
Node 14 and Angular 14

**New feature request:**

**Comment by DenysVuika** [comment]
please give proper steps to reproduce... "Try to load the application in the browser" - what application? etc
