### ISSUE TITLE
Redirect the user to the login page when is not logged in

### ISSUE THREAD

**Issue by magemello** [Alfresco/alfresco-ng2-components#975]
When a user navigate to any page of the demo shell if he is not logged in he has to be redirected to the login page.

**Comment by DenisVuyka** [comment]
This will be possible only when client can validate auth tokens and check expiration date. Without expiration user will see the content behind the route but js-api won't work

**Comment by magemello** [comment]
For now we want just to check if he has had a login with the isLohedin method

**Comment by eromano** [comment]
Any call in the JS-API has the possibility to listen the unauthorized event.
We could modify all the services to introduce a logic that handle this events.

```javascript
var promiseGetTags = this.alfrescoJsApi.core.tagsApi.getTags();
promiseGetTags.on('unauthorized', function() {
            //business logic
 });
```
