### ISSUE TITLE
Dynamic table: Table column required, dyanmic table not required. Should still be able to complete task

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#982]
If table column is required but dynamic table itself not required should be able to complete form.
Within Activiti this is the functionality.

1. Create a dynamic table within form, ensure dynamic table 'required' is unchecked
2. Add table column, ensure 'required' is checked
3. Add form to task
4. Complete task, without filling in any details

**Expected results, compared to Activiti**
Can complete task

**Actual results**
Cannot complete task

**Comment by DenisVuyka** [comment]
Cannot reproduce this issue. However it seems there's an issue with 'required' validator that needs to support dynamic tables. For now dynamic table is not validated.

**Comment by hashraf88** [comment]
Any issues will be tracked in #985
