### ISSUE TITLE
Dynamic table horizontal scroll bar overlaps and cannot interact

### ISSUE THREAD

**Issue by hashraf88** [Alfresco/alfresco-ng2-components#986]
If a cerain number of columns are added to the dynamic table a horizontal scrollbar can be used which is fine in Firefox, Chrome, IE11  but unfortunately an overlap occurs in Safari and also cannot interact with the scrollbar.
If the page is resized/enlarged the scrollbar is fine. 

<img width="771" alt="screen shot 2016-11-02 at 20 24 29" src="https://cloud.githubusercontent.com/assets/13200338/19946077/d09198fa-a13a-11e6-8ca4-c1736737d719.png">

**Comment by DenisVuyka** [comment]
@hashraf88 if you remember previous discussions - there's an old bug in Safari, if you resize window by at least 1px the scrollbar will get working back.

**Comment by hashraf88** [comment]
@magemello should we close for now?

**Comment by magemello** [comment]
@DenisVuyka If we put more space between the buttons and the table would the buttons and the scrollbar be working in this case??

**Comment by DenisVuyka** [comment]
@magemello For me buttons are still working regardless of the horizontal scrollbar glitch. Using Safari 10.0.1

**Comment by DenisVuyka** [comment]
@magemello @hashraf88 strange, but adding small margin helped solving Safari issue.
