### ISSUE TITLE
Wrong German translation for FILE_UPLOAD.MESSAGES.UPLOAD_ERROR

### ISSUE THREAD

**Issue by jsfi** [Alfresco/alfresco-ng2-components#9980]
**Type of issue:**  (check with "[x]")

> - [ ] New feature request
> - [x] Bug  
> - [ ] Support request
> - [ ] Documentation

**Current behaviour:**

[The German translation for the UPLOAD_ERROR](https://github.com/Alfresco/alfresco-ng2-components/blob/master/lib/content-services/src/lib/i18n/de.json#L247) (singular) is incorrect. It is missing the negation and should be the same as the UPLOAD_ERRORS (plural).

**Expected behavior:**

`"UPLOAD_ERROR": "{{ total }} nicht erfolgreich hochgeladen",`

**Steps to reproduce the issue:**

1. Upload multiple files.
2. Get an error on one upload request.
3. Message appears: 1 erfolgreich hochgeladen (1 upload successful).

**Component name and version:** 

adf-file-uploading-dialog (all versions)

**Browser and version:** 

all

**Comment by DenysVuika** [comment]
Thanks for reporting, we will address this issue for the next release, or you can fix the i18n file locally in your application to get the fix earlier
